### ISSUE TITLE
Common base class for Kubernetes resource models

### ISSUE THREAD

**Issue by tintoy** [kubernetes-client/csharp#101]
Hi.

I was wondering if it might be useful to have a shared base class for models representing Kubernetes resources / resource-lists (the script I wrote to generate models from Swagger does this, and I imagine autorest can do something similar).

![modelhierarchy](https://user-images.githubusercontent.com/1646284/37257134-feee9456-25b8-11e8-82e4-b4f8498999e9.jpg)

 My existing client library does this and I've found that it makes it easier to deal with resources in a generic fashion:

https://github.com/tintoy/dotnet-kube-client/blob/develop/src/KubeClient/Models/PodV1.cs
https://github.com/tintoy/dotnet-kube-client/blob/develop/src/KubeClient/Models/PodListV1.cs
https://github.com/tintoy/dotnet-kube-client/blob/develop/src/KubeClient/ResourceClients/KubeResourceClient.cs#L90
https://github.com/tintoy/dotnet-kube-client/blob/develop/src/KubeClient/ResourceClients/KubeResourceClient.cs#L122

TBH given that the official client is mostly generated code, I don't know how useful it will be within the client itself, but it's almost certainly going to be useful to some of its consumers.

Again, I get that there are existing users and this might be a breaking change (at the binary-compatibility level at least) but I still think it's something worth considering.

**Comment by tintoy** [comment]
Here's an example of where it's useful:

https://github.com/DimensionDataResearch/glider-gun-v2/blob/master/src/GliderGun.Actors/Events/JobEvents.cs
https://github.com/DimensionDataResearch/glider-gun-v2/blob/master/src/GliderGun.Actors/Events/ResourceEventBus.cs

**Comment by brendandburns** [comment]
Yeah, I see the utility, but I don't want to manually generate the code.

Do you know if AutoRest supports an extension to add a parent class? If so we can look to add that extension...

**Comment by tintoy** [comment]
Agree 😊

The classes are marked as partial, so even if it doesn't I can easily use Roslyn for "post-processing". Will have a think about it this weekend

**Comment by tintoy** [comment]
Sorry, have been a bit flat-out at work, so I haven't had time to follow up on this; I'll try to have a proper look into it this weekend.

**Comment by tintoy** [comment]
@brendandburns - looking at the `gen`repository, is the directives / transforms the right place to make this change, or do you think I'm better off creating an Autorest extension to add the base class? I could easily write a Roslyn-based console app that can parse the generated code and add the base class as required. Which would be a lot simpler but probably not fit with the "official" generation process...

**Comment by tintoy** [comment]
@brendandburns - I think part of the problem is that the swagger definitions don't directly support specifying a base class (JSON schema doesn't support inheritance). This can be done at the code level, but not the swagger level.

FWIW, I did this in my own project when generating the code (after the Swagger JSON has been processed):

https://github.com/tintoy/dotnet-kube-client/blob/ff2d9bf577663e9c29994b383e67125ea60c13d0/src/Swagger/generate_models.py#L467-L475

And the detection of resources / resource-lists is done like so:

https://github.com/tintoy/dotnet-kube-client/blob/ff2d9bf577663e9c29994b383e67125ea60c13d0/src/Swagger/generate_models.py#L62-L102

Note that this also correctly handles `StatusV1` which is not a resource list, but has a `meta` property of type `ListMetaV1`.

**Comment by tintoy** [comment]
@brendandburns - here's an example implementation. Only required a minor amount of yak-shaving (due to use of .NET Core 2.1-preview2 SDK):

https://gist.github.com/tintoy/93a8f50fb3f4dafcfa835cbeb804b441

**Comment by tintoy** [comment]
Otherwise, we _might_ be able to do what we need using the [allOf](https://github.com/Azure/autorest/blob/master/docs/developer/guide/defining-clients-swagger.md#inheritance-and-polymorphism) directive.

**Comment by tintoy** [comment]
@brendandburns - looks like I'd have to modify the `gen` repository to make this work, but there seems to be only a single script for preprocessing the Swagger document and many other languages (e.g. Go) may not want to use inheritance like this. While I have some ideas for tackling this issue, I'd appreciate it if you could provide some direction in terms of a "blessed" approach :)

(for what it's worth, I still think the Roslyn-based postprocessing might be a more workable idea in the long run even if it does make the model-generation process a two-step affair)

CC: @qmfrederik @tg123

**Comment by qmfrederik** [comment]
@tintoy An easier way may be to use interfaces instead of base classes, like in #152 .

Would interfaces work for your use cases or do you need base classes?

What would the `KubeResource` attribute do?

**Comment by tintoy** [comment]
Yeah possibly - but we'd still have the same problem of needing to somehow declare the interface implementation on each model class. So back to square one :)

**Comment by tintoy** [comment]
Will explain properly tomorrow morning :)

**Comment by tintoy** [comment]
Ok, now that I'm in front of a proper keyboard (rather than on my phone):

The issue is that, either way, we have to be able to declare a base class or interface for each model (but the current process for generating the models does not allow for this). If we forked the Python script that modifies the Swagger to create a C#-specific version then that could do the trick (but I'm not sure how willing others are to do it this way). Otherwise, we could perhaps add a separate Python script to modify the swagger (to be run after the main one) that's only run when generating for C#?

**Comment by brendandburns** [comment]
#152 is merged, so closing.
