### ISSUE TITLE
[Code style] Force code writing style verification during pull request checks

### ISSUE THREAD

**Issue by m3nax** [kubernetes-client/csharp#1011]
Force code writing style verification during pull request checks.

Objective: 
- increase the uniformity of the writing style of the code

**Comment by tg123** [comment]
`kubernetes-client.ruleset`

**Comment by m3nax** [comment]
Can we make more restrictive rule?
Making your code smoother and more consistent makes editing easier and making it easier to contribute....

**Comment by m3nax** [comment]
Witch Action check code style?

**Comment by brendandburns** [comment]
@m3nax we used to have it, but it looks like @tg123 may have accidentally removed it in https://github.com/kubernetes-client/csharp/commit/250a45741e04662a408af508ec87dfb66eed1bdb

@tg123 was this on purpose? (and my mistake for missing it at the time when I reviewed it...)

**Comment by tg123** [comment]
not a mistake

the `dotnet fmt` conflicts with[ `stylecop` ](https://github.com/kubernetes-client/csharp/blob/master/kubernetes-client.ruleset) check

cannot pass them together, so I disable the `dotnet fmt`

**Comment by m3nax** [comment]
ruleset is deprecated: https://learn.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#convert-an-existing-ruleset-file-to-editorconfig-file

Can i covert it in a .editorconfig?
