### ISSUE TITLE
[DOCS] Create library docs (github pages)

### ISSUE THREAD

**Issue by m3nax** [kubernetes-client/csharp#1012]
Request:
Simplify the use of the library by creating a documentation site.

Side gola:
- Improve library sharing

**Comment by WeihanLi** [comment]
Maybe we could use [docfx](https://github.com/dotnet/docfx) for the documentation

**Comment by tg123** [comment]
testing docfx, seems cannot handle generated api

**Comment by tg123** [comment]
https://kubernetes-client.github.io/csharp/
