### ISSUE TITLE
WebSockets - custom validation of server certificate

### ISSUE THREAD

**Issue by tintoy** [kubernetes-client/csharp#102]
Hey, @brendanburns, as previously discussed in [tintoy/dotnet-kube-client#6](https://github.com/tintoy/dotnet-kube-client/issues/6#issuecomment-371984010) I'm happy to contribute my WebSocket functionality (which includes support for custom verification of the server certificate).

But I figured it'd be worth discussing here first :)

The big gotcha (currently) is that it has a dependency on `netcoreapp2.1` because in previous versions of corefx WebSockets used WinHTTP on Windows (which didn't honour a subset of the certificate options on `ClientWebSocketOptions`) and something else on OSX / Linux (which didn't honour a _different_ subset of the certificate options). In 2.1, the WebSockets implementation is entirely implemented in managed code and fully supports customisation of SSL certificate usage / validation.

As it stands, here's how I implemented it:

https://github.com/tintoy/dotnet-kube-client/blob/develop/src/KubeClient.Extensions.WebSockets/K8sWebSocketOptions.cs#L13
https://github.com/tintoy/dotnet-kube-client/blob/develop/src/KubeClient.Extensions.WebSockets/K8sWebSocket.cs#L31

I borrowed some of the original `ClientWebSocket` code from .NET Core 2.0 and modified it to work with `2.1-preview1` (but from `2.1-preview2` onwards, the `ManagedWebSocket` types will be publicly available and much of this code can be eliminated).

The latest code from corefx is a fair bit simpler because the required managed types are available internally:

https://github.com/dotnet/corefx/blob/f1f3b3f8af21c0f782f7f0699d505a0cdb9026ba/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs#L71

**Comment by tintoy** [comment]
So it might be worth placing in a separate package (as I did in my client) that [extends the client](https://github.com/tintoy/dotnet-kube-client/blob/develop/src/KubeClient.Extensions.WebSockets/ResourceClientWebSocketExtensions.cs#L56) to add operations that are WebSocket-dependent.

**Comment by tintoy** [comment]
CC: @qmfrederik

**Comment by qmfrederik** [comment]
It's a pitty the WebSockets implementation was not complete in .NET Core 2.0 but the good news is it is being fixed in 2.1.

My 2 cents would be that it's:
* Not a problem to depend on netcoreapp2.1; I think people will move to netcoreapp2.1 fairly fast. The library can multitarget 2.0 and 2.1 with a warning that if you want to use WebSockets, you need 2.1.
* Worth getting the WebSocket fixes in CoreFX rather than copy/pasting code, though I know it can be a lengthy process (especially the certificate validation callback seems to be low prio over there).

Not sure whether there are any "One Microsoft" strings @brendanburns can pull that would bump the prio of WebSockets in CoreFX 😄 .

**Comment by tintoy** [comment]
Heh. I've been following an issue in the corefx repo (can't find it right now) where they've been looking at implementing the validation callback. From memory, I think they'd like to get it in for 2.1 (so here's hoping).

Yeah that's a good point, I hadn't thought of that - can always use `#if` / `#endif` to keep the WebSockets code available in 2.1 only.

Only other wrinkle is that, by targeting `netcoreapp` rather than `netstandard` (`netstandard2.1` seems to still be further in the future), the library can't be used on the full .NET Framework / Mono (but again, multi-targeting and conditionals can probably help there).

**Comment by qmfrederik** [comment]
I think it's dotnet/corefx#12038 you're referring to.

**Comment by tintoy** [comment]
Yep, thanks! Edited :)

**Comment by tintoy** [comment]
https://github.com/dotnet/corefx/issues/12038#issuecomment-370796142

**Comment by qmfrederik** [comment]
... that issue is marked as "api-ready-for-review"; so the next step would be for the API review team to give a formal go for the API. You may want to ping @karelz to figure out what the next steps are (i.e. when a review is planned). Once the API is greenlighted you can file a PR.

**Comment by karelz** [comment]
We meet every & steam API reviews every Tuesday (see [list](https://github.com/dotnet/apireviews)). However, technically speaking, we are API frozen for .NET Core 2.1 for last week. If you can chime in on importance of the scenarios (and how mainline they are), we might try to get it in ... otherwise post-2.1 if that works.

**Comment by tintoy** [comment]
Hi - obviously I'm biased, but... 😉

Being able to control validation of the server certificate is pretty important for Websockets (at least the way we use them). Otherwise they're unusable with servers that have self-signed certificates unless the user goes through the rigmarole of trusting the CA certificate (needs admin privileges on Windows from memory and probably on Linux too).

Having said that, we at least have a workaround in the worst case (temporarily duplicate the corefx code for initiating the connection and add support there until support is added to corefx).

**Comment by tintoy** [comment]
Is there someplace in particular I should be chiming in? 😊

**Comment by tintoy** [comment]
@karelz oh, and I suspect the same issue will bite anyone using SignalR (over WebSockets) for inter-server communication (i.e. with the managed `HubConnection` client) with self-signed certificates. As mentioned above, there are workarounds available but they're pretty ugly.

**Comment by tintoy** [comment]
Relevant issue for SignalR: https://github.com/aspnet/SignalR/issues/1389#issuecomment-363689851

**Comment by brendandburns** [comment]
Personally, I'd love to see this in 2.1, but regarding the general issue, I think that supporting DotNet standard framework is important, so let's see what we can do with conditionals/extensions.

My proposal would be:

1) Requiring net-core 2.1 seems fine. There's no reason for someone not to upgrade

2) Enabling net-standard (at the expense of this funcitonality) is also desirable.

And of course the simplest solution (conditionals vs alternate extension package) is the right choice assuming we satisfy those goals.

Thanks!
--brendan

**Comment by tintoy** [comment]
Ok, I'll work up a PR then :)

**Comment by karelz** [comment]
@tintoy please make sure the API is first approved in CoreFX (mainly to avoid wasting your time). We will see if it can get it 2.1, or not ...

**Comment by tintoy** [comment]
Ok, PR is just about ready to go, but I'm having a little trouble with the existing tests for WebSockets.
Are they expecting me to have a real server running locally for them to connect to? If so, I have a mock WebSocket server I wrote for my own client that might be useful:

https://github.com/tintoy/dotnet-kube-client/blob/develop/test/KubeClient.Extensions.WebSockets.Tests/WebSocketTestBase.cs
https://github.com/tintoy/dotnet-kube-client/blob/develop/test/KubeClient.Extensions.WebSockets.Tests/Server/Startup.cs
https://github.com/tintoy/dotnet-kube-client/blob/develop/test/KubeClient.Extensions.WebSockets.Tests/Server/Controllers/PodExecController.cs

CC: @qmfrederik @brendanburns

**Comment by brendandburns** [comment]
switching to a Mock sounds like a good idea...

Thanks!
--brendan



________________________________________

**Comment by qmfrederik** [comment]
@tintoy are you talking about a PR to corefx or kubernetes-client/csharp? If it's for corefx, I think you're better off commenting on the issue in corefx and adding the [area owners](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md) to the loop - say davidsh, Priya91 or wfurt and probably stephentoub as well.

**Comment by tintoy** [comment]
@qmfrederik, sorry, I meant kubernetes-client/csharp.

None of these tests seem to create a server (although I could be missing something obvious):

https://github.com/kubernetes-client/csharp/blob/master/tests/Kubernetes.WebSockets.Tests.cs

**Comment by tintoy** [comment]
Here's a diff of the work so far:

https://github.com/kubernetes-client/csharp/compare/master...tintoy:feature/websockets

Had to make a couple of tweaks to the `WebSocketBuilder` design (now _slightly_ different between `netstandard1.4` and `netcoreapp2.1` versions) because we can't simply construct a ClientWebSocket and call `ConnectAsync` anymore. But that's only visible if you target `netcoreapp2.1`. And once corefx supports the required SSL customisations we can drop a fair chunk of that code.

**Comment by qmfrederik** [comment]
@tintoy Correct, none of the unit tests hit the network. The idea behind that was that:
- the actual networking code lives in corefx and doesn't need to be (unit) tested in kubernetes-client/csharp;
- the responsibility of kubernetes-client/csharp is invoking the WebSockets API correctly so that's what's being tested (via the WebSocketBuilder class).

If you want to hit a server (and run integration tests), why not hit a real Kubernetes server instead of creating a mock WebSockets server?

I've done something similar when creating a C# client for Helm; it's fairly easy to set up a Kubernetes cluster in a Travis build - see e.g. https://github.com/qmfrederik/helm/blob/master/.travis.yml. 

That said, the more tests the better, whichever the approach 😄 .

**Comment by qmfrederik** [comment]
@tintoy That diff looks good - I like the fact that you can hide the complexity in the WebSocketBuilder!

That said, are you sure you can include the dotnet/corefx code in the kubernetes-client/csharp repository? They are owned by different entities (the .NET Foundation vs. CNCF) and have different licenses (MIT vs Apache). Alternatively, a separate NuGet package for just the WebSockets code would do the trick.

**Comment by tintoy** [comment]
Ah, I see what I was missing now; the mock builder never actually tries to connect :)

I think there's value in having a mock server for WebSocket requests now; mainly because some of that networking code that was in CoreFX is now bundled into the client :)

**Comment by tintoy** [comment]
> are you sure you can include the dotnet/corefx code in the kubernetes-client/csharp repository?

Very good question :)

From what I understand, the MIT license allows you to include it anywhere as long as you include the copyright notice. But I'll admit I'm hardly an authority on the matter :grin:

FWIW that's one of the reasons my client design keeps the WebSockets support entirely separate from the main client package (but mine uses extension methods for access to individual resource-API clients, so it's easier to do; with a generated client, everything is bundled into a single class unless we want to start messing with the generator).

@brendanburns - do you have an opinion here?

**Comment by tintoy** [comment]
That's a nice trick, setting up the cluster in CI - I've not tried before that but I have a project where it'd be very useful!

**Comment by tintoy** [comment]
Also, nice work on the helm client - I was thinking of building something similar (talking to Draft) a while back but you've saved me the hassle of working out how to do it!

**Comment by tintoy** [comment]
Hooray for rebasing :)
