### ISSUE TITLE
Load Deployment object from Yaml

### ISSUE THREAD

**Issue by RohanNagar** [kubernetes-client/csharp#104]
I see that #98 adds a utility object for loading from Yaml. Does this mean I will be able to load a `deployment.yaml` file as a `V1Deployment` object, and pass that in to `CreateNamespacedDeployment`?

If so, I was wondering when a new Nuget package is planning on being released with this addition. I know this change is recent but it would be nice to pull it in without having to copy over the code into my project.

Thanks!

EDIT: I copied the code into my own project. Will keep this open to hopefully track when a new package is released so I can migrate to that.

**Comment by brendandburns** [comment]
I'll see about releasing a new nuget package this weekend.

**Comment by brendandburns** [comment]
Just published `0.5.0-beta` which includes the `Yaml` changes.

**Comment by RohanNagar** [comment]
Thanks Brendan!
