### ISSUE TITLE
Provide strict model parsing

### ISSUE THREAD

**Issue by stan-sz** [kubernetes-client/csharp#1046]
Currently the deserializer silently ignores any extraneous properties (see #574). This request is to make it configurable, as there are scenarios where throwing the exception is expected, specifically when providing a type map with locally-mainteined models.

**Comment by IvanJosipovic** [comment]
I would also love to see all the serialization settings exposed to us and customizable.

**Comment by tg123** [comment]
@IvanJosipovic PRs of your idea are welcomed
