### ISSUE TITLE
Error with Yaml loading

### ISSUE THREAD

**Issue by RohanNagar** [kubernetes-client/csharp#106]
I was trying to use the `Yaml` class in version `0.5.0-beta` this morning, and ran into this error when calling `Yaml.LoadFromFileAsync`:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Stream was not readable.) ---> System.ArgumentException: Stream was not readable.
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at k8s.Yaml.<LoadFromStreamAsync>d__0`1.MoveNext()
```

It looks like changing 

```cs
using (FileStream fs = File.Open(file, FileMode.Open, FileAccess.Write, FileShare.None))
```

to

```cs
using (FileStream fs = File.Open(file, FileMode.Open, FileAccess.Read, FileShare.None))
```

fixes the problem, since in the first one the file is being opened for writing and not reading.

Would you like me to open a PR to fix this?

**Comment by tg123** [comment]
please try `File.OpenRead`

**Comment by RohanNagar** [comment]
@tg123 Yes I can get it to work for me, I just wanted to point out the bug. Are you suggesting that I submit a PR changing it to use `File.OpenRead`?

**Comment by brendandburns** [comment]
Yes, I should have done that already...

Sorry!

**Comment by RohanNagar** [comment]
Sounds good, I'll try to get one in today!
