### ISSUE TITLE
List deployments/service support for paging

### ISSUE THREAD

**Issue by fzwu** [kubernetes-client/csharp#1089]
**Describe the bug**
I use SDK to get deployments or service,but  aging fetch is not supported

**Kubernetes C# SDK Client Version**
`8.0.68`

**Server Kubernetes Version**
e.g. `1.24.2`

**Dotnet Runtime Version**
e.g. net6

**To Reproduce**
var config = KubernetesClientConfiguration.BuildConfigFromConfigFile("./admin.conf");
IKubernetes client = new Kubernetes(config);
var serviceList = await client.CoreV1.ListNamespacedServiceAsync(vo.NameSpaces);

The response result has no paging information
**Expected behavior**

I need to support paging to get Services and Deployment

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: Windows 10 
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by tg123** [comment]
may I know why do you want paging?
