### ISSUE TITLE
WebSockets request TLSv1

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/csharp#112]
which is insecure and not supported by the Kubernetes server, we should use `SslProtocols.None` instead to pick up the system defaults when the user doesn't specify anything...

**Comment by tintoy** [comment]
I think I tried None before but got an exception when connecting; let me update the tests and try again.

**Comment by tintoy** [comment]
Sorry, I think I had that confused with `SslProtocols.Default`. Will fix shortly :)

**Comment by brendandburns** [comment]
Have you tried this on Linux? I'm trying and its hanging. I'm debugging, but was wondering if you had it working...

--brendan



________________________________________

**Comment by tintoy** [comment]
The tests work in CI which is Travis, right? I'm on my way into the office now, will give it a try shortly.

**Comment by tintoy** [comment]
BTW, different client but same connection code definitely works against real K8s API:

https://github.com/tintoy/dotnet-kube-client/blob/develop/samples/noob-exec/Program.cs

**Comment by tintoy** [comment]
Is it a test that's hanging or some other code?

**Comment by tintoy** [comment]
I got caught out originally by the behaviour of WebSocket.CloseAsync but the tests cater for that.

**Comment by tintoy** [comment]
@brendanburns - just tried this on Linux (well, WSL, but close enough) and yes all tests pass.

**Comment by tintoy** [comment]
(the tests do use a real WebSocket connection)

**Comment by brendandburns** [comment]
fwiw, it was my network connection *sigh* flaky bus and my tcp socket was timing out.

**Comment by tintoy** [comment]
Tricky - I've been using cancellation tokens in tests so probably hadn't hit that particular issue :-/

Glad you worked it out though
