### ISSUE TITLE
Memory leak issue found in 8.0.4 Kubernetes C# Client SDK

### ISSUE THREAD

**Issue by Moresoph** [kubernetes-client/csharp#1123]
**Describe the bug**
Kubernetes Csharp client has a memory leak problem when using the leader election functionality.

**Kubernetes C# SDK Client Version**
8.0.4

**Server Kubernetes Version**
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"83d00b7cbf10e530d1d4b2403f22413220c37621", GitTreeState:"clean", BuildDate:"2022-11-09T19:50:11Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

**Dotnet Runtime Version**
.net 3.1 core

**To Reproduce**
![image](https://user-images.githubusercontent.com/13598265/206985403-f5206455-649d-414a-8bef-947d0709dfea.png)

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: Linux
 - Environment container
 - Cloud Azure

**Additional context**
Here is my investigation of this memory leak problem.
When we use the leader election functionality, we find that memory increases over time. 

The following picture shows that the count of the object named "Linked1CancelaationTokenSource" increased greatly.
![image](https://user-images.githubusercontent.com/13598265/206986511-f839a344-ffeb-47b2-9f42-9ffe9cb5e3a1.png)

The following picture shows the call stack of how the KubernetesClient will call the function named "CreateLinkedTokenSource" to create the object named "Linked1CancelaationTokenSource".
![image](https://user-images.githubusercontent.com/13598265/206995519-c1624228-317e-4100-8e38-faabd6e479e0.png)

The following picture shows the decompiled code from version 8.0.4 "KubernetesClient.Basic.dll". From the following decompiled code we can see, **the "Dispose()" function of the "CancellationTokenSource cts" is not called.** 
![image](https://user-images.githubusercontent.com/13598265/206987712-9247b2aa-f3d5-49fa-8768-841d7907276f.png)

**Comment by tg123** [comment]
the cts is not specific to leader election but every single rest call.

`cancel after` creates a timer in background and I do not think there is a way to cleanup it if `wait` is no longer available even calling dispose of cts.

however, I remember `timer` is very cheap obj in windows kernel. 
from your screenshot, it is just 3MB


internal of cancelafter
https://github.com/dotnet/runtime/blob/b1a2080b9ce5833802fe2d632f79de6402097f14/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L336

**Comment by tg123** [comment]
double checked the .net src, you are right, `dispose` will clean up the timer.

**Comment by tg123** [comment]
could you please clone and test if the pr works?

**Comment by tg123** [comment]
you can test with this nuget pkg https://github.com/tg123/csharp/pkgs/nuget/KubernetesClient/58619762

**Comment by tg123** [comment]
remove nuget.org, github source only
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry#authenticating-with-a-personal-access-token

**Comment by tg123** [comment]
see #725
