### ISSUE TITLE
Kubernetes Namespace pod watch can hang sometimes 

### ISSUE THREAD

**Issue by gunpuz** [kubernetes-client/csharp#1134]
**Describe the bug**

It seems that watch:
```cs
var podlistResp = kubeClient.CoreV1.ListNamespacedPodWithHttpMessagesAsync(configurationSettings.DeploymentNamespace, watch: true);

await foreach (var (type, item) in podlistResp.WatchAsync<V1Pod, V1PodList>())
{
   ...
}
```

can hang from time to time. There seems to be no clear scenario how and when to reproduce it though :(

**Server Kubernetes Version**
v1.24.3

**Dotnet Runtime Version**
net6

**To Reproduce**
It can hang "sometimes". Its not clear why.

**KubeConfig**

Default configuration
```cs
KubernetesClientConfiguration k8sConfig;
            if (!_configurationSettings.UseKubeConfig)
            {
                // Running inside a k8s cluser
                k8sConfig = KubernetesClientConfiguration.InClusterConfig();
            }
```

**Additional info**

It could be related to this issue: https://github.com/kubernetes-client/csharp/issues/884

**Comment by tg123** [comment]
what do you mean by `hang`

**Comment by gunpuz** [comment]
I think that new events are not dispached from library in `await foreach` but I don't know how to reproduce it.

**Comment by tg123** [comment]
there is an `onError` param in WatchAsync<V1Pod, V1PodList>())
maybe something happened you did not notice

**Comment by gunpuz** [comment]
Should you use error param? Seems that if error parameter is not used then exception is thrown. I dont use error param

Should this work? I have something like this: 

```cs
while(true){
   try{
       var podlistResp = kubeClient.CoreV1.ListNamespacedPodWithHttpMessagesAsync(configurationSettings.DeploymentNamespace, watch: true);

       await foreach (var (type, item) in podlistResp.WatchAsync<V1Pod, V1PodList>())
       {
           ...
       }
   }
   catch(){
   }
}
```

**Comment by brendandburns** [comment]
The above codewill not work properly. The reason for this is that you need to do an explicit List of the resources when the watch breaks.

There is a race where if a resource is created after the watch ends and before the next watch begins you will miss that resource.

The proper approach is:

```csharp
while (true) {
   var list = // list all resources here
   foreach (var item in list ) {
            ....
   }
   // watch resources here
}
```

**Comment by gunpuz** [comment]
@brendandburns  Seems that method `ListNamespacedPodWithHttpMessagesAsync` already lists existing resources and then gives back any new resources that are created.
Why do I need to list resources seperatly?

And in this example of yours, would not you miss any new resources between list and watch calls if you think that `ListNamespacedPodWithHttpMessagesAsync` does not list existing resources? Maybe i am missing something and you could provide more detailed example with methods you use?

Function name already says that - `ListNamespacedPod` + `WithHttpMessages`
```cs
var podlistResp = kubeClient.CoreV1.ListNamespacedPodWithHttpMessagesAsync(configurationSettings.DeploymentNamespace, watch: true);

```

**Comment by Kruti-Joshi** [comment]
@gunpuz , did you figure out how to stop this from happening? I have a watch code which randomly stops receiving any events and is stuck till I restart my service.

**Comment by tg123** [comment]
@Kruti-Joshi you can check if this is the cause
https://github.com/kubernetes-client/csharp/discussions/1099

**Comment by gunpuz** [comment]
@Kruti-Joshi, i think this issue went away when you "restart" the listener and listen again in a loop
