### ISSUE TITLE
V1Status not deserialized on DeleteNamespaceAsync

### ISSUE THREAD

**Issue by RogerioWagner** [kubernetes-client/csharp#1154]
**Describe the bug**
Just call the method on an existing namespace

**Kubernetes C# SDK Client Version**
`10.0.1`

**Server Kubernetes Version**
`1.23.5`

**Dotnet Runtime Version**
net7

**To Reproduce**
Call the DeleteNamespaceAsync with arguments:

ns: "existing namespace"
pretty: true
propagationPolicy: Foreground

![V1Status - Watch](https://user-images.githubusercontent.com/22862317/208921063-10c28f47-7fe8-40d0-aaf2-755b54d242f2.jpg)

**Expected behavior**
V1Status return object with most property values different of null

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: MacOS Ventura

**Comment by tg123** [comment]
10.0 is based on 1.26
seems does not work well with 1.23

see #824

**Comment by RogerioWagner** [comment]
Hi,

Before posting the issue I'd visited the #824, the reported issue is on deletion of a service, mine is deleting the namespace.

I've downgraded the client to v9.1.3 and observed the same behavior.

Do you think I should downgrade the client to a previous version?

I'll also ask to upgrade the cluster version to v1.26.x

**Comment by tg123** [comment]
could you please give 7.2 a shot?

**Comment by RogerioWagner** [comment]
I've evaluate a downgrade to 7.x but it will break the code, it was easier to upgrade the cluster to v1.25.4, so I give a try with client 9.1.3, the V1Status did not deserialized, the only HasObject property is set to true, no exception was raised; unfortunately I can't request a cluster upgrade to v1.26.x to try with client 10.x.
