### ISSUE TITLE
BadRequest: json: cannot unmarshal object into Go value of type jsonpatch.Patch with PatchNamespacedDeployment

### ISSUE THREAD

**Issue by bhadreshpanchal88** [kubernetes-client/csharp#1186]
**Describe the bug**
I am getting BadRequest response while updating the deployment image.
It was working fine with older version. I recently upgraded k8s client to 10.0.1

Here is the request json that I am sending,

{"operations":[{"value":"*****.azurecr.io/****/admin:2022.12.631.86618-release-windows2019","operationType":"Replace","path":"/Spec/Template/Spec/Containers/0/Image","op":"replace"}],"contractResolver":{}}

Response:

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"json: cannot unmarshal object into Go value of type jsonpatch.Patch","reason":"BadRequest","code":400}

**Kubernetes C# SDK Client Version**
`10.0.1`

**Server Kubernetes Version**
`1.24.6`

**Dotnet Runtime Version**
net6

**To Reproduce**

Try updating the deployment Image,

PatchNamespacedDeployment(V1Patch, Name, NamespaceName)

**Expected behavior**
It should update the deployment image on server

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: Linux
 - Environment: container
 - Cloud: Azure

**Additional context**

**Comment by tg123** [comment]
see #772
this is likely caused by json patch library 
you have to upgrade to jsonpatch.net or libraries support system.text.json

**Comment by bhadreshpanchal88** [comment]
> see #772 this is likely caused by json patch library you have to upgrade to jsonpatch.net or libraries support system.text.json

I have Microsoft.AspNetCore.JsonPatch v6.0.6 installed. 
Should I upgraded it to any more specific version you know ?

**Comment by tg123** [comment]
https://github.com/kubernetes-client/csharp/issues/772#issuecomment-1029287325
