### ISSUE TITLE
ListNamespacedEventAsync cannot use nvolvedObject.name in fieldSelector

### ISSUE THREAD

**Issue by zxyao145** [kubernetes-client/csharp#1199]
**Describe the bug**
When I use fieldSelector in ListNamespacedEventAsync, I got the error: `Operation returned an invalid status code 'BadRequest'`, and in the response, it outputs as follows:
```json
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"field label not supported: involvedObject.name","reason":"BadRequest","code":400}
```
When i use kubectl command it works fine:
![image](https://user-images.githubusercontent.com/24973084/218313255-765efd68-8216-4acd-ab93-e20bdcf0705b.png)

And if I switch to the [KubeClient library](https://github.com/tintoy/dotnet-kube-client), it works fine too, so I guess it might be a problem with kubernetes-client/csharp.

And my code is as follows:
```c#
await _kubernetes.EventsV1.ListNamespacedEventAsync(namespaceParameter: "default",fieldSelector: $"involvedObject.name={podName}")
```

**Kubernetes C# SDK Client Version**
10.0.31

**Server Kubernetes Version**
v1.26.1, and same exists on v1.24.2

**Dotnet Runtime Version**
net6

**To Reproduce**
Refer to the code above

**Expected behavior**
Filter events based on involvedObject.name

**KubeConfig**

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: Windows 10
 - Environment: local machine

**Additional context**

some stackTrace:
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'BadRequest'
         at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
         at k8s.AbstractKubernetes.k8s.IEventsV1Operations.ListNamespacedEventWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
         at k8s.EventsV1OperationsExtensions.ListNamespacedEventAsync(IEventsV1Operations operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, CancellationToken cancellationToken)
```

exception.Request:
```
https://172.17.169.68:6443/apis/events.k8s.io/v1/namespaces/default/events?fieldSelector=involvedObject.name%3Dapp-test-dev-74f58f9d6c-f7qp2
```

exception.Response:
```json
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"field label not supported: involvedObject.name","reason":"BadRequest","code":400}
```

**Comment by tg123** [comment]
hmm
maybe you could use corev1 if that is good enough to you

`involvedObject.name` should be `regarding.name` in new event api

https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/383-new-event-api-ga-graduation/README.md#backward-compatibility

**Comment by zxyao145** [comment]
> corev1

Thanks a lot,  `kubernetes.CoreV1.ListNamespacedEventAsync` works well with `involvedObject.name`, but throws then exception with `regarding.name`: 
```json
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"field label not supported: regarding.name","reason":"BadRequest","code":400}
```

I don't know if I should close this issue 😂

**Comment by tg123** [comment]
involvedobj == corev1 only
regardingobj == eventv1 only

that is why you get 400

**Comment by zxyao145** [comment]
Get it! Thanks a lot!
