### ISSUE TITLE
Create KubernetesClient.ModelConverter package

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/csharp#1223]
See: https://github.com/kubernetes-client/csharp/actions/runs/4336429133/jobs/7571709812

**Comment by tg123** [comment]
api key expired?
seems it expired last year in March too

**Comment by brendandburns** [comment]
It didn't expire (yet) but it didn't have the right privileges.

I have gone ahead and regnenerated the key and updated it in GH. Should be able to push now.
