### ISSUE TITLE
Preferred way of login into AKS cluster

### ISSUE THREAD

**Issue by wimeling** [kubernetes-client/csharp#1226]
We have been using the kubernetes client for deploying policies into the cluster. We have been using the Azure Auth provider to do so but this seems to be deprecated. The question is how do we no use the library to authenticate, I have been reading about Azure Kubelogin is that something that wee need to be using? 

            var clusterResourceGroup = await _subscriptionResource.GetResourceGroupAsync(resourceGroupName, cancellationToken);

            var managedCluster = await clusterResourceGroup.Value.GetContainerServiceManagedClusterAsync(clusterName,cancellationToken);

  var userCredentials = await managedCluster.Value.GetClusterUserCredentialsAsync(clusterName,cancellationToken: cancellationToken);

  var kubeConfigRaw = await KubernetesClientConfiguration.LoadKubeConfigAsync(new 
  MemoryStream(userCredentials.Value.Kubeconfigs.FirstOrDefault().Value));

      var authProvider = kubeConfigRaw.Users.Single().UserCredentials;

   authProvider.Config[access-token"] = authenticationToken.Token;
   authProvider.Config[expires-on"] = authenticationToken.ExpiresOn.ToUnixTimeSeconds().ToString();

            var config = KubernetesClientConfiguration.BuildConfigFromConfigObject(kubeConfigRaw);

            var client = new Kubernetes(config);

Is there any documentation on how to authenticate to a AKS cluster without using the Azure Auth provider ?

**Comment by brendandburns** [comment]
`kubelogin` is the preferred way to do login to AKS, it is an `exec` provider (https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/Authentication/ExecTokenProvider.cs)

There are some examples of valid configurations here:
https://github.com/Azure/kubelogin#exec-plugin-format

Please let us know if you run into any problems.

**Comment by tg123** [comment]
check if #1113 could help

**Comment by wimeling** [comment]
Hi Brendan and tg123,

Thank you for your response, based on the information you provided I was able to successfully get access to the AKS cluster thanks a lot.
