### ISSUE TITLE
Interactive shell support?

### ISSUE THREAD

**Issue by kibernetik542** [kubernetes-client/csharp#1238]
Is it any way to implement an interactive shell within a specific container in the pod.
Something understands /bin/bash.

I have an old code which recognizes sh -c command, by replacing to /bin/bash returns me error like:

**The server returned status code '404' when status code '101' was expected.**

My old code example:

   
    
      try
          {
            var list = new List<string> { "sh", "-c" };
            var preCommands = list.ToArray();
            var queryable =
                await client.WebSocketNamespacedPodExecAsync(request.Name, request.Namespace,
                        preCommands.Concat(request.Command), request.Container,
                        cancellationToken: cancellationToken)
                    .ConfigureAwait(false);

            var demux = new StreamDemuxer(queryable);
            demux.Start();
            var buff = new byte[16384];
            var stream = demux.GetStream(1, 1);
            var read = stream.Read(buff, 0, 16384);
            bool dataFound = false;
            byte[] newBuff = buff.Reverse().SkipWhile(point =>
            {
                if (dataFound) return false;
                if (point == 0x00) return true;
                else
                {
                    dataFound = true;
                    return false;
                }
            }).Reverse().ToArray();
            var str = Encoding.Default.GetString(newBuff);
            return str;
        }
        catch (Exception e)
        {
            throw new BadRequestException(e.Message);
        }
```

Simple commands works with this but /bin/bash commands not working.

**Comment by brendandburns** [comment]
404 is part of the web socket negotiation sequence and it indicates that either the resource doesn't exist, or (perhaps) that the Kubernetes API version that you are using has been deprecated and removed.

Can you verify that the Pod that you are trying to connect to actually exists?

If it does, what version of the client are you using? What version of the kubernetes server are you talking to?

Thanks

**Comment by kibernetik542** [comment]
> 404 is part of the web socket negotiation sequence and it indicates that either the resource doesn't exist, or (perhaps) that the Kubernetes API version that you are using has been deprecated and removed.
> 
> 
> 
> Can you verify that the Pod that you are trying to connect to actually exists?
> 
> 
> 
> If it does, what version of the client are you using? What version of the kubernetes server are you talking to?
> 
> 
> 
> Thanks


k8s version - 1.25.4
client version - 10.1.4

and yes before we tested all with kubectl and it works fine

**Comment by kibernetik542** [comment]
closing found answer in [this fix](https://github.com/kubernetes-client/csharp/issues/760)
