### ISSUE TITLE
PatchCertificateSigningRequestApprovalAsync is getting forbidden while using Inclusterconfig for kubernetes client

### ISSUE THREAD

**Issue by srinivasmummareddy** [kubernetes-client/csharp#1244]
**Describe the bug**
k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'Forbidden'\n   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)\n   at k8s.AbstractKubernetes.k8s.ICertificatesV1Operations.PatchCertificateSigningRequestApprovalWithHttpMessagesAsync(V1Patch body, String name, String dryRun, String fieldManager, String fieldValidation, Nullable`1 force, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)\n   at k8s.CertificatesV1OperationsExtensions.PatchCertificateSigningRequestApprovalAsync(ICertificatesV1Operations operations, V1Patch body, String name, String dryRun, String fieldManager, String fieldValidation, Nullable`1 force, Nullable`1 pretty, CancellationToken cancellationToken)\n  

**Kubernetes C# SDK Client Version**
e.g. `9.0.38`

**Server Kubernetes Version**
e.g.`v1.25.4+k3s1`-k3s flavor

**Dotnet Runtime Version**
e.g. net6

**To Reproduce**

**Expected behavior**
I need to patch existing csr for new signin certificate.

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: [ Linux]
 - Environmet-edge

**Additional context**
I have provided a patch  verb for the cluster role
I'm using JsonPatch.net for patching. 

`
        JsonDocument old = JsonSerializer.SerializeToDocument(readCert, serializeOptions);

        readCert.Status.Conditions = new List<V1CertificateSigningRequestCondition>()
        {
            new("True", "Approved", DateTime.UtcNow, DateTime.UtcNow, "This certificate was approved by k3s client", "Approve")
        };

        JsonDocument expected = JsonSerializer.SerializeToDocument(readCert, serializeOptions);

        JsonPatch patch = old.CreatePatch(expected);
        V1CertificateSigningRequest signedRequest = await client.CertificatesV1.PatchCertificateSigningRequestApprovalAsync(new V1Patch(patch, V1Patch.PatchType.JsonPatch), .userName);`

**Comment by srinivasmummareddy** [comment]
![image](https://user-images.githubusercontent.com/22257824/227271937-e2b0b8dd-794d-441b-8732-580787e955b1.png)
Have cross checked again whether serviceaccount I'm using for pod is having permissions or not.. Is there anything else I need to do?

**Comment by brendandburns** [comment]
Apologies if this is an obvious question, but are you certain that the pod is receiving the right serviceaccount? Have you tried logging into the pod and validating that the right token is present?

If that is the case, then you may need to instrument the code here: 
https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs

To make sure that it is loading correctly.

I have this vague feeling like k3s does something weird with their subject names, but I can't seem to find the specific issue. But you may want to examine the certificate that it is sending back.

Additionally, if you can validate that `kubectl` works correctly inside your pod, then it's definitely a bug in this library.

**Comment by srinivasmummareddy** [comment]
One more observation is that DeleteCertificateSigningRequestAsync,CreateCertificateSigningRequestAsync,ReadCertificateSigningRequestAsync methods are working as expected and only issue is with patchoperation,....

**Comment by tg123** [comment]
could you please paste `kubectl -v8 xxx` here
the sdk is simply sending `PATCH`.

i do not think server will return 403 if everything is the same as kubectl

**Comment by srinivasmummareddy** [comment]
@brendandburns  @tg123 
The issue has been resolved. The issue was bit unclear  with just forbidden message. There are many  resources service need to access to do csr approving and signing :)  

https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/

**Comment by tg123** [comment]
i still did not understand why kubectl works but sdk doesnt, any insight?
