### ISSUE TITLE
DeleteNamespacedPersistentVolumeClaim finishes earlier than the actual volume deletion

### ISSUE THREAD

**Issue by koureasstavros** [kubernetes-client/csharp#1246]
**Describe the bug**
I am using Kubernetes Client for .Net managing an Azure Kubernetes Cluster, this application has the ability to provision all necessary resources like config files, volumes, stateful-sets, ingresses, etc. So when I create the necessary resources everything execute as excepted. But, when I am deleting the resources, some of the steps are to call DeleteNamespacedPersistentVolumeClaim in order to delete also some Persistent Volumes. The code execution is finishing and if I enable the resources too quick then I throws an error because Volumes are still there (but int Terminating State).

Is there any way to make this function wait until truly the Persistent Volumes are deleted, without putting some manual fixes delays into my application's code?

**Kubernetes C# SDK Client Version**
`9.0.38`

**Server Kubernetes Version**
`1.23.15

**Dotnet Runtime Version**
. net6

**To Reproduce**
Provision Persistent Volume with client.CoreV1.CreateNamespacedPersistentVolumeClaim()
UnProvision Persistent Volume with client.CoreV1.DeleteNamespacedPersistentVolumeClaim()
Provision Persistent Volume with client.CoreV1.CreateNamespacedPersistentVolumeClaim()

**Expected behavior**
UnProvision function is ending before the actual Volume is deleted

Any ideas?

**Comment by tg123** [comment]
you have to do it yourself, sdk just provides raw api calls (for now)

**Comment by koureasstavros** [comment]
Sure, is not big deal, but I just wondering why the API Code does not doing that by default. So this comes from the raw API also.

**Comment by brendandburns** [comment]
PersistentVolumeClaims are independent of PersistentVolumes. Kubernetes is designed on purpose to be a loosely coupled system, and in this specific case, you can recreate a different PersistentVolumeClaim on an existing PersistentVolume, so their lifecycles are truly indepedent.

You can find a lot more details here:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

Closing this issue, since it is by design.
