### ISSUE TITLE
Strong named assemblies

### ISSUE THREAD

**Issue by jmuukka** [kubernetes-client/csharp#1252]
Is it possible to get NuGet packages that have signed assemblies? Our system prevents usage of unsigned assemblies.

I signed the packages myself, but since they depends on each other, compiler says that some type is in Models assembly which could not be found. There is something wrong with this procedure, either technical or logical, and it's error prone.

It would be preferred that we would not need this manual process at all and could just use the signed dlls. The signing the dlls is quite quick thing to do. We would prefer to get the signed versions soon.

I actually could do the work, and make a PR, if you could provide the .snk file.

**Comment by jmuukka** [comment]
Now I have the branch ready. It just needs your .snk and then I can update the public key in "InternalsVisibleTo".

**Comment by tg123** [comment]
strong name is no longer supported. see https://github.com/kubernetes-client/csharp/pull/535
