### ISSUE TITLE
Assemblies missing strong name signing

### ISSUE THREAD

**Issue by ofir-haviv** [kubernetes-client/csharp#1256]
**Describe the bug**
Our project uses strong name signing. While trying to compile with this nuget, I get the following errors:

##[error]CSC(0,0): Error CS8002: Referenced assembly 'KubernetesClient, Version=10.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
CSC : error CS8002: Referenced assembly 'KubernetesClient, Version=10.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [C:\__w\1\s\src\EKS\EKS.csproj]
##[error]CSC(0,0): Error CS8002: Referenced assembly 'KubernetesClient.Models, Version=10.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
CSC : error CS8002: Referenced assembly 'KubernetesClient.Models, Version=10.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [C:\__w\1\s\src\EKS\EKS.csproj]
##[error]CSC(0,0): Error CS8002: Referenced assembly 'KubernetesClient.Basic, Version=10.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
CSC : error CS8002: Referenced assembly 'KubernetesClient.Basic, Version=10.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [C:\__w\1\s\src\EKS\EKS.csproj]

This is blocker for us from using this nuget.

**Kubernetes C# SDK Client Version**
10.1.4

**Server Kubernetes Version**
N/A

**Dotnet Runtime Version**
net7

**To Reproduce**
Just compile with strong name signing.
https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name

**Expected behavior**
To be able to compile with strong name signing.

**KubeConfig**
N/A

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: N/A
 - Environment N/A
 - Cloud N/A

**Additional context**

**Comment by tg123** [comment]
may I know why you want strong name, it is not necessary

**Comment by ofir-haviv** [comment]
As for the why, I think that the official doc explains it better then me: https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named

But anyway, my company have a policy that all assemblies should have strong name. We want to take dependency on the KubernetesClient nuget, but since it's not strong name, it is making us issues, since all strong name assemblies should reference strong name assemblies.

I'll just add that strong name is very common in nugets. This is the first time I tried to use nuget that isn't strongly named. and I assume there will be more like me.

**Comment by ViktorHofer** [comment]
@tg123 please see https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md

> Because of the viral nature of strong-naming, it is recommended that publicly published .NET libraries are strong-named. Not strong-naming a .NET library excludes anyone who does need to strong-name their application or library from using it. Read more about .NET libraries and strong-naming in the [.NET Library Guidance](https://docs.microsoft.com/dotnet/standard/library-guidance/strong-naming).

We currently have a few components in the .NET stack that depend on KubernetesClient and are failing to compile because of the missing strong name key:

> CSC : error CS8002: Referenced assembly 'KubernetesClient, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
CSC : error CS8002: Referenced assembly 'KubernetesClient.Models, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

cc @eerhardt
