### ISSUE TITLE
DeleteNamespacedServiceAsync returns Service rather than Status

### ISSUE THREAD

**Issue by GilchristT** [kubernetes-client/csharp#1260]
This has been asked before in [#767](https://github.com/kubernetes-client/csharp/issues/767). The response there was that this was by design but it seems incongruous with similar commands.

`IKubernetes.CoreV1.DeleteNamespacedServiceAsync()` has a return type of `V1Service?` whereas the equivalent command for other kinds e.g., `NetworkingV1.DeleteNamespacedIngressAsync()` or `AppsV1.DeleteNamespacedDeploymentAsync()` have a return type of `V1Status?` which makes more sense to me.

As best I can tell the `V1Service` response doesn't give any sort of indicator that the delete operation succeeded or failed and the only way to check for success is to search for the service again. Am I missing a trick?

The response to the original query mentioned the change happened in 1.22 which I'm assuming is the Kubernetes version rather than the C# SDK but the OP seemed to indicate that older versions of the SDK returned a status result?

**Kubernetes C# SDK Client Version**
`10.1.19`

**Server Kubernetes Version**
`1.24.9 (AKS)`

**Dotnet Runtime Version**
`Dotnet 7`

p.s. I wasn't sure of the etiquette with regard to there already being a post on the issue but it being closed i.e. should I have commented on it rather than opening a new issue. Apologies if I should have done that.

**Comment by tg123** [comment]
everything is defined by swagger
https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec

maybe we can discus in api sig
