### ISSUE TITLE
[documentation request] add example: watch customresource (and handle timeouts)

### ISSUE THREAD

**Issue by lknite** [kubernetes-client/csharp#1298]
**Describe the bug**
There seems to be some inconsistency around watching a CRD, including an example would help to resolve confusion.

**Inconsistency**
- Watch will fail after a timeout, what's the right way to handle this to get things going again?
- Will the example below fully relist all items before watching, or will it pick back up where it left off using resourceVersion?  (documenting an example with a comment letting us know will inform all future folks who want to watch a CRD instance)
- If the below doesn't pick back up, how to implement such that it does?
- I found an example which uses resourceVersion (though not with a custom resource), maybe we need to do something similiar in csharp?  Or does using generic like below handle picking back up with the last resourceVersion automatically?  (https://www.baeldung.com/java-kubernetes-watch)

**Example**
```
            var generic = new GenericClient(kubeclient, group, version, plural);

            while (true)
            {
                try
                {
                    await foreach (var (type, item) in generic.WatchNamespacedAsync<CrdInvite>("gge"))
                    {
                        Console.WriteLine("(event) [" + type + "] " + plural + "." + group + "/" + version + ": " + item.Metadata.Name);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Exception occured while performing 'watch': " + ex);
                }
            }
```

In the kubernetes documentation it suggests handling the watch timeout like so, how does the kubernetes client library do it?

![image](https://github.com/kubernetes-client/csharp/assets/92187614/714eadb9-eef0-4225-84dd-205f28a94fda)

**Comment by IvanJosipovic** [comment]
Check out this repo, it's a informer implementation. If you put a loop around the Start code it should do what you want.

https://github.com/microsoft/reverse-proxy/tree/main/src/Kubernetes.Controller/Client

**Comment by lknite** [comment]
I think there may a "most effective" way to write this code, but not sure what that'd be.  In anycase, everything's working good enough for now to close out this ticket.
