### ISSUE TITLE
GenericClient's List method to not accept selectors (eg. labelSelector and fieldSelector)

### ISSUE THREAD

**Issue by nicholass-alcidion** [kubernetes-client/csharp#1308]
**Describe the bug**

With the removal `GenericKubernetesApi` there is no way to filter the list of custom resources using field or label selectors.

**Kubernetes C# SDK Client Version**
9+

**Server Kubernetes Version**
N/A (limitation in published API methods)

**Dotnet Runtime Version**
N/A (limitation in published API methods)

**To Reproduce**
No API Avalaible to apply selectros to `GenericClient.ListAsync` or `GenericClient.ListNamespacedAsync`

**Expected behavior**
Optional paramters or method overload that accept selector parameters

**KubeConfig**
N/A (limitation in published API methods)

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: Linux
 - Environment: Container
 - Cloud: Azure/Amazon/GCP/on-prem

**Additional context**
N/A (limitation in published API methods)

**Comment by tg123** [comment]
PR is welcomed

**Comment by prochnowc** [comment]
FYI:
Since #1372 was merged, there is no need to use GenericClient anymore.
All CustomObjectOperations now accept a generic type parameter.

**Comment by tg123** [comment]
close as #1372 merged
