### ISSUE TITLE
Using System.Text.Json Source Generator

### ISSUE THREAD

**Issue by IvanJosipovic** [kubernetes-client/csharp#1309]
I'm playing with utilizing the Source Generator approach in the Json Serializer in order to optimize performance of informers.

Benefits of this approach:
![image](https://github.com/kubernetes-client/csharp/assets/9521987/247cfd2a-faca-4482-8b18-deb31d660b8f)

See these two docs:
- https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/
- https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation

Unfortunately, I've hit a snag due to the existing Json converters being internal.

![image](https://github.com/kubernetes-client/csharp/assets/9521987/0e9efa0d-1c97-4f6f-82e8-6cb5562ac4b7)

Options:
1. Make existing converters public
2. Add Source Generation to this library
   1. It appears fairly simple to implement
   2. 
            KubernetesJson.AddJsonOptions(x => x.TypeInfoResolver = JsonTypeInfoResolver.Combine(SourceGenerationContext.Default, JsonSerializerOptions.Default.TypeInfoResolver));

            [JsonSerializable(typeof(V1Node))]
            [JsonSerializable(typeof(V1Namespace))]
            .. add all other types
            internal partial class SourceGenerationContext : JsonSerializerContext
            {
            }

 
 Thoughts?
```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-client/csharp/pull/1417
```

**Comment by tg123** [comment]
it is so cool, it is worth to have those converters public

**Comment by tg123** [comment]
merge into #1395
