### ISSUE TITLE
(question) assist with retrieving status values on a crd

### ISSUE THREAD

**Issue by lknite** [kubernetes-client/csharp#1347]
I'm using the [CustomResourceDefinition](https://github.com/kubernetes-client/csharp/blob/master/examples/customResource/CustomResourceDefinition.cs) template as shown in the examples, all code around crds is working well.

Recently I've attempted to get some status values from a clusterapi resource:
```
status:
  <snip>
  controlPlaneReady: true
  infrastructureReady: true
  observedGeneration: 2
  phase: Provisioned
```

My Crd has code like so:
```
    public class CrdCluster : CustomResourceDefinitions.CustomResource<CrdClusterSpec, CrdClusterStatus>
    {
        public override string ToString() { echo ""; }
    }

    public class CrdClusterSpec
    {
        [JsonPropertyName("asdf")]
        public string asdf { get; set; }
    }

    public class CrdClusterStatus : V1Status
    {
        [JsonPropertyName("infrastructureReady")]
        public bool infrastructureReady { get; set; }
        [JsonPropertyName("controlPlaneReady")]
        public bool controlPlaneReady { get; set; }
        [JsonPropertyName("phase")]
        public string phase { get; set; }
    }
```

Yet, in my code when I have an instance of the crd, 'cluster.CStatus' is null.

What am I missing?  The 'CStatus' is supposed to be the representation of the 'status' right?

## update ##
I modified the CustomResourceDefinition.cs from having 'CStatus' to 'Status' and now everything is working as expected.  So, why was it CStatus instead of Status?

**Comment by lknite** [comment]
I think I read your mind or something just tested that out and it worked, maybe the example needs to be updated.  If CStatus is right in the example, am trying to understand what that's all about ...

**Comment by tg123** [comment]
seems it is a bug

**Comment by lknite** [comment]
I'll submit a pull request

**Comment by lknite** [comment]
Pull request submitted which will resolve this issue.  https://github.com/kubernetes-client/csharp/pull/1348
