### ISSUE TITLE
Port exec-based client auth provider to DotNet client

### ISSUE THREAD

**Issue by dbenhur** [kubernetes-client/csharp#135]
With 1.10, this exec-based client auth credential provider alpha feature was introduced  [kubernetes/features#541](https://github.com/kubernetes/features/issues/541) for client-go.  Exec-based auth plugin should be supported by this DotNet client in addition to client-go. Umbrella issue: [kubernetes#62185](https://github.com/kubernetes/kubernetes/issues/62185)

/kind feature
/sig api-machinery

**Comment by tintoy** [comment]
If it helps at all, I implemented this a while back for [KubeClient](https://github.com/tintoy/dotnet-kube-client). Happy to contribute my implementation if it'd be useful.

https://github.com/tintoy/dotnet-kube-client/blob/27926d62bf48897837042b624412889fb7b5cdb1/src/KubeClient.Extensions.KubeConfig/K8sConfig.cs#L195
https://github.com/tintoy/dotnet-kube-client/blob/27926d62bf48897837042b624412889fb7b5cdb1/src/KubeClient/KubeApiClient.cs#L146
https://github.com/tintoy/dotnet-kube-client/blob/27926d62bf48897837042b624412889fb7b5cdb1/src/KubeClient/MessageHandlers/CommandBearerTokenHandler.cs

CC: @brendandburns

**Comment by KyleGobel** [comment]
Would be nice to have an implementation of this.  I'm not sure of a work around to connect to EKS (fairly popular I think?) out-of- cluster without it?
