### ISSUE TITLE
LeaderElector does not write logs or exceptions during failure

### ISSUE THREAD

**Issue by vrnmthr** [kubernetes-client/csharp#1390]
**Describe the bug**
I was using the LeaderElector with a LeaseLock, but failed to set RBAC on my app to create/read leases (this is not present in the default service account). This means that this piece of code was failing, probably with a different HttpStatusCode. The end result is that the LeaderElector basically "does nothing" infinitely, with no logs and no exception thrown. 

```
LeaderElectionRecord oldLeaderElectionRecord = null;
            try
            {
                oldLeaderElectionRecord = await l.GetAsync(cancellationToken).ConfigureAwait(false);
            }
            catch (HttpOperationException e)
            {
                if (e.Response.StatusCode != HttpStatusCode.NotFound)
                {
                    return false;
                }
            }
```

This is not intuitive behavior, and since there is no documentation for this that includes how to setup RBAC, it makes debugging issues difficult.

**Kubernetes C# SDK Client Version**
11.0.44

**Server Kubernetes Version**
e.g. `1.21`

**Dotnet Runtime Version**
net6

**To Reproduce**
Start leader elector without required RBAC in a cluster

**Expected behavior**
Either log error, or throw exception

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: Linux
 - Environment: Container
 - Cloud: Azure

**Additional context**

**Comment by tg123** [comment]
throw for other 4xx error?

**Comment by mmihalikcs** [comment]
I believe im running into the same issue and attempting to use the following RBAC, but doesnt seem to be working:

`Name:         expense-dev-leases
Labels:       app=expense
              app.kubernetes.io/instance=expense-dev
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=expense
              app.kubernetes.io/version=1.0.0
              helm.sh/chart=expense-0.1.1
Annotations:  meta.helm.sh/release-name: expense-dev
              meta.helm.sh/release-namespace: expense
PolicyRule:
  Resources                   Non-Resource URLs  Resource Names  Verbs
  ---------                   -----------------  --------------  -----
  leases.coordination.k8s.io  []                 []              [*]`

**Comment by tg123** [comment]
hope onerr callback helps
currently, no logger defined in sdk
