### ISSUE TITLE
Support for Mono/Xamarin

### ISSUE THREAD

**Issue by JonJam** [kubernetes-client/csharp#140]
I am trying to use this client library in a Xamarin app, but I having issues due to HttpClientHandler.ServerCertificateCustomValidationCallback in Kubernetes.ConfigInit.

This throws a NotImplementedException in Xamarin as Mono doesn't implement it, see https://github.com/mono/mono/blob/master/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs.

**Comment by brendandburns** [comment]
I'm happy to take a PR to optionalize this on Mono, but that functionality is needed for most kubernetes configs.

**Comment by JonJam** [comment]
PR Merged

**Comment by tg123** [comment]
Hi @JonJam 
I am trying to clean targets

Could you please confirm `netstandard2.0` works fine with your app?
I tested locally but I am new to xamarin not quite sure if I am doing right.

Testcases would be great

**Comment by JonJam** [comment]
Hi @tg123,

The source for my app is here: https://github.com/JonJam/kubemob, although I am no longer maintaining it.

I can confirm it does work with netstandard2.0 as I am referencing this from a netstandard2.0 shared class library.
