### ISSUE TITLE
non-generic Watch for CRD's without Type

### ISSUE THREAD

**Issue by mmercan** [kubernetes-client/csharp#1413]
**Describe the bug**

I have several CRDs which I don't have types.  I have a simple function it lists them as JToken then, rest of the application validate the configuration over JsonPath base rule engine.

`

    public async Task<List<JToken>> ListClusterCustomObject(string Group, string Version, string Plural)
    {
        var result = await _client.CustomObjects.ListClusterCustomObjectWithHttpMessagesAsync(Group, Version, Plural);

        var jToken = JToken.Parse(result.Body.ToString());
        var res = jToken?.SelectToken("items")?.ToList();
        if (res == null)
        {
            res = new List<JToken>();
        }
        return res;
    }
`

I am trying to create a similar function over Watch I have tried several methods and I have failed.
is there any method I can use for Watch which can return Response Body then I can convert it to JToken ?
or do you have any suggestion on how to work with Watch without having POCO classes for the CRD types.

**Kubernetes C# SDK Client Version**
e.g. `10.0.31`

**Server Kubernetes Version**
e.g. `1.26.3`

**Dotnet Runtime Version**
e.g. net7

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: [Windows 10]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by IvanJosipovic** [comment]
JToken is a Newtonsoft.Json object, this library uses System.Text.Json, you can try using JsonDocument and JsonElement.

Alternatively, you can generate types for the CRDs using https://github.com/IvanJosipovic/KubernetesCRDModelGen

**Comment by mmercan** [comment]
If I could receive the result.Body (string) over the Watch I could convert it to JToken  inside of the my method 
JsonDocument and JsonElement still doesn't support JsonPath (https://github.com/dotnet/runtime/issues/31068)
is there any way of working with Watch without Deserialization ?

**Comment by tg123** [comment]
`.ListClusterCustomObjectWithHttpMessagesAsync<dynamic>`?

**Comment by mmercan** [comment]
Thanks for everyone's help and suggestions, even if I have to take JsonElement  and convert to JToken 
this method solved my issues.

        Action<WatchEventType, object> onEvent = (a, b) =>
        {
            if (b is JsonElement content)
            {
                JToken token = JToken.Parse(content.ToString());
                Console.WriteLine(token.ToString());
            }
        };
        Action<Exception>? onError = null;
        Action? onClose = null;


        var result = await client.CustomObjects.ListClusterCustomObjectWithHttpMessagesAsync(Group, Version, Plural, watch: true);
        await Task.FromResult(
                     result.Watch(onEvent, onError, onClose)
         );
