### ISSUE TITLE
KubernetesClient & KubernetesClient.Models diverged

### ISSUE THREAD

**Issue by buehler** [kubernetes-client/csharp#1424]
**Describe the bug**
Recently, the KubernetesClient version 12.1.1 came out. However, the base models (KubernetesClient.Models) still are on version 12.0.16. This creates an issue when referencing both packages.

**Expected behavior**
Both packages should be on the same version or even better:  KubernetesClient depends on the Models package to create a proper dependency. This would allow package authors to create "abstractions" packages without any issues when upgrading the Kubernetes Client package.

Regards

**Comment by tg123** [comment]
see #1407 for reason. 
let us know if you can create ext  using KubernetesClient  only

**Comment by buehler** [comment]
Hey @tg123 
Thanks for the prompt response!

Since KubernetesClient relies on net6.0 and newer, I cannot create a netstandard2.0 or 2.1 library with only abstractions in it.

I actually only really need "IKubernetesObject<V1ObjectMeta>" and "IKubernetesObject".

But yeah, maybe I can drop the netstandard idea again in favor of newer framework support.

(https://github.com/buehler/dotnet-operator-sdk/tree/main/src/KubeOps.Abstractions is the source of my troubles)

I loved the idea of KubernetesClient.Models to actually only have all models in that package. But I can totally understand the move ;-)

What do you think about the matter? I could totally drop netstandard and just use .net, however this was a more or less requested feature in the SDK package.

**Comment by tg123** [comment]
you can use KubernetesClient.Classic it contains everything for netstandard2.0

**Comment by buehler** [comment]
Ty :-)
