### ISSUE TITLE
/watch APIs seems missing

### ISSUE THREAD

**Issue by qmfrederik** [kubernetes-client/csharp#146]
The Kubernetes API specifies a couple of routes, such as [watchNamespacedPod ](https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json#L8871) ([`/api/v1/watch/namespaces/{namespace}/pods/{name}`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#watch-64)) which appear to be missing from the C# client.

In my scenario, I want to make sure a delete operation has been executed, by starting a watcher for that pod, sending a delete request, and waiting for a notification to arrive conforming the pod has been deleted.

Is there a specific reason these APIs cannot be auto-generated, and do the need to be generated manually (happy to send a PR in that case), or did I just not see them?

**Comment by tg123** [comment]
watch pod example <https://github.com/kubernetes-client/csharp/blob/master/examples/watch/Program.cs>
might help

those ops are removed via
<https://github.com/kubernetes-client/gen/blob/master/openapi/preprocess_spec.py#L79
>

cc @mbohlool

**Comment by qmfrederik** [comment]
Ah, that explains, though it's still odd. #147 tries to bring them back. I'm specifically looking for a way to watch individual objects.

Use case here is: 
1. watch pod
2. send delete request for that pod
3. wait for the watcher to notify me that the delete has completed
4. proceed (e.g. create a new pod with the same name,...)

**Comment by brendandburns** [comment]
I think Swagger can't really represent the watch operation adequately, so it's removed so as not to confuse the client...

**Comment by qmfrederik** [comment]
This has been fixed recently
