### ISSUE TITLE
Cannot connect to Azure kubernetes cluster using c# sdk 

### ISSUE THREAD

**Issue by Ranjit-Kumar-Konjeti** [kubernetes-client/csharp#1480]
**Describe the bug**

**Kubernetes C# SDK Client Version**
e.g. `12.1.1`

**Server Kubernetes Version**
e.g. `1.25.5`

**Dotnet Runtime Version**
e.g. net6

**To Reproduce**
Following this doc: https://github.com/kubernetes-client/csharp/blob/master/README.md
var namespaces = client.CoreV1.ListNamespace();
foreach (var ns in namespaces.Items) {
    Console.WriteLine(ns.Metadata.Name);
    var list = client.CoreV1.ListNamespacedPod(ns.Metadata.Name);
    foreach (var item in list.Items)
    {
        Console.WriteLine(item.Metadata.Name);
    }
}

The above code does not work on the line : var namespaces = client.CoreV1.ListNamespace();
Code/visual studio 2022 hangs there 
I am using this c# kubernetes client library with client.CoreV1.ListNamespace(); I tried setting KUBECTL_PROXY and updating the host to http: //proxyip:8001 and I am not using kube login. code execution stops at the above line and my visual studio 2022 hangs and I see messages thread exited in the output window. I can get all the details by connecting to cluster using kubectl commands in the terminal window. but not through c# libraray. 

**Expected behavior**
expect to list namespaces

**KubeConfig**
normal AKS kube config file , which I can be able to connect using kubectl

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: [Windows]
 - Environment [desktop application]
 - Cloud [Azure]

**Additional context**

**Comment by tg123** [comment]
could you please paste any error you saw?

**Comment by Ranjit-Kumar-Konjeti** [comment]
I do not see any error, the code just hangs and I just see messages with thread exited in output window

**Comment by tg123** [comment]
kubelogin in kubeconfig?

**Comment by Ranjit-Kumar-Konjeti** [comment]
kuebconfig

**Comment by tg123** [comment]
i mean are you using kubelogin?
you can check kubeconfig

most likely caused by waiting for stdin

**Comment by Ranjit-Kumar-Konjeti** [comment]
I am not using kubelogin. I am just using kubeconfig to connect to cluster and check the namespace

**Comment by Ranjit-Kumar-Konjeti** [comment]
what should i do if the process is waiting for stdin?

**Comment by tg123** [comment]
could you please share your kubeconfig? **remove all sensitive info before paste**

**Comment by Ranjit-Kumar-Konjeti** [comment]
`apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
	xxx
    server: xxxx
  name: 
- cluster:xxx
    certificate-authority-data:
	xxxx
    server: xxxx
  name: 
contexts:
- context:
    cluster:xxxx 
    user: clusterAdmin_XXXXX
  name: 
- context:
    cluster: xxxx
    user: clusterAdmin_XXXXX
  name: XXXX-admin
current-context: XXXX-admin
kind: Config
preferences: {}
users:
- name: clusterAdmin_XXXXX
  user:
    client-certificate-data: 
	xxxx
    client-key-data: 
	xxxxx
    token:xxxx`

**Comment by Ranjit-Kumar-Konjeti** [comment]
any update here ? @tg123

**Comment by tg123** [comment]
cant repro, could you please do a dump to see what stuck?

**Comment by Ranjit-Kumar-Konjeti** [comment]
exactly same place where my code is stuck too. I am totally blocked by this.

**Comment by tg123** [comment]
please see #1523, i added an example and the code was used for long time in production env

**Comment by nithinbandaru1** [comment]
@tg123 The example you provided is using `command: {kubelogin}`. Here the scenario looks different.

**Comment by nithinbandaru1** [comment]
Well this issue make this software un-usable for like heavy number of users now a days. This fix is quite important!!

**Comment by treyhendon** [comment]
I've used this SDK in AKS for years with no issues creating my client - starting back in .net 5, through .net 6, and now .net8.

My only difference to building the config from file is that I don't put my path explicitly in as a parameter, I allow the system default kube context to be passed in (which I think is the same file referenced earlier in this thread).

My app has env var flags to flip from in-cluster to local file, so it's in a helper, but here's the code that loads the config from kube context (for local debugging primarily): https://github.com/RedSailTechnologies/kube-status/blob/953045099095a75a3a5467dfbfdc30dcb02bf7df/src/Helper.cs#L42

**Comment by listentorick** [comment]
So, I had the same issue. 

I switched to the async variant:

var namespaces = await client.CoreV1.ListNamespaceAsync();

This exposed an error:

HttpOperationException: Operation returned an invalid status code 'Forbidden', response body {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \"guid \" cannot list resource \"namespaces\" in API group \"\" at the cluster scope: User does not have access to the resource in Azure. Update role assignment to allow access.","reason":"Forbidden","details":{"kind":"namespaces"},"code":403}
