### ISSUE TITLE
Suggestion: Create objects from yaml without knowing the type

### ISSUE THREAD

**Issue by umerkle** [kubernetes-client/csharp#1485]
Currently you have the possibility to load objects from yaml-string with `KubernetesYaml.LoadAllFromString` and then cast the objects and create them in your cluster, or alternative you can use `KubernetesYaml.Deserialize<ObjectType>`.

But in both cases, you need to know the 'Kind' of the object(s).

Wouldn't it be cool, to be able to just load and create objects from yaml just like `kubectl apply` does?

**Comment by tg123** [comment]
i believe you are looking for 
https://github.com/kubernetes-client/csharp/issues/1215

**Comment by umerkle** [comment]
Hm, maybe...

I tried to infer from infos from the yaml to the right api group get that via reflection and also get the create method via reflection. Last one is easy, because the schema of the method name is always the same. It's just about the api group part.
Seems i can live with that for now.
