### ISSUE TITLE
LeaderElection - lack of information

### ISSUE THREAD

**Issue by rudolphgatt** [kubernetes-client/csharp#1492]
In a particular project we are using LeaderElection via Kubernetes C# client. For some reason no leader was being elected and the application was not logging any relevant information.

The root cause was lack of permissions for the endpoints resource. After doing some debugging I managed to access the following exception:
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints \"leaderendpoint\" is forbidden: User \"system:serviceaccount:app-XXX-dev:XXX\\" cannot get resource \\"endpoints\\" in API group \\"\\" in the namespace \\"app-XXX-dev\\"","reason":"Forbidden","details":{"name":"leaderendpoint","kind":"endpoints"},"code":403}
```
I suggest to remove the following if condition so that the onError event is always triggered:
https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/LeaderElection/LeaderElector.cs#L162

**Comment by tg123** [comment]
#1420 ?
