### ISSUE TITLE
GenericClient.WatchAsync/WatchNamespacedAsync ignore method parameters

### ISSUE THREAD

**Issue by alex-zyl** [kubernetes-client/csharp#1499]
**Describe the bug**

**Kubernetes C# SDK Client Version**
`13.0.1`

**Server Kubernetes Version**
`1.23.0`

**Dotnet Runtime Version**
net8

**To Reproduce**

**Expected behavior**
[WatchAsync](https://github.com/kubernetes-client/csharp/blob/b198b026de27dc8af5ee3a4c5eddae64b4c9d77d/src/KubernetesClient/GenericClient.cs#L115)
[WatchNamespacedAsync](https://github.com/kubernetes-client/csharp/blob/b198b026de27dc8af5ee3a4c5eddae64b4c9d77d/src/KubernetesClient/GenericClient.cs#L122)
Both methods accept `onError` callback and cancellation token as parameters but they're not later passed into [underlying watcher](https://github.com/kubernetes-client/csharp/blob/b198b026de27dc8af5ee3a4c5eddae64b4c9d77d/src/KubernetesClient/GenericClient.cs#L119C1-L119C1)

Expected
```
return respTask.WatchAsync<T, T>(onError, cancellationToken);
```

**KubeConfig**
not relevant

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 not relevant

**Additional context**

**Comment by tg123** [comment]
good catch, could you please send a pr to fix it?
