### ISSUE TITLE
upload KubernetesClient.Aot and deprecated KubernetesClient.Basic KubernetesClient.Models 

### ISSUE THREAD

**Issue by tg123** [kubernetes-client/csharp#1508]
sync 
https://github.com/kubernetes-client/csharp/pkgs/nuget/KubernetesClient.Aot
to nuget

deprecate KubernetesClient.Basic KubernetesClient.Models  as they are merged to main package

**Comment by guillaume-chervet** [comment]
hi @tg123 , 
I need it :)
without beta package, i cannot test it !

**Comment by brendandburns** [comment]
This was just pushed to nuget.org

**Comment by brendandburns** [comment]
https://www.nuget.org/packages/KubernetesClient.Aot/13.0.12

**Comment by guillaume-chervet** [comment]
Thank you very much!
