### ISSUE TITLE
Add static Kind and ApiVersion properties on generated model classes

### ISSUE THREAD

**Issue by qmfrederik** [kubernetes-client/csharp#151]
It would be super useful if generated classes could have a static `Kind` and `ApiVersion` property.

For example, right now I had to do:
```
if(genericObject.Kind == "Status")
{
    var status = SafeJsonConvert.DeserializeObject<V1Status>(json);
}
```

where `Status` is a magic value I had to introduce.

It would be great if I would be able to just do:
```
if(genericObject.Kind == V1Status.Kind)
{
    var status = SafeJsonConvert.DeserializeObject<V1Status>(json);
}
```

making the code a bit more explicit and allowing me to bypass the need for a magic constant.

Is this something the code generator could do?

**Comment by brendandburns** [comment]
Maybe? Swagger doesn't really represent this kind of stuff well, see the discussion here:

https://github.com/OAI/OpenAPI-Specification/issues/1313

We'd have to post-process it on, similar to what you are doing with watch, or add an Enum to the swagger spec.

**Comment by qmfrederik** [comment]
#152 fixed this
