### ISSUE TITLE
Calls over WebSockets don't handle error messages

### ISSUE THREAD

**Issue by qmfrederik** [kubernetes-client/csharp#153]
The `StreamConnectAsync` method which sets up a WebSocket connection to the Kubernetes API server doesn't handle error messages very well.

When you send an invalid request - such as `exec` or `attach`,  the server responds with a HTTP 400 Bad Request. However, the WebSocket implementation in .NET Core doesn't give you access to the HTTP body when a request fails - see https://github.com/dotnet/corefx/issues/29163.

An option is to detect the exception during the WebSocket connection setup, and do a new HTTP GET which should return the same HTTP 400 Bad Request, which can then be parsed.

**Comment by tintoy** [comment]
I've been meaning to switch us over to `HttpSocketHandler`, perhaps this could be done as part of that work?

**Comment by tintoy** [comment]
We have access to the response message in our custom connection code, so I can surface it from there. Do we have and Exception type which can expose the response message?

**Comment by qmfrederik** [comment]
This has been fixed recently
