### ISSUE TITLE
Json serialization exception in .net8

### ISSUE THREAD

**Issue by AnqiLi6** [kubernetes-client/csharp#1531]
**Describe the bug**
I got the following exception when calling `public static async Task<V1Secret> ReplaceNamespacedSecretAsync(this ICoreV1Operations operations, V1Secret body, string name, string namespaceParameter)` in .net8. However, when I switch to .net7, this error goes away. I have to target .net8. How to make this API work in .net8?

Unhandled exception. System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property

**Kubernetes C# SDK Client Version**
e.g. `13.0.1`

**Server Kubernetes Version**
e.g. `1.27.7`

**Dotnet Runtime Version**
e.g. net8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by WeihanLi** [comment]
Trim/AOT publish?
https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-8/#disabling-reflection-defaults

**Comment by AnqiLi6** [comment]
^this resolves it. Thanks!
