### ISSUE TITLE
Memory Leak with aot package ListDeployments and ListStatefulSet

### ISSUE THREAD

**Issue by guillaume-chervet** [kubernetes-client/csharp#1539]
**Describe the bug**
SlimFaas is calling ListDeployments and ListStatefulSet every Second (in the futur we will use watch). I think of memory leak because memory increase without ending.
Previous version worked on production without any crash with 180Mo of RAM set and the same code. The only change is the switch to AOT packages.

If I remove calls, the memory keep very stable.

https://github.com/AxaFrance/SlimFaas/blob/main/src/SlimFaas/ReplicasSynchronizationWorker.cs
https://github.com/AxaFrance/SlimFaas/blob/main/src/SlimFaas/Kubernetes/KubernetesService.cs

All RAM goes down in the graph bellow are OOM Killed.
![image](https://github.com/kubernetes-client/csharp/assets/52236059/141a4e93-d19d-4d64-b741-08881ea50245)

**Kubernetes C# SDK Client Version**
"KubernetesClient.Aot" Version="13.0.12"

**Dotnet Runtime Version**
.NET 8

**Comment by WeihanLi** [comment]
Is it possible to analyze some memory info from a dump?

Think the `HttpRequestMessage`/`HttpResponseMessage` and the `HttpContent` should be disposed, maybe we could try to add `using` for them firstly

![image](https://github.com/kubernetes-client/csharp/assets/7604648/d799a286-b16b-4f0f-a06e-d8990f261485)

**Comment by guillaume-chervet** [comment]
Hi fixed it in my side by this commit https://github.com/AxaFrance/SlimFaas/commit/d71b2ba065f416ae22bd0340407c928e9226e051

But it is still a bug it seem dispose does not dispose well.

I will try to memory dump.

**Comment by tg123** [comment]
yes dump please
i will try to repo by calling list

**Comment by guillaume-chervet** [comment]
I had a add week,  i will try to do it next week!

**Comment by tg123** [comment]
i ran the load test last weekend for whole afternoon, but did not see any leak.
code is simple

for(;;) { listdeployment; sleep 5s}

**Comment by tg123** [comment]
my test code
```
using k8s;

var config = KubernetesClientConfiguration.BuildDefaultConfig();
IKubernetes client = new Kubernetes(config);
Console.WriteLine("Starting Request!");


for (; ;){
    var list = client.AppsV1.ListDeploymentForAllNamespaces();
    foreach (var item in list.Items)
    {
        Console.WriteLine(item.Metadata.Name);
    }

    Thread.Sleep(5000);
    GC.Collect();
}


```

**Comment by guillaume-chervet** [comment]
Hi @tg123 @WeihanLi 

I was creating disposing a new Kubernetes client at each iteration.

**Comment by guillaume-chervet** [comment]
I still have now a tigth memory leak.
10 Mo in 2 productions week. But i have to investigate to know the source.

**Comment by tg123** [comment]
![image](https://github.com/kubernetes-client/csharp/assets/170430/ea3f0774-a653-45a1-907a-bf64b4ab8259)

**Comment by guillaume-chervet** [comment]
I still have now a tigth memory leak.
10 Mo in 2 productions week. But i have to investigate to know the source.

**Comment by guillaume-chervet** [comment]
hi @tg123 , I still have the problem with the latest verison by creating a new kubernetes client every time =>
![image](https://github.com/kubernetes-client/csharp/assets/52236059/6dbc9b5c-484e-4973-959a-b0069ad66416)

with IKubernetes client = new Kubernetes(config);

client.Dispose();

every seconds

**Comment by tg123** [comment]
@guillaume-chervet could you please do a mem dump so we can debug where is leaking

**Comment by guillaume-chervet** [comment]
I will as soon as i can @tg123 very sorry for the delay

**Comment by guillaume-chervet** [comment]
Thank you very much for your help and answers @tg123
