### ISSUE TITLE
Can not access /metrics endpoint using the  IKubernetes.HttpClient. Restults in Unauthorized access. RBAC settings are correct

### ISSUE THREAD

**Issue by sfahadrizvi** [kubernetes-client/csharp#1556]
**Describe the bug**
I am trying to access the /metrics endpoint from a service running inside a pod. I could not find any API to access the /metrics endpoint so I am using the HttpClient from the Kubernetes object. The Kubernetes object is initialized correctly.
When I try to access the /metrics endpoint using
`client.SendAsync(new HttpRequestMessage(HttpMethod.Get, endpoint), ct)` 
I get a 401. Inspecting the headers of the request I see that it has no token.

If I manually create a token from kubectl and hardcode that token in the Header `Authorization: Bearer ...` the service works fine until the token expires. Which shows the RBAC is setup correctly

Is there a way to get the token from the Kubernetes controller. I could not find any documentation to use the API to create a new token at runtime

**Comment by tg123** [comment]
see how to use client
https://github.com/kubernetes-client/csharp/discussions/1216

native metrics
https://github.com/kubernetes-client/csharp/blob/master/examples/metrics/Program.cs

**Comment by sfahadrizvi** [comment]
> see how to use client #1216
> 
> native metrics https://github.com/kubernetes-client/csharp/blob/master/examples/metrics/Program.cs

Thanks, that is how we ended up doing it. Thanks for the help again
