### ISSUE TITLE
Cannot compile using new swagger.json

### ISSUE THREAD

**Issue by ayrloong** [kubernetes-client/csharp#1571]
**Describe the bug**
I use my own swagger.json to generate the api model, but it doesn't compile properly

![image](https://github.com/kubernetes-client/csharp/assets/19401853/49f16fcf-c5b9-4253-8993-9f5402ceeec6)

I also tried using kubernetes-client gen to generate the api model, but it only generated a swagger.json file in the directory
![image](https://github.com/kubernetes-client/csharp/assets/19401853/4da23a24-c7e4-45f7-8e7f-94af9e15ae1e)
![image](https://github.com/kubernetes-client/csharp/assets/19401853/16d24230-7687-4e3b-b7a7-6df2f1244fa5)
![image](https://github.com/kubernetes-client/csharp/assets/19401853/709a6316-024a-48aa-9b0a-59518350e96e)

**Kubernetes C# SDK Client Version**
e.g. `14.0.2`

**Server Kubernetes Version**
e.g. `v1.29.2`

**Dotnet Runtime Version**
e.g. net9

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: [e.g. mac]
 - Environment [e.g. docker kubernetes]
 - Cloud [e.g. local]

**Additional context**
https://github.com/kubernetes-client/csharp/issues/1445

**Comment by tg123** [comment]
could you please share the swagger.json you generated?

**Comment by ayrloong** [comment]
this is the  swagger.json I generated
[Uploading swagger.json…]()

**Comment by ayrloong** [comment]
Thanks for your reply I want to generate CRD clientset in c#  but I'm not sure if this is possible in c# If not, I will close this issue

**Comment by tg123** [comment]
your swagger looked good

you could create pr to this repo and see if build works

**Comment by ayrloong** [comment]
Thanks you I think I can solve this problem in other ways
