### ISSUE TITLE
Nuget package is versioned differently to GitHub

### ISSUE THREAD

**Issue by APErebus** [kubernetes-client/csharp#1575]
**Describe the bug**
The latest version in this repo is `14.0.8`, however in NuGet, it's tagged as `14.0.9`.

**Kubernetes C# SDK Client Version**
e.g. `14.0.8`

NuGet: https://www.nuget.org/packages/KubernetesClient#versions-body-tab
<img width="539" alt="image" src="https://github.com/user-attachments/assets/addd298e-7f56-4b0e-ac55-390058dec4c5">

GitHub: https://github.com/kubernetes-client/csharp/releases/tag/v14.0.8

**Comment by tg123** [comment]
Thanks @WeihanLi  found the root cause
