### ISSUE TITLE
KubernetesClientConfiguration.IsInCluster() not working when automountServiceAccountToken=false

### ISSUE THREAD

**Issue by zhiweiv** [kubernetes-client/csharp#1576]
In KubernetesClientConfiguration.IsInCluster, it uses service account token file as one check condition.
```
 var tokenPath = Path.Combine(ServiceAccountPath, ServiceAccountTokenKeyFileName);
 if (!FileSystem.Current.Exists(tokenPath))
 {
     return false;
 }
```
When set automountServiceAccountToken false(https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#opt-out-of-api-credential-automounting), there is no token file injected to container, KubernetesClientConfiguration.IsInCluster doesn't work correctly.

**Comment by tg123** [comment]
any alternative way to know if the app is running inside k8s?
this is designed to use incluster auth

**Comment by zhiweiv** [comment]
In client-go, seems there is no public IsInCluster method, it suggests checking return value of InClusterConfig(https://github.com/kubernetes/client-go/blob/master/examples/in-cluster-client-configuration/main.go#L42).

We used IsInCluster beyond auth purpose, plan to remove them.

**Comment by tg123** [comment]
i believe the ask is
reband `IsInCluster` -> `HasInClusterToken` ?

**Comment by brendandburns** [comment]
I don't think that IsInCluster is intended to test whether or not the container is running inside a cluster. We could make that name change to make it more clear, but honestly I'm not sure if it's worth it.
