### ISSUE TITLE
Release 1.0.0 client?

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/csharp#158]
I don't think we're missing any major features, and no new bugs in a while, I think we're ready for a 1.0.0

@qmfrederik @tg123 @tintoy 

What do you folks think?

**Comment by tg123** [comment]
I am working on making `exec`, `attach`, `porting forward` more friendly to use. e.g. wrap channel const into a util object like java/python client does.

Started last year, really sorry about my slowness. 🐌 

Maybe it can be shipped at 1.1

**Comment by qmfrederik** [comment]
Sounds good to me - we've been using the KubernetesClient in production workloads for a while now and haven't seen any issues.

I had a quick look at our code and there are a couple of changes/improvements we'll probably want to upstream. The most important one is an API for interacting with remote processes (like @tg123 mentions), we're currently working with an API surface similar to the .NET `Process` class.
