### ISSUE TITLE
Add a code coverage tool

### ISSUE THREAD

**Issue by sesispla** [kubernetes-client/csharp#16]
With a basic unit testing framework working, we definitely need a code coverage tool to guide us during the test process.

**Comment by sesispla** [comment]
We'll have a hard time here and now... Not found so much alternatives for .NET Core so far:
* OpenCover: Only Windows support
* PartCover: This is the previous version of OpenCover (only Windows also, in maintenance mode)
* NCover: Only Windows support

I'll continue looking for alternatives

**Comment by sesispla** [comment]
@brendanburns any chance to get help from the .NET Core team?

**Comment by brendandburns** [comment]
XRef:

https://github.com/Microsoft/vstest/issues/579

**Comment by sesispla** [comment]
Thx @brendanburns 

Looks like support for dotnet test w/ Coverage is not that high in the vsteam backlog... Discussion switched to Microsoft/vstest#981

I'll keep an eye on this.

**Comment by sesispla** [comment]
Looks like there is some progress. I'll have a look ASAP and see if is possible to add coverage.

**Comment by sesispla** [comment]
Almost a year and still don't have a solution to code coverage in .NET :(

I've updated to latest coverlet bits and kubernetes-client/csharp. No luck, however.

Microsoft official coverage tool is still a Visual Studio Enterprise feature, so I don't this neither a solution. 

Still waiting for a fix from Coverlet. (Anyone can help @tonerdo with [this issue?])(https://github.com/tonerdo/coverlet/issues/16)

**Comment by tonerdo** [comment]
https://github.com/tonerdo/coverlet/pull/169 fixes the `BadImageFormatException` issue and allows Coverlet to work with this repo. Tested with my local version of https://github.com/sesispla/kubernetes-client-csharp/tree/feature/codecov

**Comment by tonerdo** [comment]
Tested with the latest release: https://www.nuget.org/packages/coverlet.msbuild/2.2.1

**Comment by sesispla** [comment]
Thank you @tonerdo confirmed that is working with the broken branch I had to add coverage. Updating to the latest version and adding coverage to the project!

**Comment by tg123** [comment]
#264
Consider close as azure pipe was established
