### ISSUE TITLE
The handler does not support client authentication certificates with this combination of libcurl (7.29.0) and its SSL backend ("NSS/3.34").

### ISSUE THREAD

**Issue by Tokumicn** [kubernetes-client/csharp#161]
The error is as follows:

The handler does not support client authentication certificates with this combination of libcurl (7.29.0) and its SSL backend ("NSS/3.34").

Please tell me what to do to solve it？

**Comment by brendandburns** [comment]
@Tokumicn 

Please see this issue here:

https://github.com/dotnet/corefx/issues/26446

And see if it resolves your issue. This looks like it is a dotnet core issue.
