### ISSUE TITLE
Watchers time out after 100 seconds

### ISSUE THREAD

**Issue by qmfrederik** [kubernetes-client/csharp#165]
- The default timeout for the `HttpClient` is 100 seconds, so the watchers will timeout after this amount of time.
- There is no default API to override the timeout on a per-request basis
- https://www.thomaslevesque.com/2018/02/25/better-timeout-handling-with-httpclient/ describes an alternative but it implies setting the timeout to Infinite for all requests and then specifying the timeout on a per-request basis for all requests.

**Comment by qmfrederik** [comment]
I'm not entirely sure, but this appears to be an issue when the server does not send any content at all in the first 100 seconds after the GET request is issued. When the server does send a first response, and subsequent updates come in intervals greater than 100 seconds, the code appears to work fine.

**Comment by brendandburns** [comment]
@qmfrederik is there an action we can take here? Or is this to document the issue for people who encounter it?
