### ISSUE TITLE
Question: How to update image version with client

### ISSUE THREAD

**Issue by RohanNagar** [kubernetes-client/csharp#179]
If want to update the image version of an existing Deployment with a newer version, how can I do that with the C# client?

Basically I'll have a new deployment YAML file that is the same as the existing one, just with the image version changed. Can I do an update on the existing deployment somehow so that I don't have to delete and recreate (which would cause downtime)?

Thanks!

**Comment by tg123** [comment]
Are you looking for `PatchNamespacedDeployment`

More: 
<https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment>

**Comment by RohanNagar** [comment]
What should I put in the `V1Patch` object? If I put either a string containing the new YAML or the `Appsv1beta1Deployment` object in the constructor for `PatchNamespacedDeployment1()`, I get this exception:

```
Unhandled Exception: System.NotSupportedException: Specified method is not supported.
   at k8s.Models.V1Patch.CustomInit()
   at k8s.Models.V1Patch..ctor(Object content)
   at KubernetesClusterClient.UpdateKubernetesDeployment(String filename, String namedspace) in C:\...\KubernetesClusterClient\src\KubernetesClusterClient.cs:line 119
```

**Comment by tg123** [comment]
please have a look at code in #78
and I will add an example code later

**Comment by RohanNagar** [comment]
Thanks, that helps!

**Comment by brendandburns** [comment]
There's a Java example here:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/PatchExample.java

That could easily be adapted to c#
