### ISSUE TITLE
integrate with VSTS

### ISSUE THREAD

**Issue by tg123** [kubernetes-client/csharp#187]
Hope MS will provide official VSTS account to build this client

benefits 
- Resharper code check (code style/possible defect)
- Windows Build and Release 
- Linux build is also supported
- Code converage

Examples:

Last build 
https://farmer1992.visualstudio.com/opensources/opensources%20Team/_build/results?buildId=134

related issues #37 #16

**Comment by brendandburns** [comment]
Do you have an example VSTS config for the build?

**Comment by tg123** [comment]
@brendanburns Azure pipelines are free for opensource now 
unlimited build time

Lets do it?

**Comment by brendanburns** [comment]
Sounds good to me. Do you want me to set it up or do you have cycles?

Thanks!

**Comment by tg123** [comment]
only you can setup it
<https://github.com/marketplace/azure-pipelines>
