### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by allantargino** [kubernetes-client/csharp#20]
I was able to use the solution on my Windows 10 client without problems.

Steps:
1. I copied my config file to: "C:\Users\myusername\.kube\"
2. After that, I installed openssl from: http://gnuwin32.sourceforge.net/packages/openssl.htm
3. Added "C:\Program Files (x86)\GnuWin32\bin" in my PATH variable
4. Run example. Success :)

![image](https://user-images.githubusercontent.com/13934447/29692132-e9d50a60-8904-11e7-925c-40e1d4108c0c.png)

Shouldn't we update the README.md documentation to share this Windows support?

**Comment by tg123** [comment]
I think no openssl required on Windows

**Comment by brendandburns** [comment]
Updated the readme with `choco` instructions. Let me know if you think there is more to add (or feel free to send a Pull Request :)

**Comment by allantargino** [comment]
The updated documentation with `choco` is perfect. Thank you @brendandburns !
