### ISSUE TITLE
Apply Equivalent

### ISSUE THREAD

**Issue by luisve1427** [kubernetes-client/csharp#210]
What is the equivalent to apply command? I tried using **CreateNamespacedSecretAsync** and it works the first time but if try once more i get a conflict error, i was expecting to behave like Apply command.

Thanks for the help

**Comment by itowlson** [comment]
I think it's `ReplaceNamespacedSecretAsync` - could you give that a go please?

**Comment by tg123** [comment]
IMHO
`apply` calls `patch` related rest api

**Comment by luisve1427** [comment]
ReplaceNamespacedSecretAsync is working for me, thanks for the help
