### ISSUE TITLE
Kubeconfig should not require certificate authority data for well known CAs.

### ISSUE THREAD

**Issue by twitchax** [kubernetes-client/csharp#220]
As the title says, the parser for the kubeconfig is too sensitive for certificate authority data.

`kubectl` will allow a blank entry if the CA is well-known (e.g., LetsEncrypt CA).  The code [here](https://github.com/kubernetes-client/csharp/blob/7c9cc88d38130947b100ecbea4feb7cbbfeb9f30/src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs#L177) prevents that scenario.

**Comment by brendandburns** [comment]
Agree that makes sense. I'd be happy for a PR or I can get to this eventually myself...

**Comment by twitchax** [comment]
I don't mind doing it.

Do we want to check the well-known-ness of the CA, or should we just let it fail during negotiation?

**Comment by brendandburns** [comment]
Fixed by #222
