### ISSUE TITLE
YamlDotNet dependency is broken

### ISSUE THREAD

**Issue by ArieShout** [kubernetes-client/csharp#224]
It looks like the current NuGet release `1.3.7-g7c9cc88d38` was built against YamlDotNet.Signed 5.0.0, which has broken file/assembly version in the DLL file (see: https://github.com/aaubry/YamlDotNet/issues/348)

YamlDotNet fixed this in version 5.0.2-pre0499 and 5.1.0. However, the return value of `DeserializerBuilder.Build` changed from `Deserializer` to `IDeserializer` (https://github.com/aaubry/YamlDotNet/commit/c0c446ec3edb22578d332b423c31b967e455b285)

If we use YamlDotNet.Signed 5.0.0, we will fail to find the assembly with strong type. If we upgrade the version to 5.1.0, we have broken API call:

> System.MissingMethodException: Method not found: 'YamlDotNet.Serialization.Deserializer YamlDotNet.Serialization.DeserializerBuilder.Build()'.

It would be great if a new release targeting YamlDotNet.Signed >= 5.1.0 is built.

**Comment by brendandburns** [comment]
ack, will update.
