### ISSUE TITLE
Please add net452 to KubernetesClient NuGet package

### ISSUE THREAD

**Issue by xinyanmsft** [kubernetes-client/csharp#239]
Please include net452 binary in the NuGet package.

Today when I invoke 'dotnet pack' on my machine, the resulting package contains net452. However the downloaded official package does not include it.

This means, when running in a full framework process, things like WebSocket authentication will not work (the issue was fixed in pull request #231, but NuGet package needs to include 452 to make it available).

Thanks!

**Comment by tg123** [comment]
I am working with integrating with azure pipeline which will enable windows base targets.

**Comment by brendandburns** [comment]
Yeah, right now the build step happens in Linux on Travis, that's probably not ideal...

**Comment by brendandburns** [comment]
Now that the pipeline is checked in, I will create a pipeline to build that artifact...
