### ISSUE TITLE
CSharp PUT wrappers

### ISSUE THREAD

**Issue by gaziqbal** [kubernetes-client/csharp#248]
It appears that the API support PUT semantics (https://github.com/kubernetes/kubernetes/issues/2114)
Are there plans to bring PUT wrappers to the CSharp client? I am not finding them right now.

**Comment by itowlson** [comment]
The `ReplaceXxx` methods have PUT semantics.  Let us know if those don't suit your situation.

**Comment by gaziqbal** [comment]
Thanks. I see that it's sending a PUT request, but for services at least, the following code fails with a 404 if there is no service of that name.


```
var service = await this.Client.ReplaceNamespacedServiceAsync(
                serviceRequest,
                serviceRequest.Metadata.Name,
                this.settings.Namespace).ConfigureAwait(false);

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"doc-svc-d16199e2-8166-49ad-a660-8fa57cc97a9c\" not found","reason":"NotFound","details":{"name":"doc-svc-d16199e2-8166-49ad-a660-8fa57cc97a9c","kind":"services"},"code":404}
```


**kubectl version**
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**minikube version**
minikube version: v0.34.1

**Comment by brendandburns** [comment]
404 indicates that the namespace/name object doesn't exist.

So either the name or the namespace in your call is wrong.

PUT requires that the object doesn't exist. If you want to create a new object, use `Create*` instead.

--brendan

**Comment by gaziqbal** [comment]
My expectation was that PUT would support create-or-replace. Is that not currently supported?
Thanks!
