### ISSUE TITLE
Provide documentation on authentication mechanisms

### ISSUE THREAD

**Issue by tomkerkhove** [kubernetes-client/csharp#249]
It looks like there are a few ways to authenicate/connect to a cluster.

```csharp
var config = KubernetesClientConfiguration.BuildConfigFromConfigFile();
var client = new Kubernetes(config);
```

Is this documented somewhere? If not, plans to provide this to clarify this part?

**Comment by brendandburns** [comment]
@tomkerkhove what specific documentation would you like to see? (and where would you find it useful, in the `README.md`?)

thanks

**Comment by tomkerkhove** [comment]
@brendandburns Ideally something that could be generated as part of the client's via enum, but given it can also come from partners that's practically impossible.

Having a list of Kubernetes official events in the docs or Readme would be good alternative, then we have at least an idea what kube will push. 

This is crucial if you want to build components on top of these events. Certainly if you want to filter some out.

**Comment by brendandburns** [comment]
Wait sorry, I am confused.  I think we're mixing two things? Isn't this request about authentication methods?

Thanks

**Comment by tomkerkhove** [comment]
Woops, I thought this was a different issue, sorry about that! Deleted my comment as it makes no sense.

Documentation in README is good enough for me!
