### ISSUE TITLE
Remove the dependency of OpenSSL executable

### ISSUE THREAD

**Issue by ArchangelSDY** [kubernetes-client/csharp#26]
Hi,

I see currently this library depends on an OpenSSL executable to do some key format conversion. We are building a web service so opening a new process seems a bit heavy. Do you have any plan to drop this dependency? Some libraries such as BouncyCastle might help.

Thanks.

**Comment by brendandburns** [comment]
Until very recently, dotnet core didn't support the right features https://github.com/dotnet/corefx/issues/14284

But this is now supported in dotnet 2.0, we need to write the code...

**Comment by krabhishek8260** [comment]
This has still not been resolved with dotnet core 2.0. The 2.0 release has a new method CopyWithPrivateKey(RSA privatekey) to set the private key but there is no way to create the RSA private ey object from the key file. I confirmed this with .net core team.

**Comment by qmfrederik** [comment]
@krabhishek8260 Did you look at Bouncy Castle? I'm pretty sure you can use Bouncy Castle to create the RSA private key; you can then pass that info to CopyWithPrivateKey.
