### ISSUE TITLE
Provide support for asynchronous watch

### ISSUE THREAD

**Issue by tomkerkhove** [kubernetes-client/csharp#262]
As of today you can create a watch for event as following:
```csharp
var kubernetesClient = new k8s.Kubernetes(_kubernetesConfiguration);
var kubernetesNamespace = _configuration.GetValue<string>("NAMESPACE");
HttpOperationResponse<V1EventList> eventsPerNamespace = await kubernetesClient.ListNamespacedEventWithHttpMessagesAsync(kubernetesNamespace, watch: true, cancellationToken: cancellationToken);

_watch = eventsPerNamespace.Watch<V1Event>((type, item) =>
{
    foreach (var handler in handlers)
    {
        handler.HandleEvent(item);
    }
});
```

Are there plans to provide an asynchronous version? This would be great to have if we want to perform I/O operations/call services.

**Comment by tg123** [comment]
you can do this
`.Watch<V1Pod>(async (type, item) =>.....`

**Comment by tomkerkhove** [comment]
Using async actions is actually not recommended, see https://msdn.microsoft.com/en-us/magazine/jj991977.aspx -
> One subtle trap is passing an async lambda to a method taking an Action parameter; in this case, the async lambda returns void and inherits all the problems of async void methods. As a general rule, async lambdas should only be used if they’re converted to a delegate type that returns Task (for example, Func<Task>).

**Comment by tg123** [comment]
Thanks @tomkerkhove 
I learnt a lot from your link.

Could you please advise the pattern for async watcher?

**Comment by qmfrederik** [comment]
@tomkerkhove The callbacks you pass to the Watch method are essentially event handlers. The article you reference states:

> To summarize this first guideline, you should prefer async Task to async void. Async Task methods enable easier error-handling, composability and testability. **The exception to this guideline is asynchronous event handlers, which must return void**. This exception includes methods that are logically event handlers even if they’re not literally event handlers (for example, ICommand.Execute implementations).

You should be good here. The callbacks will trigger your async code, creating a new Task. They will not `await` your task - so it's your responsibility to make sure you implement error handling, etc.

**Comment by tomkerkhove** [comment]
In that case it's not really nice imo but i'll just stick with sync processing then.
