### ISSUE TITLE
CI - Resharper checks are timing out on all builds

### ISSUE THREAD

**Issue by qmfrederik** [kubernetes-client/csharp#272]
It looks like the Resharper checks have been timing out on all Windows builds since at least last Friday, causing the builds to fail alltogether.

**Comment by tg123** [comment]
seems run out of credit of free vsts resource

**Comment by brendandburns** [comment]
perhaps we should disable it for now?

**Comment by tg123** [comment]
@brendandburns agree can we apply more free credit from azure for oss?

**Comment by tg123** [comment]
Merged I will follow up style check

**Comment by tomkerkhove** [comment]
As far as I know, you should be able to get more build time for OSS project.

**Comment by qmfrederik** [comment]
Azure DevOps OSS policies aside, Resharper checks for a project of this size don't normally take 1 hour; I think there's another issue with the Resharper task timing out.

**Comment by tomkerkhove** [comment]
Do you have by any chance a build where this was the case?

**Comment by qmfrederik** [comment]
This one probably: https://github.com/kubernetes-client/csharp/runs/83935158, though it looks like the build logs are not retained in Azure DevOps.

**Comment by tomkerkhove** [comment]
Too bad :/
