### ISSUE TITLE
Is it possible to Create a job using existing cronjob

### ISSUE THREAD

**Issue by zeross1337** [kubernetes-client/csharp#277]
Hi Guys,

I'm new with this client but I can't find the possibilities. So is it possible to create a job using from an existing cronjob (or trigger existing cronjob). And how can I get this to work?

Thanks!

**Comment by qmfrederik** [comment]
The short answer is 'yes'. You can use `IKubernetes.CreateNamespacedCronJobWithHttpMessagesAsync` to create a new CronJob or `IKubernetes.CreateNamespacedJobWithHttpMessagesAsync` to create a new Job.

The main parameter you need to specify is `V1Job body` (or similar for the cron job); the value of this parameter should match the YAML you use to create the cron job using `kubectl create -f`.

**Comment by zeross1337** [comment]
Hi Frederik,

I have tried a function to get all the existing cronjobs:

` KubernetesClientconfig = new KubernetesClientConfiguration { Host = "http://127.0.0.1:8001" };
            KubernetesClient = new Kubernetes(KubernetesClientconfig);
            var namespaces = KubernetesClient.ListCronJobForAllNamespaces1WithHttpMessagesAsync().GetAwaiter().GetResult();`

But I get an exception Microsoft.Rest.HttpOperationException: 'Operation returned an invalid status code 'NotFound''

Can you help me out?

**Comment by qmfrederik** [comment]
Yeah, the error message is very limited - see #58.

Can you wrap that in a try/catch statement like this:

```csharp
try
{
    KubernetesClientconfig = new KubernetesClientConfiguration { Host = "http://127.0.0.1:8001" }; 
    KubernetesClient = new Kubernetes(KubernetesClientconfig); var namespaces = 
    KubernetesClient.ListCronJobForAllNamespaces1WithHttpMessagesAsync().GetAwaiter().GetResult();
}
catch (HttpOperationException httpOperationException)
{
    var phase = httpOperationException.Response.ReasonPhrase; 
    var content = httpOperationException.Response.Content; 
}
```

and have a look at what the value of `content` is?

**Comment by zeross1337** [comment]
The value of content: "Not Found"
The value of content: "404 page not found\n"

**Comment by qmfrederik** [comment]
Did you open http://127.0.0.1:8001 via kubectl proxy?
Can you access http://127.0.0.1:8001/apis/batch/v2alpha1/cronjobs using your browser? What response do you get?
What version of Kubernetes is your server running?

**Comment by zeross1337** [comment]
I used Azure CLI to connect with the kubernetes dashboard on http://127.0.0.1:8001/

With proxy on I get 404 code. the server could not find the requested resource

Version kubernetes: 1.12.6

**Comment by qmfrederik** [comment]
In that case, I'm not sure what the issue is. `GET /apis/batch/v2alpha1/cronjobs` [is listed as a valid endpoint for 1.12](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#list-all-namespaces-cronjob-v2alpha1-batch). If it doesn't work using your browser, there must be something else.

**Comment by brendandburns** [comment]
@zeross1337 you shouldn't need the proxy. This library will pick the right credentials out of your kubeconfig file to talk to the AKS cluster directly...

**Comment by uhansen** [comment]
Just tried this out, seeing the same problem - if you have multiple AKS clusters in your kubeconfig it doesn't work, if you have only one it works

**Comment by brendandburns** [comment]
@uhansen can you provide more details to reproduce? It should work with multiple clusters in your config file. That sounds like a bug...

**Comment by Dunge** [comment]
Just leaving this here if someone else try to do this with the recent version of the kubernetes api c# client lib:

```
        public async Task LaunchJob(string nameSpace, string name)
        {
            var jobs = await _client.ListNamespacedCronJobAsync(nameSpace);
            var job = jobs.Items.FirstOrDefault(j => j.Metadata.Name == name);
            if (job == null)
                throw new Exception("Job not found");

            var newJob = new V1Job
            {
                ApiVersion = "batch/v1",
                Kind = "Job",
                Metadata = new V1ObjectMeta
                {
                    GenerateName = job.Metadata.Name + "-",
                },
                Spec = job.Spec.JobTemplate.Spec
            };

            var result = await _client.CreateNamespacedJobAsync(newJob, nameSpace);
        }
```
