### ISSUE TITLE
Allow to set HttpClient when creating the client

### ISSUE THREAD

**Issue by omerlh** [kubernetes-client/csharp#279]
Currently, there is overload that let you set the HttpClient (for example, if you want to override the default timeout) and use `KubernetesClientConfiguration`. There is such a constructor on the generated `Kubernetes` object - but it doesn't accept configuration.

**Comment by ajamrozek** [comment]
After you construct your client. You can set the HttpClient property properties.

var client = new Kubernetes(k8sClientConfig);
client.HttpClient.Timeout = new TimeSpan(0, 0, 0, 30);

**Comment by winromulus** [comment]
I would also like to have this option so I can use the HttpClientFactory.
Currently I'm suffering from the DNS update issue of the standard client.

**Comment by DavidParks8** [comment]
I want to use HttpClientFactory as well, and the change was fairly small, all things considered. Take a look at #302.
