### ISSUE TITLE
Getting error while calling ListNamespacedSecret

### ISSUE THREAD

**Issue by eddyuk** [kubernetes-client/csharp#288]
While attempting to run ListNamespacedSecret in cluster (`KubernetesClientConfiguration.InClusterConfig()`), getting following error: 

> Operation returned an invalid status code 'Forbidden'

 It is working on my local development machine when initiating with KubernetesClientConfiguration.BuildDefaultConfig().
I'm using .NET Standard 4.7.2 with Windows 2019 node

**Comment by s-leonard** [comment]
Did you work this out, I'm also getting this issue, I cant see what permissions I need to grant?

**Comment by s-leonard** [comment]
actually I've got it working, this issue had answer [273](https://github.com/kubernetes-client/csharp/issues/273#issuecomment-492114211)
