### ISSUE TITLE
Is there a way to add "limit" query option to ListClusterCustomObjectAsync?

### ISSUE THREAD

**Issue by weng271190436** [kubernetes-client/csharp#292]
https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks

I am trying to add a "limit" query option when I am retrieving my custom objects. I might be mistaken but it seems that the c# client does not support this yet.

Since this is generated codes can we regenerate KubernetesExtensions.cs?

**Comment by krabhishek8260** [comment]
The client supports limit.

`public static V1PodList ListPodForAllNamespaces(this IKubernetes operations, bool? allowWatchBookmarks = default(bool?), string continueParameter = default(string), string fieldSelector = default(string), string labelSelector = default(string), int? limit = default(int?), string pretty = default(string), string resourceVersion = default(string), int? timeoutSeconds = default(int?), bool? watch = default(bool?))`

**Comment by weng271190436** [comment]
Ah I see. But 
public async Task<HttpOperationResponse<object>> ListClusterCustomObjectWithHttpMessagesAsync(string group, string version, string plural, string fieldSelector = default(string), string labelSelector = default(string), string resourceVersion = default(string), int? timeoutSeconds = default(int?), bool? watch = default(bool?), string pretty = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken))

doesn't support limit so kubernetes API doesn't support limit on Custom Objects yet?

Thanks!
