### ISSUE TITLE
Custom Resource Definitions: Get or Create

### ISSUE THREAD

**Issue by sadedil** [kubernetes-client/csharp#295]
As far as i see, i can get all native K8s objects with queries like `client.ListNamespacedPod`. Is there any support for CRD's?

In my example we are using Argo's Workflow CRD.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
```

How can i `get` or `create` this type of resource with this library. It's not necessary to be strongly typed. I've full `yaml` file and i want to `create` in a K8s cluster.

**Comment by darobs** [comment]
Yes, there are methods for CRDs. Look for `CreateCustomResourceDefinition` and so on. CRDs are always cluster-level objects, so there are no "namespaced" methods.

Once you create a CRD, you can manage custom objects. Those methods are all named with "CustomObject" -  for example `ListNamespacedCustomObject`.  They accept and return "object" types, which are implemented as a Newtonsoft `JObject`.

**Comment by sadedil** [comment]
Thanks @darobs,

I'll check this.

**Comment by lknite** [comment]
Could someone give a little detail on how to use ListNamespacedCustomObject to list out crd items?

**Comment by IvanJosipovic** [comment]
@lknite also check out https://github.com/IvanJosipovic/KubernetesCRDModelGen  ;)

**Comment by lknite** [comment]
@IvanJosipovic Thank you!  That's exactly what I needed next ... the CRDs exist in kubernetes, need to load them up as objects to then create / modify new objects ...
