### ISSUE TITLE
Port Forward example not working

### ISSUE THREAD

**Issue by gittadesushil** [kubernetes-client/csharp#297]
I am using Port forward example where I need to forward the port of running service. I have service running inside pod on port 3122. 
When I redirect it to 8080. The url is localhost:8080 and has UI but I don't see full UI. Only I can see the service name mentioned in Title bar of browser.

Debug:
```
if (bytesRec == 0 || Encoding.ASCII.GetString(bytes,0,bytesRec).IndexOf("<EOF>") > -1) {  
                            break;  
}
```
Coming always false `Encoding.ASCII.GetString(bytes,0,bytesRec).IndexOf("<EOF>") > -1`

But if I execute same using kubectl command then it works perfectly fine. 
`kubectl port-forward service/dbdashboard 8080:3122 -n my_namespace`

**Note:** k8s cluster is not installed on my system. I am using k8s cluster which is installed on Azure cloud.

**Comment by gittadesushil** [comment]
It started working if I close the listener in while loop.
`handler = listener.Accept();`

```
while (true)
                    {
                        int bytesRec = handler.Receive(bytes);
                        stream.Write(bytes, 0, bytesRec);
                        if (bytesRec == 0 || Encoding.Default.GetString(bytes, 0, bytesRec).IndexOf("<EOF>", StringComparison.InvariantCultureIgnoreCase) > -1)
                        {
                            Console.WriteLine("We are in brake mode!");
                            break;
                        }
                        else
                        {
                            Console.WriteLine(Encoding.Default.GetString(bytes, 0, bytesRec));
                        }
                        listener.Close(); //This has to be close because if TCP connection is more than 6 then 6th request will in pending state. 
                    }
```
Can someone please look into my suggestion? I feel example need modification.

**Comment by blushingpenguin** [comment]
I encountered this as well, you just need to change
```csharp
var demux = new StreamDemuxer(webSocket);
```
to
```csharp
var demux = new StreamDemuxer(webSocket, StreamType.PortForward);
```

**Comment by gittadesushil** [comment]
@blushingpenguin 
After using `var demux = new StreamDemuxer(webSocket, StreamType.PortForward);`. still I see some request are in pending state.  Resulting I don't see all resources get loads.
According to [This link](https://developers.google.com/web/tools/chrome-devtools/network/reference#timing-explanation)

> Queueing. The browser queues requests when:
> There are higher priority requests.
> There are already six TCP connections open for this origin, which is the limit. Applies to HTTP/1.0 and HTTP/1.1 only.
> The browser is briefly allocating space in the disk cache

So I think it's necessary to close listener after every request full-fill. Do you have better solution?

**Comment by blushingpenguin** [comment]
I don't see what Chrome's behaviour has to do with .NET's HttpClient?  As it is the port forward sample is actually broken -- the stream isn't demuxed appropriately and includes random binary garbage which would explain why your browser isn't loading what you are port fowarding correctly. What's wrong with your code apart from that I couldn't say without seeing it.

**Comment by gittadesushil** [comment]
@blushingpenguin I am using same example as it is. 
UseCase : There is micro-service running on k8s cloud where it cannot be ingress outside. So to do that I need to use port forward so that service should available to testing team. To check this port forward is working I can hit the url in chrome and see weather everything is loaded (Service has UI stuffs in it).

**Comment by wbuck** [comment]
Just to be clear, is this port-forwarding example the equivalent to running the following from the command line?

```shell
kubectl port-forward <pod-name> 80:8080 --namespace "default"
```

**Comment by msieorbus** [comment]
its been a while, but have you manage to solve it ? for me example is also not working. i used exact same way as in code snippet provided. I just changed ports to use 2000 and 5000

**Comment by tg123** [comment]
@msieorbus are you sure it is not working, if so, please file an issue, it would remind me to take a look this weekend
