### ISSUE TITLE
Why so many targeted frameworks?

### ISSUE THREAD

**Issue by DavidParks8** [kubernetes-client/csharp#303]
Targeting a bunch of specific frameworks kind of defeats the point of using .net standard, does it not? I looked through the code and it seems like there are good initial reasons for targeting a bunch of platforms, but now that .net core has matured a bit, it might be time to look into unifying to just .net standard 2.0 and adding convenience methods/support for Microsoft.Extensions.DependencyInjection and Microsoft.Extensions.Configuration.

Thoughts?

**Comment by brendandburns** [comment]
I want to make sure that we continue to support Mono/Xamarin.

And if I remember correctly there were challenges with .net standard and SSL certificate handling.

But in general, I the goal would be a minimal set that spans all relevant use cases (Framework, Core and Mobile)

**Comment by tg123** [comment]
@brendandburns 

<https://docs.microsoft.com/en-us/dotnet/standard/net-standard>

IMHO, we should target `.netstandard` only for all platform
