### ISSUE TITLE
CPU Usage Info

### ISSUE THREAD

**Issue by kollerdroid** [kubernetes-client/csharp#306]
I would like to get an average percentage value of the CPU usage from the cluster.

I tried to get some info from node status but all I found is capacity and allocatable CPU (core count).

I have also not found in pod status. (eg. CPU Requests)

I think I need something like that the output of 
`kubectl describe node <nodename>`

> ...
> Allocated resources:
>   (Total limits may be over 100 percent, i.e., overcommitted.)
>   Resource           Requests    Limits
>   --------           --------    ------
>   cpu                250m (12%)  0 (0%)
>   memory             0 (0%)      0 (0%)
>   ephemeral-storage  0 (0%)      0 (0%)

Is there a way to get CPU usage info for the cluster (or the CPU Requests of the pods)?

**Comment by brendandburns** [comment]
The go code in the kubectl client calculates that from the Node object. See a similar ask here:

https://github.com/kubernetes-client/java/issues/717#issuecomment-535774658

Closing since the question is answered. If you want to reopen please use the `/reopen` command in a comment.
