### ISSUE TITLE
[Kuberenetes Client] The constructor of kubernetes may referenced to null HttpClientHandler

### ISSUE THREAD

**Issue by Incarnation-p-lee** [kubernetes-client/csharp#307]
The constructor will invoke InitializeFromConfig, and the method will reference to `HttpClientHandler` from base class `ServiceClient`.

```C#
        public Kubernetes(KubernetesClientConfiguration config, HttpClient httpClient, bool disposeHttpClient) : this(httpClient, disposeHttpClient)
        {
            ValidateConfig(config);
            CaCerts = config.SslCaCerts;
            SkipTlsVerify = config.SkipTlsVerify;
            InitializeFromConfig(config);
        }
```

But the related constructor of base class `ServiceClient` only create new handler only if client is null, so there may be one path that makes `HttpClientHandler` to be null.

```C#
        protected void InitializeHttpClient(HttpClient httpClient, HttpClientHandler httpClientHandler, params DelegatingHandler[] handlers)
        {
            //Init lock object
            lockUserAgent = new object();


            if (httpClient == null)
            {
                if (httpClientHandler == null)
                {
                    httpClientHandler = CreateRootHandler();
                }


                HttpClientHandler = httpClientHandler;


                DelegatingHandler currentHandler = CreateHttpHandlerPipeline(httpClientHandler, handlers);


                HttpClient = new HttpClient(currentHandler, false);
                FirstMessageHandler = currentHandler;
            }
            else
            {
                HttpClient = httpClient;
            }


            //Set Default info in user agent
            SetDefaultAgentInfo();
        }
```

https://github.com/Azure/azure-sdk-for-net/blob/45cdad6bc3f20b36220d303a44f99895bdba28b7/sdk/mgmtcommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L341-L367

So could you please help to confirm is this expected ? Or How can I pass the httpClient in a correct way  ? Thanks a lot.

**Comment by brendandburns** [comment]
That seems like a bug in the code that should be fixed in the AutoRest codebase, or we should work around in our code...

Do you want to file a bug on the autorest code?

**Comment by Incarnation-p-lee** [comment]
I think it can be fixed by autorest part, as this file is auto-generated.

**Comment by brendandburns** [comment]
Ok, I'm going to close this. Once the AutoRest generator is fixed, it should get picked up here automatically....

If you want to reopen this for some reason, please use the `/reopen` bot command.
