### ISSUE TITLE
Rename repo from csharp to dotnet

### ISSUE THREAD

**Issue by bruno-garcia** [kubernetes-client/csharp#311]
I believe a more appropriate name for this repo would be: `dotnet`.

The reasoning behind it is that although the language used to write it was C#, it serves as a .NET client. That is, it will be used by F#, VB and any other CLS language. Similarly the `javascript` repo is written in TypeScript. But regardless of the language, it's serves as the JavaScript client.

**Comment by brendandburns** [comment]
I totally get where you're coming from.

It was discussed when we created this repo, I don't think it's worth churn at this point, but we could update the README/links in k8s.io to show that it works with F#, etc.

**Comment by bruno-garcia** [comment]
Thanks for replying. I believe F# and VB developers would expect it to work with their languages since the vast majority of libraries in the .NET ecosystem are actually written in C#. Perhaps an F# or VB devs would be willing to contribute with samples.

Also, perhaps it's worth noting that GitHub creates a redirect from the old name to the new.
But if this was discussed and yet you prefer(?) to keep it `csharp`, feel free to close the issue.

**Comment by brendandburns** [comment]
fwiw, (just for clarity) I don't really care one way or the other, and I can see the argument for `dotnet`

But the names of these repos were decided by the Kubernetes SIG-API group, so any changes to the names needs to go through them. I don't really have the cycles to do that myself at this time, but if you wanted to propose it and work through the SIG to get it approved, that's 100% fine with me.

Let me know if there are questions (and thanks!)

**Comment by bruno-garcia** [comment]
/reopen

@brendandburns I can try to attend a SIG meeting and bring this case in.
It's just a nice to have so if it's too much hassle to get it approved I'm happy to close this.

But a rename is simple and given that old links follow to the new repository name, I'm unaware of a reason not to do this.
