### ISSUE TITLE
Applying a new Kubernetes context to local Kubeconfig file

### ISSUE THREAD

**Issue by Yagil1990** [kubernetes-client/csharp#316]
Hi, 
I have a K8SConfiguration object of a new Kubernetes context (of an AKS cluster), and I want to set it to the local Kubeconfig file (and overwrite existing context if exists), just as the "az aks get-credentials --overwrite-existing" does.

Is there a way (or any future task) to perform it using Kubernetes-client ?

Thanks, 
Ran.

**Comment by brendandburns** [comment]
Not currently supported, but I'd be happy to have a PR adding support for writing a K8SConfiguration object to file.
