### ISSUE TITLE
Nuget package is not getting built for all target frameworks

### ISSUE THREAD

**Issue by alexanderboswell** [kubernetes-client/csharp#317]
In the [project file](https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/KubernetesClient.csproj), net452 is listed as a target framework but when viewing the published package it is not listed as being supported:
![image](https://user-images.githubusercontent.com/21343215/67705723-c8afd580-f974-11e9-959c-3b0f9c474e09.png)

It looks like in the [project file](https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/KubernetesClient.csproj) it is only building the packages for `"'$(OS)' != 'Windows_NT'"`.

I have been able to build the package locally for net452, so it seems to be supported and working but the build pipeline is not generating a package.

**Comment by tg123** [comment]
This is because the project is built on linux.
Github Action is a better place to have the build run where Windows is supported

**Comment by brendandburns** [comment]
Yeah, we should migrate to github actions...

**Comment by tg123** [comment]
start at KubernetesClient 1.6.20
net452 was included
