### ISSUE TITLE
Clean up outside collaborators

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-client/csharp#318]
Hey there @kubernetes-client/csharp-admins ,

One of the github-admins here. -- We have a [longstanding issue] on cleaning up outside collaborators, and are now actively planning on removing them on December 1st.

At this point, people that are actively contributing to the Kubernetes project should be promoted to [org members][mem], and any repo specific permissions should be managed through their associated configuration in [kubernetes/org].

With that in mind, the following people are listed as outside collaborators:

- @itowlson 
- @tg123 

Both @itowlson and @tg123  are active and I'd encourage [applying for membership to kubernetes-client org][mem]. 😄 

If you have any questions or comments, please don't hesitate to ask in here or feel free to poke me in slack 👍 

Thanks!

assigning csharp-admins:
/assign @brendanburns @krabhishek8260

/sig contributor-experience
/priority important-soon

[longstanding issue]: https://github.com/kubernetes/community/issues/3178
[mem]: https://github.com/kubernetes/community/blob/master/community-membership.md#member
[kubernetes/org]: https://github.com/kubernetes/org
[devstats]: https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All

**Comment by tg123** [comment]
Thanks for inviting.
I am happy to join the org

https://github.com/kubernetes/org/issues/1351

**Comment by krabhishek8260** [comment]
I have replied on the above open issue.

**Comment by mrbobbytables** [comment]
Thanks!

**Comment by mrbobbytables** [comment]
Permissions have been cleaned up. 

@itowlson  -- Please go ahead and file for [org membership](https://github.com/kubernetes/community/blob/master/community-membership.md#member) and we can pursue adding you the appropriate groups for repo permissions 👍

If you have any questions, please don't hesitate to reopen or ping me on slack.

Thanks!
/close
