### ISSUE TITLE
Support lower runtime version netstandard 1.0+ netframework 4.0

### ISSUE THREAD

**Issue by tg123** [kubernetes-client/csharp#32]
Hi

Is there a plan that this library would support lower dotnet runtime? like:
*  netstandard 1.0
* netframework 4.0

**Comment by brendandburns** [comment]
I don't know what is needed? I'm in favor of supporting as compatible a standard as we can as long as we can get the library to do what we need.

**Comment by tg123** [comment]
We want to run this client on `.net45`. Benefit from `netstandard1.3`, it now can target on `net46`. 

This issue wants to define the minimal version of netstandard version and netframework version this library support.

in other words: will this library support `net45` or any other lower versions

**Comment by felixfbecker** [comment]
I would like to use this with targeting .NET Standard 2.0
```
error: Package KubernetesClient 0.1.0-beta is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package KubernetesClient 0.1.0-beta supports: netcoreapp1.1 (.NETCoreApp,Version=v1.1)
```

**Comment by tg123** [comment]
please update to higher version > 0.3.0-beta

**Comment by felixfbecker** [comment]
Ah, that fixed it. Thanks.
