### ISSUE TITLE
IsInCluster() returning false when in cluster

### ISSUE THREAD

**Issue by alexanderboswell** [kubernetes-client/csharp#321]
This is related to the closed issue #285 .

I have my dotnet app running in the cluster on a Windows Server 2019 node. I am getting a `unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined` when using `KubernetesClientConfiguration.InClusterConfig();`. From reviewing how the client works this error is thrown when IsInCluster() is false.

I have connected to the container and can see that these variables are set and the files exist:
![image](https://user-images.githubusercontent.com/21343215/68512150-697f7a00-022c-11ea-98c1-c05facbf9001.png)

From reviewing the code, it appears that these are all the values that are checked when testing for IsInCluster() in this file: https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs. 

As asked in the issue #285, I do have the kubernetes service running:
![image](https://user-images.githubusercontent.com/21343215/68512973-b2d0c900-022e-11ea-93db-b5a0929211fc.png)

So the issue I am having is that the values exist but it doesnt seem like the client is able to retrieve them for some reason. It hasn't attempted to make a request to the API at the time it throws this error so I don't believe it is a rbac issue.

I have also created a test app that implements the same logic as the IsInCluster() method and ran it in the same namespace. This returned the values successfully.

**Comment by brendandburns** [comment]
So, I notice that the path in that code uses forward slashes. I wonder if dotnet on windows doesn't like such paths? That's my best guess.  I will send a PR to fix that and see if it fixes this for you.

**Comment by alexanderboswell** [comment]
I think I might have found the issue, let me test and report my findings.

**Comment by brendandburns** [comment]
ok, thx

**Comment by brendandburns** [comment]
Any updates here? Thanks.

**Comment by alexanderboswell** [comment]
I am running my service as the Windows account 'NT AUTHORITY\NETWORK SERVICE' which would have admin privileges also. It seems it doesn't have access to those environment variables by default. Do you know under what context those files are added and environment variables are set for a Windows node?

**Comment by alexanderboswell** [comment]
This doesnt seem to be an issue with the client, but related to how the Windows node is setup with the service account information.

**Comment by brendandburns** [comment]
ok, can you follow up w/ SIG-Windows on Kubernetes Slack to see how the node is setup?

Thanks!

**Comment by PatrickLang** [comment]
@alexanderboswell - Kubernetes only sets environment variables on the entrypoint process for the container. They're not available to background services. Can you try creating a wrapper script that:

1. Sets these with `[System.Environment]::SetEnvironmentVariable('key', 'value',[System.EnvironmentVariableTarget]::Machine)`
2. Then calls Start-Service

**Comment by alexanderboswell** [comment]
Just a follow up, I was successful in setting these environment variables in the start script for a container as Patrick outlined.
