### ISSUE TITLE
Cordon Node method missing?

### ISSUE THREAD

**Issue by kagoyal** [kubernetes-client/csharp#325]
I can find delete node, but not cordon node in library.

**Comment by brendandburns** [comment]
Cordon isn't an API call. It's a series of API calls.

The relevant Go code is here:
https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/drain/drain.go#L352

You will need to write equivalent logic using the API calls.

If you do write the code and want to contribute, we'd gladly take a PR adding support for cordon.
