### ISSUE TITLE
Feature: Data types for Istio and Extensions

### ISSUE THREAD

**Issue by JulianBirch** [kubernetes-client/csharp#327]
Self explanatory: there's quite a few Kubernetes objects one might wish to control that aren't part of this or any other* .NET API right now.

**Comment by brendandburns** [comment]
The story in general for generating code for non-core objects isn't great.

In general the https://github.com/kubernetes-client/gen repository should be capable of generating clients that are compatible with this library, but the instructions for how to do that are largely non-existent.

I'll think and see if there isn't a better way to accomplish this.

**Comment by tg123** [comment]
reopen if needed
