### ISSUE TITLE
Include net452 to KubernetesClient NuGet package

### ISSUE THREAD

**Issue by BenRoberts86** [kubernetes-client/csharp#328]
We are trying to run `KubernetesClient` under mono however we are hitting the issue that `HttpClientHandler.ServerCertificateCustomValidationCallback` is not implemented, so cannot use the `netstandard2.0` package version. The code has a path for `NET452` but the package doesn't seem to be published to NuGet, please can this be added?

It seems some work was done previously to enable this via Azure pipelines (see https://github.com/kubernetes-client/csharp/issues/239 ) however the NET452 version is still not available via NuGet.

**Comment by tg123** [comment]
the `push to nuget` part is not yet enabled, please allow us some time to have it done

**Comment by tg123** [comment]
start at KubernetesClient 1.6.20
net452 was included
