### ISSUE TITLE
Question: Is it possible to list pods associated with given service?

### ISSUE THREAD

**Issue by gittadesushil** [kubernetes-client/csharp#331]
I have use case:
I need to find out the pods associated with x service. I tried to look them using labels but always it's not feasible.

**Comment by brendandburns** [comment]
List pods with labels should be possible.

Can you send the code you are trying and describe what's not working correctly?

Thanks!

**Comment by gittadesushil** [comment]
Yes I list the pods using labels. Tat's working fine.
