### ISSUE TITLE
Does not support multiple resources in one yaml file (separated by ---), load multi yaml documents from a single file - Yaml.loadAll() method

### ISSUE THREAD

**Issue by nikunjbanker** [kubernetes-client/csharp#338]
Does not support multiple resources in one yaml file (separated by ---), which is quite common in daily use.

So do you get any plan for this? Its there in JAVA client library - https://github.com/kubernetes-client/java/pull/207

Thanks.

**Comment by brendandburns** [comment]
fwiw, this was really annoying to implement in the Java library, you have to have a map from apigroup/kinds -> concrete types to do this right.

I will add something manual as a start.

**Comment by brendandburns** [comment]
I added a simplified implementation here:

https://github.com/kubernetes-client/csharp/pull/344

It's a starting point. We can expand it to automagically find all of the apigroup -> Type mappings via reflection like Java does.

**Comment by brendandburns** [comment]
There is code for this merged in `1.6.11` see this example:

https://github.com/kubernetes-client/csharp/blob/master/examples/yaml/Program.cs
