### ISSUE TITLE
Again: KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

### ISSUE THREAD

**Issue by sadedil** [kubernetes-client/csharp#339]
I know this is same with the #285, but there is something strange about the **v1.6.8**.

Today I've update *KubernetesClient* Version from **1.6.5** to **1.6.8**, then I've started to receiving this error. Then rollback and problem solved.

I've checked (with `env` command) the all other pods, all of them has *KUBERNETES_SERVICE_HOST* and *KUBERNETES_SERVICE_PORT* environment variables. No problem.

I think there is a race problem, maybe the v1.6.8 has some performance improvements and environment variables loaded after the code checked this values.

P.S. This is not an RBAC issue. My SA has enough permission.

**Comment by brendandburns** [comment]
Is this on Windows or Linux?

**Comment by sadedil** [comment]
Linux containers

**Comment by brendandburns** [comment]
Looks like this might be the same as #341 ? Does it work if you downgrade to 1.6.6?

Thanks

**Comment by sadedil** [comment]
Didn’t try with 1.6.6. But downgrade to 1.6.5 solved the problem.

**Comment by brendandburns** [comment]
Ok, I think this is the same as #341 

We merged a fix in #342 which is now in `1.6.9` so it would also be interesting to see if `1.6.9` works for you also.

Thanks

**Comment by sadedil** [comment]
Hi @brendandburns 

I've updated to 1.6.10 and it works as expected.

Thanks for the solution.
