### ISSUE TITLE
BuildConfigFromConfigFile() hangs

### ISSUE THREAD

**Issue by aloneguid** [kubernetes-client/csharp#352]
The static methods on `KubernetesClientConfiguration` like `BuildConfigFromFile` are hanging when using from certain environments where SynchronisationContext is not default. For instance WPF, Xamarin etc. Specifically on any line that uses `.GetAwaiter().GetResult();`.

Could you provide true async methods where you are waiting for operation result?

**Comment by brendandburns** [comment]
Just for clarity, you're looking for something like:

```
Task<KubernetesConfiguration> BuildConfigFromFileAsync(...)
```

**Comment by aloneguid** [comment]
Correct. Going further, in my opinion there should be no code relying on `.GetResult()` as it's potentially deadlocking. If users of this library want to be synchronous they are always welcome to introduce locking themselves.

**Comment by brendandburns** [comment]
I added the async methods. Since the sync methods are part of the existing contract, it's a breaking change to remove them, so I kept them as well.  Seems like a decent balance.

**Comment by aloneguid** [comment]
Thank you, looks good :)

**Comment by brendandburns** [comment]
Can you put an LGTM on the PR? Then we can get it merged.

Thanks!

**Comment by lolodi** [comment]
Thanks for your timely fix I was able to get unblocked but looking at the rest of the code it looks like the default behavior is to use `.GetAwaiter().GetResult();` everywhere, even in the generated code. 
This can create deadlocks if the consumer has its own SynchronizationContext as pointed out by @aloneguid. As I was reading [here](https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f) this is not recommended and `.ConfigureAwait(false)` should be used before the `.GetAwaiter().GetResult();` to avoid the default SynchronizationContext capturing behavior. I found an interesting article [here](https://docs.microsoft.com/en-us/archive/msdn-magazine/2011/february/msdn-magazine-parallel-computing-it-s-all-about-the-synchronizationcontext) that elaborates more about the whole SynchronizationContext.
Would it be possible to change the library to expose real Async API for every action as well as using `.ConfigureAwait(false)` for the forcefully synchronized ones?

**Comment by brendandburns** [comment]
The generated code is generated by the AutoRest tool:

https://github.com/Azure/autorest

The fixes would need to come from there.

--brendan



________________________________

**Comment by lolodi** [comment]
I see. But even without the AutoRest changes, it is possible to avoid binding on the caller SyncronizationContext and expose more async APIs. There is an interesting article [https://devblogs.microsoft.com/dotnet/configureawait-faq/](https://devblogs.microsoft.com/dotnet/configureawait-faq/) and running the underlying async operation in a `Task.Run().GetAwaiter().GetResult()` should be enough to guarantee that the operation is executed in a background task withouth a SyncronizationContext.
