### ISSUE TITLE
Upgrade Microsoft.AspNetCore.WebUtilities from version 1.1.2 to 2.2.0

### ISSUE THREAD

**Issue by pragyamehta** [kubernetes-client/csharp#356]
I am working on a project targeting netstandard2.0 that takes a dependency on KubernetesClient. My project directly references Microsoft.AspNetCore.WebUtilities Version 2.2.0, but KubernetesClient references version 1.1.2.
I need to package my project as a nuget package and provide it to a consumer. If I add the version 2.2.0 in the nuspec file while creating the nuget package, KubernetesClient fails at runtime since it looks for 1.1.2 assembly version of the dll. 
I unfortunately have a restriction that I cannot add assembly redirects :(

Can we upgrade the version of this nuget package to 2.2.0 for netstandard2.0?

**Comment by brendandburns** [comment]
I'm ok with this. Can you send a PR?

**Comment by pragyamehta** [comment]
Yes, absolutely! Thanks for agreeing with this change :)

**Comment by pragyamehta** [comment]
https://github.com/kubernetes-client/csharp/pull/358
Here is the PR. I am unable to link this issue in the PR unfortunately.

**Comment by pragyamehta** [comment]
@brendandburns thanks for accepting the PR. I'm not familiar with the nuget release cycle. When will a new nuget package be released?

**Comment by brendandburns** [comment]
The ci/cd system automatically pushes a new nuget package it should be there shortly.

--brendan

________________________________

**Comment by brendandburns** [comment]
Closing since #358 has merged.
