### ISSUE TITLE
Build fails on VS Enterprise 2019 Version 16.4.5

### ISSUE THREAD

**Issue by pragyamehta** [kubernetes-client/csharp#357]
**The TargetFramework value 'xamarinios10' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.	

The TargetFramework value 'monoandroid81' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.**

Mobile development with .NET is already installed for this VS
![Annotation 2020-02-11 162805](https://user-images.githubusercontent.com/22248649/74291961-81fba680-4ceb-11ea-9971-62b61ab311c8.png)

**Comment by brendandburns** [comment]
I admit I don't really use VS Enterprise so I'm not sure I can help with this. If you figure it out, I'm happy to take a PR to fix the .sln/.csproj files.

**Comment by tg123** [comment]
you may want use dotnet build to avoid this
@brendanburns I suggest to remove those targets as in #345 they are never in our nuget package and covered by netstandard

the reason they were introduce is to support ssl and websocket on those platfrom

**Comment by brendandburns** [comment]
@tg123 does that mean that a Xamarin user can use the `netstandard` nugets from mobile?

**Comment by tg123** [comment]
@brendanburns
Yes 
https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/net-standard
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

I am happy to reforge the targets if you approve

**Comment by brendandburns** [comment]
@tg123 sure, that sounds great, thanks.
