### ISSUE TITLE
Some kubernetes objects do not implement IKubernetesObject

### ISSUE THREAD

**Issue by JochenGuck** [kubernetes-client/csharp#362]
I have found some Kubernetes objects which do not implement IKubernetesObject:
- Extensionsv1beta1Ingress
- Networkingv1beta1Ingress
I use the Kubernetes client  version 1.6.16-gb07e78afa4 
Is this on purpose or a bug?

**Comment by tg123** [comment]
I checked the generator, it is a bug.
and fix is on the way

**Comment by JochenGuck** [comment]
Thank you very much for the quick response to the issue
