### ISSUE TITLE
Feature: Add leader election

### ISSUE THREAD

**Issue by zhiweiv** [kubernetes-client/csharp#368]
Client go contains api for leader election(https://github.com/kubernetes/client-go/tree/master/tools/leaderelection), 
there is also an implmentation in java client(https://github.com/kubernetes-client/java/tree/master/extended/src/main/java/io/kubernetes/client/extended/leaderelection).

Do we have plan to add it in C#?

**Comment by CarlosLanderas** [comment]
I was going to add the same feature requests. I have just finised the first beta of the AspNetCore HealthChecks operator and I need leader election to be able to have several replicas:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/src/HealthChecks.UI.K8s.Operator

Is there any way to implement this with this client right no?.

Thanks!

**Comment by tg123** [comment]
/remove-lifecycle stale

still working on it, busy there days
