### ISSUE TITLE
Code style checker before checking in

### ISSUE THREAD

**Issue by tg123** [kubernetes-client/csharp#37]
Sadly, C# did not have a `go fmt` yet.
A check tool before checking in is wanted.

the tool should include, but not limit to, those features:
 * naming convention
 * line coding (crlf / lf)
 * utf8 bom 
 * run on all platform (linux, mac, windows, ...)

some candidates:
https://github.com/dotnet/codeformatter
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

**Comment by sesispla** [comment]
Maybe [StyleCop.Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) is what we are looking for. Not sure if it can work with dotnet/cli, but worth to take a look.

StyleCop is the old guy helping us keep code uniform between developers, in the full Visual Studio/Windows world :)

Some [config examples](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md)

**Comment by tg123** [comment]
I will have a look too.

I am porting some tools to .net core

https://github.com/tg123/codeformatter
https://github.com/tg123/editorconfig-core-net

and working on a .net core version of eclint to combine those tools together.

**Comment by rahulrai-in** [comment]
Is this issue still open? I can see that .editorconfig file is present in the code. Is there anything else that needs to be done?

**Comment by tg123** [comment]
please see #187 
Will/May apply resharper code style checker

**Comment by rahulrai-in** [comment]
Why do we need to apply Resharper code style check? Would we like do away with .editorconfig?

**Comment by tg123** [comment]
`.editorconfig` is a place to store policy
a tool (resharper or something else) is need to enforce policies wthin `.editorconfig` are applied to all files

those policies might be a battle between

```
func {
}
```

and 
```
func
{
}
```

unluckily, there is no `go fmt` for dotnet at the moment.

**Comment by rahulrai-in** [comment]
Just wanted to make sure that I understand this correctly. Do we want to execute R# using the editorconfig on the solution then?

**Comment by tg123** [comment]
@rahulrai-in sorry for the unclear
Resharper would be one choice for code style checking tools
but it does not support `.editorconfig` as I know

I just want to use `Resharper` to act as code style checking tools via VSTS and the polices might be defined somewhere else.
