### ISSUE TITLE
Null Reference Exception returned in creating new V1PersistentVolumeClaim

### ISSUE THREAD

**Issue by jamesonatdell** [kubernetes-client/csharp#371]
I am running into an "Object reference not set to an instance of an object" exception when trying to create a new V1PersistentVolumeClaim object. I have compared it to my implementation in python, and it is the same code that works with the Kubernetes Python client. This happens locally and when deployed in Kubernetes.

I have checked over the K8s python client documentation as well, and I can't find any required fields I'm missing. As an extra measure, I hardcoded them in - I initially tried by passing them in as variables. Could anyone point me in the right direction?

Thank you in advance.

client.CreateNamespacedPersistentVolumeClaim(new V1PersistentVolumeClaim() {

{
                 ApiVersion = "v1",
                 Kind = "Service",
                 Metadata = new V1ObjectMeta()
                 {
                     Name = "testdeploymentcsharp",
                     NamespaceProperty = "workspace-name",
                     Labels = new Dictionary<string, string>()
                     {
                         { "app", "testdeploymentcsharp" }
                     }
                 },
                 Spec = new V1PersistentVolumeClaimSpec()
                 {
                     StorageClassName = "ci-storage-def",
                     Resources = new V1ResourceRequirements()
                     {
                         Requests = new Dictionary<string, ResourceQuantity>(){
                             {"storage", new ResourceQuantity("8Gi")}
                         }
                     },
                     AccessModes = { "ReadWriteOnce" }
                 }
             }
}, "namespace");

**Comment by brendandburns** [comment]
This is almost certainly a problem in JSON serialization.

Do you have a stack trace?

I will try to write a unit test that reproduces this.

**Comment by jamesonatdell** [comment]
Thank you. That is very kind of you!

I had a feeling too. Here is ex.StackTrace:

"   at orchestrator.Controllers.WorkspaceController.CreatePVC(String name, String namespaceName, String storageType, Int32 storageSize, Kubernetes client) in C:\\code\\projectfolder\\orchestrator\\orchestrator.api\\Controllers\\WorkspaceController.cs:line 292"

Not too useful...here is the message:

"Object reference not set to an instance of an object."

Not too useful either. :( Since It's a null reference, it throws on the object creation, not a specific field of the object, I think?

**Comment by tg123** [comment]
this is not stack from k8scharp any more trace?

**Comment by jamesonatdell** [comment]
I'm unsure how to get a different trace, one I debug over this object it throws the exception, and I cann ex.StackTrace...is there a more robust trace method?

**Comment by tg123** [comment]
@jamesonatdell 
could you please write a simple main only program which contains the code only that would reproduce your error?

then we can debug it and see what happen

**Comment by jamesonatdell** [comment]
Hi, apologies! Yes, I will make a tiny app that recreates this.

**Comment by NavidK0** [comment]
@jamesonatdell 

Hey there! I was running into the same issue today until I figured out that it was happening to me because I was using shorthand list syntax rather than explicitly defining the type.

In your code, you are using the shorthand in "AccessModes". Replace `AccessModes = { "ReadWriteOnce" }` with `AccessModes = new List<string> {"ReadWriteOnce"}` and it might just solve your issue.

```cs
client.CreateNamespacedPersistentVolumeClaim(new V1PersistentVolumeClaim
{
    ApiVersion = "v1",
    Kind = "Service",
    Metadata = new V1ObjectMeta
    {
        Name = "testdeploymentcsharp",
        NamespaceProperty = "workspace-name",
        Labels = new Dictionary<string, string>
        {
            {"app", "testdeploymentcsharp"}
        }
    },
    Spec = new V1PersistentVolumeClaimSpec
    {
        StorageClassName = "ci-storage-def",
        Resources = new V1ResourceRequirements
        {
            Requests = new Dictionary<string, ResourceQuantity>
            {
                {"storage", new ResourceQuantity("8Gi")}
            }
        },
        AccessModes = new List<string> {"ReadWriteOnce"}
    }
}, "namespace");
```

That being said, it definitely does seem like an internal serialization issue.
