### ISSUE TITLE
Using List...Async(watch: true) with HttpClientFactory the .Watch callback is never invoked

### ISSUE THREAD

**Issue by narthollis** [kubernetes-client/csharp#374]
I have setup a `Kubernetes` using a `HttpClient` from `HttpClientFactory`, and called one of the `List...Async` methods, passing `watch: true`. i have then setup the the watch callback using the extension methods
`resp.Watch((eventType, resource) => _logger.LogInformation("{type}, {resource}", eventType, resource))`
However my callback is never invoked - even when I add/remove a matching resource in the cluster.

If don't provide a `HttpClient` when constructing the `Kubernetes` object everything works as expected - The callback is initially invoked for all of the current resources, and then any add/remove/updates to the cluster also cause the callbacks to be called.

**Comment by brendandburns** [comment]
Odd. Do you know that the `HttpClient` is doing authentication correctly? It's possible that authentication is failing (though I would think you'd see an exception)

**Comment by tg123** [comment]
this is because it installed an watcher http handler, `WatcherDelegatingHandler`, to the client kubernetes client created.
it is not possible to install it for a customize httpclient.

but anyway,
the client sdk did not provide any solution for customized httpclient to install watcher handler.

let me think how to make this smoothly and friendly to use a pre created httpclient.

**Comment by narthollis** [comment]
> Odd. Do you know that the `HttpClient` is doing authentication correctly? It's possible that authentication is failing (though I would think you'd see an exception)

I assume Auth is working as if i try a `List...Async` without `watch:true` I get the expected result.

Would it be possible to add the `WatcherDelegatingHandler` using https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientbuilderextensions.addhttpmessagehandler?view=dotnet-plat-ext-3.1 do you think?

**Comment by tg123** [comment]
@narthollis not really i think, that one is for client builder not the client

**Comment by narthollis** [comment]
From what I can see it looks like `AddHttpMessageHandler` adds the callback to the `HttpMessageHandlerBuilderActions` collection on the `HttpClientFactoryOptions` for that named client.

This collection then appears to be read by HttpClientFactory for each HttpClient constructed

https://github.com/dotnet/extensions/blob/1286a6ff55e300352dabeb6d778c9fcdd258bd08/src/HttpClientFactory/Http/src/DefaultHttpClientFactory.cs#L190

**Comment by narthollis** [comment]
I have been able to confirm that using `.AddHttpMessageHandler(s => new WatcherDelegatingHandler());` resolves this issue.

I made a local clone of the repository and modified `src/KubernetesClient/WatcherDelegatingHandler.cs`, making `WatcherDelegatingHandler` public.

After building I used this local copy in my service and was able to use a HttpClientFactory constructed HttpClient and `List....Async().Watch(...)`

would it be possible to get a new build of this library with `WatcherDelegatingHandler` public?

**Comment by tg123** [comment]
or can you sent a PR let client library to handle it inside the library?

**Comment by narthollis** [comment]
I could see doing this setup with an extension method on `IHttpClientBuilder`

something like 

```csharp
public static IHttpClientBuilder AddKubernetesWatchHandler(this IHttpClientBuilder builder) {
    return builder.AddHttpMessageHandler(s => new WatcherDelegatingHandler());
}
```

This would resulting in a dependency on `Microsoft.Extensions.Http`

Outside of this I am not sure how to get the `WatcherDelegatingHandler` into the HttpClient.
