### ISSUE TITLE
ListNamespacedServiceWithHttpMessagesAsync with watch=true doesn't respect cancellation token with empty list

### ISSUE THREAD

**Issue by plisy** [kubernetes-client/csharp#375]
When trying to watch for service based on fieldSelector and the service doesn't exist, cancellation token is not respected and the call hangs.

``` C#
var cts = new CancellationTokenSource();
cts.CancelAfter(TimeSpan.FromSeconds(30));

var service = await KubernetesClient.ListNamespacedServiceWithHttpMessagesAsync(
                        namespaceParameter: DefaultNamespace,
                        fieldSelector: "metadata.name=non-existing-service",
                        watch: true,
                        cancellationToken: cts.Token);
```

KuberneteClient version: `1.6.12`

_Edit: Added timeout for cancellation token cancellation._

**Comment by tg123** [comment]
not throwing 404?
I am going to test locally

**Comment by plisy** [comment]
Unfortunately no, I think the watch param is causing it being stuck.

**Comment by brendandburns** [comment]
I believe that this is the expected behavior. It's wait for you to potentially create a service that matches that selector.

**Comment by plisy** [comment]
That's right the issue is that it doesn't respect the cancellation token, Once the cancellation token is cancelled, so should be the request.

**Comment by tg123** [comment]
the reason is that `StreamReader` does not take/support cancellation token.
I sent some workaround to make streamreader can handle such scenario.


BTW: typically, you may want to create a `watcher` with the response and would not notice something stuck inside the `watcher`
