### ISSUE TITLE
Errors and unexpected behavior with CustomObjects

### ISSUE THREAD

**Issue by Bliamoh** [kubernetes-client/csharp#380]
I'm trying to create a CRUD controller for CustomObjects. For the moment I can list and delete my CustomObjects but I'm having errors when using CreateNamespacedCustomObject() and PatchNamespacedCustomObject(). My CustomObjects are [ScaledObject from KEDA](https://github.com/kedacore/keda/blob/master/deploy/crds/keda.k8s.io_scaledobjects_crd.yaml). 

### CreateNamespacedCustomObject():

Here is the code I use:

``` 
ScaledObject so = new ScaledObject
{
	ApiVersion = "keda.k8s.io/v1alpha1",
	Kind = "ScaledObject",
	Metadata = new Metadata
	{
		Name = "my-scaledobject-name",
		Namespace = "default",
		Labels = new Labels
		{
			DeploymentName = "my-deploy-name"
		}
	},
	Spec = new Spec
	{
		ScaleTargetRef = new ScaleTargetRef
		{
			DeploymentName = "my-deploy-name"
		},
		PollingInterval = 5,
		CooldownPeriod = 10,
		MinReplicaCount = 2,
		MaxReplicaCount = 10,
		Triggers = new List<Trigger>
		{
			new Trigger
			{
				Type = "rabbitmq",
				Metadata = new TriggerMetadata
				{
					QueueName = "MyQueue",
					Host = "RabbitMqHost",
					QueueLength = "5"
				}
			}
		}
	}
};

_k8sClient.CreateNamespacedCustomObject(so, "keda.k8s.io", "v1alpha1", "default", "scaledobjects");
```

When executing it, I receive the following error:

```
"ScaledObject in version "v1alpha1" cannot be handled as a ScaledObject: unmarshalerDecoder: Object 'Kind' is missing in '{
  "ApiVersion": "keda.k8s.io/v1alpha1",
  "Kind": "ScaledObject",
  "Metadata": {
    "Labels": {
      "DeploymentName": "my-deploy-name"
    },
    "Name": "my-scaledobject-name",
    "Namespace": "default"
  },
  "Spec": {
    "CooldownPeriod": 10,
    "MaxReplicaCount": 10,
    "MinReplicaCount": 2,
    "PollingInterval": 5,
    "ScaleTargetRef": {
      "DeploymentName": "my-deploy-name"
    },
    "Triggers": [
      {
        "Metadata": {
          "Host": "RabbitMqHost",
          "QueueLength": "5",
          "QueueName": "MyQueue"
        },
        "Type": "rabbitmq"
      }
    ]
  }
}', error found in #10 byte of ...| ]
  }
}|..., bigger context ...|        "Type": "rabbitmq"
      }
    ]
  }
}|..."
```

I don't understand why the 'Kind' filed if not recognized... 

Since CreateNamespacedCustomObject() can use 'object' or JSON string as parameter, I also tried to convert my object in JSON string but I also have an error, though it's a different one: 

```
"the object provided is unrecognized (must be of type ScaledObject): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" } (227b5c2261706956657273696f6e5c223a5c226b6564612e6b38732e696f ...)"
```

### PatchNamespacedCustomObject():

Unlike the classic Kubernetes objects Patch methods that take a V1Patch object as parameter, the PatchNamespacedCustomObject takes an object as parameter. So I tried to use it like that:

```
_k8sClient.PatchNamespacedCustomObject(myModifiedScaledObject, "keda.k8s.io", "v1alpha1", "default", "scaledobjects", "my-scaledobject-name");
```

Where myModifiedScaledObject contains all the original values of the ScaledObject I want to update but Spec.MinReplicaCount changed from "2" to "3". 
It seems to work fine but **before** I execute this code my ScaledObject looked like that:

```
Name:         my-scaledobject-name
Namespace:    default
Labels:       deploymentName=my-deploy-name
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"keda.k8s.io/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"labels":{"deploymentName":"my-deploy-name"},"name...
API Version:  keda.k8s.io/v1alpha1
Kind:         ScaledObject
Metadata:
  Creation Timestamp:  2020-03-23T13:21:14Z
  Generation:          1
  Resource Version:    1531698
  Self Link:           /apis/keda.k8s.io/v1alpha1/namespaces/default/scaledobjects/my-scaledobject-name
  UID:                 4caf3f76-0ab9-44f3-81b7-9cb101238bce
Spec:
  Cooldown Period:    10
  Max Replica Count:  10
  Min Replica Count:  2
  Polling Interval:   5
  Scale Target Ref:
    Deployment Name:  my-deploy-name
  Triggers:
    Metadata:
      Host:          RabbitMqHost
      Queue Length:  5
      Queue Name:    MyQueue
    Type:            rabbitmq
Events:              <none>
```

And **after** the code execution, my ScaledObject looks like that:

```
Name:         my-scaledobject-name
Namespace:    default
Labels:       deploymentName=my-deploy-name
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"keda.k8s.io/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"labels":{"deploymentName":"my-deploy-name"},"name...
Metadata:
  Name:  my-scaledobject-name
Spec:
  Cooldown Period:    10
  Max Replica Count:  10
  Min Replica Count:  3
  Polling Interval:   5
  Scale Target Ref:
    Deployment Name:  my-deploy-name
  Triggers:
    Metadata:
      Host:          RabbitMqHost
      Queue Length:  5
      Queue Name:    MyQueue
API Version:         keda.k8s.io/v1alpha1
Kind:                ScaledObject
Metadata:
  Creation Timestamp:  2020-03-23T13:21:14Z
  Generation:          2
  Resource Version:    1531875
  Self Link:           /apis/keda.k8s.io/v1alpha1/namespaces/default/scaledobjects/my-scaledobject-name
  UID:                 4caf3f76-0ab9-44f3-81b7-9cb101238bce
Spec:
  Cooldown Period:    10
  Max Replica Count:  10
  Min Replica Count:  2
  Polling Interval:   5
  Scale Target Ref:
    Deployment Name:  my-deploy-name
  Triggers:
    Metadata:
      Host:          RabbitMqHost
      Queue Length:  5
      Queue Name:    MyQueue
    Type:            rabbitmq
Events:              <none>
```

So all the fields have been duplicated. Even if we can see that there is a field "Spec.MinReplicaCount: 3", it didn't override the old values as I expected.

Since I couldn't find any example on how to manage CustomObjects I don't know if I'm doing it wrong or if it's a bug from the kubernetes client.

**Comment by brendandburns** [comment]
I think this is due to case sensitivity. It should be `kind: foo` not `Kind: Foo`

**Comment by Bliamoh** [comment]
Only my property name has a uppercase. When I serialize it in JSON I get this string which has keys in lowercase: 
```
"{\"apiVersion\":\"keda.k8s.io/v1alpha1\",\"kind\":\"ScaledObject\",\"metadata\":{\"labels\":{\"deploymentName\":\"my-deploy-name\"},\"name\":\"my-scaledobject-name\",\"namespace\":\"default\"},\"spec\":{\"cooldownPeriod\":10,\"maxReplicaCount\":10,\"minReplicaCount\":2,\"pollingInterval\":5,\"scaleTargetRef\":{\"deploymentName\":\"my-deploy-name\"},\"triggers\":[{\"metadata\":{\"host\":\"RabbitMqHost\",\"queueLength\":\"5\",\"queueName\":\"MyQueue\"},\"type\":\"rabbitmq\"}]}}"
``` 
I also tried to put a string with keys in uppercase but I get the same error. 
Here is my deserialized object, maybe it could help:

```
public class ScaledObject
{
	[JsonPropertyName("apiVersion")]
	public string ApiVersion { get; set; }

	[JsonPropertyName("kind")]
	public string Kind { get; set; }

	[JsonPropertyName("metadata")]
	public Metadata Metadata { get; set; }

	[JsonPropertyName("spec")]
	public Spec Spec { get; set; }
}

public class Metadata
{
	[JsonPropertyName("labels")]
	public Labels Labels { get; set; }

	[JsonPropertyName("name")]
	public string Name { get; set; }

	[JsonPropertyName("namespace")]
	public string Namespace { get; set; }
}

public class ScaleTargetRef
{
	[JsonPropertyName("deploymentName")]
	public string DeploymentName { get; set; }
}

public partial class Labels
{
	[JsonPropertyName("deploymentName")]
	public string DeploymentName { get; set; }
}

public class Spec
{
	[JsonPropertyName("cooldownPeriod")]
	public int CooldownPeriod { get; set; }

	[JsonPropertyName("maxReplicaCount")]
	public int MaxReplicaCount { get; set; }

	[JsonPropertyName("minReplicaCount")]
	public int MinReplicaCount { get; set; }

	[JsonPropertyName("pollingInterval")]
	public int PollingInterval { get; set; }

	[JsonPropertyName("scaleTargetRef")]
	public ScaleTargetRef ScaleTargetRef { get; set; }

	[JsonPropertyName("triggers")]
	public List<Trigger> Triggers { get; set; }
}

public class Trigger
{
	[JsonPropertyName("metadata")]
	public TriggerMetadata Metadata { get; set; }

	[JsonPropertyName("type")]
	public string Type { get; set; }
}

public class TriggerMetadata
{
	[JsonPropertyName("host")]
	public string Host { get; set; }

	[JsonPropertyName("queueLength")]
	public string QueueLength { get; set; }

	[JsonPropertyName("queueName")]
	public string QueueName { get; set; }
}
```

I'm using System.Text.Json.Serialization to manage my JSON serialization/deserialization but I also tried with Newtonsoft.Json but it didn't change anything.

**Comment by brendandburns** [comment]
I was judging by the error message that you printed above:

```
"ScaledObject in version "v1alpha1" cannot be handled as a ScaledObject: unmarshalerDecoder: Object 'Kind' is missing in '{
  "ApiVersion": "keda.k8s.io/v1alpha1",
  "Kind": "ScaledObject",
  "Metadata": {
...
```

In that error message, the field names are definitely capitalized, so perhaps the serialization isn't working as expected?

**Comment by Bliamoh** [comment]
Ok I managed to fix my issue. Indeed it was a problem with capitalized fields and a misunderstanding of [this comment ](https://github.com/kubernetes-client/csharp/issues/295#issuecomment-541810513). I thought that CustomObject methods could accept object **OR** JSON string as parameter... My bad.

However, to fix my issue I had to rename all my properties with lowercase to match the case expected by Kubernetes. Though, it is breaking the [capitalization conventions of C#](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions#capitalization-rules-for-identifiers). 
Is there a way to respect the capitalization conventions of C# by keeping my properties like this:
```
[JsonPropertyName("kind")]
public string Kind { get; set; }
```
instead of this:
```
[JsonPropertyName("kind")]
public string kind { get; set; }
```
and still have the CustomObject methods working? 
Actually, having CustomObject methods that accept JSON string as well as 'object' type would let the user the choice of what to use:
- the easy way with 'object' type if the properties are correctly named
- the little longer way with a JSON string serialization to do before using the CustomObject method

**Comment by andykernahan** [comment]
> Is there a way to respect the capitalization conventions of C# ...

I suspect that Newtonsoft is not aware of the `JsonPropertyNameAttribute` and hence does not respect it.

Is it possible for you to use the Newtonsoft attributes instead? (see [`V1Pod`](https://github.com/kubernetes-client/csharp/blob/c48fc0dc562908e5eab78cb825b9a6a1240c2ea0/src/KubernetesClient/generated/Models/V1Pod.cs#L80) for example):
```csharp
[Newtonsoft.Json.JsonPropertyAttribute(PropertyName = "kind")]
public string Kind { get; set; }
```
Newtonsoft also respects the data contract attributes, if you prefer not to take the Newtonsoft dependency:
```csharp
[System.Runtime.Serialization.DataMemberAttribute(Name = "kind")]
public string Kind { get; set; }
```

**Comment by Bliamoh** [comment]
Yes that's what I just discovered. I don't know what I did wrong last time when I tried to use Newtonsoft.Json instead of System.Text.Json.Serialization but now it's working just fine! Looks like the attribut [System.Text.Json.Serialization.JsonPropertyName("kind")] is not supported by Newtonsoft. 
Thx both of you for the help. I'm closing this.
