### ISSUE TITLE
Watcher thread utilisation.

### ISSUE THREAD

**Issue by andykernahan** [kubernetes-client/csharp#381]
Currently each `Watcher` instance causes a thread to be blocked until the next `WatchEvent` is read from the HTTP connection. In a system where there are many `Watcher` instances, this may cause the number of threads to grow large.

I believe this behaviour is caused by `WatcherDelegatingHandler` (and its related types) not being asynchronous all the way. The following (abbreviated) call graph illustrates this:
```
Watcher.WatcherLoop
 PeekableStreamReader.ReadLineAsync
  StreamReader.ReadLineAsync
   TextReader.ReadLineAsync               // (1) starts task
    PeekableStreamReader.ReadLine         // (2)
     CancelableStream.Read                // waits
      ChunkedEncodingReadStream.ReadAsync // (3)
```
The task (and its thread) started by 1 to asynchronously invoke 2 is ultimately blocked waiting for 3.

We can observe this behaviour by viewing the parallel stacks after creating ten `Watcher` instances:
```csharp
public async Task WatcherThreadBehaviour()
{
    using (var server = new MockKubeApiServer(testOutput, async httpContext =>
    {
        httpContext.Response.StatusCode = 200;
        await httpContext.Response.Body.FlushAsync();
        await Task.Delay(Timeout.Infinite);
        return true;
    }))
    {
        var client = new Kubernetes(new KubernetesClientConfiguration
        {
            Host = server.Uri.ToString()
        });
        for (int i = 0; i < 10; i++)
        {
            client.ListNamespacedPodWithHttpMessagesAsync("default", watch: true)
                  .Watch<V1Pod, V1PodList>(delegate { });
        }
        await Task.Delay(Timeout.Infinite);
    }
}
```
We observe the ten blocked threads:

![parallel stacks](https://user-images.githubusercontent.com/63398/77347159-51b61780-6d2f-11ea-977f-4a276c1c66bb.png)

Note this behaviour predates #376, prior to which we observed the following:
```
Watcher.WatcherLoop
 PeekableStreamReader.ReadLineAsync
  StreamReader.ReadLineAsync
   TextReader.ReadLineAsync         // (1) starts task
    PeekableStreamReader.ReadLine   // (2)
     ChunkedEncodingReadStream.Read // (3)
```
![parallel stacks](https://user-images.githubusercontent.com/63398/77346934-ee2bea00-6d2e-11ea-872c-a53ff31e3112.png)

I believe it possible to eliminate this behaviour by making `WatcherDelegatingHandler` asynchronous all the way. I'm happy to undertake this change, or liaise with @tg123 to effect it?

**Comment by tg123** [comment]
PR is warmly welcomed

I checked the code
https://referencesource.microsoft.com/#mscorlib/system/io/textreader.cs,198

do you mean to replace the `textreader`?

**Comment by andykernahan** [comment]
I believe that we can retain the use of `TextReader`. However, as we [cannot](https://referencesource.microsoft.com/#mscorlib/system/io/streamreader.cs,792) derive from `SteamReader` introducing this issue, I propose we make `PeekableStreamReader` a decorator instead.
