### ISSUE TITLE
Duplicate Null Check in WebSocketNamespacedPodExecAsync in Kubernetes.WebSocket.cs

### ISSUE THREAD

**Issue by tylerje** [kubernetes-client/csharp#382]
Line 65 has a duplicate null check for the command param. It can be removed given the same code is on line 55.

**Comment by tg123** [comment]
Yes it is
BTW Could you please send a PR for it?

**Comment by tylerje** [comment]
Yes. Will have it submitted in a few minutes.

**Comment by tylerje** [comment]
@tg123 I've submitted the PR but looks like LF not finding my user. Could be because the PR was created under my org "tylerjensen" rather than my personal GitHub account?

**Comment by tg123** [comment]
@tylerje 
I think so.
`git amend` and `push -f`

**Comment by tylerje** [comment]
@tg123 -- was able to resolve the CLA issue. It's ready for review now.

**Comment by brendandburns** [comment]
Closing this issue since 384 merged.
