### ISSUE TITLE
Environment variable values are not coerced to strings during serialization

### ISSUE THREAD

**Issue by ridhoq** [kubernetes-client/csharp#387]
Hello, I am currently manipulating yaml configurations and ran into an issue where environment variable values containing ints and bools were not correctly being coerced to strings.

I have created a failing test case here: https://github.com/ridhoq/csharp/blob/201e2be09b1fb30fe86cc68ff65aaeb4f1141a21/tests/KubernetesClient.Tests/YamlTests.cs#L325

The test output results in:
 ```
k8s.Tests.YamlTests.EnvVariableShouldBeStrings

Assert.Equal() Failure
                                  ↓ (pos 111)
Expected: ···: PORT\n      value: "3000"\n    image: vish/stress\n    name: c···
Actual:   ···: PORT\n      value: 3000\n    image: vish/stress\n    name: cpu···
                                  ↑ (pos 111)
   at k8s.Tests.YamlTests.EnvVariableShouldBeStrings() in /Users/ridwan/git/csharp/tests/KubernetesClient.Tests/YamlTests.cs:line 343
```
In this case, the integer value in an environment variable value will break yaml validation.

1. Can a maintainer help me confirm that this is actually a bug?
2. I am happy to submit a PR if it is a bug. In order to submit a fix, I need to better understand how `YamlDotNet` is being used in the `SaveToString<T>(T value)` method. Does anybody have any pointers on how to proceed debugging this?

**EDIT** - clarifying that the issue is for environment variables specifically

**Comment by tg123** [comment]
I think this is a yaml related
quotes is not required in yaml even for string

**Comment by austinpray** [comment]
This definitely smells like a yaml parsing library silently allowing undefined behavior

https://github.com/ridhoq/csharp/blob/201e2be09b1fb30fe86cc68ff65aaeb4f1141a21/tests/KubernetesClient.Tests/YamlTests.cs#L327-L337

In ruby:

```ruby
require 'yaml'

muh_yaml = <<-YAML
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"
YAML

pp YAML.load(muh_yaml)
```

I get 

```
{"apiVersion"=>"v1",
 "kind"=>"Pod",
 "metadata"=>
  {"name"=>"envar-demo", "labels"=>{"purpose"=>"demonstrate-envars"}},
 "spec"=>
  {"containers"=>
    [{"name"=>"envar-demo-container",
      "image"=>"gcr.io/google-samples/node-hello:1.0",
      "env"=>
       [{"name"=>"DEMO_GREETING", "value"=>"Hello from the environment"},
        {"name"=>"DEMO_FAREWELL", "value"=>"Such a sweet sorrow"}]}]}}
```

now if I do

```diff
     env:
     - name: DEMO_GREETING
-       value: "Hello from the environment"
+       value: ""Hello from the environment""
```

I get 

```
Traceback (most recent call last):
	4: from /tmp/test.rb:21:in `<main>'
	3: from /home/austin/.rbenv/versions/2.7.0/lib/ruby/2.7.0/psych.rb:277:in `load'
	2: from /home/austin/.rbenv/versions/2.7.0/lib/ruby/2.7.0/psych.rb:390:in `parse'
	1: from /home/austin/.rbenv/versions/2.7.0/lib/ruby/2.7.0/psych.rb:456:in `parse_stream'
/home/austin/.rbenv/versions/2.7.0/lib/ruby/2.7.0/psych.rb:456:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 12 column 7 (Psych::SyntaxError)
```

Googling for yaml validators online they seem to all throw a fit with your testcase. Wrapping in single quotes like `'"3000"'` does net me a string with a value `"3000"` in several languages though.

**Comment by ridhoq** [comment]
> I think this is a yaml related
> quotes is not required in yaml even for string

Hi @tg123! 

The resulting yaml in from the test case is:
```
apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
  - env:
    - name: PORT
      value: 3000
    image: vish/stress
    name: cpu-demo-ctr
```
While quotes are not needed, it does not pass validation when using something like https://kubeyaml.com/ as shown in the screenshot:
![image](https://user-images.githubusercontent.com/943533/77809212-cdc89c00-705c-11ea-9610-9b27844f1d06.png)

This makes me think this is a bug.

**Comment by tg123** [comment]
I believe it is not a bug
We did not use the library to `generate` yaml, instead, only to load yaml config.

**Comment by brendandburns** [comment]
ports are IntOrStr so either int or string is valid

https://godoc.org/k8s.io/apimachinery/pkg/util/intstr

I think the kubeyaml validator has a bug.

**Comment by ridhoq** [comment]
Hi @brendanburns!

My example is a bit vague so allow me to clarify

The bug has to do strictly **environment variables** in a container spec block. As seen [here](https://godoc.org/k8s.io/api/core/v1#EnvVar), the environment variable value must strictly be a string. In my input, I set the environment variable named `PORT` to the value `"3000"`. I deserialize the object and reserialize it (without any modification) using `Yaml.SaveToString<T>(T value)`. The resulting value is `3000` without quotes. When this configuration gets applied to the cluster, it is evaluated as type `int` and validation fails as seen in the kubeyaml validator.

Please let me know if that logic follows.

**Comment by brendandburns** [comment]
Ah, sorry for my mistake, I was skimming your YAML.

This seems to be a bug in YamlDotNet:
https://github.com/aaubry/YamlDotNet/issues/33

I will dig around in the library and see if there is a way to handle it better, we may need a custom serializer for environment variables.

**Comment by brendandburns** [comment]
fwiw, you can use the `!!str` tag to force this in the output but clearly that's not ideal.

**Comment by ridhoq** [comment]
No worries! Thanks for finding that issue on `YamlDotNet` - very surprising that this has been around since 2013...

One thing to note is that this behavior is not limited to `int`. If we have an environment variable set to `"true"` and deserialize it, it will be just `true` and validation will fail. So a fix will likely need to be aware of the underlying type. Another thing to note that this issue is not strictly restricted to environment variables, but also for other string types such as annotations.

WRT a workaround: I am currently using the following code:

```csharp
        // see yaml spec to for more on explicit type tagging:
        // https://yaml.org/spec/1.2/spec.html#id2761292
        private static readonly string _explictStrYamlTag = "!!str ";

        public static string StringifyValue(string value)
        {
            return $"{_explictStrYamlTag}{value}";
        }
```
I pass environment variable values as well as annotation values to the that function. And at the very end of my processing, I strip the `!!str` anywhere it exists.

```csharp
fileText.Replace(_explictStrYamlTag, string.Empty);
```

This solution makes me sad, but, I am not sure what the else can be done. Again, I'm happy to submit a fix, but I'd like some guidance about how the library generally wants to handle these types of cases. I'm also interested in how other client libraries are handling this.

**Comment by ridhoq** [comment]
Actually, looks like this PR solves the issue well enough: https://github.com/cloudbase/powershell-yaml/pull/41

Wonder if this type of fix should make it upstream to `YamlDotNet`. If not, perhaps we can implement something like this here?

**Comment by ridhoq** [comment]
I pinged the aaubry/YamlDotNet#33 issue, and it looks like the suggestion is to implement an event emitter from cloudbase/powershell-yaml#41. Any objections to a solution like this before I proceed?
