### ISSUE TITLE
Have better support for custom operations

### ISSUE THREAD

**Issue by admilazz** [kubernetes-client/csharp#391]
The Kubernetes client has poor support for custom query-string values, subobjects, or actions.

1. To insert a query-string value, you need to create a new client for the request and inject an HTTP request handler that parses and modifies the URI of the request as it passes through. Very ugly.
2. To operate on a subobject, you need to have knowledge of the Kubernetes client implementation details and inject unrelated stuff into the Kind or Name so that the correct URL gets constructed from the various pieces.
3. To invoke a custom action, you need to fake it with other requests. For example, to send a POST request you hack it by "creating" something (since the Create... methods happen to use POST requests). Some requests are not possible to send at all.
4. The client has a very limited set of supported HTTP status codes. For example, a custom action that returns 202 Accepted will cause an exception to be thrown.

My recommendation is to expose a low-level client in addition to the high-level client. I have implemented something like this myself, and it works like this. Despite being low-level, it's often less verbose than the current high-level API.

````
// these are all roughly equivalent
KubernetesResponse resp;
resp = await client.New(pod).Put().ExecuteAsync(cancelToken);
resp = await client.New<V1Pod>(ns: "test").Put().SetBody(pod).ExecuteAsync();
resp = await client.New(HttpMethod.Post, "pods", "test", "podName").
    .SetBody(pod).ExecuteAsync();
resp = await client.New(HttpMethod.Post, "pods", "test", "podName", "v1", "").
    .SetBody(pod).ExecuteAsync();
resp = await client.New().SetMethod(HttpMethod.Post).SetType("pods").SetVersion("v1")
    .SetNamespace("test").SetName("podName").SetBody(pod).ExecuteAsync();

KubernetesRequest req =
    new KubernetesRequest(client) { Method = HttpMethod.Post, Type = "pods" , ... };
resp = await req.ExecuteAsync();

// requests can be used repeatedly, or cloned and modified
resp = await req.ExecuteAsync(); // send it again (multiple executions can be done in parallel)

class MyClass
{
    public MyClass(KubernetesRequest req) => this.req = req.Clone().SetQuery("foo", "bar");
    ...
}

// errors do not cause exceptions and all information from the response is accessible
if(resp.IsNotFound) { ... }
else if(resp.IsError) { V1Status status = resp.GetError(); ... }
else if(resp.StatusCode == HttpStatusCode.Accepted) { ... }
else { var pod = resp.GetBody<V1Pod>(); ... }

// you can also customize other things
KubernetesRequest req = client.New(myobj).Subresource("password")
    .SetContentType("text/plain").SetBody("secret").Put();

req = client.New(myobj).Subresource("password").SetAccept("text/plain").SetBody(null)
    .SetHeader("x-whatever", value)
    .SetQuery("key", "value")
    .SetQuery("key", "value2");

// it supports watches as well.
// watch changes to 'myobj', restarting and handling 410 Gone as needed
watch = new Watch<MyType>(client.New(myobj));
watch.OnEvent += xxx;
watch.Start();

// watch changes to lists of objects, in a namespace or in all namespaces
watch = new Watch<MyType>(client.New<MyType>().SetNamespace("test"));
watch = new Watch<MyType>(client.New<MyType>());

// a lower-level watch interface that doesn't handle automatic restarting, 410 Gone, etc.
wr = new WatchReader(await client.New(myobj).WatchVersion("").ExecuteAsync());
while(await wr.ReadAsync()) { ... }
````

**Comment by valorl** [comment]
Yes, I was thinking about making an issue for this too recently. An "unstructured" or "low level" client where we can simply query/watch an api+group+kind and deserialize it ourselves would be really nice.

**Comment by admilazz** [comment]
Alternately, you could add some methods like Delete, Get, Post, Patch, etc. that match the current more monolithic style, e.g.
````
KubernetesResponse Post(body, group, version, type, ns, name, subresource, query, headers, ...)
KubernetesResponse Raw(method, requestUri, headers, body)
````

Nonetheless, I personally prefer the fluent style of client and will consider sending a PR for it, since it's useful for things other than custom requests.

**Comment by brendandburns** [comment]
I'd be happy for someone to add a `RawRequest` method similar to the Raw method here:

https://github.com/kubernetes-client/javascript/blob/master/examples/raw-example.js#L10

The code itself is mostly generated so we can't modify the client.

**Comment by macsux** [comment]
Liek this?
https://github.com/macsux/kubernetes-client-csharp/blob/feature/rx-informers/src/KubernetesClient/Kubernetes.Generic.cs

**Comment by admilazz** [comment]
> Like this?

From the looks of it, 1) it only supports listing (though it may be just one example), 2) it expects a certain form of list in the response, 3) it doesn't support custom request URLs or subresources, 4) it doesn't support custom query-string parameters, and 4) it only allows 200 OK responses (which may be okay for listing but not in general).

**Comment by admilazz** [comment]
I added this as a [separate project](https://github.com/AdamMil/KubernetesClient.Fluent) for now.
