### ISSUE TITLE
 the kubernetes client corresponds to the Kubernetes version

### ISSUE THREAD

**Issue by badounan** [kubernetes-client/csharp#40]
I am very pleased to be able to see c# version of the kubernetes client.

But I do not know what version of the corresponds.

Can I use this client when my kubernetes version is 1.6.2?

I have found some issues. The status code of the return interface does not seem to be too right.

**Comment by brendandburns** [comment]
What nuget package are you using?  This is generated from a 1.8.x Swagger spec, but I believe that it should work correctly with 1.6.2.

Can you send a stack trace for the error you are seeing?

Thanks!

**Comment by badounan** [comment]
I was using the source code before the realese. The status code is not clear between 200 and 201 when create pod.
My english is poor. I will send a stack trace later.

**Comment by badounan** [comment]
I got http status code 415 when created pod. Then i changed the content-type to application/json, it became better.
That's why?

**Comment by brendandburns** [comment]
the 201 vs 200 thing should be fixed at head (and I think in the latest nuget package...)

**Comment by badounan** [comment]
thank you very much

**Comment by brendandburns** [comment]
Closing this, please re-open if you run into problems.
