### ISSUE TITLE
KubernetesClientConfiguration.BuildDefaultConfig does not handle multiple files specified by KUBECONFIG env-var

### ISSUE THREAD

**Issue by rynowak** [kubernetes-client/csharp#409]
From the k8s docs:

> The KUBECONFIG environment variable holds a list of kubeconfig files. For Linux and Mac, the list is colon-delimited. For Windows, the list is semicolon-delimited. The KUBECONFIG environment variable is not required. If the KUBECONFIG environment variable doesn’t exist, kubectl uses the default kubeconfig file, $HOME/.kube/config.

> If the KUBECONFIG environment variable does exist, kubectl uses an effective configuration that is the result of merging the files listed in the KUBECONFIG environment variable.

It looks like this has just yet to be implemented. 

[This code](https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs#L41) assumes that the KUBECONFIG env-var only contains a single filename. 

The result is that if you've got multiple files (on Windows at least) you'll get an exception saying that the file could not be found. (After attempting to find a file matching the env-var verbatim).

Originally reported here: https://github.com/dotnet/tye/issues/351

**Comment by brendandburns** [comment]
Yeah, the `KUBECONFIG` merging logic is super-complicated and not defined anywhere. It's basically only defined in the golang code that actually does the merge.

What specific merging are you looking for? It wouldn't be hard to add some simplistic merging (e.g. merge-if-not-present) but it won't exactly match what the Golang client does.

**Comment by jkotalik** [comment]
Probably just a simple merging (merge-if-not-present) is fine for now. I'd be willing to contribute this 😄 .

I'm reading some of the docs for the rules for merging kubeconfig with an environment variable, and it sounds like the goal of it was [to be a simple merge-if-not-present]( https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#merging-kubeconfig-files).

>Otherwise, if the KUBECONFIG environment variable is set, use it as a list of files that should be merged. Merge the files listed in the KUBECONFIG environment variable according to these rules:
>  - Ignore empty filenames.
>  - Produce errors for files with content that cannot be deserialized.
>  - The first file to set a particular value or map key wins.
>  - Never change the value or map key. Example: Preserve the context of the first file to set current-context. Example: If two files specify a red-user, use only values from the first file’s red-user. Even if the second file has non-conflicting entries under red-user, discard them.

Has the Golang client evolved past these rules at this point?

**Comment by rynowak** [comment]
@brendanburns - is this the logic you're referring to? https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/loader.go#L176

I did a brief tour and it looks like the Java and Go kubernetes-client packages don't implement this either. AFAIK the go library would fail in the same way .NET does, and the Java library would log a warning and continue with just the first file.

---

Per @jkotalik's comments - I think if we able to do a merge-if-not present that would be more useful than crashing.

it sounds like the **exact** semantics of what *merge* means, are tied up in how this library works: https://github.com/imdario/mergo#usage
