### ISSUE TITLE
No implementation for kubectl top node / top pod

### ISSUE THREAD

**Issue by RSBlek** [kubernetes-client/csharp#416]
For simple logging / monitoring there should be a method to get the cpu and ram metrics of nodes and pods that are provided by the kubectl top node &kubectl top pod commands.

I couldn't find a direct call to that command. Is there a possible workaround that i can use to get the metrics of a node?

**Comment by brendandburns** [comment]
There's no specific API call for `kubectl top` it's actually a pretty complicated piece of logic inside of kubectl.

You can use the CustomObjects API to pull the metrics directly from the metrics server.

There's a discussion here:
https://github.com/kubernetes-client/java/issues/675

with pointers to the relevant `kubectl` code.

We'd take a PR for this if you want to write it.

**Comment by RSBlek** [comment]
@brendanburns Thanks, the CustomObjects API in conjunction with the metrics server was just what i was looking for. 

For readers:

The following can be used as "quickfix" to get the node metrics. I think that reading the pod metrics will work the same

```
    public class NodeMetrics
    {
        [JsonProperty(PropertyName = "metadata")]
        public V1ObjectMeta Metadata { get; set; }

        [JsonProperty(PropertyName = "timestamp")]
        public DateTime Timestamp { get; set; }

        [JsonProperty(PropertyName = "window")]
        public String Window { get; set; }

        [JsonProperty(PropertyName = "usage")]
        public IDictionary<string, ResourceQuantity> Usage { get; set; }
    }
```
```
    public class NodeMetricsList
    {
        [JsonProperty(PropertyName = "apiVersion")]
        public string ApiVersion { get; set; }

        [JsonProperty(PropertyName = "kind")]
        public string Kind { get; set; }

        [JsonProperty(PropertyName = "metadata")]
        public V1ObjectMeta Metadata { get; set; }

        [JsonProperty(PropertyName = "items")]
        public IEnumerable<NodeMetrics> Items { get; set; }
    }
```
```
Kubernetes client = ...
JObject customObject = (JObject)await client.GetClusterCustomObjectAsync("metrics.k8s.io", "v1beta1", "nodes", "");
NodeMetricsList nodeMetricsList = customObject.ToObject<NodeMetricsList>();
```

**Comment by brendandburns** [comment]
Cool, glad it worked! If you want to get this into a PR, we'd happily take the addition.

**Comment by alarco-l** [comment]
If it's up to grab, i'm willing to help on this one as first contribution.

If I understand correctly, the metrics from `metrics server` are not included in the openapi use to generate csharp client code.

As it will not be generated and metrics are not config (`KubeConfigModels` folder), i'm not sure where I have to put the model class for `NodeMetrics`, `NodeMetricsList`, `PodMetrics` and `PodMetricsList`.

Also is the `Extensions.cs` file, the correct place to put extensions methods for `nodes metrics`, `nodes metrics by namespace`, `pods metrics` and `pods metrics by namespace` using either `GetClusterCustomObjectAsync` or `GetNamespacedCustomObjectAsync` ?

```csharp
// PodMetricsList
var customObject = (JObject)await client.GetNamespacedCustomObjectAsync("metrics.k8s.io", "v1beta1", "NAMESPACE_NAME", "pods", "");

var customObject = (JObject)await client.GetClusterCustomObjectAsync("metrics.k8s.io", "v1beta1", "pods", "");

// NodeMetricsList
var customObject = (JObject)await client.GetNamespacedCustomObjectAsync("metrics.k8s.io", "v1beta1", "NAMESPACE_NAME", "nodes", "");

var customObject = (JObject)await client.GetClusterCustomObjectAsync("metrics.k8s.io", "v1beta1", "nodes", "");
```

My last question, is about the naming of models class, should be named like generated code `V1beta1NodeMetrics` or simply `NodeMetrics` ?

**Comment by tg123** [comment]
close as #466
