### ISSUE TITLE
Autogenerated OpenAPI schema classes don't work as expected

### ISSUE THREAD

**Issue by macsux** [kubernetes-client/csharp#417]
CustomResourceDefinition includes support for specifying OpenAPI schema. The generated classes that define the model for OpenAPI seem to be having issues with some types of common schema semantics. Here's an OpenAPI schema as generated by NJsonSchema

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "MyCustomResource",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "spec": {
      "x-nullable": true,
      "oneOf": [
        {
          "$ref": "#/definitions/MyCustomResourceSpec"
        }
      ]
    },
    "status": {
      "x-nullable": true,
      "oneOf": [
        {
          "$ref": "#/definitions/MyCustomResourceStatus"
        }
      ]
    }
  },
  "definitions": {
    "MyCustomResourceSpec": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "value": {
          "type": "string",
          "x-nullable": true
        },
        "item": {
          "type": "string",
          "x-nullable": true
        },
        "Replicas": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "MyCustomResourceStatus": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Replicas": {
          "type": "integer",
          "format": "int32"
        }
      }
    }
  }
}
```
When we try to deserialize this into V1beta1JSONSchemaProps ex.`JsonConvert.DeserializeObject<V1beta1JSONSchemaProps>(schema.ToJson())`, it generates a single item in `Properties["spec"].OneOf` with null value. This is incorrect and should have resulted in value being another `V1beta1JSONSchemaProps` with `RefProperty` set to what we see as part of the `$ref` in the schema.

This is currently acting as a bottleneck for a PR I was getting ready to submit that allows generating and installing CRDs, but I suspect will cause the same issue when trying to read `CustomResourceDefinition` from API server as it will fail correct deserialization (and can potentially corrupt the CRD if used to modify its structure).

**Comment by brendandburns** [comment]
Take a look at the spec here:
https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

I think the issue is that v1beta1.JSONSchemaProps is JSONSchema, not OpenAPI.

v1.JSONSchemaProps is OpenAPI v3

There's a big discussion here:
https://github.com/kubernetes/kubernetes/issues/49879

So I think you need to use the `v1JSONSchemaProps` object:
https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/generated/Models/V1JSONSchemaProps.cs

and I _think_ it will work.

**Comment by macsux** [comment]
But you can't really use a different version - the type is hardcoded as part of the object tree. It appears as part of `V1beta1CustomResourceDefinition` in `Spec.Validation.OpenAPIV3Schema` and `Spec.Versions.Schema.OpenAPIV3Schema`. This bug essentially makes it impossible to do CRDs for v1beta1 k8s using the using models.

**Comment by macsux** [comment]
We could probably fix this up by changing the type of the two places mentioned above to the V1 type. This can be done as part of the c# second phase gen project

**Comment by macsux** [comment]
I checked the newer type (V1) and it has the same issue. I propose the following:
1. Replace autogenerated type with JsonSchema from NJsonSchema package (it's already referenced as part of CustomResources PR)
2. Attach a custom converter to properly serialize/deserialize JsonSchema as the property of the object tree

**Comment by macsux** [comment]
Ok, I got the bottom of this whole thing. Kubernetes does not support `$ref` as normal JsonSchema or OpenAPI do. See ongoing issue https://github.com/kubernetes/kubernetes/issues/54579
 Therefore any schemas being created/generated need to be massaged to inline schemas (which does work with the autogenerated classes).
