### ISSUE TITLE
Meta: Code review for larger PRs

### ISSUE THREAD

**Issue by macsux** [kubernetes-client/csharp#426]
I'm wondering if we can get some eyes on some of the larger open PRs and get them fixed up and merged. I'm continuing to add a lot of new features to the codebase - my code analysis counter is actually telling me that if the generated code is excluded, the pending PRs almost double the existing codebase. At this point, I'm finding it is becoming a major chore to maintain so many open PRs as many of them depend on others and any new work that incrementally adds features needs to be reapplied in many branches to keep everything in sync. I get a feeling I'm pumping out code faster than it can get reviewed and merged in, at least for some of the larger initiatives.

**Comment by tg123** [comment]
appreciate your contribution
I promise more time on PRs in coming weeks

hope they can be merged soon.

**Comment by brendandburns** [comment]
definitely appreciate the help. Breaking PRs up into much smaller changes will really help get them reviewed faster. I understand that it's tricky to do this, but it becomes much easier to grok each change and fit the reviews into the rest of life :)

**Comment by brendandburns** [comment]
fwiw, #402 is ready to go, I think, but it needs a unit test. So there are some PRs that could get merged with some small changes.
