### ISSUE TITLE
Code styling issues

### ISSUE THREAD

**Issue by macsux** [kubernetes-client/csharp#433]
With the recent introduction of code style rules, I wanted to bring up a few issues I hope we can address:

1. Some types of checks are not reformatted using `dotnet format`. This causes a significant loss in productivity trying to fix up formatting issues. Examples of where auto formatted doesn't work is a requirement for extract lines after braces. If there's another tool that can "auto-format", I think it should be put into README.md as guidance
2. I disagree with `SA1503: Braces should not be ommited` for `if` statements. A lot of validation checks such as `if (type == null) throw new ArgumentNullException(nameof(type));` turn into 4 lines of code
```
            if (type == null)
            {
                throw new ArgumentNullException(nameof(type));
            }

```
which only detracts from the readability of code. I propose this rule is removed
3. There are rules in there right now to validate things like namespace naming convention which `k8s` is failing
4. Legitimate warnings are being drowned in the formatting "noise" on build atm, some of which we won't be able to address (like namespace naming). 
5. I'm also noticing a VERY significant degradation of IDE performance with the latest style changes, as I suspect there's a ton of background threads trying to run Roslyn analyzers. 
6. In some cases, the code actually becomes less efficient. Example: JObject.Contains is defined explicitly in the newer version but older the one that targets 4.5.2. The current rule makes you cast it to IDictionary as you're not supposed to access it implicitly, meaning newer targets are using less optimized code path. 

**I think there needs to be a balance struck on which rules to enforce, as previous experience with projects that enforced very strict linting rules without the ability to automatically reformat the code has discouraged contributions as it turned into a major chore.**

**Comment by macsux** [comment]
So on a personal note, this is big enough of an issue for me to not want to contribute going forward. I'm fine with some styling rules, but this just ridiculous. I just spent half a day going through some existing PRs fixing line breaks and other things to make it conform to the new rules, but at this point 
1. My IDE is slow
2. Much of the existing code became less readable
3. Build is full of warnings that are unrelated to my code or something that can or should be addressed
4. Existing style rules of Rider/Resharper conflict with those in the project - it formats code in a way that conflicts

**Comment by tg123** [comment]
sorry and I totally understand your feeling
absolutely we can discuss any enforced rules or code style

this project was once with resharper code check but removed due to build system reasons #274 

I am moving some MS internal practice to this project as we have many styles in this project. those enforced rules are/will base on those internal rules.

1 I am working to clean up remaining warning (~4K) and have them enforced, warning or suppressed.

2 Braces rule we can totally talk.
IHMO, modern lang such as Go enforced this rule at compile time. no chance to write code like `if (xx) doXX;`
I am writing Java with IDEA before, and my team does not allow empty

3 no format tools for now, I will put resharper/vs format configure file in repo

**Comment by macsux** [comment]
IMO the braces rule should be left up to the developer, there are many instances where brevity is warranted by the shorter syntax. I hardly think Java should be used as the north star on this given that it's an insanely verbose language with tons of baggage that we have partially shredded in our ecosystem with .NET Core. There are a ton of cases where a simple "if... return" or if...throw at the beginning of the method is way more readable then 4 lines as indicated above.

If possible, please prioritize automated reformatters to eliminate this manual chore.

**Comment by brendandburns** [comment]
fwiw, the braces rule is one that I believe in. Braces add clarity, and in this project we prioritize readability and consistency over individual decisions.

I do agree that we definitely do need have as much of this as possible be automated.

I don't want to force people to manually reformat code. However, I don't think automation will ever be perfect. Most languages (golang, nodejs) have a mix of automatic automatic validation (gofmt, prettier) and linters (golint, tslint) that require manual fixes.

I understand that this can be frustrating, but I strongly believe in consistent style in community open source projects and this is consistent with both the Kubernetes approach and also the approach in other kubernetes clients (e.g. Javascript, Java and Python all have style enforcement)

If this drives you away from the project, we'd obviously be disappointed, I value your contributions and am grateful for the time and effort you've put into the client. I hope that we can get to a place where you are still comfortable contributing and we also ensure consistency and readability in our source.

**Comment by macsux** [comment]
Sorry guys for a bit of a tantrum with my last comment there, I was just really frustrated as for how long it took to reconcile all the stuff and crazy amount of conflicts I got after rebases. 

It would be great if we can get ReSharper / rider ruleset loaded, IMO it can tackle pretty much all of this if properly configured. If we can get it to a point where this is something you can do quickly before check-in, I think it will make the experience much smoother.

**Comment by tg123** [comment]
#439 I reviewed the rule one by one this weekend we can discuss the rules before breaking build
