### ISSUE TITLE
How to search custom objects in all namspaces?

### ISSUE THREAD

**Issue by JochenGuck** [kubernetes-client/csharp#438]
Is there an equivalent of e.g. ListSecretForAllNamespacesAsync for namespaced custom objects?
I'm not able to find a ListCustomObjectForAllNamespacesAsync.

**Comment by brendandburns** [comment]
This is unfortunately missing in the swagger used to generate those methods, see the dicussion here:

https://github.com/kubernetes-client/java/issues/941

**Comment by macsux** [comment]
https://github.com/kubernetes-client/csharp/pull/412 would allow you to do it.

**Comment by tg123** [comment]
`ListClusterCustomObject`
