### ISSUE TITLE
code style rule proposal

### ISSUE THREAD

**Issue by tg123** [kubernetes-client/csharp#439]
# Style checking rules proposal

To ensure a better code quality, we introduce some tools, FxCopAnalyzers and StyleCop, to enforce some code style checking when running CI.
However, some of rules are not reasonable or too strict to write code with.

To make the process smoothly, all rules are categorized into 3 levels

 * :x: Treat as error
 * :warning: Warning only
 * :ok: Allow, suppress warning

Here are the initial levels according to my personal experiences, we can discuss about all those levels and make separate PR to fix them steadily
(only current warnings in our code are listed)

## Documentation

| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [SA1649](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1649.md) | The file name of a C# code file does not match the first type declared in the file. | Documentation Rules | :x:
| [SA1600](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1600.md) | A C# code element is missing a documentation header. | Documentation Rules | :ok:
| [SA1601](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1601.md) | A C# partial element is missing a documentation header. | Documentation Rules | :ok:
| [SA1602](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1602.md) | An item within a C# enumeration is missing an Xml documentation header. | Documentation Rules | :warning:
| [SA1611](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1611.md) | A C# method, constructor, delegate or indexer element is missing documentation for one or more of its parameters. | Documentation Rules | :warning:
| [SA1612](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1612.md) | The documentation describing the parameters to a C# method, constructor, delegate or indexer element does not match the actual parameters on the element. | Documentation Rules | :warning:
| [SA1615](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1615.md) | A C# element is missing documentation for its return value. | Documentation Rules | :warning:
| [SA1618](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1618.md) | A generic C# element is missing documentation for one or more of its generic type parameters. | Documentation Rules | :warning:
| [SA1622](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1622.md) | A `<typeparam>` tag within the Xml header documentation for a generic C# element is empty. | Documentation Rules | :warning:
| [SA1623](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1623.md) | The documentation text within a C# property's `<summary>` tag does not match the accessors within the property. | Documentation Rules | :warning:
| [SA1625](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1625.md) | The Xml documentation for a C# element contains two or more identical entries, indicating that the documentation has been copied and pasted. This can sometimes indicate invalid or poorly written documentation. | Documentation Rules | :warning:
| [SA1629](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1629.md) | A section of the Xml header documentation for a C# element does not end with a period (also known as a full stop). | Documentation Rules | :ok:
| [SA1633](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1633.md) | A C# code file is missing a standard file header. | Documentation Rules | :ok:
| [SA1642](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1642.md) | The XML documentation header for a C# constructor does not contain the appropriate summary text. | Documentation Rules | :warning:

## Layout
| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [SA1500](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1500.md) | The opening or closing brace within a C# statement, element, or expression is not placed on its own line. | Layout Rules | :x:
| [SA1507](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1507.md) | The C# code contains multiple blank lines in a row. | Layout Rules | :warning:
| [SA1509](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1509.md) | An opening brace within a C# element, statement, or expression is preceded by a blank line. | Layout Rules | :warning:
| [SA1512](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1512.md) | A single-line comment within C# code is followed by a blank line. | Layout Rules | :ok:
| [SA1513](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1513.md) | A closing brace within a C# element, statement, or expression is not followed by a blank line. | Layout Rules |  :x:
| [SA1515](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1515.md) | A single-line comment within C# code is not preceded by a blank line. | Layout Rules | :ok:
| [SA1516](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1516.md) | Adjacent C# elements are not separated by a blank line. | Layout Rules | :ok:

## Maintainability
| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [SA1119](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1119.md) | A C# statement contains parenthesis which are unnecessary and should be removed. | Maintainability Rules | :x:
| [SA1400](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1400.md) | The access modifier for a C# element has not been explicitly defined. | Maintainability Rules | :x:
| [SA1401](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1401.md) | A field within a C# class has an access modifier other than private. | Maintainability Rules | :x:
| [SA1402](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1402.md) | A C# code file contains more than one unique type. | Maintainability Rules | :x:
| [SA1405](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1405.md) | A call to Debug.Assert in C# code does not include a descriptive message. | Maintainability Rules | :x:
| [SA1413](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1413.md) | The last statement in a multi-line C# initializer or list is missing a trailing comma. | Maintainability Rules | :warning:

## Naming

| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [SA1300](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1300.md) | The name of a C# element does not begin with an upper-case letter. | Naming Rules | :x:
| [SA1306](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1306.md) | The name of a field in C# does not begin with a lower-case letter. | Naming Rules | :x:
| [SA1309](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1309.md) | A field name in C# begins with an underscore. | Naming Rules | :ok:
| [SA1312](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1312.md) | The name of a variable in C# does not begin with a lower-case letter. | Naming Rules | :x:
| [SA1314](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1314.md) | The name of a C# type parameter does not begin with the capital letter T. | Naming Rules | :x:

## Ordering
| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [SA1200](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1200.md) | A C# using directive is placed outside of a namespace element. | Ordering Rules | :warning:
| [SA1201](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1201.md) | An element within a C# code file is out of order in relation to the other elements in the code. | Ordering Rules | :ok:
| [SA1202](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1202.md) | An element within a C# code file is out of order within regard to access level, in relation to other elements in the code. | Ordering Rules | :ok:
| [SA1203](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1203.md) | A constant field is placed beneath a non-constant field. | Ordering Rules | :ok:
| [SA1204](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1204.md) | A static element is positioned beneath an instance element of the same type. | Ordering Rules | :ok:
| [SA1206](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1206.md) | The keywords within the declaration of an element do not follow a standard ordering scheme. | Ordering Rules | :ok:
| [SA1210](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1210.md) | The using directives within a C# code file are not sorted alphabetically by namespace. | Ordering Rules | :ok: 
| [SA1214](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1214.md) | A readonly field is positioned beneath a non-readonly field. | Ordering Rules |  :ok:

## Readability
| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [SA1108](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1108.md) | A C# statement contains a comment between the declaration of the statement and the opening brace of the statement. | Readability Rules | :x:
| [SA1113](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1113.md) | A comma between two parameters in a call to a C# method or indexer, or in the declaration of a method or indexer, is not placed on the same line as the previous parameter. | Readability Rules | :warning:
| [SA1116](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1116.md) | The parameters to a C# method or indexer call or declaration span across multiple lines, but the first parameter does not start on the line after the opening bracket. | Readability Rules | :warning:
| [SA1117](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1117.md) | The parameters to a C# method or indexer call or declaration are not all on the same line or each on a separate line. | Readability Rules | :warning:
| [SA1118](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1118.md) | A parameter to a C# method or indexer, other than the first parameter, spans across multiple lines. | Readability Rules | :warning:
| [SA1120](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1120.md) | The C# comment does not contain any comment text. | Readability Rules | :ok:
| [SA1121](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1121.md) | The code uses one of the basic C# types, but does not use the built-in alias for the type. | Readability Rules | :warning:
| [SA1122](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1122.md) | The C# code includes an empty string, written as `""`. | Readability Rules | :warning:
| [SA1124](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1124.md) | The C# code contains a region. | Readability Rules | :x:
| [SA1127](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1127.md) | A generic constraint on a type or method declaration is on the same line as the declaration, within a C# code file. | Readability Rules | :warning:
| [SA1128](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1128.md) | A constructor initializer is on the same line as the constructor declaration, within a C# code file. | Readability Rules | :warning:
| [SA1131](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1131.md) | A comparison was made between a variable and a literal or constant value, and the variable appeared on the right-hand side of the expression. | Readability Rules | :x:
| [SA1134](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1134.md) | An attribute is placed on the same line of code as another attribute or element. | Readability Rules | :warning:

## Spacing
| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [SA1001](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1001.md) | The spacing around a comma is incorrect, within a C# code file. | Spacing Rules | :warning:
| [SA1009](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1009.md) | A closing parenthesis within a C# statement is not spaced correctly. | Spacing Rules | :warning:
| [SA1012](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1012.md) | An opening brace within a C# element is not spaced correctly. | Spacing Rules | :warning:
| [SA1027](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1027.md) | The code contains a tab or space character which is not consistent with the current project settings.
 | Spacing Rules | :x:
| [SA1028](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1028.md) | A line of code ends with a space, tab, or other whitespace characters before the end of line character(s). | Spacing Rules | :warning:
| [SA0001](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md) | All diagnostics of XML documentation comments has been disabled due to the current project configuration. | Special Rules | :warning:

## Usage
| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [CA1816](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1816) | Call GC.SuppressFinalize correctly | Microsoft.Usage | :x:
| [CA1801](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1801) | Review unused parameters | Microsoft.Usage | :warning:
| [CA2200](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA2200) | Rethrow to preserve stack details | Microsoft.Usage | :warning:
| [CA2213](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA2213) | Disposable fields should be disposed | Microsoft.Usage | :warning:
| [CA2225](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA2225) | Operator overloads have named alternates | Microsoft.Usage | :warning:
| [CA2227](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA2227) | Collection properties should be read only | Microsoft.Usage | :warning:
| [CA2237](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA2237) | Mark ISerializable types with SerializableAttribute | Microsoft.Usage | :warning:
| [CA5359](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA5359) | Do Not Disable Certificate Validation | Microsoft.Usage | :ok:

## Design
| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [CA1018](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1018) | Mark attributes with AttributeUsageAttribute | Microsoft.Design | :warning:
| [CA1028](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1028) | Enum storage should be Int32 | Microsoft.Design | :warning:
| [CA1031](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1031) | Do not catch general exception types | Microsoft.Design | :warning:
| [CA1034](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1034) | Nested types should not be visible | Microsoft.Design | :warning:
| [CA1051](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1051) | Do not declare visible instance fields | Microsoft.Design | :warning:
| [CA1054](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1054) | URI parameters should not be strings | Microsoft.Design | :warning:
| [CA1062](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1062) | Validate arguments of public methods | Microsoft.Design | :warning:
| [CA1063](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1063) | Implement IDisposable correctly | Microsoft.Design | :x:

## Globalization
| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [CA1303](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1303) | Do not pass literals as localized parameters | Microsoft.Globalization | :ok:
| [CA1304](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1304) | Specify CultureInfo | Microsoft.Globalization | :ok:
| [CA1305](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1305) | Specify IFormatProvider | Microsoft.Globalization | :ok:
| [CA1307](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1307) | Specify StringComparison | Microsoft.Globalization | :ok:
| [CA1308](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1308) | Normalize strings to uppercase | Microsoft.Globalization | :ok:

## Naming
| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [CA1707](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1707) | Identifiers should not contain underscores | Microsoft.Naming | :x:
| [CA1715](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1715) | Identifiers should have correct prefix | Microsoft.Naming | :x:
| [CA1716](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1716) | Identifiers should not match keywords | Microsoft.Naming | :x:
| [CA1720](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1720) | Identifiers should not contain type names | Microsoft.Naming | :x:

## Performance
| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [CA1802](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1802) | Use Literals Where Appropriate | Microsoft.Performance | :x:
| [CA1812](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1812) | Avoid uninstantiated internal classes | Microsoft.Performance | :x:
| [CA1822](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1822) | Mark members as static | Microsoft.Performance | :x:
| [CA1825](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1825) | Avoid zero-length array allocations | Microsoft.Performance | :x:
| [CA1827](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1827) | Do not use Count/LongCount when Any can be used | Microsoft.Performance | :x:

## Reliability
| Code | Comment | Category | Level |
| ------------- | ------------- | ------------- | ------------- | 
| [CA2000](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA2000) | Dispose objects before losing scope | Microsoft.Reliability | :x:
| [CA2007](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA2007) | Do not directly await a Task | Microsoft.Reliability | :x:
| [CA2008](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA2008) | Do not create tasks without passing a TaskScheduler | Microsoft.Reliability | :x:

**Comment by macsux** [comment]
My thoughts on few items:
CA1822 - Should only apply to non-public members, as the public API surface should not be restricted by internal method implementation (which may change).
CA1720 - I can potentially see needing to do this with `out` parameters before they can be cast to an actual type we're working with, requiring two variables that are basically same. Ex. `out` JToken when I totally know that what I'm getting is a JObject, and how I intend to work with it going forward so I'll cast assign it to another variable as first step. What should it be called then?
CA1707 - idk if this would apply to a common modern convention of using entire identifier `_` to indicate discard
SA1503 - I'm still of the opinion that this one should be allowed with caveat that its action appears on a new line, given how much briefer it makes the code look improving readability.

**Comment by macsux** [comment]
I've also noticed that CA2000 comes up often. The Informers codebase uses RX with CompositeDisposable, as well as uses extension method `.DisposeWith(this IDisposable src, CompositeDisposable aggregate)` extensively, which causes this one to appear. I guess we can put a suppression wherever it is used, but it's a very common violation of this rule in that codebase.
