### ISSUE TITLE
Question: Is is possible to modify config maps of pod and upload the changes?

### ISSUE THREAD

**Issue by gittadesushil** [kubernetes-client/csharp#441]
I want to update the config for already available pod running on cluster. I have to modify the config map and then upload and then restart the pod.

**Comment by tg123** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically

**Comment by brendandburns** [comment]
Closing issue since question is answered. Please use `/reopen` to reopen if necessary.
