### ISSUE TITLE
Q: Publish MockKubeApiServer as a package?

### ISSUE THREAD

**Issue by morfj** [kubernetes-client/csharp#445]
It would be helpful when writing tests on code that is using the kubernetes client to be able to easily fire up a mock server - like the one already in the tests folder: MockKubeApiServer.

Any chance to get this published in a "dev" package or similar?

**Comment by tg123** [comment]
it is NOT a real kubeapi server
only returns predefined content no matter what was sent to it.

why not create one using minikube?

**Comment by morfj** [comment]
I am aware its not "real", but it is still useful to record and gauge the interaction with the "cluster". For a full integration test/system test I will spin up a real cluster, but for tests that are just at the "collaboration" level of code, a mocked server would be very useful. The alternative would be to inject a stubbed client implementation and short-circuit the interaction there.

**Comment by tg123** [comment]
No plan to publish a test proj
I suggest you have it `git submodule` personally if you want

**Comment by morfj** [comment]
Thank you for the feedback. I might just try the submodule approach.
