### ISSUE TITLE
[Meta] Kubernetes member application

### ISSUE THREAD

**Issue by macsux** [kubernetes-client/csharp#447]
I want to apply for the Kubernetes community membership. As per https://github.com/kubernetes/community/blob/master/community-membership.md I need 2 references. @brendandburns @tg123 would you be willing to be sponsors of the applications?

Apologies for opening an issue for this, but I wasn't sure a better way to request this.

**Comment by brendandburns** [comment]
I'm definitely happy to sponsor. Please email me the membership PR when you create it, github notifications are way to spammy so they don't get through my filters.

**Comment by tg123** [comment]
for sure, sorry for the late reply.

did you open PR here?
https://github.com/kubernetes/org

**Comment by macsux** [comment]
Not yet, wanted to get your answer first. Will open today
