### ISSUE TITLE
Isolate security from KubernetesClient

### ISSUE THREAD

**Issue by macsux** [kubernetes-client/csharp#449]
This is related to https://github.com/kubernetes-client/csharp/issues/448
There's a desire in downstream projects to not work with KubernetesClient directly, but instead, only use code found in KubernetesGeneric to keep dependency small. 

Atm KubernetesClient security is strongly tied to concrete implementation because authentication is done via "Credentials" property, which gets called on every method to API server. Instead, the proposal is to refactor security into an HttpHandler which can live outside of KubernetesClient. The goal, and we would like to work with is preconfigured HttpClient which can be used to talk to Kubernetes server which would seamlessly handle authentication and watch queries. 

If there's no objections, I would like to introduce new HttpHandler that invokes the equivalent of what is found in every autogenerated call for authentication. 
```
if (Credentials != null)
            {
                cancellationToken.ThrowIfCancellationRequested();
                await Credentials.ProcessHttpRequestAsync(httpRequest, cancellationToken).ConfigureAwait(false);
            }
```

Assuming acceptance of modular project structure, this will allow downstream consumers to opt-in to the "raw" client, and not be burdened by heavy dependence on Kubernetes object. This would be code equivalent of what `kubectl get --raw` allows you to do.

**Comment by brendandburns** [comment]
I think that the `Credential` stuff is done via the code generation. I don't think it's necessary to move the credentials into an `HttpHandler` for the default usage. However, I think it is fine to refactor the code so that you can build an `HttpHandler` that re-uses the same logic as the `Credential`
