### ISSUE TITLE
DeleteNamespacedPod return Status, Reason and Message value empty

### ISSUE THREAD

**Issue by gittadesushil** [kubernetes-client/csharp#452]
When I execute DeleteNamespacedPod API, then I see result.Status empty along with Message and Reason. 
```
 var result = Client.DeleteNamespacedPod(pod.Name,
                    pod.NamespaceName,
                    null, null, 10,
                    null, "Foreground");
```
Is anyone facing the same issue?

**Comment by brendandburns** [comment]
Deleting a pod is an asynchronous operation that can return a Status if the operation is ongoing.

You need to poll on the object until it's 404 to ensure that it's actually deleted.

**Comment by gittadesushil** [comment]
> Deleting a pod is an asynchronous operation that can return a Status if the operation is ongoing.
> 
> You need to poll on the object until it's 404 to ensure that it's actually deleted.

You mean I need to keep poll the DeleteNamespacedPod method until result.status is 404?

**Comment by brendandburns** [comment]
Yes, that works, see the description here:

https://github.com/kubernetes/kubernetes/issues/42594#issue-212251821
