### ISSUE TITLE
Support BOOKMARK in Watch

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/csharp#453]
See:
https://github.com/kubernetes-client/java/pull/963

**Comment by lodejard** [comment]
I just hit this same problem. Specifically, it's missing from the ListClusterCustomObject methods

**Comment by brendandburns** [comment]
/lifecycle frozen

@lodejard can you clarify? This is only related to Watches, it shouldn't affect List methods.

**Comment by bergeron** [comment]
Were bookmarks already implemented in https://github.com/kubernetes-client/csharp/commit/33e0b28138d6e7580b1335d7bcfff466d5821a43?

I receive bookmark events when listing with `allowWatchBookmarks: true`.  

I think @lodejard means that all the `List*WithHttpMessagesAsync` methods accept an `allowWatchBookmarks` boolean except for `ListNamespacedCustomObjectWithHttpMessagesAsync` and `ListClusterCustomObjectWithHttpMessagesAsync`.
