### ISSUE TITLE
Client Configuration within the target Cluster

### ISSUE THREAD

**Issue by awdm** [kubernetes-client/csharp#456]
How would I go about client configuration if my program is running within the cluster it's supposed to communicate with? Can I use the default BuildConfigFromConfigFile()?

**Comment by tg123** [comment]
`InClusterConfig()` ?

**Comment by brendandburns** [comment]
If you use `KubernetesClientConfiguration.BuildDefaultConfig()` it will work in both workstation and cluster configurations, see the example here:

https://github.com/kubernetes-client/csharp/blob/master/examples/simple/PodList.cs#L10
