### ISSUE TITLE
How can I execute a command with parameters through "WebSocketNamespacedPodExecAsync"?

### ISSUE THREAD

**Issue by Mahmoud-Karam** [kubernetes-client/csharp#462]
I am able to execute the following command in powershell
`kubectl --namespace myNameSpace exec myPodName cat myFileName.txt`

How can I execute the same command thought "_WebSocketNamespacedPodExecAsync_"

Also any reference on how to pass a command with parameters to "_WebSocketNamespacedPodExecAsync_" would be highly appreciated

**Comment by Mahmoud-Karam** [comment]
The error that I get when I write the command with parameters in the same field is:
`OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"cat myFileName.txt\": executable file not found in $PATH": unknown`

**Comment by Mahmoud-Karam** [comment]
@brendandburns Can you please help me in this?

**Comment by Mahmoud-Karam** [comment]
I was able to do it as follows:
`WebSocket webSocket = await client.WebSocketNamespacedPodExecAsync(myPodName, myNameSpave, new string[] { "cat", "composer.json" });`
Reference:
https://github.com/kubernetes-client/csharp/commit/d20e2597b9f41e8dcf8925bdd383d34d444f9d44

**Comment by brendandburns** [comment]
Cool, glad you got it working! Closing this issue.
