### ISSUE TITLE
Is there a C-Sharp method/code-snippet to upload a file from my local machine to a pod?

### ISSUE THREAD

**Issue by Mahmoud-Karam** [kubernetes-client/csharp#464]

**Comment by brendandburns** [comment]
There's not a utility currently, the equivalent Java code is here:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/Copy.java#L41

Which should be pretty easy to adapt to C#.

We would gladly take a PR adding this support too.

**Comment by Mahmoud-Karam** [comment]
Thanks a lot @brendanburns

**Comment by lazarkrstic** [comment]
@Mahmoud-Karam  Can you post your code snippet for C#?

**Comment by Mahmoud-Karam** [comment]
> @Mahmoud-Karam Can you post your code snippet for C#?

@lazarkrstic I didn't work on it unfortunately.

**Comment by lazarkrstic** [comment]
Solved in https://github.com/kubernetes-client/csharp/issues/949#issuecomment-1190083366
