### ISSUE TITLE
Is there a method to taint and label nodes in Kubernetes cluster? Do you have any C# examples for it?

### ISSUE THREAD

**Issue by txr150430** [kubernetes-client/csharp#467]
I tried getting the list of nodes in C# client and then label and taint some of the nodes for our use case. Do you have any recommendations on the methods we could use for adding and removing labels and taints for nodes? Or do you recommend labeling and tainting them only using CLI commands.

```
foreach(var node in client.ListNode().Items){
                    nodes.Add(node.Metadata.Labels.ToString());
                }
```
Simple commands I was hoping to run in C# clients were:

`kubectl taint nodes <nodename> taintkey=taintvalue:NoSchedule`

and

`kubectl label node <nodename> test-node-affinity=test`

Your inputs would be definitely helpful.

**Comment by brendandburns** [comment]
We don't currently have such functions. You will need to do it yourself by modifying the node object and then using the client to replace the object in the server. You can see the Java equivalent of label here:

https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java

It's probably worth adding something similar to this client, but in the meantime that example should be pretty easy to port to C#

**Comment by txr150430** [comment]
Thanks for your response @brendandburns . This helps thanks. Would be definitely helpful if we have a stable client to perform these operations. We also observed that the PatchNode utility for updating labels in our C# client had overwritten all the values in our Nodes unlike appending the contents alone. So these kinds of methods might help few devs in the future. Thanks.
