### ISSUE TITLE
DeleteNamespacedJob and DeleteNamespacedJobAsync has incorrect return type

### ISSUE THREAD

**Issue by zpittmansf** [kubernetes-client/csharp#475]
According to the spec https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#delete-job-v1-batch, a V1Status object should be returned from either of these methods. The generated code is matching the spec. However, if you call
DeleteCollectionNamespacedJobWithHttpMessagesAsync and read the content of the response you will see a Kind of Job being returned. It seems to be returning the Job that was attempted to be deleted but that doesn't map up with the api spec of what a delete job v1 batch should return, a V1Status.

This is likely a problem for all the generated clients but it's not clear to me how this is all generated (hard to connect the dots all the way upstream to the k8s api). Could someone help me understand where that mapping is failing in the pipeline of generating this code?

Here is the generated code that is trying to de-serialize to a V1Status (per the spec) but the actual return type is the job object that was targeted for deletion:
```
// Deserialize Response
            if ((int)_statusCode == 200)
            {
                _responseContent = await _httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
                try
                {
                    _result.Body = SafeJsonConvert.DeserializeObject<V1Status>(_responseContent, DeserializationSettings);
                }
                catch (JsonException ex)
                {
                    _httpRequest.Dispose();
                    if (_httpResponse != null)
                    {
                        _httpResponse.Dispose();
                    }
                    throw new SerializationException("Unable to deserialize the response.", _responseContent, ex);
                }
            }
```

Docker for desktop Windows
k8s 1.16.5

**Comment by brendandburns** [comment]
The OpenAPI spec that the code is generated from is here:

**Comment by zpittmansf** [comment]
@brendanburns shouldn't the non-async method return 200 when the operation is completed and the async method return long running operation object of some sort? OpenAPI v2 wouldn't be a concern if the methods themselves were not trying to do too much.

**Comment by brendandburns** [comment]
That is what Kubernetes does, the V1Status is the long running operation object and the server returns `201` afaik.

The thing about OpenAPI spec is that it doesn't allow you to have different return types given different status codes, a return type is defined for a URL Path/Method tuple. In OpenAPI 3 you can have return type be a `oneOf` which gives you the opportunity to return multiple different types (possibly due to different status codes)

(at least that's my understanding, I'm not an OpenAPI expert by any means)

**Comment by zpittmansf** [comment]
I was just suggesting that this problem could have been handled without the need of mapping return types based on status codes. Have a synchronous method that always returns 200 or 5xx and the asynchronous method would always return 202 as a long running operation. This would allow the caller to decide if they want to await or not and would then also align properly with expectations of using sync vs async methods in .net.

**Comment by brendandburns** [comment]
Lots of designs are possible, but at this point the way that the Kubernetes APIServer behaves is pretty much set in stone, so clients will need to acomodate the way that it is done.
