### ISSUE TITLE
API call to submit a deployment gets back HTTP 422 (Unprocessable Entity) error

### ISSUE THREAD

**Issue by firazs** [kubernetes-client/csharp#48]
I am getting an HTTP 422 (Unprocessable Entity) error for an API call I am making to submit a deployment (json attached, submitting the same json through kubectl works fine), the API call is
k8sClient.CreateNamespacedDeploymentWithHttpMessagesAsync

The only relevant line in the APIServer logs is the following:
I1104 00:08:00.847824       1 wrap.go:42] POST /apis/apps/v1beta1/namespaces/default/deployments?pretty=true: (45.627034ms) 422 [[FxVersion/4.7.2114.0 OSName/WindowsServer2012R2Datacenter OSVersion/6.3.9600 k8s.Kubernetes/0.0.0.0] 167.220.1.198:34012]

[deployment-gateway.json.txt](https://github.com/kubernetes-client/csharp/files/1450891/deployment-gateway.json.txt)

**Comment by brendandburns** [comment]
Can you add the body of the Deployment that you sent?

Thanks!

**Comment by brendandburns** [comment]
fwiw, side conversation indicates that this is because we don't handle `IntOrString` correctly...

**Comment by firazs** [comment]
Attached to original comment

**Comment by tg123** [comment]
seems need a hack to autorest, I am trying to give a solution.

**Comment by brendandburns** [comment]
@tg123 see: https://github.com/kubernetes-client/gen/pull/30

You may be able to do something similar for C#

**Comment by tg123** [comment]
@brendandburns thanks 
seems autorest template does not support add user defined jsonconverters, I am searching for workarounds.
