### ISSUE TITLE
Is there a `kubectl apply` equivalent?

### ISSUE THREAD

**Issue by simonvane** [kubernetes-client/csharp#482]
What would be the best way to achieve the equivalent of `kubectl apply -f instance.yaml`? Are there any examples of that sort of thing?

Thank you.

(As a bit of background I would like to deploy some secrets and an instance of an operator)

**Comment by brendandburns** [comment]
I think you probably want to use the `replaceNamespacedDeployment/etc` set of functions, unless you are specifically looking for the `apply` version tracking.

**Comment by brendandburns** [comment]
Duplicate of #304 closing in favor of that issue.
