### ISSUE TITLE
Watcher could implement either keep alive or retry mechanism

### ISSUE THREAD

**Issue by petermicuch** [kubernetes-client/csharp#486]
Similar to issue mentioned [here](https://github.com/kubernetes-client/python/issues/124) for python client, it would be really nice if [Watcher](https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/Watcher.cs) does not drop connection after 30 minutes. Right now I am handling OnClose and OnError events and recreate Watcher after short period of time since connection was closed. Even better would be if watch supports Observable and one could use [Rx](https://github.com/dotnet/reactive) to handle changes.

**Comment by brendandburns** [comment]
We need to build a higher level "Informer" on top of the Watcher to handle reconnecting after a watch stops.

In general, you can't rely on a watch lasting forever. You have to List/Watch in a loop, but we should build a utility to make that easy for people to do correctly.

**Comment by petermicuch** [comment]
@brendandburns does it mean this will be considered? Loop is exactly what I am doing now, so in case this would be already build in, it would be great. Use-cases for watch are usually long running tasks in my opinion. Observable would be even better as you can trigger delayed processing, buffering or throttling of events.

**Comment by brendandburns** [comment]
We definitely should build up the Informer code. There are some starting points here:

https://github.com/kubernetes-client/csharp/pull/394

But it got hung up in the design phase.

**Comment by tomaszgawlik** [comment]
@petermicuch Would you be able to share your look example please? 
I'm trying to write an application, which is watching kubernetes events and sends them to Grafana. 
But having troubles with restarting the stream after it's closed.

**Comment by petermicuch** [comment]
You have to call `_kubernetesClient.ListEventForAllNamespacesWithHttpMessagesAsync(watch: true);` inside while loop and not reuse the stream, then it will work. Also why do you await to get a `response`? That is responsibility of Watcher you are getting from `watch` call.

```
            while (true)
            {
                _logger.LogInformation($"Starting new watch stream");
                var streamTokenSource = new CancellationTokenSource();
                
                var response = _kubernetesClient.ListEventForAllNamespacesWithHttpMessagesAsync(watch: true);
                var watch = response.Watch<V1Event, V1EventList>((type, @event) =>
                    {
                        _logger.LogInformation($"Event received action here..");
                    }, (error) => { _logger.LogError(error, $"Watch error"); },
                    () =>
                    {
                        _logger.LogInformation("Event watch onClosed triggered");
                        streamTokenSource.Cancel();
                    });

                await Task.Delay(-1, streamTokenSource.Token);
                watch.Dispose();
            }
```

I have not compiled or tried this modified code, but should work. Also consider retrying on error with some delay. Would be nice if there is some kind of resilience implemented.

If you want to know more, just check code of [Watcher](https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/Watcher.cs) itself.

**Comment by tg123** [comment]
close and move discuss to #533 
workaround here
https://github.com/kubernetes-client/csharp/issues/533#issuecomment-749418238
