### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sraillard** [kubernetes-client/csharp#487]
Maybe I have missed something, but after reading the README.md file and looking at the examples, I didn't find more information about the (very numerous) methods and the philosophy for using this library.

Even when checking the Kubernetes OpenAPI, it isn't straightforward to understand how the Kubernetes methods were translated in this library.

I really see a huge potential, but I don't know where to get minimal reference documentation.

**Comment by brendandburns** [comment]
This library assumes a working knowledge of Kubernetes and it's various resource types (e.g. Pods, Deployments, etc)

If you are not familiar with Kubernetes yet, there are numerous learning resources available, e.g.https://azure.microsoft.com/en-us/resources/kubernetes-learning-and-training/ and of course https://kubernetes.io

Once you are familiar with Kubernetes (or if you already are) then I would look at the general Kubernetes API documentation:
https://kubernetes.io/docs/reference/using-api/api-overview/

and the Kubernetes API Reference:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/

That should get you where you need to go.

**Comment by brendandburns** [comment]
If you have specific questions, you may also find that the Kubernetes Slack community (https://slack.kubernetes.io) has a number of channels where people are very helpful.

**Comment by sraillard** [comment]
Sorry, I have Kubernetes experience and knowing the basics of the Kubernetes API and kubectl don't help much!
As I said, I don't see how the Kubernetes API resources names are translated as methods.

This library has clearly a great potential, without more documentation it may have a limited potential users.

**Comment by sraillard** [comment]
I have tried to figure out how to do basics tasks, and I'm sharing a code snippet if it can help other. Maybe it can be useful to make an new example but the code has certainly to be reviewed.

It's linked also to tickets #304 and #482 discussing a `kubectl apply` feature. In the kubclient JavaScript library, there is an example for doing an apply: https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/apply/apply-example.ts

In the C# sharp library, I didn't find a way to make a generic apply of the objects, so there is a switch for each object types (only service and deployment are supported in this example). There is also a workaround for an annoying bug regarding replacing service.

I would have preferred to use the patch methods, but I didn't find a way to create a JsonPatchDocument from two objects (the one read in file to be applied and the one already in Kubernetes to be updated).

This code is:
* Configuring a Kubernetes connection
* Creating a namespace if not found
* Reading a YAML file with object definitions
* Creating objects if not found
* Updating objects if already created

```
using k8s;
using k8s.Models;
using Microsoft.Rest;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace kubeclient_test
{
    class Program
    {
        static async Task Main(string[] args)
        {

            // Configuration using kubeconfig file
            var config = KubernetesClientConfiguration.BuildConfigFromConfigFile("k8s.yaml");
            Kubernetes client = new Kubernetes(config);

            // Application namespace (lowercase)
            string ns_app = "myapp";
            // Check if the namespace has to be created
            try
            {
                // Try to read the namespace
                V1Namespace ns = client.ReadNamespace(ns_app);
                // If no exception, the namespace already exists
                Console.WriteLine("Namespace [" + ns_app + "] exists");
            }
            catch (HttpOperationException ex) when (ex.Response.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                // Object not found (HTTP error 404)
                // Create the namespace
                client.CreateNamespace(new V1Namespace { Metadata = new V1ObjectMeta { Name = ns_app } });
                Console.WriteLine("Namespace [" + ns_app + "] created");
            }

            // Mapping object to be read between apiVersion/kind in the YAML file and object names
            var typeMap = new Dictionary<String, Type>
            {
                { "v1/Service", typeof(V1Service) },
                { "apps/v1/Deployment", typeof(V1Deployment) }
            };
            // Read and parse the YAML file
            var objects = await Yaml.LoadAllFromFileAsync("myapp.yaml", typeMap);
            // Loop over objects (file order is kept)
            foreach (var obj in objects)
            {
                // Check the object type
                switch (obj.GetType().Name)
                {
                    // v1/Service
                    case "V1Service":
                        // Cast the read object
                        V1Service svc = (V1Service)obj;
                        try
                        {
                            // Try to read the current object
                            V1Service svc_current = client.ReadNamespacedService(svc.Metadata.Name, ns_app);
                            // Workaround for long running bug in Kubernetes
                            // https://github.com/kubernetes/kubernetes/issues/91459
                            if (svc.Metadata.ResourceVersion == null)
                            {
                                svc.Metadata.ResourceVersion = svc_current.Metadata.ResourceVersion;
                            }
                            if (svc.Spec.ClusterIP == null)
                            {
                                svc.Spec.ClusterIP = svc_current.Spec.ClusterIP;
                            }
                            // Replace the current object in the correct namespace (the whole object is rewritten)
                            client.ReplaceNamespacedService(svc, svc.Metadata.Name, ns_app);
                            Console.WriteLine("Service [" + ns_app + "/" + svc.Metadata.Name + "] updated");
                        }
                        catch (HttpOperationException ex) when (ex.Response.StatusCode == System.Net.HttpStatusCode.NotFound)
                        {
                            // Object not found (HTTP error 404)
                            // Create the object in the correct namespace
                            client.CreateNamespacedService(svc, ns_app);
                            Console.WriteLine("Service [" + ns_app + "/" + svc.Metadata.Name + "] created");
                        }
                        break;
                    // apps/v1/Deployment
                    case "V1Deployment":
                        // Cast the read object
                        V1Deployment depl = (V1Deployment)obj;
                        try
                        {
                            // Try to read the current object
                            V1Deployment depl_current = client.ReadNamespacedDeployment(depl.Metadata.Name, ns_app);
                            // Replace the current object in the correct namespace (the whole object is rewritten)
                            client.ReplaceNamespacedDeployment(depl, depl.Metadata.Name, ns_app);
                            Console.WriteLine("Deployment [" + ns_app + "/" + depl.Metadata.Name + "] updated");
                        }
                        catch (HttpOperationException ex) when (ex.Response.StatusCode == System.Net.HttpStatusCode.NotFound)
                        {
                            // Object not found (HTTP error 404)
                            // Create the object in the correct namespace
                            client.CreateNamespacedDeployment(depl, ns_app);
                            Console.WriteLine("Deployment [" + ns_app + "/" + depl.Metadata.Name + "] created");
                        }
                        break;
                }
            }
        }
    }
}
```

**Comment by brendandburns** [comment]
Yep, there's definitely areas for improvement like generic Apply.

There is a patch example here:
https://github.com/kubernetes-client/csharp/blob/master/examples/patch/Program.cs

Which shows how to create a JsonPatchDocument.

We'd obviously be happy for any code or documentation that you'd like to contribute. It's definitely a work in progress.

**Comment by brendandburns** [comment]
Ah, I saw you're looking for a utility that can compute a patch, given two different objects. That doesn't exist, but it would be a cool thing to add.

**Comment by brendandburns** [comment]
Also, the general pattern is:

`Create<ResourceName>`, `Read<ResourceName>`, `Delete<ResourceName>`, `Replace<ResourceName>`

Hope that helps!

**Comment by sraillard** [comment]
Regarding the method naming, maybe I have to add this comment to #490, but I don't understand for example the difference between `Read` and `Get`. Also, there are methods starting with `Connect` and I didn't understand the purpose.

**Comment by sraillard** [comment]
Regarding the JSON diff, I think it could be useful to create a `patch `between a object already created and a possible new version (like the kubectl apply). That would be less invasive than a `replace`.
