### ISSUE TITLE
Extension methods are difficult to use in automated tests.

### ISSUE THREAD

**Issue by simonvane** [kubernetes-client/csharp#488]
I am using `CreateNamespacedCustomObjectAsync` (which works really well thanks) and other similar methods that are in `k8s.KubernetesExtensions` rather than the `k8s.IKubernetes`.

The problem that is giving me is that I can't use mocking frameworks to mock extension methods in my unit tests. This means I have to look at the source to see what the implementation is for the extension methods then mock the internal calls.

It would be a lot easier for me to test if those methods were on the `IKubernetes` interface.

**Comment by brendandburns** [comment]
I would be open to adding an IKubernetesExtensions interface that extends IKubernetes.

**Comment by simonvane** [comment]
Thanks @brendanburns  and sorry for the delayed response.

That would help me but it would mean that consumers would need to inject two dependencies if they want to use methods from both `IKubernetes` and `IKubernetesExtensions`. There seems to be an artificial distinction there.

- Is there any reason why they couldn't be added to `IKubernetes` instead?
- You may have a way around this but static classes cannot implement an interface so I'm wondering how this idea would work?

Thanks.

**Comment by brendandburns** [comment]
Both IKubernetes and IKubernetesExtensions are generated so its tricky to make modifications. (if you can figure out a way to make it work without changing those two interface's .cs files than it's prob. ok.

**Comment by homeahmed2012** [comment]
Any updates on this issue? @brendandburns
