### ISSUE TITLE
Methods in KubernetesExtensions doesn't abstract fully from the REST API calls.

### ISSUE THREAD

**Issue by simonvane** [kubernetes-client/csharp#489]
I am using methods like `KubernetesExtensions.GetNamespacedCustomObjectAsync` which make it really easy to call the Kubernetes API so thanks for that.

The difficulty I am having is that I still have to know a lot about the underlying implementation to use the methods. I have to do quite a lot of work to get useful error information out/logged and I don't know if I have covered the possible cases very well.

A rough example of the code I am writing is as follows:
```
private static async Task<object?> GetCustomObject()
{
    try
    {
        var config = KubernetesClientConfiguration.BuildDefaultConfig();
        using var client = new Kubernetes(config);

        return await client.GetNamespacedCustomObjectAsync("group", "version", "namespace", "plural", "name");
    }
    catch (HttpOperationException httpOperationException) when (httpOperationException.Response?.StatusCode == HttpStatusCode.NotFound)
    {
        return null;
    }
    catch (HttpOperationException httpOperationException)
    {
        V1Status? status = null;
        try
        {
            status = JsonConvert.DeserializeObject<V1Status>(httpOperationException.Response?.Content);
        }
        catch
        {
            // ignore deserialization error
        }

        if (status is { } && string.IsNullOrWhiteSpace(status.Reason) == false && string.IsNullOrWhiteSpace(status.Message) == false)
        {
            return new InvalidOperationException($"GetNamespacedCustomObjectAsync failed. Reason: [{status.Reason}]. Message: [{status.Message}]. Code: [{status.Code}].", httpOperationException);
        }
        else
        {
            return new InvalidOperationException($"GetNamespacedCustomObjectAsync failed with message [{httpOperationException.Message}] and content [{httpOperationException.Response?.Content}].", httpOperationException);
        }
    }
}
```

What I'd really like is:
- methods like `GetNamespacedCustomObjectAsync` return null when nothing found rather than throw.
- any errors that are thrown be as typed as specifically as possible with all of that parsed information in it.

Do you think these are things that could be considered?

Thanks.

**Comment by brendandburns** [comment]
Most of this code is generated, so any improvements to things like this either need to be in wrappers/extensions or in the code generator.

I think that will be a pretty heavy lift. I think if we want to hand-write some sort of wrapper methods or helpers that build diferent exceptions from HttpOperationException, that might be a place to start.

But the trouble is that the Kubernetes API surface area is quite large, so to make this manageable we have to generate all of the code, and that leads to some less than idiomatic solutions.

**Comment by simonvane** [comment]
Hi @brendandburns,

Sorry for the delayed response and thanks for the explanation re code generation.

It would be really helpful to have some extension methods to build exceptions (https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions#use-exception-builder-methods). That would at least means I didn't have to work that out in the first place and I'd know that all of the cases had been handled properly. 

It does still mean that in all of my code I still have to test that `HttpOperationExceptions` have been handled and add the try/catch to do so.

Would it be possible to wrap the call to the `...WithHttpMessagesAsync` methods in that try/catch block in the code generator template?

If you could point me in the right direction I could perhaps look at contributing.

Cheers.
