### ISSUE TITLE
Changing context of Kubernetes object

### ISSUE THREAD

**Issue by AlvinRamoutar** [kubernetes-client/csharp#495]
Building a Kubernetes object as such;
`new Kubernetes(KubernetesClientConfiguration.BuildDefaultConfig());`
uses whatever config(s) are defined in the `KUBECONFIG` environment variable.

If the result is a merged config with multiple contexts how do we change between them?
If this is not supported, then what is the recommended way to do so?

**Comment by tg123** [comment]
could you change `current-context` in you config?
or you just do not want to touch `current-context` but switching context?

if so you have to call `BuildConfigFromConfigFile` yourself passing context as a parameter

**Comment by AlvinRamoutar** [comment]
Thanks for the input @tg123  @brendanburns ,
My process as of now for changing contexts will look as follows;

1. Destroy existing Kubernetes client
2. Build a new one and pass context as a parameter

Will leave this open for a bit for more feedback on this, and so I can test this out.

**Comment by AlvinRamoutar** [comment]
Apologies for not providing an update - ended up staying with my current process of recreating Kubernetes client on context change.
