### ISSUE TITLE
Generic / base class to build custom objects (crd instances)

### ISSUE THREAD

**Issue by sabbadino** [kubernetes-client/csharp#502]
Hi, is there in the c# k8s client a generic base class to build in a typed way a crd instance to pass to calls such as CreateNamespacedCustomObject ? 

As far as I can tell , the spec session is the one that varies from crd to crd, while the rest (or most of the rest ) is the same for any crd

I am currently using CustomKubernetesEntity from the https://github.com/buehler/dotnet-operator-sdk, but i would like to avoid to add this reference 
thank you

**Comment by tg123** [comment]
`IKubernetesObject`?

**Comment by sabbadino** [comment]
Yes this can be the starting point , but there is not a full concrete type ..
I am using this 
https://github.com/buehler/dotnet-operator-sdk/blob/master/src/KubeOps/Operator/Entities/CustomKubernetesEntity%7BTSpec%2CTStatus%7D.cs

which actually use types from this repo as starting point
