### ISSUE TITLE
[Question] Is it possible to use jsonpath similar to 'kubectl get pods -o jsopath ="{...}" using this client?

### ISSUE THREAD

**Issue by gal-ofir-ms** [kubernetes-client/csharp#503]
As per the title, if so, is there an example somewhere that I might've missed?

**Comment by tg123** [comment]
you have to do it yourself by call `ListNamespacedPod`

**Comment by gal-ofir-ms** [comment]
What parameter do I pass that indicates jsonpath? is it fieldSelector? Or do you mean that I have to get the entire response and extract the desired fields from it myself

**Comment by tg123** [comment]
`fieldSelector` is a `filter` for which pods to return from server side, not the `field` of the returning objs
you have to do jsonpath with the raw objs
