### ISSUE TITLE
the encoding bug of Yaml.ByteArrayStringYamlConverter

### ISSUE THREAD

**Issue by king311247** [kubernetes-client/csharp#507]
the yaml utils Yaml.ByteArrayStringYamlConverter use utf-8 to encoding byte[] to string, but the json serialize utils use the base64 to convert byte[] to string 

use the sdk to create like V1Secret will cause the encoding bug,because the sdk use the SafeJsonConvert to serialize 

![image](https://user-images.githubusercontent.com/10952874/97389208-c9c36c00-1914-11eb-9b89-2c91ac573bd7.png)
![image](https://user-images.githubusercontent.com/10952874/97389241-d3e56a80-1914-11eb-9463-5ad86b3dd47b.png)

solution:
change the code like this

![image](https://user-images.githubusercontent.com/10952874/97389401-2a52a900-1915-11eb-9759-e29694bf2625.png)

**Comment by tg123** [comment]
byte[] in secret should be always base64 encoded.
could you paste the code where you use yaml?

**Comment by king311247** [comment]
> byte[] in secret should be always base64 encoded.
> could you paste the code where you use yaml?

the byte[] in secret base64 is right,I means the yaml utils int kubernetes-client 
https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/Yaml.cs 

![image](https://user-images.githubusercontent.com/10952874/97398248-d2706e00-1925-11eb-8fa2-a853d50d26c3.png)

Deserialized object's  byte[] Property is utf-8
before use http to send, use then SafeJsonConvert  to serialize is base64,so the secret content is changed

**Comment by king311247** [comment]
> > byte[] in secret should be always base64 encoded.
> > could you paste the code where you use yaml?
> 
> the byte[] in secret base64 is right,I means the yaml utils int kubernetes-client
> https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/Yaml.cs
> 
> ![image](https://user-images.githubusercontent.com/10952874/97398248-d2706e00-1925-11eb-8fa2-a853d50d26c3.png)
> 
> Deserialized object's byte[] Property is utf-8
> before use http to send, use then SafeJsonConvert to serialize is base64,so the secret content is changed

my yaml content:

`apiVersion: v1
kind: Secret
metadata:
  name: default-server-secret
  namespace: @@namespace@@
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN2akNDQWFZQ0NRREFPRjl0THNhWFhEQU5CZ2txaGtpRzl3MEJBUXNGQURBaE1SOHdIUVlEVlFRRERCWk8KUjBsT1dFbHVaM0psYzNORGIyNTBjbTlzYkdWeU1CNFhEVEU0TURreE1qRTRNRE16TlZvWERUSXpNRGt4TVRFNApNRE16TlZvd0lURWZNQjBHQTFVRUF3d1dUa2RKVGxoSmJtZHlaWE56UTI5dWRISnZiR3hsY2pDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUwvN2hIUEtFWGRMdjNyaUM3QlBrMTNpWkt5eTlyQ08KR2xZUXYyK2EzUDF0azIrS3YwVGF5aGRCbDRrcnNUcTZzZm8vWUk1Y2Vhbkw4WGM3U1pyQkVRYm9EN2REbWs1Qgo4eDZLS2xHWU5IWlg0Rm5UZ0VPaStlM2ptTFFxRlBSY1kzVnNPazFFeUZBL0JnWlJVbkNHZUtGeERSN0tQdGhyCmtqSXVuektURXUyaDU4Tlp0S21ScUJHdDEwcTNRYzhZT3ExM2FnbmovUWRjc0ZYYTJnMjB1K1lYZDdoZ3krZksKWk4vVUkxQUQ0YzZyM1lma1ZWUmVHd1lxQVp1WXN2V0RKbW1GNWRwdEMzN011cDBPRUxVTExSakZJOTZXNXIwSAo1TmdPc25NWFJNV1hYVlpiNWRxT3R0SmRtS3FhZ25TZ1JQQVpQN2MwQjFQU2FqYzZjNGZRVXpNQ0F3RUFBVEFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWpLb2tRdGRPcEsrTzhibWVPc3lySmdJSXJycVFVY2ZOUitjb0hZVUoKdGhrYnhITFMzR3VBTWI5dm15VExPY2xxeC9aYzJPblEwMEJCLzlTb0swcitFZ1U2UlVrRWtWcitTTFA3NTdUWgozZWI4dmdPdEduMS9ienM3bzNBaS9kclkrcUI5Q2k1S3lPc3FHTG1US2xFaUtOYkcyR1ZyTWxjS0ZYQU80YTY3Cklnc1hzYktNbTQwV1U3cG9mcGltU1ZmaXFSdkV5YmN3N0NYODF6cFErUyt1eHRYK2VBZ3V0NHh3VlI5d2IyVXYKelhuZk9HbWhWNThDd1dIQnNKa0kxNXhaa2VUWXdSN0diaEFMSkZUUkk3dkhvQXprTWIzbjAxQjQyWjNrN3RXNQpJUDFmTlpIOFUvOWxiUHNoT21FRFZkdjF5ZytVRVJxbStGSis2R0oxeFJGcGZnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdi91RWM4b1JkMHUvZXVJTHNFK1RYZUprckxMMnNJNGFWaEMvYjVyYy9XMlRiNHEvClJOcktGMEdYaVN1eE9ycXgrajlnamx4NXFjdnhkenRKbXNFUkJ1Z1B0ME9hVGtIekhvb3FVWmcwZGxmZ1dkT0EKUTZMNTdlT1l0Q29VOUZ4amRXdzZUVVRJVUQ4R0JsRlNjSVo0b1hFTkhzbysyR3VTTWk2Zk1wTVM3YUhudzFtMApxWkdvRWEzWFNyZEJ6eGc2clhkcUNlUDlCMXl3VmRyYURiUzc1aGQzdUdETDU4cGszOVFqVUFQaHpxdmRoK1JWClZGNGJCaW9CbTVpeTlZTW1hWVhsMm0wTGZzeTZuUTRRdFFzdEdNVWozcGJtdlFmazJBNnljeGRFeFpkZFZsdmwKMm82MjBsMllxcHFDZEtCRThCay90elFIVTlKcU56cHpoOUJUTXdJREFRQUJBb0lCQVFDZklHbXowOHhRVmorNwpLZnZJUXQwQ0YzR2MxNld6eDhVNml4MHg4Mm15d1kxUUNlL3BzWE9LZlRxT1h1SENyUlp5TnUvZ2IvUUQ4bUFOCmxOMjRZTWl0TWRJODg5TEZoTkp3QU5OODJDeTczckM5bzVvUDlkazAvYzRIbjAzSkVYNzZ5QjgzQm9rR1FvYksKMjhMNk0rdHUzUmFqNjd6Vmc2d2szaEhrU0pXSzBwV1YrSjdrUkRWYmhDYUZhNk5nMUZNRWxhTlozVDhhUUtyQgpDUDNDeEFTdjYxWTk5TEI4KzNXWVFIK3NYaTVGM01pYVNBZ1BkQUk3WEh1dXFET1lvMU5PL0JoSGt1aVg2QnRtCnorNTZud2pZMy8yUytSRmNBc3JMTnIwMDJZZi9oY0IraVlDNzVWYmcydVd6WTY3TWdOTGQ5VW9RU3BDRkYrVm4KM0cyUnhybnhBb0dCQU40U3M0ZVlPU2huMVpQQjdhTUZsY0k2RHR2S2ErTGZTTXFyY2pOZjJlSEpZNnhubmxKdgpGenpGL2RiVWVTbWxSekR0WkdlcXZXaHFISy9iTjIyeWJhOU1WMDlRQ0JFTk5jNmtWajJTVHpUWkJVbEx4QzYrCk93Z0wyZHhKendWelU0VC84ajdHalRUN05BZVpFS2FvRHFyRG5BYWkyaW5oZU1JVWZHRXFGKzJyQW9HQkFOMVAKK0tZL0lsS3RWRzRKSklQNzBjUis3RmpyeXJpY05iWCtQVzUvOXFHaWxnY2grZ3l4b25BWlBpd2NpeDN3QVpGdwpaZC96ZFB2aTBkWEppc1BSZjRMazg5b2pCUmpiRmRmc2l5UmJYbyt3TFU4NUhRU2NGMnN5aUFPaTVBRHdVU0FkCm45YWFweUNweEFkREtERHdObit3ZFhtaTZ0OHRpSFRkK3RoVDhkaVpBb0dCQUt6Wis1bG9OOTBtYlF4VVh5YUwKMjFSUm9tMGJjcndsTmVCaWNFSmlzaEhYa2xpSVVxZ3hSZklNM2hhUVRUcklKZENFaHFsV01aV0xPb2I2NTNyZgo3aFlMSXM1ZUtka3o0aFRVdnpldm9TMHVXcm9CV2xOVHlGanIrSWhKZnZUc0hpOGdsU3FkbXgySkJhZUFVWUNXCndNdlQ4NmNLclNyNkQrZG8wS05FZzFsL0FvR0FlMkFVdHVFbFNqLzBmRzgrV3hHc1RFV1JqclRNUzRSUjhRWXQKeXdjdFA4aDZxTGxKUTRCWGxQU05rMXZLTmtOUkxIb2pZT2pCQTViYjhibXNVU1BlV09NNENoaFJ4QnlHbmR2eAphYkJDRkFwY0IvbEg4d1R0alVZYlN5T294ZGt5OEp0ek90ajJhS0FiZHd6NlArWDZDODhjZmxYVFo5MWpYL3RMCjF3TmRKS2tDZ1lCbyt0UzB5TzJ2SWFmK2UwSkN5TGhzVDQ5cTN3Zis2QWVqWGx2WDJ1VnRYejN5QTZnbXo5aCsKcDNlK2JMRUxwb3B0WFhNdUFRR0xhUkcrYlNNcjR5dERYbE5ZSndUeThXczNKY3dlSTdqZVp2b0ZpbmNvVlVIMwphdmxoTUVCRGYxSjltSDB5cDBwWUNaS2ROdHNvZEZtQktzVEtQMjJhTmtsVVhCS3gyZzR6cFE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---`

use the yaml util in kubernetes-client to load to object（at this time， the content is still the same as yaml content）
![image](https://user-images.githubusercontent.com/10952874/97399084-5545f880-1927-11eb-8649-3ee2066c0da4.png)

use the SafeJsonConvert.SerializeObject(targetResource) (at this time the content  is changed)
![image](https://user-images.githubusercontent.com/10952874/97399298-d43b3100-1927-11eb-8a8e-b1dd3cdb4c10.png)

and the yaml in k8s is like this 

`apiVersion: v1
data:
  tls.crt: TFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVTjJha05EUVdGWlEwTlJSRUZQUmpsMFRITmhXRmhFUVU1Q1oydHhhR3RwUnpsM01FSkJVWE5HUVVSQmFFMVNPSGRJVVZsRVZsRlJSRVJDV2s4S1VqQnNUMWRGYkhWYU0wcHNZek5PUkdJeU5UQmpiVGx6WWtkV2VVMUNORmhFVkVVMFRVUnJlRTFxUlRSTlJFMTZUbFp2V0VSVVNYcE5SR3Q0VFZSRk5BcE5SRTE2VGxadmQwbFVSV1pOUWpCSFFURlZSVUYzZDFkVWEyUktWR3hvU21KdFpIbGFXRTU2VVRJNWRXUklTblppUjNoc1kycERRMEZUU1hkRVVWbEtDa3R2V2tsb2RtTk9RVkZGUWtKUlFVUm5aMFZRUVVSRFEwRlJiME5uWjBWQ1FVd3ZOMmhJVUV0RldHUk1kak55YVVNM1FsQnJNVE5wV2t0NWVUbHlRMDhLUjJ4WlVYWXlLMkV6VURGMGF6SXJTM1l3VkdGNWFHUkNiRFJyY25OVWNUWnpabTh2V1VrMVkyVmhia3c0V0dNM1UxcHlRa1ZSWW05RU4yUkViV3MxUWdvNGVEWkxTMnhIV1U1SVdsZzBSbTVVWjBWUGFTdGxNMnB0VEZGeFJsQlNZMWt6Vm5OUGF6RkZlVVpCTDBKbldsSlZia05IWlV0R2VFUlNOMHRRZEdoeUNtdHFTWFZ1ZWt0VVJYVXlhRFU0VGxwMFMyMVNjVUpIZERFd2NUTlJZemhaVDNFeE0yRm5ibW92VVdSamMwWllZVEpuTWpCMUsxbFlaRGRvWjNrclprc0tXazR2VlVreFFVUTBZelp5TTFsbWExWldVbVZIZDFseFFWcDFXWE4yVjBSS2JXMUdOV1J3ZEVNek4wMTFjREJQUlV4VlRFeFNha1pKT1RaWE5YSXdTQW8xVG1kUGMyNU5XRkpOVjFoWVZscGlOV1J4VDNSMFNtUnRTM0ZoWjI1VFoxSlFRVnBRTjJNd1FqRlFVMkZxWXpaak5HWlJWWHBOUTBGM1JVRkJWRUZPQ2tKbmEzRm9hMmxIT1hjd1FrRlJjMFpCUVU5RFFWRkZRV3BMYjJ0UmRHUlBjRXNyVHpoaWJXVlBjM2x5U21kSlNYSnljVkZWWTJaT1VpdGpiMGhaVlVvS2RHaHJZbmhJVEZNelIzVkJUV0k1ZG0xNVZFeFBZMnh4ZUM5YVl6SlBibEV3TUVKQ0x6bFRiMHN3Y2l0RloxVTJVbFZyUld0V2NpdFRURkEzTlRkVVdnb3paV0k0ZG1kUGRFZHVNUzlpZW5NM2J6TkJhUzlrY2xrcmNVSTVRMmsxUzNsUGMzRkhURzFVUzJ4RmFVdE9Za2N5UjFaeVRXeGpTMFpZUVU4MFlUWTNDa2xuYzFoellrdE5iVFF3VjFVM2NHOW1jR2x0VTFabWFYRlNka1Y1WW1OM04wTllPREY2Y0ZFclV5dDFlSFJZSzJWQlozVjBOSGgzVmxJNWQySXlWWFlLZWxodVprOUhiV2hXTlRoRGQxZElRbk5LYTBreE5YaGFhMlZVV1hkU04wZGlhRUZNU2taVVVrazNka2h2UVhwclRXSXpiakF4UWpReVdqTnJOM1JYTlFwSlVERm1UbHBJT0ZVdk9XeGlVSE5vVDIxRlJGWmtkakY1Wnl0VlJWSnhiU3RHU2lzMlIwb3hlRkpHY0dablBUMEtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJWRVV0TFMwdExRbz0=
  tls.key: TFMwdExTMUNSVWRKVGlCU1UwRWdVRkpKVmtGVVJTQkxSVmt0TFMwdExRcE5TVWxGY0VGSlFrRkJTME5CVVVWQmRpOTFSV000YjFKa01IVXZaWFZKVEhORksxUllaVXByY2t4TU1uTkpOR0ZXYUVNdllqVnlZeTlYTWxSaU5IRXZDbEpPY2t0R01FZFlhVk4xZUU5eWNYZ3JhamxuYW14NE5YRmpkbmhrZW5SS2JYTkZVa0oxWjFCME1FOWhWR3RJZWtodmIzRlZXbWN3Wkd4bVoxZGtUMEVLVVRaTU5UZGxUMWwwUTI5Vk9VWjRhbVJYZHpaVVZWUkpWVVE0UjBKc1JsTmpTVm8wYjFoRlRraHpieXN5UjNWVFRXazJaazF3VFZNM1lVaHVkekZ0TUFweFdrZHZSV0V6V0ZOeVpFSjZlR2MyY2xoa2NVTmxVRGxDTVhsM1ZtUnlZVVJpVXpjMWFHUXpkVWRFVERVNGNHc3pPVkZxVlVGUWFIcHhkbVJvSzFKV0NsWkdOR0pDYVc5Q2JUVnBlVGxaVFcxaFdWaHNNbTB3VEdaemVUWnVVVFJSZEZGemRFZE5WV296Y0dKdGRsRm1hekpCTm5samVHUkZlRnBrWkZac2Rtd0tNbTgyTWpCc01sbHhjSEZEWkV0Q1JUaENheTkwZWxGSVZUbEtjVTU2Y0hwb09VSlVUWGRKUkVGUlFVSkJiMGxDUVZGRFprbEhiWG93T0hoUlZtb3JOd3BMWm5aSlVYUXdRMFl6UjJNeE5sZDZlRGhWTm1sNE1IZzRNbTE1ZDFreFVVTmxMM0J6V0U5TFpsUnhUMWgxU0VOeVVscDVUblV2WjJJdlVVUTRiVUZPQ214T01qUlpUV2wwVFdSSk9EZzVURVpvVGtwM1FVNU9PREpEZVRjemNrTTVielZ2VURsa2F6QXZZelJJYmpBelNrVllOelo1UWpnelFtOXJSMUZ2WWtzS01qaE1OazByZEhVelVtRnFOamQ2Vm1jMmQyc3phRWhyVTBwWFN6QndWMVlyU2pkclVrUldZbWhEWVVaaE5rNW5NVVpOUld4aFRsb3pWRGhoVVV0eVFncERVRE5EZUVGVGRqWXhXVGs1VEVJNEt6TlhXVkZJSzNOWWFUVkdNMDFwWVZOQloxQmtRVWszV0VoMWRYRkVUMWx2TVU1UEwwSm9TR3QxYVZnMlFuUnRDbm9yTlRadWQycFpNeTh5VXl0U1JtTkJjM0pNVG5Jd01ESlpaaTlvWTBJcmFWbEROelZXWW1jeWRWZDZXVFkzVFdkT1RHUTVWVzlSVTNCRFJrWXJWbTRLTTBjeVVuaHlibmhCYjBkQ1FVNDBVM00wWlZsUFUyaHVNVnBRUWpkaFRVWnNZMGsyUkhSMlMyRXJUR1pUVFhGeVkycE9aakpsU0VwWk5uaHVibXhLZGdwR2VucEdMMlJpVldWVGJXeFNla1IwV2tkbGNYWlhhSEZJU3k5aVRqSXllV0poT1UxV01EbFJRMEpGVGs1ak5tdFdhakpUVkhwVVdrSlZiRXg0UXpZckNrOTNaMHd5WkhoS2VuZFdlbFUwVkM4NGFqZEhhbFJVTjA1QlpWcEZTMkZ2UkhGeVJHNUJZV2t5YVc1b1pVMUpWV1pIUlhGR0t6SnlRVzlIUWtGT01WQUtLMHRaTDBsc1MzUldSelJLU2tsUU56QmpVaXMzUm1weWVYSnBZMDVpV0N0UVZ6VXZPWEZIYVd4blkyZ3JaM2w0YjI1QldsQnBkMk5wZUROM1FWcEdkd3BhWkM5NlpGQjJhVEJrV0VwcGMxQlNaalJNYXpnNWIycENVbXBpUm1SbWMybDVVbUpZYnl0M1RGVTROVWhSVTJOR01uTjVhVUZQYVRWQlJIZFZVMEZrQ200NVlXRndlVU53ZUVGa1JFdEVSSGRPYml0M1pGaHRhVFowT0hScFNGUmtLM1JvVkRoa2FWcEJiMGRDUVV0NldpczFiRzlPT1RCdFlsRjRWVmg1WVV3S01qRlNVbTl0TUdKamNuZHNUbVZDYVdORlNtbHphRWhZYTJ4cFNWVnhaM2hTWmtsTk0yaGhVVlJVY2tsS1pFTkZhSEZzVjAxYVYweFBiMkkyTlROeVpnbzNhRmxNU1hNMVpVdGthM28wYUZSVmRucGxkbTlUTUhWWGNtOUNWMnhPVkhsR2FuSXJTV2hLWm5aVWMwaHBPR2RzVTNGa2JYZ3lTa0poWlVGVldVTlhDbmROZGxRNE5tTkxjbE55TmtRclpHOHdTMDVGWnpGc0wwRnZSMEZsTWtGVmRIVkZiRk5xTHpCbVJ6Z3JWM2hIYzFSRlYxSnFjbFJOVXpSU1VqaFJXWFFLZVhkamRGQTRhRFp4VEd4S1VUUkNXR3hRVTA1ck1YWkxUbXRPVWt4SWIycFpUMnBDUVRWaVlqaGliWE5WVTFCbFYwOU5ORU5vYUZKNFFubEhibVIyZUFwaFlrSkRSa0Z3WTBJdmJFZzRkMVIwYWxWWllsTjVUMjk0Wkd0NU9FcDBlazkwYWpKaFMwRmlaSGQ2TmxBcldEWkRPRGhqWm14WVZGbzVNV3BZTDNSTUNqRjNUbVJLUzJ0RFoxbENieXQwVXpCNVR6SjJTV0ZtSzJVd1NrTjVUR2h6VkRRNWNUTjNaaXMyUVdWcVdHeDJXREoxVm5SWWVqTjVRVFpuYlhvNWFDc0tjRE5sSzJKTVJVeHdiM0IwV0ZoTmRVRlJSMHhoVWtjcllsTk5jalI1ZEVSWWJFNVpTbmRVZVRoWGN6TktZM2RsU1RkcVpWcDJiMFpwYm1OdlZsVklNd3BoZG14b1RVVkNSR1l4U2psdFNEQjVjREJ3V1VOYVMyUk9kSE52WkVadFFrdHpWRXRRTWpKaFRtdHNWVmhDUzNneVp6UjZjRkU5UFFvdExTMHRMVVZPUkNCU1UwRWdVRkpKVmtGVVJTQkxSVmt0TFMwdExRbz0=
kind: Secret`

**Comment by tg123** [comment]
could you please check out the unittest

https://github.com/kubernetes-client/csharp/blob/3772ffb838f737ae86baa739e0309209e3514557/tests/KubernetesClient.Tests/YamlTests.cs#L326

do you mean yaml should deserialize string into raw byte[] instead of base64?

**Comment by king311247** [comment]
> nstead of base64?
yes,change the yaml deserialize/serialize string into raw byte[] instead of base64,the it will same as SafeJsonConvert.SerializeObject(Secret)

you can compare with the Secret, that on is  use the sdk to create Secret and another use kubectl apply to create Secret( both use the same yaml)

**Comment by king311247** [comment]
> could you please check out the unittest
> 
> https://github.com/kubernetes-client/csharp/blob/3772ffb838f737ae86baa739e0309209e3514557/tests/KubernetesClient.Tests/YamlTests.cs#L326
> 
> do you mean yaml should deserialize string into raw byte[] instead of base64?

yaml:
`string kManifest = @"
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi
";`

sdk create secret:
![image](https://user-images.githubusercontent.com/10952874/97409476-a01c3c00-1938-11eb-95b9-8c6232825466.png)

kubectl apply secret:
![image](https://user-images.githubusercontent.com/10952874/97409544-c510af00-1938-11eb-88a6-27e73f477f9c.png)

**Comment by tg123** [comment]
let me confirm
calling `create/apply` via sdk yields a bad `byte[]` value
right?

seems nothing to do with yaml
client side did extra base64 for the byte[] values

**Comment by king311247** [comment]
> let me confirm
> calling `create/apply` via sdk yields a bad `byte[]` value
> right?
> 
> seems nothing to do with yaml
> client side did extra base64 for the byte[] values

not the command of create/apply problem.
i means the c# kubernetes-client load the yaml to object and use the sdk to send Secret ; and another way is use kubectl apply -f yaml to create Secret ,and kubectl get Secret -o yaml, the Secret's data are diff
