### ISSUE TITLE
Nuget package versionning

### ISSUE THREAD

**Issue by sraillard** [kubernetes-client/csharp#514]
When installing the Nuget package, I can a version number (for example, today the most recent is version 3.0.7).
But I can't see any reference to this package version number from the git repository.
If I want to know in which package version a fix is done, how I can find its version?
Do you plan to tag the commit used to build the package with its version?

**Comment by brendandburns** [comment]
Every pull request that merges kicks off a build/release cycle, so the latest nuget is always at HEAD and as you subtract patch versions you work backwards in pull requests merged.

We should probably tag the repo also...

**Comment by tg123** [comment]
see also #400

**Comment by sraillard** [comment]
In the repo, where the Nuget package version is set? I think knowning what is in the version installed is important! Or we just keep the version updated to the latest...

**Comment by tg123** [comment]
version auto inc when `push to nuget` job runs
https://github.com/kubernetes-client/csharp/blob/master/.github/workflows/nuget.yaml

here base version defined
https://github.com/kubernetes-client/csharp/blob/master/version.json

**Comment by sraillard** [comment]
Ok, thank you, that's not very common to have the versioning made by the build system! 
This is making difficult/impossible to find which commit/PR is linked to a version number.

**Comment by qmfrederik** [comment]
The SHA of the Git commit off which the NuGet package was built is visible in the properties of the KubernetesClient.dll file (see screenshot below).

You can access it programmatically using this code:

```csharp
var k8sClientVersionAttribute = (AssemblyInformationalVersionAttribute)typeof(k8s.Kubernetes).Assembly.GetCustomAttribute(typeof(AssemblyInformationalVersionAttribute));
var k8sClientVersion = k8sClientVersionAttribute.InformationalVersion;
```

See https://github.com/dotnet/nerdbank.gitversioning for more information on the system used to generate the version information.

![image](https://user-images.githubusercontent.com/9918129/105194462-e3520980-5b39-11eb-8f28-b668431c05d3.png)

**Comment by sraillard** [comment]
Thank you!
