### ISSUE TITLE
Recommendation for initializing KubernetesClientConfiguration for production AKS cluster

### ISSUE THREAD

**Issue by smithago** [kubernetes-client/csharp#516]
Hello,

We are using the .net client to create custom resources on kubernetes during provisioning. 
What is the recommended way to generate the KubernetesClientConfiguration object? Maybe in-turn how do we generate and keep kube config for production servers? We generally use service principles identity during provisioning.

Thanks,
Smitha (smithasa@microsoft.com)

**Comment by brendandburns** [comment]
Is this inside the cluster? If it is inside the cluster, you should use Kubernetes Service Accounts:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

This code will pick up that identity/auth info automatically if it is running inside a Pod.

**Comment by smithago** [comment]
This is outside the k8s cluster, with help internal, here is a possible solution to use service principle credentials using [Kubelogin](https://github.com/Azure/kubelogin) 
1. Use kubelogin setup and run for service principle. 
2. .net client code to pass in the env variables below

```csharp
k8s.KubeConfigModels.K8SConfiguration configModel = KubernetesClientConfiguration.LoadKubeConfig(stream);
            configModel.Users.First().UserCredentials.ExternalExecution.EnvironmentVariables = new List<Dictionary<string, string>>
            {
                new Dictionary<string, string>()
                {
                    { "name", "AAD_SERVICE_PRINCIPAL_CLIENT_ID" },
                    { "value", spConfig.ClientId },
                },
                new Dictionary<string, string>()
                {
                    { "name", "AAD_SERVICE_PRINCIPAL_CLIENT_SECRET" },
                    { "value", spConfig.ClientSecret },
                },
            };

            var config = KubernetesClientConfiguration.BuildConfigFromConfigObject(configModel);
            var kubeClient = new Kubernetes(config);

```

**Comment by smithago** [comment]
And here is variation which has no dependency on Kubelogin, basically generate the token yourself, you still have to make sure the AAD auth is enabled for AKS and Service Principle ObjectID has the right ClusterRoleBinding set on AKS.

```csharp
private const string AzureKubernetesServerId = "6dae42f8-4368-4678-94ff-3960e28e3630";
        
public async Task<string> GenerateAzureKubernetesTokenAsync()
        {
            var tokenCache = new TokenCache();

            var uriBuilder = new UriBuilder(_spConfig.AadEndpoint);
            uriBuilder.Path = _spConfig.TenantId;

            var authenticationContext = new AuthenticationContext(uriBuilder.ToString(), tokenCache);
            var clientCredential = new ClientCredential(_spConfig.ClientId, _spConfig.ClientSecret);

            var result = await authenticationContext.AcquireTokenAsync(AzureKubernetesServerId, clientCredential);

            return result.AccessToken;
        }
    }

// set the service principle access token
            k8s.KubeConfigModels.K8SConfiguration configModel = KubernetesClientConfiguration.LoadKubeConfig(stream);
            configModel.Users.First().UserCredentials.Token = await _tokenProvider.GenerateAzureKubernetesTokenAsync();

            var config = KubernetesClientConfiguration.BuildConfigFromConfigObject(configModel);
            return new Kubernetes(config);

```

**Comment by tg123** [comment]
just use config.TokenProvider = `the token provider from aad`

**Comment by sw-ms-pradipbaria** [comment]
> ```cs
> AzureKubernetesServerId 
> ```

@smithago 
Thanks for code snippet, can you please let me know from where I can get AzureKubernetesServerId?
Or any sample/reference link for this detail.

Thanks.
