### ISSUE TITLE
PatchNamespacedCustomObject does not support taking v1patch as argument

### ISSUE THREAD

**Issue by rapatchi** [kubernetes-client/csharp#528]
Hi, 

I am trying to update the status of CRD using the above API PatchNamespacedCustomObject. As it does not support V1Patch as argument i get the below error:
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml","reason":"UnsupportedMediaType","code":415}

Is the above above API the correct one which I should use for patching CRD. I even tried using PatchNamespacedCustomObjectStatus. But it throws 404 error with response message as:

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"clusterconnectroutes.clusterconnect.azure.com \"testservicecr\" not found","reason":"NotFound","details":{"name":"testservicecr","group":"clusterconnect.azure.com","kind":"clusterconnectroutes"},"code":404}

**Comment by brendandburns** [comment]
Please have a look at the example here:

**Comment by brendandburns** [comment]
fwiw, the URL for the first request is correct, but your Content-type header is wrong.

If the example above doesn't help, please send your complete code for patching so that we can debug.

**Comment by rapatchi** [comment]
Yes I did took a look into that example. But there is no overload PatchNamespacedCustomObject  which takes V1Patch as argument so that the content-type header could be passed correctly. It currently only takes object as argument.

**Comment by smartservice-energy** [comment]
Either the GetHeader(object body) method should be amended with
            if (body is V1Patch)
            {
                return GetHeader(body as V1Patch);
            }
or the generated code must take as the first argument as V1Patch body instead of object body

**Comment by tg123** [comment]
true
`PatchNamespacedCustomObject` did not handle `object` param. `GetHeader` returned json instead of patch
