### ISSUE TITLE
Behavior of dry run with ReplaceNamespacedServiceAsync

### ISSUE THREAD

**Issue by kuldeepGDI** [kubernetes-client/csharp#531]
Hi, I am trying to call ReplaceNamespacedServiceAsync with dryRun set to "All". I am expecting the dry run to fail in my test, but it does not. However, the actual run without dryRun parameter fails as expected.

What is the behavior for dryRun in this situation ? I have to update both deployment and service file with new ports, and since these are two separate transactions, i want to make sure that the updates occur only when both dryRuns are successful. Am I doing something wrong OR my understanding on dryRun is wrong ? 

Thanks

**Comment by kuldeepGDI** [comment]
I am attaching here the screenshot from my sample 

![image](https://user-images.githubusercontent.com/61690328/100631129-afbde480-332b-11eb-88c1-aba1e0ade318.png)

![image](https://user-images.githubusercontent.com/61690328/100631164-b8aeb600-332b-11eb-96bd-4c9b41e5e303.png)

when I pass dryRun "All" no exception is thrown. However, I expect it to throw an exception just like it would without dryRun argument. e.g. I receive following error in HttpOperationException when i run it without dryRun argument. 

![image](https://user-images.githubusercontent.com/61690328/100631353-eb58ae80-332b-11eb-9297-c43e8f49969f.png)


Thank you

**Comment by brendandburns** [comment]
I'm not sure if 'dry-run' applies to `replace`. It's not present in `kubectl` and I'm not sure what it would even mean.

I suspect that it's an error in the OpenAPI spec that includes `dry-run` as a parameter for `replace`.

What is your use case?

**Comment by k2ibegin** [comment]
I am away from my other laptop and account so using my personal github account. 

The use case is that we change the ports in deployment file and then in the service yml. However, I want to make sure that it is atomic operation, which means, to make sure that only run this on both deployment and services when the dry Run is successful on both of them. I am trying to avoid a scenario where for some reason, the deployments file was updated with new ports but service updation somehow failed. My sequence of update is replaceNamespacedDeployment and then replaceNamespacedServices. 

I was also thinking may be to restore the deployment if for some reason replaceService fails and replaceDeployment succeeded. However, this solution feels not clean imo in the code.

**Comment by kuldeepGDI** [comment]
The use case is that we change the ports in deployment file and then in the service yml. However, I want to make sure that it is atomic operation, which means, to make sure that only run this on both deployment and services when the dry Run is successful on both of them. I am trying to avoid a scenario where for some reason, the deployments file was updated with new ports but service updation somehow failed. My sequence of update is replaceNamespacedDeployment and then replaceNamespacedServices.

I was also thinking may be to restore the deployment if for some reason replaceService fails and replaceDeployment succeeded. However, this solution feels not clean imo in the code. In addition, i have also not looked into this possibility as i was hoping that dryRun will make this simpler.

**Comment by brendandburns** [comment]
In general, this sort of transactional update of multiple objects in Kubernetes isn't very well supported. The second update could fail for a variety of reasons beyond basic validation.

Additionally, you are introducing a tight dependency between deployment and service that will be inherently brittle in an asynchronous world.

If you really want to do an atomic update like this, the more Kubernetes style approach is to introduce a custom resource (CRD) and an operator. That way you can make an atomic update to your single resource, and then your operator can perform the updates to both the service and the deployment in a self-healing loop that ensures that both deployment and service are updated.

**Comment by kuldeepGDI** [comment]
Thank you. Are there any samples associated with createing CRD and operator via this client library  ?
