### ISSUE TITLE
Not Able to set annotation using the client library

### ISSUE THREAD

**Issue by digeler** [kubernetes-client/csharp#532]
i have this deployment in my code ,but the annotation fails :
 private V1Deployment BuildDeployment() =>
            new V1Deployment
            {
                ApiVersion = $"{V1Deployment.KubeGroup}/{V1Deployment.KubeApiVersion}",
                Kind = V1Deployment.KubeKind,
                Metadata = new V1ObjectMeta
                {
                    Name = KubernetesServiceName,
                    Annotations = new NameValueDictionary
                    {
                       ["prometheus.io/scrape"] = "true",
                       ["prometheus.io/path"] = "/metrics",
                       ["prometheus.io/port"] = "52325"
                    }

                },
                Spec = new V1DeploymentSpec
                {
                    Replicas = ReplicaCount,
                    Selector = new V1LabelSelector
                    {
                        MatchLabels = new Dictionary<string, string>
                        {
                            ["app"] = KubernetesServiceName
                        }
                    },

when running the code i get the following error  : 
Deploy-PolyManagementApiService: HelmUpgradeCommand failed. [ExitCode=1 StandardError=Error: UPGRADE FAILED: unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found 5, error found in #10 byte of ...|io/port":52325,"prom|..., bigger context ...|metheus.io/path":"/metrics","prometheus.io/port":52325,"prometheus.io/scrape":true},"name":"manageme|...
 StandardOutput=]

can you show me an example please how do i pass these annotations ?

thank you.

**Comment by brendandburns** [comment]
I _think_ that the problem here is that you have a number `52325` instead of a string `"52325"` as the value in your annotation.

I'm not sure where that's coming from.

Can you give a more complete example of your code? It's hard for me to tell where the parsing is failing.

**Comment by digeler** [comment]
Sure ,here is my full deployment yaml : 

 public override IReadOnlyCollection<IKubernetesObject> BuildObjects() =>
            base.BuildObjects().
                Concat(
                    new IKubernetesObject[]
                    {
                        BuildLoadBalancerService(),
                        BuildDeployment()
                    }).
                ToList();

        private V1Deployment BuildDeployment() =>
            new V1Deployment
            {
                ApiVersion = $"{V1Deployment.KubeGroup}/{V1Deployment.KubeApiVersion}",
                Kind = V1Deployment.KubeKind,
                Metadata = new V1ObjectMeta
                {
                    Name = KubernetesServiceName,
                    Annotations = new Dictionary<string, string>
                    {
                       ["prometheus.io/scrape"] = "true",
                       ["prometheus.io/path"] = "/metrics",
                       ["prometheus.io/port"] = "52325"
                    }

                },
                Spec = new V1DeploymentSpec
                {
                    Replicas = ReplicaCount,
                    Selector = new V1LabelSelector
                    {
                        MatchLabels = new Dictionary<string, string>
                        {
                            ["app"] = KubernetesServiceName
                        }
                    },
                    Template = new V1PodTemplateSpec
                    {
                        Metadata = new V1ObjectMeta
                        {
                            Labels = new Dictionary<string, string>
                            {
                                ["app"] = KubernetesServiceName,
                                ["aadpodidbinding"] = StaticInformation.IdentitySelector
                            }
                        },
                        Spec = new V1PodSpec
                        {
                            ShareProcessNamespace = true,
                            Containers = new[]
                            {
                                new V1Container
                                {
                                    Name = KubernetesServiceName,
                                    Image = DockerImageIdentifier.ToString(),
                                    ImagePullPolicy = "Always",
                                    Env = new[]
                                    {
                                        new V1EnvVar
                                        {
                                            Name = "CLUSTER_NAME",
                                            Value = _globalClusterContext.Name
                                        },
                                        new V1EnvVar
                                        {
                                            Name = "NAMESPACE_NAME",
                                            ValueFrom = new V1EnvVarSource
                                            {
                                                FieldRef = new V1ObjectFieldSelector
                                                {
                                                    FieldPath = $"{nameof(V1StatefulSet.Metadata)}.namespace".ToLower()
                                                }
                                            }
                                        },
                                        new V1EnvVar
                                        {
                                            Name = "POD_NAME",
                                            ValueFrom = new V1EnvVarSource
                                            {
                                                FieldRef = new V1ObjectFieldSelector
                                                {
                                                    FieldPath = $"{nameof(V1Deployment.Metadata)}.{nameof(V1Deployment.Metadata.Name)}".ToLower()
                                                }
                                            }
                                        },
                                        new V1EnvVar
                                        {
                                            Name = "CONTAINER_NAME",
                                            Value = KubernetesServiceName
                                        },
                                        new DoubleQuotedEnvironmentVariable
                                        {
                                            Name = "POCOSerializationOnly",
                                            Value = 1.ToString()
                                        }
                                    },
                                    VolumeMounts = new List<V1VolumeMount>
                                    {
                                        new V1VolumeMount
                                        {
                                            Name = nameof(ServiceConfigurationManager.ServiceConfigurationVolume).Kebaberize(),
                                            MountPath = ServiceConfigurationManager.ServiceConfigurationVolume,
                                            ReadOnlyProperty = true
                                        },
                                        new V1VolumeMount
                                        {
                                            Name = "diagnostics",
                                            MountPath = "/tmp"
                                        }
                                    },
                                    LivenessProbe = new V1Probe
                                    {
                                        InitialDelaySeconds = 10,
                                        PeriodSeconds = 30,
                                        TimeoutSeconds = 20,
                                        HttpGet = new V1HTTPGetAction
                                        {
                                            Port = 443,
                                            Path = "/health",
                                            Scheme = "HTTPS"
                                        }
                                    },
                                    ReadinessProbe = new V1Probe
                                    {
                                        InitialDelaySeconds = 3,
                                        PeriodSeconds = 20,
                                        TimeoutSeconds = 15,
                                        HttpGet = new V1HTTPGetAction
                                        {
                                            Port = 443,
                                            Path = "/health",
                                            Scheme = "HTTPS"
                                        }
                                    },
                                    Resources = PodConstrains.ToResourceRequirements(),
                                    Ports =
                                        _ports.Select(
                                            port =>
                                                new V1ContainerPort
                                                {
                                                    ContainerPort = port,
                                                    Name = $"port-{port}"
                                                }).ToList()
                                },
                                new V1Container
                                {
                                    Name = "diagsidecar",
                                    Image = "mcr.microsoft.com/dotnet/nightly/monitor:5.0.0-preview.1",
                                    Args = new List<string>
                                    {
                                        "--urls", "http://*:52323", "--metricUrls", "http://*:52325"
                                    },
                                    ImagePullPolicy = "Always",
                                    VolumeMounts = new List<V1VolumeMount>
                                    {
                                        new V1VolumeMount
                                        {
                                            Name = "diagnostics",
                                            MountPath = "/tmp"
                                        }
                                    },
                                    SecurityContext = new V1SecurityContext
                                    {
                                        Capabilities = new V1Capabilities
                                        {
                                            Add = new List<string>
                                            {
                                                "SYS_PTRACE"
                                            }
                                        }
                                    },
                                    Ports = new List<V1ContainerPort>
                                    {
                                        new V1ContainerPort
                                        {
                                            ContainerPort = 52325
                                        }
                                    }
                                }
                            },
                            Volumes = new List<V1Volume>
                            {
                                new V1Volume
                                {
                                    Name = nameof(ServiceConfigurationManager.ServiceConfigurationVolume).Kebaberize(),
                                    ConfigMap = new V1ConfigMapVolumeSource
                                    {
                                        Name = ServiceConfigurationTypeName.Kebaberize(),
                                        Items = new[]
                                        {
                                            new V1KeyToPath
                                            {
                                                Key = ServiceConfigurationTypeName,
                                                Path = $"{ServiceConfigurationTypeName}.json"
                                            }
                                        }
                                    }
                                },
                                new V1Volume
                                {
                                    Name = "diagnostics",
                                    EmptyDir = new V1EmptyDirVolumeSource()
                                }
                            }
                        }
                    }
                }

when i run it i get the following error : 
Deploy-PolyManagementApiService: HelmUpgradeCommand failed. [ExitCode=1 StandardError=Error: UPGRADE FAILED: unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|/scrape":true},"name|..., bigger context ...|metadata":{"annotations":{"prometheus.io/scrape":true},"name":"managementapiweb"},"spec":{"replicas"|...
 StandardOutput=]

thanks Brendan ,much appreciated.

**Comment by brendandburns** [comment]
I assume that you are serializing this to JSON? How are you serializing it?

Somewhere along the way strings are being converted into JSON literals (e.g. `true` or `5243`) which is then causing the parser on the other side to be unhappy.

**Comment by akanso** [comment]
Creating deployments with annotations works fine for me. (both for the deployment, and its pods)

I used the client:

```
var k8SClientConfig = KubernetesClientConfiguration.BuildConfigFromConfigFile();
IKubernetes client = new Kubernetes(k8SClientConfig);
```
The full code is shown below.

Running the example:
```
dotnet run
```
```
strating main()
creating deployment: deploy-sample
fetching deployment: deploy-sample
Annotations:
- Key = deployment.kubernetes.io/revision, Value = 1
- Key = prometheus.io/path, Value = /metrics
- Key = prometheus.io/port, Value = 52325
- Key = prometheus.io/scrape, Value = true
```

```
dotnet --version
5.0.100
```

```
lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

```
kubectl describe pod | grep -i -a5  annotations
Priority:     0
Node:         akanso-workstation/172.16.6.4
Start Time:   Mon, 21 Dec 2020 17:50:51 +0000
Labels:       app=deploy-sample
              pod-template-hash=6d5fd786db
Annotations:  prometheus.io/path: /metrics
              prometheus.io/port: 52325
              prometheus.io/scrape: true
Status:       Running
IP:           10.1.73.200
```
The full code I used is shown below:

```
using System;
using System.Collections.Generic;
using k8s;
using k8s.Models;
using System.Threading.Tasks;
using System.Threading;
using Microsoft.Rest.Serialization;


namespace custom_resource
{
    class Program
    {
        private static async Task Main(string[] args)
        {
            Console.WriteLine("strating main()");

            //creating client
            var k8SClientConfig = KubernetesClientConfiguration.BuildConfigFromConfigFile();
            IKubernetes client = new Kubernetes(k8SClientConfig);


            V1Deployment myDeploy = new V1Deployment()
            {
                ApiVersion = "apps/v1",
                Kind = "Deployment",
                Metadata = new V1ObjectMeta()
                {
                    Name = "deploy-sample",
                    NamespaceProperty = null,
                    Annotations = new Dictionary<string, string>
                    {
                        ["prometheus.io/scrape"] = "true",
                        ["prometheus.io/path"] = "/metrics",
                        ["prometheus.io/port"] = "52325"
                    },
                    Labels = new Dictionary<string, string>()
                    {
                        { "app", "deploy-sample" }
                    }
                },
                Spec = new V1DeploymentSpec
                {
                    Replicas = 1,
                    Selector = new V1LabelSelector()
                    {
                        MatchLabels = new Dictionary<string, string>
                    {
                        { "app", "deploy-sample" }
                    }
                    },
                    Template = new V1PodTemplateSpec()
                    {
                        Metadata = new V1ObjectMeta()
                        {
                            CreationTimestamp = null,
                            Labels = new Dictionary<string, string>
                            {
                                { "app", "deploy-sample" }
                            },
                            Annotations = new Dictionary<string, string>
                            {
                                ["prometheus.io/scrape"] = "true",
                                ["prometheus.io/path"] = "/metrics",
                                ["prometheus.io/port"] = "52325"
                            },
                        },
                        Spec = new V1PodSpec
                        {
                            Containers = new List<V1Container>()
                        {
                            new V1Container()
                            {
                                Name = "nginx",
                                Image = "nginx:1.7.9",
                                ImagePullPolicy = "Always",
                                Ports = new List<V1ContainerPort> { new V1ContainerPort(80) }
                            }
                        }
                        }
                    }
                },
            };
            try
            {
                var result = client.CreateNamespacedDeployment(myDeploy, "default");
            }
            catch (Microsoft.Rest.HttpOperationException httpOperationException) when (httpOperationException.Response.StatusCode == System.Net.HttpStatusCode.Conflict)
            {
                Console.WriteLine("deployment already exists: {0}", myDeploy.Name());
            }
            catch (Microsoft.Rest.HttpOperationException httpOperationException)
            {
                var phase = httpOperationException.Response.ReasonPhrase;
                var content = httpOperationException.Response.Content;
                Console.WriteLine("response content {0}", content);
                Console.WriteLine("response phase {0}", phase);
            }

            try
            {
                // creating a generic client 
                var generic = new GenericClient(k8SClientConfig, "apps", "v1", "deployments");
                Console.WriteLine("fetching deployment: {0}", myDeploy.Name());

                // using awaitable Read
                var fetchedCR = await generic.ReadNamespacedAsync<V1Deployment>(
                myDeploy.Metadata.NamespaceProperty ?? "default",
                myDeploy.Metadata.Name).ConfigureAwait(false);

                Console.WriteLine("Annotations:");
                foreach (KeyValuePair<string, string> kvp in fetchedCR.Metadata.Annotations)
                {
                    Console.WriteLine("- Key = {0}, Value = {1}", kvp.Key, kvp.Value);
                }
            }
            catch (Microsoft.Rest.HttpOperationException httpOperationException)
            {
                var phase = httpOperationException.Response.ReasonPhrase;
                var content = httpOperationException.Response.Content;
                Console.WriteLine("response content {0}", content);
                Console.WriteLine("response phase {0}", phase);
            }
        }
    }
}
```

**Comment by digeler** [comment]
thank you ill try it and let you know.
