### ISSUE TITLE
How to access the namespace of currently running pod via client

### ISSUE THREAD

**Issue by kuldeepGDI** [kubernetes-client/csharp#534]
Hi,

Is it possible to access or read the namespace value for the currently executing pod. My code is a worker app that is running inside a pod in the same namespace as other services, sharing the same namespace. I want to use ListNameSpaced instead of ListAllNamespace... call, but since i want to have the namespace string for the prior call, i am wondering if this is possible?

Ofcourse, another solution is to have namespace value in appsettings, but since my use case is that we will always have these services running same namespace, i want to achieve it via accessing namespace value from my k8s client service.

Thanks

**Comment by tg123** [comment]
seems you are looking for something like `whoami`
I did not know if k8s api can do it, but i am interest in it as well

**Comment by brendandburns** [comment]
There are two ways:
1) It is in a file as documented here:

https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod

The file is: `/var/run/secrets/kubernetes.io/serviceaccount/namespace`


2) You can use the "downward API" to expose this data as a volume via a Pod config.

See the info here:
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

Hope that helps! We could definitely consider adding this to the client library to make it easier. Happy to take a PR

**Comment by k2ibegin** [comment]
I need to explore these. So far we just went with appsettings approach, as with ListAllNamespaces we had to give service account role to all namespaces, something that is not as good as just giving that role for only "specific" namespace. I agree that it would be nice to have this feature in client library.

**Comment by brendandburns** [comment]
Closing this as I believe the question is answered.
