### ISSUE TITLE
How to set securityContext:   capabilities:  in  V1PodSecurityContext c#

### ISSUE THREAD

**Issue by digeler** [kubernetes-client/csharp#542]
We are upgrading our podidentity to 1.7 and one of the requirement is to add this : 
 securityContext:
  capabilities:
    drop:
    - NET_RAW
    
https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/

i cannot find a way to add it using the spec : 
![image](https://user-images.githubusercontent.com/4949529/103528489-b7bdf680-4e8c-11eb-9606-26f74baddd01.png)

i can see the capabilities but trying to find where i can add it  : 

basicly i need to add this class  : 
 V1SecurityContext()
but i dont know where to place it : 

here is a partial code of my builder : 
 private V1Deployment BuildDeployment() =>
            new V1Deployment
            {
                ApiVersion = $"{V1Deployment.KubeGroup}/{V1Deployment.KubeApiVersion}",
                Kind = V1Deployment.KubeKind,
                Metadata = new V1ObjectMeta
                {
                    Name = KubernetesServiceName
                },
                Spec = new V1DeploymentSpec
                {
                    Replicas = ReplicaCount,
                    Selector = new V1LabelSelector
                    {
                        MatchLabels = new Dictionary<string, string>
                        {
                            [AppLabel] = KubernetesServiceName
                        }
                    },
                    Template = new V1PodTemplateSpec
                    {
                        Metadata = new V1ObjectMeta
                        {
                            Labels = new Dictionary<string, string>
                            {
                                [AppLabel] = KubernetesServiceName,
                                ["aadpodidbinding"] = StaticInformation.IdentitySelector
                            }
                        },
                        Spec = new V1PodSpec
                        {
                            Containers = new[]
                            {
                                new V1Container
                                {
                                    Name = KubernetesServiceName,
                                    Image = DockerImageIdentifier.ToString(),
                                    ImagePullPolicy = "Always",
                                    Env = new[]
                                    {
                                        new V1EnvVar
                                        {
                                            Name = "CLUSTER_NAME",
                                            Value = _globalClusterContext.Name
                                        },
                                        new V1EnvVar
                                        {
                                            Name = "NAMESPACE_NAME",
                                            ValueFrom = new V1EnvVarSource
                                            {
                                                FieldRef = new V1ObjectFieldSelector
                                                {
                                                    FieldPath = $"{nameof(V1StatefulSet.Metadata)}.namespace".ToLower()
                                                }
                                            }
                                        },

thank you.

**Comment by brendandburns** [comment]
It's in

Deployment -> DeploymentSpec -> PodTemplateSpec -> PodSpec -> Container -> Security

https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/generated/Models/V1Container.cs#L301

**Comment by brendandburns** [comment]
Oh, I think I misunderstood, you want to know how to set it in the SecurityContext, it's here:

**Comment by digeler** [comment]
Thanks Brendan , 
it exist but am not able to locate it in the builder i always get  : 

![image](https://user-images.githubusercontent.com/4949529/103640864-71829900-4f59-11eb-90a3-da12b0dc0860.png)

can you share a sample where do i place it within the code.
thank you.

**Comment by brendandburns** [comment]
I think you need to do:

```
{
  Capabilities = new V1Capabilities
  {
      ...
   }
}
```
