### ISSUE TITLE
Can't use HttpClientFactory when connecting to multiple K8s clusters

### ISSUE THREAD

**Issue by govenkat-ms** [kubernetes-client/csharp#545]
In our scenario, at runtime we obtain the kubeconfig and dynamically instantiate the KubernetesClient object. However, we cannot pass the HttpClientFactory object in the aforementioned constructor since the http message handlers are different per cluster. How can we effectively use a shared SocketHttpHandler here in order to take advantage of its connection pooling, periodic DNS refreshes etc.? Is there an example that involves caching of these clients and using a shared handler?

**Comment by tg123** [comment]
here is another issue https://github.com/kubernetes-client/csharp/issues/533#issuecomment-749418238 
I use a tricky way to replace SocketHttpHandler in order to deal with vip RST issue
