### ISSUE TITLE
Generate YAML for Kubernetes SDK

### ISSUE THREAD

**Issue by VenkateshSrini** [kubernetes-client/csharp#546]
HI,

I would like to have a feature similar to **Kubectl get Configmap -o yaml --export**. At present, there is a provision to get the objects in the cluster. But when I want to serialize the objects as YAML. I use the same YAMLDotNetSerializer that is used as a reference in SDK. I create the below code 
```
 var yamlSerialiationBuilder = new SerializerBuilder();
            yamlSerialiationBuilder.ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitDefaults);
            yamlSerialiationBuilder.WithEventEmitter(nextemitter => new QuoteSurroundingEventEmitter(nextemitter));
            yamlSerialiationBuilder.WithNamingConvention(CamelCaseNamingConvention.Instance);
            var yamlSerializer = yamlSerialiationBuilder.Build();
            using (var stringWriter = new StringWriter())
            {
                yamlSerializer.Serialize(stringWriter, v1ConfigMap);
                return stringWriter.ToString();
            }
```
I have used a QuoteSourroundingEventEmitter to put quotes in value. Though it is not that successful. My observation is that the YAML generated is not similar to the YAML that we write and do KubeCtl Apply. My request is

1. Can we have a method in each Kubernetes object that can serialize itself as YAML
2. Can you suggest a correction to the above code so that the YAML that is generated is similar to what we write for doing Kubectl Apply

**Comment by tg123** [comment]
https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/Yaml.cs#L170

let me know if not working

**Comment by VenkateshSrini** [comment]
@tg123 ,

Thanks that worked.
