### ISSUE TITLE
Constructors that take a HttpClient do not work with Watch behaviors

### ISSUE THREAD

**Issue by akrock** [kubernetes-client/csharp#547]
In researching potential workarounds for #533 I was attempting to use the constructors where I could supply my own `HttpClient`.

These constructors appear to be non functional with the Watch behaviors and will hang and then eventually hit a timeout after 100 seconds. This appears to be due to some of the specialized logic that gets evaluated when the `Kubernetes` client constructs it's own `HttpClient`. 

https://github.com/kubernetes-client/csharp/blob/97ed40c5a816c43d0377ba2bf524ac27ee65f80a/src/KubernetesClient/Kubernetes.ConfigInit.cs#L166

To meet what I would expect as a consumer of the library, **one** of the following should happen:

1. Constructors that are not fully compatible with all functionality of the library would not be externally available.
2. **Any** `HttpClient` with **any** configuration passed to the library is able to be used. This assumes that either the code is refactored to not require special changes to the `HttpClient` or it applies the needed changes in a way that is safe to all `HttpClients`.
3. Tools that can be used externally from the library to properly prepare a `HttpClient` for use with the library are provided, and the constructors that consume a `HttpClient` validate that the `HttpClient` is "prepared" for use with the library, and all of this is heavily documented.

**Comment by tg123** [comment]
have to install the `WatchHandler` in order the get watch work

I am trying to hack into stub generator part to solve such kind of issue

**Comment by akrock** [comment]
Yeah I saw that `DelegatingWatchHandler` that they were adding...

**Comment by CarlosLanderas** [comment]
I faced this problem when building some unit tests with MockHttpClient and Kubernetes Client Library.
I did some dirty cheats:

` var messageHandler = new MockHttpMessageHandler(BackendDefinitionBehavior.Always);`

`new Kubernetes(MockKubernetesConfiguration.GetTestConfiguration(), new HttpClient(GetKubernetesWatcherDelegatingHandler(messageHandler)))`

 private static DelegatingHandler GetKubernetesWatcherDelegatingHandler(HttpMessageHandler innerHandler)
```
        {
            var watcherHandler = typeof(IKubernetes).Assembly.GetTypes().First(t => t.Name.Contains("WatcherDelegatingHandler"));
            var instance = Activator.CreateInstance(watcherHandler) as DelegatingHandler;
            instance.InnerHandler = innerHandler;
            return instance;
        }
```
