### ISSUE TITLE
Dependency conflicts with Microsoft.Rest.ClientRuntime 3.0.3

### ISSUE THREAD

**Issue by dbarentine** [kubernetes-client/csharp#55]
I've tried to install KubernetesClient 0.2.0-beta via nuget but I get the following error:
 Starling.NR -> KubernetesClient 0.2.0-beta -> Microsoft.Rest.ClientRuntime (>= 3.0.3) 
 Starling.NR -> Microsoft.AspNetCore.All 2.0.3 -> Microsoft.Extensions.Configuration.AzureKeyVault 2.0.0 -> Microsoft.Azure.KeyVault 2.3.2 -> Microsoft.Rest.ClientRuntime (>= 2.3.8 && < 3.0.0).

I'm currently running version 2.3.8 of the Microsoft.Rest.ClientRuntime. I went looking for the 3.0.3 version but it seems that it has been unlisted: https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/3.0.3

I did manually install it and everything seems to still work. I haven't currently tried anything that was dependent on the old version though.

It would be nice if this library targeted the latest 2.x release (at the moment 2.3.10) instead of the currently unlisted 3.x version.

**Comment by tg123** [comment]
I think it is a best practice to depend on a listed version
