### ISSUE TITLE
Watch requests ignore first watch event, because it is parsed as a *List object

### ISSUE THREAD

**Issue by qmfrederik** [kubernetes-client/csharp#551]
If you issue a request which should watch (i.e., `?watch=true` in the querystring), the `WatcherDelegatingHandler` kicks in.

This handler will intercept the first line (this is the first JSON object which is returned) and hand it off to the REST api.
The following lines (all other JSON objects) can then be processed by the `Watcher` class.

This is in the assumption that if I call e.g. `/api/v1/namespaces/default/pods/?watch=true`, the first item will be a list of pods and the next items will be pod events.

However, reading the documentation, attempting this with cURL/wget, indicate that the first line is _also_ a watch event.

As a result, the first watch event is always ignored.

**Comment by qmfrederik** [comment]
This notion that the first object returned is the list is documented in this kubernetes-client/csharp codebase (and even covered by unit tests), so this made me think that perhaps the API behavior has changed over time. So far, I haven't been able to confirm this, though.

**Comment by tg123** [comment]
#313 ?
All lines are captured by `LineSeparatedHttpContent` including the FIRST one

**Comment by qmfrederik** [comment]
I stand corrected - you are right.

But the first line is a watch event, and should not be sent to the REST API, right?

FWIW, I could get the watcher to work with a simpler `HttpContent` implementation:

```csharp
    /// <summary>
    /// The <see cref="HttpContent"/> which is returned by the <see cref="WatchHandler"/>. The <see cref="WatchHttpContent"/>
    /// returns an empty content (intended to be used by the REST API), and the original content is stored in the
    /// <see cref="OriginalContent"/> property (for use by the Watch API).
    /// </summary>
    public class WatchHttpContent : HttpContent
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WatchHttpContent"/> class.
        /// </summary>
        /// <param name="inner">
        /// The inner content being wrapped.
        /// </param>
        public WatchHttpContent(HttpContent inner)
        {
            this.OriginalContent = inner ?? throw new ArgumentNullException(nameof(inner));
        }

        /// <summary>
        /// Gets the original content being wrapepd.
        /// </summary>
        public HttpContent OriginalContent
        { get; private set; }

        /// <inheritdoc/>
        protected override Task SerializeToStreamAsync(Stream stream, TransportContext context)
        {
            return Task.CompletedTask;
        }

        /// <inheritdoc/>
        protected override bool TryComputeLength(out long length)
        {
            length = 0;
            return true;
        }

        /// <inheritdoc/>
        protected override void Dispose(bool disposing)
        {
            this.OriginalContent.Dispose();

            base.Dispose(disposing);
        }
    }
```
