### ISSUE TITLE
error "no such file or directory" when run kubernetes client in cloud

### ISSUE THREAD

**Issue by guyb14** [kubernetes-client/csharp#552]
my code create kubernetes client and GetAPIVersions.
when it run local on my PC with kubectl proxy it run perfect and also all the rest of kubernetes code, but when i deploy this function to cloud the exception for all function are "No such file or directory" 
what the problem ? (in python it work)

**Comment by tg123** [comment]
could you please provide more details and exception?

**Comment by guyb14** [comment]
No such file or directory TRACE: at
System.Diagnostics.Process.ForkAndExecProcess(String filename, String[]
argv, String[] envp, String cwd, Boolean redirectStdin, Boolean
redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32
userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd,
Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) at
System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) at
System.Diagnostics.Process.Start() at
k8s.Authentication.GcpTokenProvider.RefreshToken() at
k8s.Authentication.GcpTokenProvider.GetAuthenticationHeaderAsync(CancellationToken
cancellationToken) at
Microsoft.Rest.TokenCredentials.ProcessHttpRequestAsync(HttpRequestMessage
request, CancellationToken cancellationToken) at
k8s.Kubernetes.GetAPIVersionsWithHttpMessagesAsync(Dictionary`2
customHeaders, CancellationToken cancellationToken) at
k8s.KubernetesExtensions.GetAPIVersionsAsync(IKubernetes operations,
CancellationToken cancellationToken) at
k8s.KubernetesExtensions.GetAPIVersions(IKubernetes operations) at
RunJob.Function.HandleAsync(HttpContext context) in
/workspace/Function.cs:line 140

**Comment by tg123** [comment]
check `cmd-path`
gcp cli needed to generate token

same as #478

**Comment by guyb14** [comment]
when i check in the function for directory /usr/lib/google-cloud-sdk/bin
it not exists. (not gcloud command) , in python it work.

the command for deploy is:
gcloud functions deploy RunJob --region=europe-west1 --runtime dotnet3
--entry-point RunJob.Function --trigger-http --vpc-connector
mot-dev-connector --env-vars-file=..\..\repos\functions\EnvVars\EnvVars.yaml

Did I miss something?

**Comment by guyb14** [comment]
sorry for my question, but need help
How do I make sure that during deployment C# function there will be gcloud
command ?

today the path to gcloud command not exists

**Comment by tg123** [comment]
https://cloud.google.com/sdk/docs/install
please have `gcloud` installed with your c# app

**Comment by guyb14** [comment]
can you tell how to do that? whet i need to add to the deploy command (its
a google cloud function)

**Comment by tg123** [comment]
please referrer
https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#environments-without-gcloud
to auth with c# client

here c# client is using `gcloud` to generate token to access k8s server, you switch to cert based recommended by guide above
