### ISSUE TITLE
How to forward multiple local HTTP connections over single websocket port-forward connection to Kubernetes?

### ISSUE THREAD

**Issue by jijiechen** [kubernetes-client/csharp#559]
I tried [the port forward example](https://github.com/kubernetes-client/csharp/blob/master/examples/portforward/PortForward.cs) in the repo. It worked for a single local HTTP connection. When I was trying to reuse the mechanism to forward multiple local HTTP connections, I got confused.

The situation I ran into was that after some data was sent to the `StreamDemuxer`, an `EndOfMessage` was received from server, so the underlying websocket connection was disconnected immediately. It seemed the websocket did not allow me to forward multiple requests/connections to it at all.

I assume the `StreamDemuxer` would allow me to initialize multiple streams mapping to my multiple local HTTP connections. So the websocket should not be disconnected after a single request, and the `StreamDemuxer` should allow forwarding independent streams. 

However, the situation was the opposite:
1. the websocket was closed immediately after the first forwarded request;
2. the `StreamDemuxer` only allows streamIndex `0` and `1` corresponding to the `dataStream` and the `errorStream`.

Does this mean that I should initialize a separated websocket connection for each proxed local HTTP request/connection? If so, why bother we build up such a good "persistent connection" websocket mechanism? Or there is something wrong with my understanding?

**Comment by brendandburns** [comment]
Port forwarding should generally work for multiple connections. However, port-forwarding is conceptually a single TCP connection. If your server closes the TCP connection after serving a request (e.g. `Connection: Close` header or somesuch) then you'll have to re-establish the connection. Similarly if you close the connection after the client disconnects, you'll have to re-create the port-forwarding session.

But in general, yes, port-forwarding should work for multiple HTTP connections. Note that it _won't_ work for parallel connections (e.g. simultaneous requests) the requests have to be pipelined.

**Comment by jijiechen** [comment]
Thanks for the reply.

> But in general, yes, port-forwarding should work for multiple HTTP connections. Note that it won't work for parallel connections (e.g. simultaneous requests) the requests have to be pipelined.

This is what confused me. The situation I ran into  proved this not to be true.

To be accurate, an `EndOfMessage` was sent by the server following the response of the first batch of HTTP requests (instead of the first single request), and the underlying websocket was disconnected immediately after this. This is handled by the code [at here](https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/StreamDemuxer.cs#L235). So I generally was not able to send multiple batches of HTTP requests over the single websocket connection.

Is this the situation in your environment too?

My server version is:
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by brendandburns** [comment]
Thanks for the pointer. I think that's a bug in the code, I think we should keep the websocket open in that case when doing port-forwarding (as opposed to 'exec' or 'attach'

I will see about updating the code.

**Comment by jijiechen** [comment]
I spent some time on this issue uncontinously and fount it may not be an issue of this CSharp client.
I tried other websocket clients and they failed too.

When the websocket disconnects, an error prompts by the kubelet on the VM where the pod locates.
```sh
Jun 24 14:32:55 kube1-node3 kubelet[3223]: E0624 14:32:55.535513    3223 conn.go:254] Error on socket receive: read tcp 127.0.0.1:40050->127.0.0.1:48250: use of closed network connection
```

I tried to modify the `wscat` utility and forward an HTTTP request to server:
```
git clone https://github.com/websockets/wscat
cd wscat
```

Open and edit wscat to forward an HTTP request when hit enter from console. Code postion at [L313](https://github.com/websockets/wscat/blob/master/bin/wscat#L313):
```js
// original implementation:  ws.send(data);
// change to these:
// send the stream index
var prefix = Buffer.from ([0x00]);
// compose an HTTP request
var buf = Buffer.concat([prefix, Buffer.from('GET / HTTP/1.1\r\nHost: localhost:8080\r\nUser-Agent: curl/7.75.0\r\nAccept: */*\r\n\r\n', 'utf8')]);

// send over to server
ws.send(buf);
```

Save and execute the updated websocket test utility:
```sh
API_TOKEN=<token>
node ./bin/wscat -n -s "v4.channel.k8s.io" -H "Authorization: Bearer $API_TOKEN" -c wss://<apiserver>:6443/api/v1/namespaces/bookinfo/pods/productpage-v1-768c66c68d-68dmc/portforward?ports=9080
```

When hit enter from console, an HTTP request is forwarded to server and response is returned successfully.
Then the connection closes very immediately after the first play, and an error is logged by kubelet.

**Comment by Fresa** [comment]
Late to the party, but to conclude, the websocket implementation of port forward / exec / attach etc cannot handle multiple requests on the same connection because the websocket protocol does not support multiplexing.

That said, I have implemented a .NET version of [SPDY](https://github.com/Fresa/Spdy). 

Here's an example how it can be integrated with this project: 
https://github.com/Fresa/Port/blob/3e71108358f8ac300f2405fac57e0487ae79a185/src/Server/Kubernetes/KubernetesExtensions.cs#L13

**Comment by jijiechen** [comment]
Thanks @Fresa 
Great effort! I'll try it out.
