### ISSUE TITLE
Help - load any k8s resource via api

### ISSUE THREAD

**Issue by Rob623** [kubernetes-client/csharp#562]
Hi,
I'm trying to build a custom loader that reads yaml files (via your Yaml. LoadAllFromString(...))
then I'm using CreateNamespacedCustomObject(...) to create whatever was loaded in the cluster.

I'm holding the object to be created as IKubernetesObject<V1ObjectMeta> (I`m talking about the 'body' param)
group, api, kind and plural info is taken from the objects metadata via 
kubObject.GetKubernetesTypeMetadata()

I was able to use it successfully on a deployment:
client.CreateNamespacedCustomObject(body=v1deployment, group="apps", api="v1", namespace="foo", plural="deployments")

however the same thing on a service fails with 'NotFound' invalid status code:
client.CreateNamespacedCustomObject(body=v1service, **group=""**, api="v1", namespace="foo", plural="services")

am I missing something? the main difference I see is that services have an empty group value.
alternatively, is there a better way to achieve this generic functionality? (hopefully without mapping all of the object kinds)

Thanks in advance

**Comment by tg123** [comment]
please use `GenericClient` instead
we have some tricky workaround for empty group


https://github.com/kubernetes-client/csharp/blob/3fd47e5644f273fa66cf15530ea12bdfa7e81a76/src/KubernetesClient/GenericClient.cs

**Comment by Rob623** [comment]
I see that GenericClient only has read and delete methods, not create but I used the same trick that you did there with a normal client and now it works (I`ve attached an instance of the TweakApiHandler).

Is there a scenario where anyone would want to do a call with "/apis//"?

**Comment by tg123** [comment]
`/apis//` is a flaw of the generator :(

**Comment by Rob623** [comment]
so shouldn't the fix be done there? 
anyway, thanks for the help!

**Comment by brendandburns** [comment]
This is basically an bug in Kubernetes itself. When we created the first versions of k8s we didn't have an notion of `apiGroups` and so the initial objects exist in a incompatible empty resource version.

This means that there isn't a clean way to fix this.

The right way to do it is to fix the paths in the Kubernetes API server, but this isn't practical since it would break every single client out there.

Consequently, we just need to work around the idiosyncracy in the api groups.

**Comment by Rob623** [comment]
I get that but and since there is no clean possibility, how about inserting the fix into the url generator? 
the fix being something along the lines of: if no group, skip|delete / 
I`m not familiar with the url generator code so I don't really know if thats possible or prevented by something...
