### ISSUE TITLE
Exception when kube config contains additional properties

### ISSUE THREAD

**Issue by buehler** [kubernetes-client/csharp#566]
Hey there :)

Someone just found out in relation to my operator sdk (https://github.com/buehler/dotnet-operator-sdk/issues/149) that the construction of the kube config fails if it contains additional properties.

I looked into your code and discovered, that the `Yaml.LoadAllFromString` method does include the `.IgnoreUnmatchedProperties` call on the deserializer builder, but the `public static T LoadFromString<T>` does not.

To make this more resilient and possible for users with AWS kubernetes (which adds additional properies to the kube config) it would be nice to include the `IgnoreUnmatchedProperties` call to the load from string method as well.

Regards

**Comment by brendandburns** [comment]
Sounds reasonable to me (and matches other parsers). We'd be happy to take a PR to do this.
