### ISSUE TITLE
[Question] Server-Side Apply

### ISSUE THREAD

**Issue by zhiweiv** [kubernetes-client/csharp#576]
Do we have API to use Server-Side Apply(https://kubernetes.io/docs/reference/using-api/server-side-apply)?

**Comment by tg123** [comment]
see bburns comments
https://github.com/kubernetes-client/csharp/issues/304#issuecomment-533322560

**Comment by brendandburns** [comment]
It does work if you use the Patch operations with content type `application/apply-patch+yaml`

There's a patch example here:
https://github.com/kubernetes-client/csharp/blob/master/examples/patch/Program.cs

You'll need to adapt it to do an apply instead.

**Comment by brendandburns** [comment]
Please use `/reopen` if you need further assistance.

**Comment by zhiweiv** [comment]
I did local change with the source code, added application/apply-patch+yaml to V1Patch.PatchType. The request worked, however it returns Created(201) instead 200, the logic in Kubernetes.cs regards non-200 as exception.
```
if ((int)_statusCode != 200)
            {
                var ex = new HttpOperationException(string.Format("Operation returned an invalid status code '{0}'", _statusCode));
                if (_httpResponse.Content != null) {
                    _responseContent = await _httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
                }
                else {
                    _responseContent = string.Empty;
                }
```

**Comment by tg123** [comment]
the status code is generated from swagger
which api are you calling?

the jsonpatchtype, will sync with upstream
or you can PR if you are ready

**Comment by zhiweiv** [comment]
Here is the stack:
```
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Created'
   at k8s.Kubernetes.PatchNamespacedPodWithHttpMessagesAsync(V1Patch body, String name, String namespaceParameter, String dryRun, String fieldManager, Nullable`1 force, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken) in E:\csharp-master\src\KubernetesClient\generated\Kubernetes.cs:line 13328
   at k8s.KubernetesExtensions.PatchNamespacedPodAsync(IKubernetes operations, V1Patch body, String name, String namespaceParameter, String dryRun, String fieldManager, Nullable`1 force, String pretty, CancellationToken cancellationToken) in E:\csharp-master\src\KubernetesClient\generated\KubernetesExtensions.cs:line 6775
   at k8s.KubernetesExtensions.PatchNamespacedPod(IKubernetes operations, V1Patch body, String name, String namespaceParameter, String dryRun, String fieldManager, Nullable`1 force, String pretty) in E:\csharp-master\src\KubernetesClient\generated\KubernetesExtensions.cs:line 6731
   at patch.Program.Main(String[] args)
```

**Comment by tg123** [comment]
it should be 200
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#patch-pod-v1-core
check e2e test here
```
   [MinikubeFact]
        public void PatchTest()
```

what is your k8s server version

**Comment by zhiweiv** [comment]
I am using 1.19.7
You can try **kubectl apply -f pod.yaml --server-side --v=7**, the output:
```
I0311 16:50:16.035268   18780 round_trippers.go:421] PATCH https://aostest-aos-aks-33387f-a8d4cc2c.hcp.southeastasia.azmk8s.io:443/api/v1/namespaces/default/pods/test2?fieldManager=kubectl&force=false
I0311 16:50:16.035268   18780 round_trippers.go:428] Request Headers:
I0311 16:50:16.040237   18780 round_trippers.go:432]     Content-Type: application/apply-patch+yaml
I0311 16:50:16.042235   18780 round_trippers.go:432]     User-Agent: kubectl/v1.19.7 (windows/amd64) kubernetes/1dd5338
I0311 16:50:16.043235   18780 round_trippers.go:432]     Authorization: Bearer <masked>
I0311 16:50:16.044236   18780 round_trippers.go:432]     Accept: application/json
I0311 16:50:16.241240   18780 round_trippers.go:447] Response Status: 201 Created in 195 milliseconds
```

**Comment by brendandburns** [comment]
I think both 200 and 201 are legal.

The fact that 201 throws is a bug in the swagger spec for patch:

https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

If you look through there it only lists 200 as a potential response.

Honestly, I think that autorest is being too literal here, it should be happy with an y 20x response, but the right fix is to doctor the swagger to include 201 as a potential response.

**Comment by brendandburns** [comment]
(that doc is generated from the swagger also, fwiw)

**Comment by brendandburns** [comment]
Actually, the problem is in the Kubernetes code itself:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L807

I'll see if I can send a patch to fix that.

**Comment by brendandburns** [comment]
(and given that it's going to take a while for that fix to get in, I'll see about doctoring the generator too)

**Comment by zhiweiv** [comment]
This k8s fix has been merged,  can this be fixed recently, or we have to wait k8s 1.22 release?

**Comment by zhiweiv** [comment]
/remove-lifecycle stale
Still waiting k8s 1.22 release.

**Comment by tg123** [comment]
1.22 released
