### ISSUE TITLE
 Query-Port-forward from localhost-port to pod-port

### ISSUE THREAD

**Issue by PiyaShedbalkar** [kubernetes-client/csharp#577]
How do I achieve below command using Kubernetes-client in csharp? Please address 
kubectl port-forward <pod-name> <localhost-port>:<pod-port>

I tried with WebSocketNamespacedPodPortForwardAsync but I don't know where should I pass localhost-port and pod-port parameter

**Comment by tg123** [comment]
take a look at
examples/portforward/PortForward.cs
