### ISSUE TITLE
typo of V1PathJsonConverter

### ISSUE THREAD

**Issue by zhiweiv** [kubernetes-client/csharp#578]
V1PathJsonConverter is only used by V1Patch, I guess the name should be V1PatchJsonConverter?
https://github.com/kubernetes-client/csharp/blob/d48e93c1f67d9666891c4f5b14bb7ebcd3dc0b0e/src/KubernetesClient/V1Patch.cs#L6-L7

**Comment by tg123** [comment]
Oh yup it is
LOL
