### ISSUE TITLE
Error messages are lost in HTTP 400 responses

### ISSUE THREAD

**Issue by qmfrederik** [kubernetes-client/csharp#58]
When requests are rejected by Kubernetes, the server responds with HTTP 400. The body contains a JSON object with additional error information. This information is lost in the C# client.

Here's an example:

```csharp
await client.CreateNamespacedPodAsync(
    new Corev1Pod() 
    {
         // Pod configuration
    }).ConfigureAwait(false);
```

got me:

```
Microsoft.Rest.HttpOperationException: 'Operation returned an invalid status code 'BadRequest''
```

which doesn't help me debug my problem.

Fiddler reveals the server did return an error message:
```json
{
  "kind":"Status",
  "apiVersion":"v1",
  "metadata":{},
  "status":"Failure",
  "message":"Deployment in version \"v1\" cannot be handled as a Pod: no kind \"Deployment\" is registered for version \"v1\"",
  "reason":"BadRequest",
  "code":400
}
``` 

It would be great if the C# API could surface that error message.

**Comment by tg123** [comment]
cloud you please show your sever version?

**Comment by qmfrederik** [comment]
Sure, it's AKS on Azure:

```yml
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by qmfrederik** [comment]
Observed the same for HTTP 422, this results in:

```
Microsoft.Rest.HttpOperationException: 'Operation returned an invalid status code '422''
```

whereas the server gave more info:

```
HTTP/1.1 422 Unprocessable Entity
Content-Type: application/json
Date: Thu, 30 Nov 2017 18:20:49 GMT
Content-Length: 842

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"webdriver-a123\" is invalid: spec.containers[0].env[0].name: Invalid value: \"WEBDRIVER:ADBHOST\": a valid C identifier must start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name',  or 'MY_NAME',  or 'MyName', regex used for validation is '[A-Za-z_][A-Za-z0-9_]*')","reason":"Invalid","details":{"name":"webdriver-a123","kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"XXX:YYY\": a valid C identifier must start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name',  or 'MY_NAME',  or 'MyName', regex used for validation is '[A-Za-z_][A-Za-z0-9_]*')","field":"spec.containers[0].env[0].name"}]},"code":422}
```

The error message from Kubernetes is valid, it's just that the Exception which surfaces in .NET doesn't contain all the information the server did send back

**Comment by tg123** [comment]
did you mean that client should throw an exception with detailed message?

**Comment by qmfrederik** [comment]
Yes, exactly.

**Comment by brendandburns** [comment]
@qmfrederik See this related issue (and approach) here:

https://github.com/Azure/autorest/issues/931#issuecomment-291540997

I'm going to close this, as it's possible, and anything bigger requires substantive changes to AutoRest [and aren't required imho, given that you can get the Content]

**Comment by thrixton** [comment]
@brendanburns , would you be open to a PR with a troubleshooting section in README.md with instructions on extracting the error response from httpOperationException?
