### ISSUE TITLE
Csharp client

### ISSUE THREAD

**Issue by rajivml** [kubernetes-client/csharp#583]
HI,

Any reason why csharp client is marked as "Work in Progress" because looking at the commits it's been there from 2-3 years.

![image](https://user-images.githubusercontent.com/46923567/111027405-2469ea00-8416-11eb-92a1-80cdb595cd4b.png)

**Comment by tg123** [comment]
LOL
never stopped improved it

**Comment by brendandburns** [comment]
Closing this issue :)

**Comment by rajivml** [comment]
@brendanburns @tg123 can I consider it stable :) ?

**Comment by eskaufel** [comment]
@rajivml I have been using it for a while now, and it is good. When using a watcher in cloud scenarios, the load balancers sometimes disconnect and leave you with a half-closed TCP connection. There has been a recent patch, but only for .net 5, enabling TCP-keepalive to solve this. The project is active and updated regularly.

**Comment by tg123** [comment]
@rajivml you can 
and feel free to file any bug you found
