### ISSUE TITLE
Improve Watcher Pattern

### ISSUE THREAD

**Issue by mpoettgen** [kubernetes-client/csharp#584]
Initially I've had a bit of trouble understanding the Watcher pattern, so I've looked at the implementation and found a few things that may be worthwhile to be changed/added.

# Current situation

## The `Watcher` object is not 'cancellable' and/or 'awaitable'

If I understand things correctly the consumer is supposed to keep the `Watcher` around for as long as he wants to watch a resource and then dispose it. In an async context it would be nicer to be able to signal termination using a `CancellationToken` and have an awaitable `Task` somewhere (like the [ExecuteTask](https://github.com/dotnet/runtime/blob/6791d05494f5aa4d1a789525c2708e775aafdc07/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/BackgroundService.cs#L24) property) that completes when the `Watcher` is done watching. This would be similar to the pattern in the `BackgroundWorker`.

## Putting the `WatcherLoop` onto the thread pool may not always be necessary/desired

If your `Watcher` is already running on a thread pool tread, then all that this thread will be doing is wait for the watcher loop to finish in another thread. It can do that asynchronously, but anyways...

## API usage is not really obvious

As I said, it took me a while to understand how it works.

# Proposal

1. Add `StartWatch` extension methods, similar to the `Watch` extension methods, but getting an extra `CancellationToken` parameter and returning a `Task` object.
2. Add private constructors to the `Watcher` class that take the extra `CancellationToken`, but do not run the `WatcherLoop`. The `CancellationToken` can be registered with the `CancellationTokenSource`.
3. Add static `StartWatch` methods to the `Watcher` class that construct `Watcher` objects and then execute the `WatcherLoop` returning the `Task`. The `Watcher` objects can be disposed automatically, when the `WatcherLoop` is done.

If this is something that would be considered, I would be willing to create a pull request.

**Comment by tg123** [comment]
PRs are welcomed for sure

Please take a look here 
https://github.com/lodejard/WatchExample/blob/9d6934d665f1c53162a6e5e4c66874ba66374320/Worker.cs

I am trying to add awaitable and enumerable APIs to watcher object.
still testing the changes and some glitches need to be fixed

#581 

cc @lodejard

**Comment by davidfowl** [comment]
IAsyncEnumerable is the answer to this as it is model 2 but with compiler support (await foreach)

**Comment by mpoettgen** [comment]
@tg123, your [StyleOnePointFive](https://github.com/lodejard/WatchExample/blob/6e4d6d745160bf185363c40ce9182dcda5618ada/Worker.cs#L97) is basically what I had in mind with my proposal.

I agree with @davidfowl, that an `IAsyncEnumerable` makes the API even easier to consume. I can see that your [StyleThree](https://github.com/lodejard/WatchExample/blob/6e4d6d745160bf185363c40ce9182dcda5618ada/Worker.cs#L197) implements that pattern. 

There are a few things where I'm not sure yet, whether I like them. For example [WatchAsync<T>](https://github.com/lodejard/WatchExample/blob/6e4d6d745160bf185363c40ce9182dcda5618ada/FakeImplementation/ExampleKubernetesClient.cs#L17) returns a `WatchStream<T>` instead of an `IAsyncEnumerable<(WatchEventType, T)>`. I guess that is, because the WatchStream (which is btw. enumerable, but not of type `Stream`) contains the underlying stream and response and you want those to be disposable. It may be nicer to defer making the request to the GetAsyncEnumerator. Not sure, if that would work. Unless someone calls GetAsyncEnumerator to enumerate the watched objects, there may be no need to ask for watched objects and the `IAsyncEnumerator` is disposable.

What is the use-case for the `WatchAsyncWithHttpMessagesAsync<T>` method? If it is not needed, then you do not need to wrap the WatchStream in the HttpOperationResponse, just to unwrap it again afterwards. Consumers could do funny things like calling `client.WatchAsyncWithHttpMessagesAsync<V1Pod>(...).Watch<V1Pod, WatchStream<V1Pod>>(...)` with that API.

The `Watcher` class currently supports sending "Status" events via the `OnError` handler. What do you have in mind for those?

I'll play around with this some more and provide feedback. Overall this looks very promising. Thanks for the work. Let me know where I can help.

**Comment by mpoettgen** [comment]
@tg123 disregard my previous comment. I've just noticed your pull-request #586 and that addresses the concerns that I had. I like how you re-implemented the WatcherLoop using the IAsyncEnumerable.

**Comment by mmajcica** [comment]
I'm having issues understanding this "watcher pattern". Can someone point me to some documentation where I can learn more about it? Is there any document here that can explain how "watching" precisely work?

Thanks

**Comment by mpoettgen** [comment]
You can find an example at https://github.com/mpoettgen/cert-manager-acme-httphook/blob/main/src/cert-manager-acme-httphook/ChallengeOperator.cs. However there is a pull request #586 which makes things easier once it is implemented.

**Comment by tg123** [comment]
@mmajcica 
basically api server will push changes to you when you start a query with `watch=true` <https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes>

here the sdk wraps it to a friendly and c# way for you use. in this case you can use `async foreach` to iterate changes from server.
