### ISSUE TITLE
Limited length of the received file

### ISSUE THREAD

**Issue by MistmareRUS** [kubernetes-client/csharp#589]
Hi, I need to receive text file from kubernetes, which length is about 16kb. But in stream I can read only 4096b and many "\0" symbols. Is it possible to receive files more than 4kb?

![image](https://user-images.githubusercontent.com/40337373/111650490-66c86800-8816-11eb-9370-44d5c4532fca.png)

**Comment by brendandburns** [comment]
That method for Exec won't work. That method is auto-generated from OpenAPI, but OpenAPI doesn't understand the WebSockets based protocol that Exec uses.

Please look at the Exec example here:

https://github.com/kubernetes-client/csharp/blob/master/examples/exec/Exec.cs
