### ISSUE TITLE
Please provide performance testing metrics of Kubernetes client /csharp (Throughput, latency)

### ISSUE THREAD

**Issue by arjaiswa** [kubernetes-client/csharp#593]
Could you please provide some metric  of this API 
1. How many requests per seconds ?
2. What is the throttle part ?
3. Latency 
4. Which approach you are using to retry http connection?

**Comment by brendandburns** [comment]
For throughput and latency these are going to be more determined by both the Kubernetes api server that you are connecting to as well as the client code that you write, as well as the network between them.

There is no throttling in the client library (you would have to add a custom Handler if you wanted that)

I'm not sure what you mean by retry, but if you mean to retry errors (e.g. on server 500) there is no retry logic, you will need to implement that in your client.
