### ISSUE TITLE
AutoMapper 10.x

### ISSUE THREAD

**Issue by tomaszliptak** [kubernetes-client/csharp#594]
Hi,
Do you plan to migrate AutoMapper dependency to the newest version?

**Comment by tg123** [comment]
any reason?
you can also declare it in your own csproj

**Comment by tomaszliptak** [comment]
Are you sure I can use v10.x and your code will work?

**Comment by tg123** [comment]
not supported officially at the moment

**Comment by tomaszliptak** [comment]
Do you have any plans and some estimated date when it could be supported?

**Comment by brendandburns** [comment]
We'd take a PR to do this though if you want to write it.

**Comment by mpoettgen** [comment]
@tg123, @brendandburns, I've done a quick check by

* running all tests in `KubernetesClient.Tests`
* updating AutoMapper to 10.0.0 in `KubernetesClient`
* running all tests in `KubernetesClient.Tests` again

According to test results nothing broke. Is it true, that AutoMapper is only used by the `VersionConverter`? Does anyone know, whether there is anything else to watch out for?

**Comment by tg123** [comment]
yes it is for converting old/beta model to newer one, vice versa
