### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by thrixton** [kubernetes-client/csharp#605]
Thanks for the great library.  
Would you be open to a PR with Debug / Info logging?  
I'm thinking all the CRUD operations should at least have Info log with the name of the resource.
Debug logging would be great to have the full resource output but that might not be suitable for all (PII etc....).

**Comment by tg123** [comment]
service client tracing?

https://docs.microsoft.com/en-us/dotnet/api/microsoft.rest.serviceclienttracing?view=azure-dotnet

**Comment by brendandburns** [comment]
We'd definitely consider such a PR. Thanks!
