### ISSUE TITLE
Nullable reference types

### ISSUE THREAD

**Issue by martinothamar** [kubernetes-client/csharp#606]
Hey,

I'm working on a .NET 5 project and we use NRT. We do have nullrefs from time to time and recently on responses from this library. Has NRT been considered here?

Concrete example, if you list out pods that have been evicted, the `ContainerStatuses` property on a pod will be null: https://github.com/kubernetes-client/csharp/blob/8ab95b6b920e8a10b4c0122e09d158be2005aa15/src/KubernetesClient/generated/Models/V1PodStatus.cs#L135

In this specific case I think this property should either be annotated as nullable (`IList<V1ContainerStatus>?`) or be an empty list by default. The response from k8s API just doesn't return this field so I'm assuming that's why it ends up null, so maybe NRT is the correct option here?

**Comment by brendandburns** [comment]
Unfortunately all of this code is generated and the specific generator (AutoRest 2) is deprecated. So I don't think that this change is going to happen any time soon.

**Comment by eskaufel** [comment]
Is there no plan to update the code generator?

**Comment by tg123** [comment]
> Is there no plan to update the code generator?

Working on it

**Comment by brendandburns** [comment]
Yeah, my point was not to say "we'll never do this" just "it may take a while"

**Comment by WeihanLi** [comment]
This issue should keep open I think.

**Comment by martinothamar** [comment]
Sure, I don't mind 😄
