### ISSUE TITLE
Can I fetch a specific k8s version?

### ISSUE THREAD

**Issue by daveabrock** [kubernetes-client/csharp#612]
I have a specific use case where I need to fetch namespace data based on the k8s version (for example, pick `namespace-x` if the version is < `1.20`). I see versions of the specific API I can fetch but don't see anything around the specific k8s version. Am I missing anything?

**Comment by brendandburns** [comment]
We don't currently have support for this, you'll need to make the raw request yourself.

You could follow the example here for Watch:

https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/Kubernetes.Watch.cs#L16

To see what you need to do for a 'raw' request to the versions URL (`/version`)

**Comment by daveabrock** [comment]
Got it. Thanks for the response!
