### ISSUE TITLE
Get Unauthorized when using KubernetesClient in Azure webapp

### ISSUE THREAD

**Issue by fsigalov** [kubernetes-client/csharp#613]
I'm using a kubeconfig file that works with kubectl, but is not working through KubernetesClient in an Azure webapp. This is working on my dev machine. I'm not sure what issue the IIS hosting is causing.
I saw this [issue](https://github.com/kubernetes-client/csharp/issues/319) but the cert it's creating from the kubeconfig file already has DigitalSignature set.
Here's my code 
```          
            var configModel = KubernetesClientConfiguration.LoadKubeConfig(m_kubeConfig);
            var config = KubernetesClientConfiguration.BuildConfigFromConfigObject(configModel);
            HttpClientHandler handler = new HttpClientHandler();
            handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
            handler.SslProtocols = System.Security.Authentication.SslProtocols.Tls12;
            handler.ClientCertificateOptions = ClientCertificateOption.Manual;
            HttpClient httpClient = new HttpClient(handler);
            kubernetesClient = new Kubernetes(config, httpClient);
```

**Comment by fsigalov** [comment]
It turned out that the above code was not working locally either. I updated the code to set a ClientCert on the handler.
`            handler.ClientCertificates.Add(CertUtils.GeneratePfx(config));`
And that fixes my local run, but it changes the Azure error to "The request was aborted: Could not create SSL/TLS secure channel."

**Comment by brendandburns** [comment]
fwiw, you should definitely not set `HttpClientHandler.DangerousAcceptAnyServerCertificateValidator`

It shouldn't be necessary, and it makes it possible for someone to man in the middle your SSL.

I don't know about what might be different in Azure WebApps, is the version of dotnet the same in both cases?

**Comment by fsigalov** [comment]
I understand that, I'm trying to get it to work at all. I can reduce it to the necessary steps after that.
Yes dotnet should be the same. I'm using framework 4.7.2.

**Comment by tg123** [comment]
merge to #643
