### ISSUE TITLE
Secrets are decoded from Base64

### ISSUE THREAD

**Issue by matthew-walker-prolucid** [kubernetes-client/csharp#614]
Hello,

I used F# code similar to the following to retrieve a secret from the k8s API:

```fsharp
open k8s
open k8s.Models
open System.IO
open System.Threading

let retrieveSecret (client: IKubernetes) (nspace: string) (secret: string) : Async<string> =
    async {
        let! v1Secret = client.ReadNamespacedSecretAsync (secret, nspace, "false", CancellationToken.None) |> Async.AwaitTask
        return Yaml.SaveToString v1Secret
    }

[<EntryPoint>]
let main argv =
    let kClientConfig = KubernetesClientConfiguration.BuildDefaultConfig()
    use kClient = new Kubernetes(kClientConfig)
    
    async {
        let! secretText = retrieveSecret kClient "mynamespace" "mysecret"
        return printfn "%s" secretText
    } |> Async.RunSynchronously

    0
```

Which will print the secret `mysecret` from the namespace `mynamespace`.  The issue is that the secret is printed with a `data` field, which is assumed to be base64-encoded, but is instead printed as plain text, making the secret printed ill-formed.

As a workaround, I have replaced `"\ndata:"` with `"\nstringData:"` in the output, but this is obviously less than ideal and the secret returned should be of the correct form.

Unfortunately, I do not currently have the time to offer to help fix this.

Versions:

k8s server: tested on 1.17.6
KubernetesClient for .NET: 5.0.4

**Comment by tg123** [comment]
the api call returns a `V1Secret` with a `Data` field type `IDictionary<string, byte[]>`
the []byte is the data from your base64 string which is by design

**Comment by brendandburns** [comment]
Is the issue that we we serialize to Yaml we don't re-serialize it to base64?

**Comment by matthew-walker-prolucid** [comment]
> Is the issue that we we serialize to Yaml we don't re-serialize it to base64?

Yes, this is the issue.  The issue is with serialization using the Yaml class; it produces secrets that aren't base64 encoded and so can't be consumed by anything following the kubernetes API.
