### ISSUE TITLE
Git commit for nuget package

### ISSUE THREAD

**Issue by fsigalov** [kubernetes-client/csharp#615]
I'm using v4.0.26 from Nuget (Because it's the last version that support .netstandard2.0). How can I figure out what commit hash that package corresponds to?
(I'm getting a InvalidCastException from    k8s.KubernetesClientConfiguration.AddCertificates(HttpClientHandler handler) but can't see why that would be happening from the code. Maybe this was an old bug that was fixed?)

**Comment by tg123** [comment]
4.0.26 is generate from this build
https://github.com/kubernetes-client/csharp/runs/2307344493?check_suite_focus=true

code
https://github.com/kubernetes-client/csharp/tree/7d66489cb4c6b67972e59e80350ca14a855d179d

cert related to netstandard2.0 removed in 5.0 were used in websocket only. 

could you please paste the stack?

**Comment by fsigalov** [comment]
```
[InvalidCastException: Unable to cast object of type 'System.Net.Http.HttpClientHandler' to type 'System.Net.Http.WebRequestHandler'.]
   k8s.KubernetesClientConfiguration.AddCertificates(HttpClientHandler handler) +113
   k8s.KubernetesClientConfiguration.CreateDefaultHttpClientHandler() +46
   Microsoft.Mt.Deployment.Service.Tools.KubectlWrapper..ctor(String rootPath, String exeName, String kubeConfigFile, String logSource) in e:\depot\mtmain\private\mt\HubStudio\Deployment.Service\Tools\KubectlWrapper.cs:37```
