### ISSUE TITLE
Support for provideClusterInfo and installHint in KubeConfig Models under ExternalExecution.

### ISSUE THREAD

**Issue by namra98** [kubernetes-client/csharp#618]
Hi Team,
Thanks for this great library.

Kubernetes has recently added support in kubeConfig for provideClusterInfo and installHint properties recently.
Link : https://kubernetes.io/docs/reference/access-authn-authz/_print/#configuration

These are not yet implemented in csharp library.
We were trying to deserialize this updated kubeconfig to C# kubernetes model, but this is failing with error as below:
**provideClusterInfoProperty not found on type k8s.KubeConfigModels.ExternalExecution.**

Current workaround is to remove this property manually from kubeconfig and then do deserialzation.

I can raise a PR for adding these properties in ExternalExecution Model.
Let me know if this sounds good.

**Comment by brendandburns** [comment]
A PR to add support for this would be great.

Thanks!

**Comment by namra98** [comment]
Fixed by https://github.com/kubernetes-client/csharp/pull/620
