### ISSUE TITLE
ConnectGetNamespacedPodExec fails with 'Upgrade Required'

### ISSUE THREAD

**Issue by qmfrederik** [kubernetes-client/csharp#62]
I'm trying to use the C# client to execute a command in a container in a pod.
I assumed that `ConnectGetNamespacedPodExec` would allow me to execute a command and return the standard output and error output.

That doesn't seem to work, though: calls to `ConnectGetNamespacedPodExec` and `ConnectPostNamespacedPodExecAsync` both fail with an exception:

```
Microsoft.Rest.HttpOperationException: 'Operation returned an invalid status code 'BadRequest''
```

The server returns the following data:
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}
```

**Comment by qmfrederik** [comment]
As a sidenote, I'm guessing this fails because Kubernetes wants to upgrade this to WebSocket calls. I'd be fine for me if I have access to raw `Stream` objects which allow me to write to standard input and read from standard output and error output.

**Comment by tg123** [comment]
I am doing websocket relate calls
a little busy recent days

**Comment by brendandburns** [comment]
@qmfrederik Yeah, I think that in general being able to split the calls like this would be a good idea.

It requires an upstream AutoRest change...

**Comment by brendandburns** [comment]
I'm going to close this, since the overall error is expected and we're working on WebSockets support elsewhere.

If someone wants to open an issue (here or with AutoRest) about splitting the generated code, that works for me...
