### ISSUE TITLE
[Question] How would I get all the files from a pod so I can send them to an API?

### ISSUE THREAD

**Issue by Tom284** [kubernetes-client/csharp#622]
I have collected all the pods from my cluster but I don't know how I can now get the files from each pod. I am not trying to copy the files, I just want to get the files so I can send them one after the other to an API. So that I could do something like this:

![image](https://user-images.githubusercontent.com/55879415/118496865-cfec2f00-b724-11eb-80ec-234adc52d682.png)

How would I do this?

**Comment by tg123** [comment]
are you looking for api equivalent of `kubectl cp`?

**Comment by Tom284** [comment]
Yes, but I don't necessarily want to copy files somewhere, I just want to be able to use them in code.
