### ISSUE TITLE
nuget package is missing debug symbols/deterministic builds/etc..

### ISSUE THREAD

**Issue by f2calv** [kubernetes-client/csharp#625]
The nuget package generated is missing a bunch of features which would make debugging easier.

Above all else the debug Symbols snupkg package is missing, plus a few other nuget 'best practises' could be implemented.

![image](https://user-images.githubusercontent.com/16097639/118710974-4b320b80-b81f-11eb-82d0-4f92ab22f5b1.png)

I can see some effort has been made to get symbols working in the past, however it's not yet working... pr incoming.

**Comment by tg123** [comment]
#626 merged

**Comment by f2calv** [comment]
Latest version now w/symbols :)

![image](https://user-images.githubusercontent.com/16097639/118917763-def3fc80-b931-11eb-93b5-fe704036b12a.png)
