### ISSUE TITLE
Nuget package release notes

### ISSUE THREAD

**Issue by sseetharaman6** [kubernetes-client/csharp#627]
Hi, 
I am new to using the c# client and I had some questions -
I was wondering where I can look up what goes into each release of https://www.nuget.org/packages/KubernetesClient/ and where I can find the release notes, what PRs went into it?  
Also https://github.com/kubernetes-client/csharp/releases  is a bit-dated. Can the nuget packages be considered official releases?

**Comment by tg123** [comment]
You can take nuget as official release
every single commit will go into nuget package automatically and minor ver++

**Comment by Davidsv** [comment]
It would be useful to have proper release notes, especially for major versions and breaking changes!

**Comment by jack4it** [comment]
> You can take nuget as official release
> every single commit will go into nuget package automatically and minor ver++

how do we tell which commits go into each version? having a hard time to figure that out

**Comment by tg123** [comment]
I created a small tools to generate changelog
hmm, will find a place to host it 

```
================ 6.0.1 ====================
Gen v1.22.0 (#677)

* generator to support bool?

* gen v1.22.0

* trim version convertor

* bump ver

================ 5.0.20 ====================
fix build warning (#678)

================ 5.0.19 ====================
port autorest2 template to local generate tools (#669)

* port autorest to watch generator

* rename KubernetesWatchGenerator -> KubernetesGenerator

* add validate

* fix format

* fix generate code warnings

* fix line ending

* fix missing property found by comp check

* do not new http method

================ 5.0.18 ====================
fix flaky leader election tests (#676)

* force max thread

* add log

* use countdown to sync

* add logs

* add thread

================ 5.0.17 ====================
Fix typos (#674)

================ 5.0.16 ====================
Initial port of cache functions from java client (#665)

* Initial port of cache functions from java client

* Move lock in Cache.Replace to be less disruptive

* Remove IListerWatcher as it's not used at the moment

* Added todo in Cache.Get as reminder

* TApiType implement IKubernetesObject

* TApiType implement IKubernetesObject

* TApiType implement class along with IKubernetesObject

* Disable failing test until it can be figured out

* Ran `dotnet format --fix-whitespace --fix-style` to put formatting in compliance

* Moved contents of KubernetesClient.Util into KubernetesClient project

* Moved contents of KubernetesClient.Util into KubernetesClient project #2 :(

================ 5.0.15 ====================
Fixed regex to quote strings with leading zeros (#667)

================  ====================
Makes `realFileSystem` readonly (#655)

Makes `realFileSystem` read-only since it would not be updated

================ 5.0.13 ====================
fix leader election lease duration (#653)

* fix leader election lease duration

* fix cast

================ 5.0.12 ====================
fix sec issue (#647)

* fix sec issue

* update oidc instead

* Revert "update oidc instead"

This reverts commit c19672cdb99569e090edfbd06148162e0569c68c.

================ 5.0.11 ====================
Add support for loading namespaces from pod configuration. (#640)
```

**Comment by LYMI2771** [comment]
Hello @tg123,

Did this tool online? It's hard to found out which generated code version map to nuget package version.

By the way, the version of our cluster is 1.14.10, I want a exactly match client, which nuget version I can take?

Thanks.

**Comment by tg123** [comment]
i believe there was no 1.14 based sdk :(
but i think sdk ver1.4 should work with your cluster


BTW: 2 yr behind?

| SDK Version | Kubernetes Version | .NET Targeting                        |
|-------------|--------------------|---------------------------------------|
| 6.0         | 1.22               | netstandard2.1;net5                   |
| 5.0         | 1.21               | netstandard2.1;net5                   |
| 4.0         | 1.20               | netstandard2.0;netstandard2.1         |
| 3.0         | 1.19               | netstandard2.0;net452                 |
| 2.0         | 1.18               | netstandard2.0;net453                 |
| 1.6         | 1.16               | netstandard1.4;netstandard2.0;net452; |
| 1.4         | 1.13               | netstandard1.4;net451                 |
| 1.3         | 1.12               | netstandard1.4;net452                 |

**Comment by LYMI2771** [comment]
> i believe there was no 1.14 based sdk :(
> but i think sdk ver1.4 should work with your cluster
> 
> BTW: 2 yr behind?
> 
> SDK Version	Kubernetes Version	.NET Targeting
> 6.0	1.22	netstandard2.1;net5
> 5.0	1.21	netstandard2.1;net5
> 4.0	1.20	netstandard2.0;netstandard2.1
> 3.0	1.19	netstandard2.0;net452
> 2.0	1.18	netstandard2.0;net453
> 1.6	1.16	netstandard1.4;netstandard2.0;net452;
> 1.4	1.13	netstandard1.4;net451
> 1.3	1.12	netstandard1.4;net452

Thanks, that's what I need. 

Our cluster is pretty old. And we plan to upgrade it to 1.19 in future.

**Comment by MaxHorstmann** [comment]
A simple solution I suggest is to tweak the existing GitHub Actions workflow to automatically create a matching release for every published NuGet version. See PR #759.
