### ISSUE TITLE
ResourceQuantity "AsInt64" accessor not implemented

### ISSUE THREAD

**Issue by philBrown** [kubernetes-client/csharp#628]
The documentation for [`ResourceQuantity`](https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/ResourceQuantity.cs) states...

> Quantity is a fixed-point representation of a number. It provides convenient marshaling/unmarshaling in JSON and YAML, in addition to String() and **AsInt64()** accessors

While there is certainly a `ToString()` method, there is no _integer_ accessor.

This makes it quite difficult to compare quantities.

**Comment by brendandburns** [comment]
I suspect those docs got copy/pasted when we ported that code from Golang. We'd be happy to take a PR to add this.

**Comment by tg123** [comment]
should impl `IComparable`
that is more c#

**Comment by philBrown** [comment]
@tg123 I'm actually after mathematical operations to calculate quota utilisation, ie `used / hard` so accessing scalar values is more desirable

**Comment by tg123** [comment]
got it, so the underlay implementation is a `Fraction` object
would exposing it solve your issue?

**Comment by philBrown** [comment]
@tg123 Yes, that would pretty much do the job
