### ISSUE TITLE
Question: how could we switch kubernetes context?

### ISSUE THREAD

**Issue by WeihanLi** [kubernetes-client/csharp#632]
Can we switch kubernetes context in code without update the config file?

**Comment by brendandburns** [comment]
You should be able to use:

`BuildConfigFromConfigObject`

https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs#L181

And pass in a "currentContext" parameter to select a context.

**Comment by WeihanLi** [comment]
Thanks @brendanburns , could we provider `Contexts` for list all context? Since we load the config file, we may load all contexts defined in the config file I think, so that we could get a list of context easily

**Comment by brendandburns** [comment]
It's already public here:

https://github.com/kubernetes-client/csharp/blob/225bb1f59b650e6849858f52608ef917b2484ddb/src/KubernetesClient/KubeConfigModels/K8SConfiguration.cs#L38
