### ISSUE TITLE
Could we make the `KubeConfigDefaultLocation`  public?

### ISSUE THREAD

**Issue by WeihanLi** [kubernetes-client/csharp#634]
Could we public `KubeConfigDefaultLocation` in
<https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs#L22>

Sometime I wanna analyze the kube config by myself, it may be useful for me to load the default kube config file.

**Comment by tg123** [comment]
PR welcomed
