### ISSUE TITLE
Error: Nuget install

### ISSUE THREAD

**Issue by Goncalo-sousa** [kubernetes-client/csharp#637]
Error: Could not install package 'KubernetesClient 5.0.9'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.		

When i try to install kubernets client i always get this error. I already try other .net framework  versions to no avail. Im doing a university project and would like some help in starting this project.

**Comment by tg123** [comment]
net45 is no long supported, please update to net5
or you can have earlier version of the sdk

**Comment by Goncalo-sousa** [comment]
Thanks, I solved the problem using .NET core long-support, I was using .NET framework, I always had an error, I decided to change it.
