### ISSUE TITLE
Error : nugget install - doesn't have a strong name

### ISSUE THREAD

**Issue by om-gupta** [kubernetes-client/csharp#638]
Visual studio is giving an error below after installing nugget package version 4.0.26

Error - referenced assembly KubernetesClient version=4.0.0.0 doesn't have a strong name

Just wanted to check  is this kubernetes client not signed assembly?? Or do we have any strong reason to not signed the assembly??

Appreciate for any input.

Regards,
Om

**Comment by tg123** [comment]
3.0 i believe
.net4.5 support was removed 

still using .net45? update to net5?

**Comment by om-gupta** [comment]
We are using  net48

**Comment by tg123** [comment]
all windows only .net version are supported since 4.x

**Comment by om-gupta** [comment]
It's full framework net48 application but it's giving an error above after adding the nugget package version 4.0.26 ...

It seems like this version 4.0.26 dll is not signed with strong name..
Could you please give any other version which DLL which signed with strong name??

My application doesn't allow nugget which is not signed with strong name.

Appreciate for your help.

**Comment by om-gupta** [comment]
I can see till 4.0.26 version supporting Netstandard2.0 but DLL is signed with strong name..
Can anyone pls confirm what version of DLL is signed with strong name??

**Comment by tg123** [comment]
strong name is deprecated 
<https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named>

after we drop support of .net frameworks, no strong name will be added

**Comment by om-gupta** [comment]
Thanks 

What version of SDK were we supporting strong name?? 

Wanted to use OLDER version of SDk for now until our application is not fully migrated on Net5

**Comment by tg123** [comment]
please consider 3.x based on kubernetes 1.19 (EOL 2021-09-30)

**Comment by om-gupta** [comment]
Ok..thanks..let me try once..
