### ISSUE TITLE
[Question] Executing a command in a pod/executing a command. 

### ISSUE THREAD

**Issue by Tom284** [kubernetes-client/csharp#642]
I want to execute this command:
`kubectl exec -it clamd-m94dh -c clamd  -- clamdscan --multiscan /host-fs `
through code.

I have been trying to use this code:

```
var webSocket =
                await client.WebSocketNamespacedPodExecAsync(pod.Metadata.Name, "default",
               { "-c clamd", "-- clamdscan", "--multiscan", "/host-fs" },
                pod.Spec.Containers.Where(x => x.Name == "clamd").SingleOrDefault().Name
                   ).ConfigureAwait(false);

            var demux = new StreamDemuxer(webSocket);
            demux.Start();

            var buff = new byte[4096];
            var stream = demux.GetStream(1, 1);
            var read = stream.Read(buff, 0, 4096);
            var str = System.Text.Encoding.Default.GetString(buff);
            Console.WriteLine(str);
```
but it doesn't work, as it says **no such file or directory: unknown**

How should I approach this? 

(using `kubectl exec -it clamd-m94dh -c clamd  -- clamdscan --multiscan /host-fs` in cmd works.)

**Comment by brendandburns** [comment]
In your command:
`{ "-c clamd", "-- clamdscan", "--multiscan", "/host-fs" }`

`-c clamd` is a command being sent to `kubectl`, as is the `-- ` in the second argument.

In fact the `--` marks the separator between the stuff sent to `kubectl` and the stuff sent to be executed in the container.

So I think you want:
`{ "clamdscan", "--multiscan", "/host-fs" }`

As you command.

**Comment by Tom284** [comment]
It works. Thank you so much!! This helped me enormously! You are amazing!
