### ISSUE TITLE
How to get a kubeconfig for a deployed app

### ISSUE THREAD

**Issue by joshbinney** [kubernetes-client/csharp#645]
I have an app service in azure that needs to use the kubernetes api. I have this working locally as I have run commands through the command line that generated a kubeconfig file for my user account in azure. However I need to generate a kubeconfig for my app when it is deployed in azure. Also, when using my local kubeconfig file in azure I get ssl errors, why is this?

**Comment by tg123** [comment]
replied in #643, close this ticket if that helps
