### ISSUE TITLE
System.Text.Encodings.Web version upgrade due to security issue

### ISSUE THREAD

**Issue by shrja-ms** [kubernetes-client/csharp#646]
Hi,
Currently the code is using System.Text.Encodings.Web version 4.5.0, but it has a security issue, and we should be using System.Text.Encodings.Web version 4.5.1 to mitigate this.

But I could not find correct reference of that. Can someone help on this please?

**Comment by tg123** [comment]
should also send a PR to `IdentityModel.OidcClient`

**Comment by shrja-ms** [comment]
Thanks @tg123  I am using this in my repo as a package. When should I expect this to be published?

**Comment by tg123** [comment]
I will merge it as soon as tests passed
the latest oidc version is 4.0.0 but introduced something breaking changes, I will still lock `System.Text.Encodings.Web` to 4.5.1 and update oidc client later

**Comment by shrja-ms** [comment]
Great! Thanks for quick resolution.
I am using KubernetesClient Version  5.0.11, Can you publish a new package as well?

**Comment by tg123** [comment]
see https://www.nuget.org/packages/KubernetesClient/5.0.12

**Comment by shrja-ms** [comment]
Thanks @tg123 It worked.
