### ISSUE TITLE
Using V1ReplicationController in the api project will cause ambiguity, and swagger will not work properly

### ISSUE THREAD

**Issue by Snuger** [kubernetes-client/csharp#649]
Using V1ReplicationController in the api project will cause ambiguity, and swagger will not work properly

**Comment by brendandburns** [comment]
Can you add more information about what you are trying to do and what isn't working correctly?

**Comment by Snuger** [comment]
I have solved it in the configuration in swagger

**Comment by Snuger** [comment]
> Can you add more information about what you are trying to do and what isn't working correctly?

I have solved it in the configuration in swagger
