### ISSUE TITLE
Double encoding of pem secret

### ISSUE THREAD

**Issue by kangtao** [kubernetes-client/csharp#652]
Hi,

From my experiments, C# SDK will encode the secret data when calling patch API to k8s server. Is this by design? The reason I ask is that I need to set a secret from a pem certificate. What I do is to have a secret yaml template, get encoded pem from somewhere, decode it, and replace the yaml placeholder with actual pem value. But I will run into the yaml format issue where pem does not have right indentation.  I could not really find a way to manipulate yaml to have right indentation so I am wondering what is the best practice here. I need to load perm in runtime and ideally I just want to use pem encoded version instead of actual pem

Yaml template:

---
apiVersion: v1
kind: Secret
metadata:
  name: my-tls
type: kubernetes.io/tls
data:
  tls.crt: $CERT_PLACEHOLDER
  tls.key:$KEY_PLACEHOLDER
---

After I replace placeholders with actual value. It will run into yaml format issue:

---
apiVersion: v1
kind: Secret
metadata:
  name: my-tls
type: kubernetes.io/tls
data:
  tls.crt: -----BEGIN CERTIFICATE-----
AAAAAAAAAAAAA
BBBBBBBBBBBBB
CCCCCCCCCCCC
-----END CERTIFICATE-----
  tls.key: -----BEGIN CERTIFICATE-----
AAAAAAAAAAAAA
BBBBBBBBBBBBB
CCCCCCCCCCCC
-----END CERTIFICATE-----
---

**Comment by tg123** [comment]
byte[] will become base64 encode string, this is by design
