### ISSUE TITLE
"No connection could be made because the target machine actively refused it."

### ISSUE THREAD

**Issue by amsoedal** [kubernetes-client/csharp#654]
We have a customer who is running into this error consistently both on GKE and minikube. They are able to reach their cluster via other means.  Running "ListServicesInNamespaceAsync" times out after 30s with many instances of the HttpRequestException: "No connection could be made because the target machine actively refused it.: No connection could be made because the target machine actively refused it.:"

Here is the customer issue: https://github.com/microsoft/mindaro/issues/193

Could this be related to the application hosted in the cluster, since it reproduces for the eShopOnContainers application on both minikube and GKE?

**Comment by brendandburns** [comment]
What version of the library are you using? Is it possible that it is related to:

https://github.com/kubernetes-client/csharp/issues/585
https://github.com/kubernetes-client/csharp/issues/600

**Comment by tg123** [comment]
`No connection` sounds like connection issues.
did you run `telnet to check` before?

**Comment by amsoedal** [comment]
@brendanburns we'll upgrade and open a new issue if this reproduces. Thanks!
