### ISSUE TITLE
Getting wrong Kubernetes pod status through client API

### ISSUE THREAD

**Issue by vct4433** [kubernetes-client/csharp#658]
I am trying to get the Kubernetes pod status through the Kubernetes C# client library. One of my pods is a crash loop in the state. But the status of the pod from API is running. How to get the actual status of the pod?

I am using

c# library. Code is
```
using k8s;
var config = KubernetesClientConfiguration.InClusterConfig();
var client = new Kubernetes(config);
var namespaces = client.ListNamespacedPodAsync("cronjob").GetAwaiter().GetResult();
foreach (var ns in namespaces.Items)
{
   var status = ns.Status.Phase;
   Console.WriteLine(status);             
}
```
Output is

 Running 
 Running
But the actual result is while using kubectl command is

```
kubectl get pods -n cronjob

test3-1625640480-9vjg4         0/1     CrashLoopBackOff   5          5m51s
test1-cron-1625640600-mrqcg    0/1     Completed          0          4m39s
```

**Comment by brendandburns** [comment]
You want to look at `Pod.Status.ContainerStatuses[n].State...`

In general if you're wondering things like this, looking at the `kubectl` code can give you a good sense for what it is printing from:

https://github.com/kubernetes/kubectl
