### ISSUE TITLE
Interest in a controller interface?

### ISSUE THREAD

**Issue by ddieruf** [kubernetes-client/csharp#659]
I was wanting to create a K8s controller using this client and saw that there are no formal provisions. Looking at the Java client they have a [controller extension](https://github.com/kubernetes-client/java/tree/master/extended/src/main/java/io/kubernetes/client/extended/controller), as a separate project. If I rewrote that extension in csharp would there be interest in bringing it in?

**Comment by ddieruf** [comment]
As I get deeper I see they have the notion of informers. I don't believe csharp has that, correct?

**Comment by ddieruf** [comment]
I _believe_ I can pull out the idea of an `InformerFactory` for a simple `Watch` function that accomplishes that same idea but is not very versatile.

**Comment by tg123** [comment]
#351 #347
check out unmerged PRs

**Comment by ddieruf** [comment]
Thank you @tg123. Wow looks like they were on a good path but things got a little complicated. It would be so nice to have an Rx based informer in this client. I really want to create a controller for my project but want to do it in the most up to date, efficient way.

**Comment by ddieruf** [comment]
Before I go too far with this I am going to evaluate using @falox approach [here](https://github.com/falox/csharp-operator-sdk). It's a bit dated but could maybe be refreshed to something up to date.

**Comment by brendandburns** [comment]
I think there is definite interest, it has (as you see) gotten complicated in the implementation.

I think the right way to do this is to start small and incrementally build.

e.g. I would start with a Watch-based cache (basically us a List/Watch to maintain an in-memory live cache of the state of the API) once we get that merged, we can start building Informers and such on top of that.

But definitely eager to see this get built.

**Comment by ddieruf** [comment]
I totally agree with this approach. Further, I feel like we have quite a bit of this already created. It just needs to be organized as one thought. I would like to take a stab at that :)

**Comment by brendandburns** [comment]
That would be awesome!

**Comment by ddieruf** [comment]
For those reading along, here's the first PR.

https://github.com/kubernetes-client/csharp/pull/665

**Comment by ddieruf** [comment]
@tg123 and @BrandonSharp I am seeking a little advice on how to proceed...

As I get into `Cache.Controller` and `Cache.SharedProcessor` they utilize Java's `ThreadPoolExecutor` and `ScheduledExecutorService`s. The internals of these two classes are definitely achievable in C# but are going to make the PR considerably larger.

If you are not familiar with the executor services they introduce the ability to control background threads (pool sizes, queues, workers, etc). Also they give you options like scheduling recurring processes.

C# of course has `Task` and `TaskFactory` abilities. As an alternate solution, I could couple those with things like `Semaphore` and `Threading.Timer` to create a smaller less versatile version of executors (notably, I probably wouldn't build the notion of workers as ThreadPoolExecutor has).

A third option would be to convert the things that `Controller` and `SharedProcessor` are meant to manage into tasks but this will offer even less fine-grain thread control. Also, this will deviate the code base considerably from Java. So keeping things in-sync will be more of a challenge.

I haven't spent much time getting deep into Rx but if I was a betting man (which I am), I would say this is an inflection point. What are your thoughts about all this? Have I maybe missed another option?

**Comment by ddieruf** [comment]
A quick update @brendandburns and @tg123, things are progressing well. I have a good async model and am making my way through tests.

I have chosen to get the entire informer pattern working with tests, but will break things up logically into PRs. It's a lot to digest.

**Comment by tillig** [comment]
I just started down the controller creation path myself. I'm working mine into the [.NET generic host mechanism](https://docs.microsoft.com/en-us/dotnet/core/extensions/generic-host) so the things being monitored are all handled by [`BackgroundService` implementations](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.backgroundservice?view=dotnet-plat-ext-5.0), which takes care of app start/stop and other sorts of concerns. Unfortunately, I'm definitely having to replicate some of the Java and Go logic to handle things; it'd be nice to have more baked in, even if it was a separate package.

**Comment by IvanJosipovic** [comment]
There are two projects that help build .NET Operators.
https://github.com/buehler/dotnet-operator-sdk
https://github.com/containersolutions/dotnet-operator-sdk

 Hope this helps.

**Comment by ddieruf** [comment]
I have this PR in queue - https://github.com/kubernetes-client/csharp/pull/682 - which introduces GenericK8sApi.

I have informers ready to go as well. Controllers are not too far behind. I hope we can have a proper controller pattern in the official client. Similar to Java client.

**Comment by IvanJosipovic** [comment]
I found that the MS Yarp project has some interesting Operator code in it, https://github.com/microsoft/reverse-proxy/tree/main/src/OperatorFramework
