### ISSUE TITLE
ListNamespacedCronJob error

### ISSUE THREAD

**Issue by drodriguez78** [kubernetes-client/csharp#661]
* ListNamespacedCronJob1({namespace}) work
* ListNamespacedCronJob1Async({namespace}) work
* ListNamespacedCronJob({namespace}) does not work (Operation returned an invalid status code 'NotFound'\r\n\tResponse: Status 500 (InternalServerError))

and job.Status.LastSuccessfulTime always null

**Comment by tg123** [comment]
server ver
check server side logs 

500 means server side error
