### ISSUE TITLE
Serialization of string that starts with 0

### ISSUE THREAD

**Issue by JAMH-CBB** [kubernetes-client/csharp#663]
I am trying to deserialize a configmap that contains `data` values that begins with `0`. With the current implementation of `StringQuotingEmitter.cs` used by `Yaml.cs` it skips this type of value and therefore it is not quoted. When K8s tries to read the configmap it reports an error as it tries to parse the value as a `Int64` and not a string.

Example configmap:  
```
apiVersion: v1
data:
  operatorid: "00211"
kind: ConfigMap
metadata:
  name: map
  namespace: default
```

Code to reproduce issue:
```
var fileContent = File.ReadAllText(@"testfile.yaml");
var yamlContent = Yaml.LoadFromString<V1Deployment>(fileContent);
var output = Yaml.SaveToString(yamlContent);
```

Expected outcome:
`operatorid: "00211"` 

Actual outcome:
`operatorid: 00211`

Proposed solution is to change `QuotedRegex` in `StringQuotingEmitter` from:
`^(\~|null|true|false|-?(0|[1-9][0-9]*)(\.[0-9]*)?([eE][-+]?[0-9]+)?)?$`
to
`^(\~|null|true|false|-?(0|[0-9]*)(\.[0-9]*)?([eE][-+]?[0-9]+)?)?$`
This will catch strings that start with zeros and quote them.

**Comment by brendandburns** [comment]
Yeah, that looks like a bug in the regexp. Happy to take a PR to fix this.

Thanks!
