### ISSUE TITLE
Save Configuration

### ISSUE THREAD

**Issue by cdhunt** [kubernetes-client/csharp#664]
Is there a method to save the configuration back to file? I'm looking for the equivalent of `kubectl config use-context`. I don't just want to change it in config object in memory, but persist it.

**Comment by brendandburns** [comment]
There is not currently a method for this. We'd be happy to take a PR if you wanted to add it.

**Comment by cdhunt** [comment]
Would serializing a KubernetesConfiguration include all the properties?

**Comment by brendandburns** [comment]
You could try, I'm not certain that it would work correctly, but it's a good place to start.
