### ISSUE TITLE
IOException when deleting config file post-load

### ISSUE THREAD

**Issue by philliphoff** [kubernetes-client/csharp#67]
On Windows, deleting the Kubernetes configuration file immediately after `KubernetesClientConfiguration.BuildFromConfigFile(FileInfo)` will likely result in an `IOException` with error message:

```
The process cannot access the file '<file>' because it is being used by another process.
```

The issue is due to `KubernetesClientConfiguration.LoadKubeConfig(FileInfo)` opening a `Stream` from the `FileInfo` for deserialization but never disposing of it.  This leaves the file in an open state long enough for subsequent file operations on that file to fail (again, on Windows).

**Comment by brendandburns** [comment]
closing since #68 was merged...
