### ISSUE TITLE
Log issue

### ISSUE THREAD

**Issue by sczhh** [kubernetes-client/csharp#687]
After updating to the latest version, there seems to be a problem with log reading. The previous version did not have this problem

**Comment by tg123** [comment]
may i know what do you mean by 'a problem with log reading'

**Comment by sczhh** [comment]
When I set the "follow" parameter, the method freezes.

**Comment by tg123** [comment]
this is a know bug fixed by #681

I was thinking you are talking about `logs emitted by sdk`

**Comment by sczhh** [comment]
How should I use it?

**Comment by tg123** [comment]
either wait for release copy or clone my branch then add src ref

**Comment by sczhh** [comment]
Is the old "ReadNamespacedPodLogAsync" method unavailable?

**Comment by tg123** [comment]
yes api does not get changed

**Comment by sczhh** [comment]
Hope to post soon because I am using it.

**Comment by stefanloerwald** [comment]
I'm affected by the same issue. Trying to instantiate a `StreamReader` with a log stream created by `ReadNamespacedPodLogAsync` results in error `Stream was not readable.`:

```cs
var log_stream = await kubernetes_client.ReadNamespacedPodLogAsync(pod_name, "default", container: "foo", follow: true, cancellationToken: cancellation_token);
using var sr = new StreamReader(log_stream);
```

Works fine with V5.0.20, but not with V6.0.1.

**Comment by tg123** [comment]
fixed by #681

**Comment by stefanloerwald** [comment]
I now get a different error for reading logs:

```log
Cannot access a disposed object.
Object name: 'Http2ReadStream'.
   at System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.Read(Span`1 destination)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.get_EndOfStream()
```

My code is:
```cs
var log_stream = await kubernetes_client.ReadNamespacedPodLogAsync(pod_name, "default", container: "foo", follow: true, cancellationToken: cancellation_token);
using var sr = new StreamReader(log_stream);
while (!sr.EndOfStream) // exception thrown here
{
   var line = await sr.ReadLineAsync();
}

**Comment by stefanloerwald** [comment]
@tg123 would you like me to open a new issue for this or should we just re-open this one?

**Comment by tg123** [comment]
dup #704

**Comment by tg123** [comment]
please use `ReadNamespacedPodLogWithHttpMessagesAsync` as a temp workaround, fix is on the way
