### ISSUE TITLE
Update Reconcile Access Entity Previous Spec

### ISSUE THREAD

**Issue by Crespalvaro** [kubernetes-client/csharp#689]
Hello, I might be struggling with something really basic but is there a way to get the previous spec of an entity when update event is reconciled? How am I suppose to detect what changed on a custom resource update?

**Comment by tg123** [comment]
`watch=1` to retrieve all history?

**Comment by Crespalvaro** [comment]
That will return a watcher so I subscribe to an object events. I would like to know if its possible to access previous versions of a resource whereas you are not using a watcher

**Comment by tg123** [comment]
new watcher will receive all history of a resource including previous version for sure. can you use that?
