### ISSUE TITLE
Where can I find Compatibility table for SDK?

### ISSUE THREAD

**Issue by unlucky** [kubernetes-client/csharp#691]
Where can I find the SDK compatibility table?
Which version of SDK support k8s v1.20?

**Comment by tg123** [comment]
4.0 generated from 1.20
according to k8s api compatibility policy, should work with 1.21 and 1,19 api server

check update here
https://github.com/kubernetes-client/csharp/commits/master/version.json


BTW, Will do better doc to provide version matrix

**Comment by unlucky** [comment]
Thx a lot!
