### ISSUE TITLE
'No such file or directory' when attempting to build configuration from file (stream) in AWS Lambda 

### ISSUE THREAD

**Issue by StevenDewey** [kubernetes-client/csharp#692]
Error message: 
Ex: k8s.Exceptions.KubeConfigException: external exec failed due to: No such file or directory
   at k8s.KubernetesClientConfiguration.ExecuteExternalCommand(ExternalExecution config)
   at k8s.KubernetesClientConfiguration.SetUserDetails(K8SConfiguration k8SConfig, Context activeContext)
   at k8s.KubernetesClientConfiguration.InitializeContext(K8SConfiguration k8SConfig, String currentContext)
   at k8s.KubernetesClientConfiguration.GetKubernetesClientConfiguration(String currentContext, String masterUrl, K8SConfiguration k8SConfig)
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFileAsync(Stream kubeconfig, String currentContext, String masterUrl)

When running the lambda locally the `KubernetesClientConfiguration.BuildConfigFromConfigFile(memoryStream)` works perfectly, but when deployed in AWS Lambda it says No such file or directory, which I know isn't true since I know the file is successfully read in from S3. Could be a difference in my local machine being windows and the lambda being linux? 

Any help troubleshooting would be greatly appreciated!

**Comment by tg123** [comment]
please check if you can read `~/.kube/config` in your lambda (i do not think so)

**Comment by StevenDewey** [comment]
> please check if you can read `~/.kube/config` in your lambda (i do not think so)

Hi @tg123 thanks for the response. Do I need to read from that directory if I am passing in a fileStream directly to the BuildConfigFromConfigFile method? I would assume the the code would only check that file if using the default constructor: 
![image](https://user-images.githubusercontent.com/8305608/132375909-f76efda9-8a1d-4db7-97d6-f430fc952fe8.png)

Whereas I am using this constructor: 
![image](https://user-images.githubusercontent.com/8305608/132376245-c273237e-4e96-41f5-bd4d-a853a68ae023.png)

from here: 
![image](https://user-images.githubusercontent.com/8305608/132376560-7052d45f-9b3d-4bd7-ac16-13d37e969fbc.png)

Do you see what I'm saying?

**Comment by tg123** [comment]
sorry i don't get it at first 
i checked your stack again, it seems the exception happens when you were trying to acquire the access token.
probably depends on command from aws cli

could you please check related config section?

**Comment by StevenDewey** [comment]
> sorry i don't get it at first
> i checked your stack again, it seems the exception happens when you were trying to acquire the access token.
> probably depends on command from aws cli
> 
> could you please check related config section?

@tg123 I double checked the config file and everything looks good. I have confidence the config file is correct because I can run the lambda locally and it receives the same config file from S3 and the kubernetes client is initialized just fine. The only thing that seems different is that when the code is run in a deployed lambda it is running in a linux container instead of on my local windows PC. And this error "No such file or directory" seems to be a generic linux error within Process.Start(). I found a couple related articles: 
https://stackoverflow.com/questions/52599105/c-sharp-under-linux-process-start-exception-of-no-such-file-or-directory
https://stackoverflow.com/questions/3949161/no-such-file-or-directory-but-it-exists

I have tried converting from dos to unix but that didn't seem to solve the problem. 

Anyhow, I have a workaround that I can use, but it involves not using this library. I'd really like to use it but I am at a loss as to why it won't successfully initialize in a deployed lambda.

**Comment by tg123** [comment]
curious what the executable is
can i see your config?

external cmd works on your local machine does not mean it will on lambda

**Comment by StevenDewey** [comment]
@tg123 sent you an email with the config file attached for you to review.

**Comment by tg123** [comment]
after checking your `config`

here is there rootcause

```
  user:
    exec:
      ........
      command: aw
```

sdk calls open `aws` when running inside lambda env which does not exist.
the reason you can run it locally it is because `aws` was installed in your machine.

seems the same issue below
https://stackoverflow.com/questions/33513604/call-aws-cli-from-aws-lambda

**Comment by StevenDewey** [comment]
@tg123 indeed that seems to be the case. I will investigate this. Thanks for the help!
