### ISSUE TITLE
Job Verify should catch

### ISSUE THREAD

**Issue by csurfleet** [kubernetes-client/csharp#695]
I've just spent a couple of hours trying to figure out an 'UnprocessableEntity' issue. I had a job which contains this resources section:
```
Resources = new V1ResourceRequirements()
{
  Limits = new Dictionary<string, ResourceQuantity>
  {
    { "memory", new ResourceQuantity("512") },
    { "cpu", new ResourceQuantity("0.5") },
  },
  Requests = new Dictionary<string, ResourceQuantity>
  {
    { "memory", new ResourceQuantity("256Mi") },
    { "cpu", new ResourceQuantity("0.25") },
  }
}
```

The first memory item is missing the 'Mi', however a call to job.Validate passes, its only when we try to run it that we get an issue (which doesn't highlight the reason for being unprocessable). I think that Validate should be flagging this up?

I'm happy to do the work for this if you agree.

**Comment by tg123** [comment]
hmm how the can client side know `512 bytes` is not a valid value?

**Comment by csurfleet** [comment]
I'd imagine we would have to check the value has a valid suffix? (Mi and whatever other valid measures there are) Its definitely not a valid definition if it will always result in processable, and as the error message currently does nothing to drive people to the issue a little bit of pre-checking would turn lots of investigation into a simple fix for the dev?

I don't think a 'memory' value is ever valid without a measure attached?

**Comment by csurfleet** [comment]
I've just been looking around and you're correct, it defaults to bytes. I still can't see anything in my EKS audit logs for the actual reason its unprocessable at just 512, I assume there is a minimum memory limit that can be assigned to a container which we could use, but so far I'm unable to find it in the docs!

**Comment by tg123** [comment]
maybe we can search in server code, but I believe server should accept it.
should file a bug to server side if not documented

**Comment by brendandburns** [comment]
I suspect there is a default `LimitRange` set on your namespace that sets the minimum bytes:

**Comment by mroussel** [comment]
I have the same issue. Did you find a workaround or a solution ?
