### ISSUE TITLE
NamespacedPodExecAsync (and WebSocketNamespacedPodExecAsync) StdOut 

### ISSUE THREAD

**Issue by anongitmous** [kubernetes-client/csharp#697]
Hi,

I'm using KubernetesClient 5.0.17 in a .NET 5.0 console application. I had originally implemented pod/container exec functionality in my app using WebSocketNamespacedPodExecAsync, and everything was working as expected except for a particular behavior which I will do my best to explain. Let us say that I've invoked WebSocketNamespacedPodExecAsync with the command 'bash'. Reading the remote StdOut stream, I get a prompt, e.g. 
bash-4.4#

If I now enter a command e.g. 'ls' and hit the Enter key, my console will now appear thusly:
bash-4.4# ls
ls
application.version lib64                sbin
bin                           media             srv
dev                          mnt                 sys
entrypoint.sh          opt                  tmp
etc                          proc                 usr
home                      root                 var
lib                           run
bash-4.4#
bash-4.4#

The first line is the original prompt along with the command I entered, the second line is a repeat of the command I entered, lines 3-9 are the results of the 'ls' command, line 10 is the prompt text 'bash-4.4#' and line 11 is a repetition of the prompt text.

Via debugging, I could see that upon sending the 'ls' command to the pod/container StdIn, I get three distinct responses back via the pod/container StdOut:
1. ls
2. the directory listing
3. the prompt text in duplicate

I'm running this from Windows, and I noticed that the input that is sent to the pod/container StdIn follows the '\r\n' convention, so I thought that maybe that was causing the issue, but even if I changed that to have just '\n' (followed by a null), I got the same strange results.

I then looked around and found NamespacedPodExecAsync, and reimplemented my solution, but I got the exact same results. Using kubectl to connect to the same pod/container and using the same commands, I do not get the strange responses.

Here's the code I'm currently using (there are a lot of steps which aren't important I believe, I'm just trying to show the relevant calls):

`int exitCode = await _k8sClient.NamespacedPodExecAsync(_pod.Name, _pod.Namespace, containerName, cmd, _openStdIn, HandleContainerStreams, cancellationToken);`

```
// read console input stream, send to pod/container input stream
int bytesRead = await consoleStdInStream.ReadAsync(someBuffer, 0, someBufferSize, cancellationToken);
await containerInputStream.WriteAsync(someBuffer, 0, bytesRead , cancellationToken);
```

```
// read pod/container stdOut stream, send to console stdOut stream (I get three distinct responses for each command I enter)
int bytesRead = await containerStdOutStream.ReadAsync(someBuffer, 0, someBufferSize, cancellationToken);
await consoleStdOutStream.WriteAsync(someBuffer, 0, bytesRead , cancellationToken);
```

Any light that could be shed on what I'm doing wrong would be appreciated.

Thank you,

Matt

**Comment by brendandburns** [comment]
Can you try setting tty to true? (or if it is true, set it to false :) I suspect that it is something in the shell's interaction w/ stdout.

**Comment by anongitmous** [comment]
> Can you try setting tty to true? (or if it is true, set it to false :) I suspect that it is something in the shell's interaction w/ stdout.

Thank you. I have been setting tty to true or false depending upon whether a flag is passed  (I believe, after the fashion of how kubectl does it with -t). If I set it to always be false, i.e.

`int exitCode = await _k8sClient.NamespacedPodExecAsync(_pod.Name, _pod.Namespace, containerName, cmd, false, HandleContainerStreams, cancellationToken);`

Then the behavior changes as follows if the command is 'bash':
1. The output is no longer formatted. (please see attached screenshots)
2. I no longer get a bash prompt (i.e. 'bash-4.4# ' is missing, and my prompt is merely an empty line)
3. When I type in a command such as 'ls' and press the Enter key, I get the error `bash: line 1: $'ls\r': command not found`. If I then re-enable the logic that replaces the Windows `\cr\lf` with `\lf\null` prior to sending to the pod's StdIn, the command successfully executes, but
4. Upon executing a command, I get only the output, and once the command has completed, I'm back with no prompt again.

If tty is true, the result of executing 'ls' appears as:
![image](https://user-images.githubusercontent.com/25258587/133658296-47cc860e-40ec-4b24-93cf-44a78f6f7cb9.png)

if not:
![image](https://user-images.githubusercontent.com/25258587/133658447-d31a380b-0dc7-4bcf-a9ee-4ff050e76b90.png)
