### ISSUE TITLE
Signed assemblies?

### ISSUE THREAD

**Issue by philliphoff** [kubernetes-client/csharp#70]
As the library assemblies are unsigned, they cannot be referenced by assemblies that are (required to be) signed, which then excludes its use in certain applications.

It'd be great to offer a signed flavor of the assemblies.

(Alternatively, one could fork the repo, build, and sign a forked version, but that's a good deal of overhead to take on.)

**Comment by brendandburns** [comment]
@philliphoff I'm relatively new to packaging libraries... Any pointers on how to produced a signed package?

Is it this:
https://blog.nuget.org/20170914/NuGet-Package-Signing.html

**Comment by philliphoff** [comment]
It's less about producing a signed NuGet *package* (though that's probably not a bad idea) but having signed *assemblies* within the package.

This is probably a good starting point: [https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name)

A complication is that signing your assembly means that the transitive closure of assemblies it references must also be signed.  Currently the Kubernetes library references the [`BouncyCastle.NetCore`](https://www.nuget.org/packages/BouncyCastle.NetCore/) NuGet package, which does *not* contain signed assemblies.  It's not clear to me how that package is different from the [`Portable.BouncyCastle`](https://www.nuget.org/packages/Portable.BouncyCastle/) NuGet package, which *has* signed assemblies, and who's author seems to be more closely affiliated with the BouncyCastle organization.

**Comment by brendandburns** [comment]
It seems like strong-naming isn't really a best practice any more?

https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/

Again, I'm not an expert here...



________________________________________

**Comment by philliphoff** [comment]
I wouldn't call myself an expert either.  That said, there *were* some very passionate arguments within the .NET community in recent years for the end of strong-named signed (library) assemblies, but I'd disagree that that has become "best practice".  There are valid arguments for not signing assemblies, but I'd argue that they've generally been mitigated through more deliberate versioning schemes and automatic NuGet assembly binding redirects.  JSON.NET, one of the most ubiquitous 3rd party libraries, continues to be strongly-named (at least in .NET FW/Core/Standard platform flavors).

In my opinion, the primary argument *for* strong-named assemblies is that, to *not* do so would be arbitrarily writing off a subset of your potential users (who otherwise require strong-naming and are unwilling to commit the time/effort to maintain their own fork of a library for the sole purpose of applying strong-naming themselves).

**Comment by brendandburns** [comment]
Thanks for the feedback, I'll try to get it up and running (this is the first time I've done one of these....)

--brendan

________________________________

**Comment by discosultan** [comment]
Here's another reference to relevant information which brings out pros and cons of signing:

https://github.com/dotnet/corefx/blob/5b186f1857c1af98057cd0f34e93169f280bb76c/Documentation/project-docs/strong-name-signing.md
