### ISSUE TITLE
JSON deserialization of non-JSON content in proxy-related methods

### ISSUE THREAD

**Issue by philliphoff** [kubernetes-client/csharp#71]
The generated methods for the proxy-related REST calls (e.g. `ProxyGETNamespacedServiceWithHttpMessagesAsync()`) expect responses to be JSON-serialized strings; this is often not the case (e.g. when a web site is being proxied and raw HTML, CSS, and JavaScript are returned).

Those proxy-related methods should probably just pass through the raw response content.

**Comment by brendandburns** [comment]
Yeah, this is tricky to do correctly. It will be improved when Port forwarding is supported.
