### ISSUE TITLE
DeleteNamespacedJob with V1DeleteOptions parameter is not working in 6.0.1

### ISSUE THREAD

**Issue by Bliamoh** [kubernetes-client/csharp#710]
Starting with the version 6.0.1, the DeleteNamespacedJob function is not working as intended with a V1DeleteOptions parameter.

I made some tests, and in the 5.0.20 version of KubernetesClient, when doing this:

``` C#
client.DeleteNamespacedJob(myJob, myNamespace, new V1DeleteOptions { PropagationPolicy = "Background" });
```

The job `myJob` and all its associated pods were deleted. But starting with the version 6.0.1 of KubernetesClient, only the job is deleted and all the pods are kept. 

But the strange part about this is that either in version 5.0.20 or in version 6.0.1, calling the PropagationPolicy parameter like this will work:

``` C#
client.DeleteNamespacedJob(myJob, myNamespace, propagationPolicy: "Background");
```

I experienced this issue in a Kubernetes cluster v1.21.4 hosted with Docker Desktop and in a Kubernetes cluster v1.20.4 hosted in a Linux environment.

**Comment by tg123** [comment]
Thanks for reporting
