### ISSUE TITLE
V1ObjectMeta validation fails

### ISSUE THREAD

**Issue by mburumaxwell** [kubernetes-client/csharp#712]
When an object (e.g. `V1CronJob`) is parsed from a YAML file, validation fails because the `V1ObjectMeta` objects it uses throw an `NullReferenceException` It appears that since version 6 of this library, validating instances of `V1ObjectMeta` validates `ManagedFields` and `OwnerReferences` which may be null in some scenarios.

Culprit code:

https://github.com/kubernetes-client/csharp/blob/7bbf6aa37405d51c626611b2d443f9d098e9aa08/src/KubernetesClient/generated/Models/V1ObjectMeta.cs#L402-L409

**Comment by tg123** [comment]
thanks for reporting, the validate func is empty in 5- ver LOL

**Comment by mburumaxwell** [comment]
Yes it was that's why it worked. Thanks for the fix ...
