### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by mbendtsen** [kubernetes-client/csharp#721]
I can't seem to get this to work.

Working on an AKS cluster and I want one of my services to get access to kubernetes data like replicas. 
Nothing happens. No able to debug this because it is running in Azure, but when SSH into a pod and trying to call the kubernetes API with curl I get a 401.

What I'm I missing?

```c-sharp
        public KubernetesManager()
        {
            var k8sConfig = KubernetesClientConfiguration.InClusterConfig();
            client = new k8s.Kubernetes(k8sConfig);
        }

        public async Task<(int desired, int count)> GetReplicaset(string deployment, string deploymentNamespace)
        {
            var v1Scale = await client.ReadNamespacedReplicaSetScaleAsync(deployment, deploymentNamespace);

            return (v1Scale.Spec.Replicas.Value, v1Scale.Status.Replicas);
        }
```

**Comment by mbendtsen** [comment]
It might be because the service account don't have access to the api

**Comment by tg123** [comment]
thanks for confirming. reopen if still have any issues.
