### ISSUE TITLE
Missing DrainNode method

### ISSUE THREAD

**Issue by jingao-msft** [kubernetes-client/csharp#726]
Our team needs to use kubernetes-client to remove a specific node from cluster.  We found the sdk includes the method DeleteNode(), but we don't find DrainNode() method.  I'm wondering if DeleteNode() is good enough for us to remove unwanted node, will this method evict pods on the issued node first before deleting it?
Plus, will this method remove the node gracefully?

**Comment by tg123** [comment]
we do not have the fancy tool yet :(
but PRs are welcomed

you can find port java kubectl to .net (planned but lazy)
https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDrain.java
