### ISSUE TITLE
V1Status object returned from DeleteNamespacedDeployment() empty

### ISSUE THREAD

**Issue by cadamantidis** [kubernetes-client/csharp#73]
Hey all,

I have found an interesting issue that I'm not sure is an incorrect use of the library or a bug.

When I call `DeleteNamespacedDeployment()` the `V1Status` object that is returned has null for all of the attributes if the action was successful.  If the action was a failure, you get a `Microsoft.Rest.HttpOperationException` with a response that looks like it contains a `V1Status` object.

It seems, from other implementations of the same functions in other client libraries (python, go, etc) and from the kubectl verbose output that return statuses should have an attribute status of "Success" on successful executions.

Thanks!
Chris

**Comment by tg123** [comment]
please have a look at
https://github.com/kubernetes-client/csharp/blob/master/examples/namespace/Namespace.cs#L72

you should call ObjectView
