### ISSUE TITLE
Too old resource version when using the watch API (possible stale cache issues)

### ISSUE THREAD

**Issue by ymarcus93** [kubernetes-client/csharp#740]
Hi all.

I'm trying to use the `Watch()` method on the response I get from `ListNamespacedDeploymentWithHttpMessageAsync()`.

My code is as follows:

```c#
var deployment = await kubeClient.ReadNamespacedDeploymentAsync(deploymentName, deploymentNamespace);
// Use deployment in method that patches the spec
await SomeLogicThatPatchesTheDeployment(deployment);
// Watch the deployment using the same deployment queried earlier.
var listWatchDeploymentResp = kubeClient.ListNamespacedDeploymentWithHttpMessagesAsync(
   namespaceParameter: deployment.Namespace(),
   resourceVersion: deployment.ResourceVersion(),
   fieldSelector: $"metadata.name={deployment.Metadata.Name}",
   watch: true
);
var deploymentWatcher = listWatchDeploymentResp.Watch<V1Deployment, V1DeploymentList>(...)
// ...
// Dispose deploymentWatcher after using it
```

I'm setting `resourceVersion` to the deployment I received **before** calling `SomeLogicThatPatchesTheDeployment()` on it, so that I can receive all watch events, including `Modified` events caused by patching the deployment.

----

The problem is sometimes I get a `KubernetesException` stating "too old resource version". Why is this happening? The time in between `SomeLogicThatPatchesTheDeployment()` and `ListNamespacedDeploymentWithHttpMessagesAsync()`  is < 5 seconds; does the Kube API Server really not know about the `ResourceVersion` for the `deployment` that was first queried?

In addition, after looking at the Kubernetes documentation (https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes), it seems that this problem could have occurred due to a stale cache issue. Perhaps the `deployment` read on the first line above was read from the cache, rather than querying from the server, so the code always had a stale version. But even in that case, I would assume the call to `SomeLogicThatPatchesTheDeployment()` would fail for a similar reason. In reality, my code fails on the `Watch` call as explained above--never on the patch code. So honestly I'm not sure what is going on here.

Are there any remedies for this? Also, that same link above states the following:

> A given Kubernetes server will only preserve a historical list of changes for a limited time. Clusters using etcd3 preserve changes in the last 5 minutes by default. When the requested watch operations fail because the historical version of that resource is not available, clients must handle the case by recognizing the status code 410 Gone, clearing their local cache, performing a list operation, and starting the watch from the resourceVersion returned by that new list operation. Most client libraries offer some form of standard tool for this logic. (In Go this is called a Reflector and is located in the k8s.io/client-go/cache package.)

Does this library have a way to force a clear of the local cache?

**Comment by brendandburns** [comment]
Yes. There's a big discussion of this here:

https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes

In particular:

"A given Kubernetes server will only preserve a historical record of changes for a limited time. Clusters using etcd 3 preserve changes in the last 5 minutes by default. When the requested watch operations fail because the historical version of that resource is not available, clients must handle the case by recognizing the status code 410 Gone, clearing their local cache, performing a new get or list operation, and starting the watch from the resourceVersion that was returned."
