### ISSUE TITLE
Kuberentes C# Client, get allocated resources for a node

### ISSUE THREAD

**Issue by remus-corneliu** [kubernetes-client/csharp#749]
I'm trying to get the allocated resources for a Node using Kuberenetes C# client but I cannot figure out where or how do I get the information.

I'm debugging a V1Node instance and I see in Status property Capacity and Allocatable (Defaults to Capacity), but I cannot see anything regarding left for use capacity or allocated capacity (CPU and RAM).

To be more specific I'm reffering to this section

![image](https://user-images.githubusercontent.com/41466855/144292999-ad7fe2bb-3a67-411c-a73a-6fc16ecf957f.png)

Some help would be much appreciated.

**Comment by brendandburns** [comment]
Please see the discussion here:

https://github.com/kubernetes-client/csharp/issues/416

That is the best option. The code that generates that table in `kubectl` is all run client side and it is fairly complex.

**Comment by remus-corneliu** [comment]
@brendandburns I'm using the implementation provided by @ludovicalarcon 

```
JObject nodesObject = (JObject)await cluster.GetClusterCustomObjectAsync(Register.GROUP_NAME, Register.VERSION, "nodes", "");
k8sNodeMetricsList nodesMetricsList = nodesObject.ToObject<k8sNodeMetricsList>();
```
and I get values for CPU and RAM but I don't know what exactly do they represent

![image](https://user-images.githubusercontent.com/41466855/144479928-32c7d595-d4ee-4ce3-b6c8-6e6c1f12fb20.png)

For memory I found something which might help me converting to Mi (I guess this is a milli-unit?) [convertion](https://github.com/kubernetes/apimachinery/blob/v0.22.4/pkg/api/resource/quantity.go#L117). Can this be converted to Mb ?what is the relation between Mi and Mb.

but for CPU I have no idea what "n" stands for nor how or into what to convert it in. My node's capacity is 40 CPUs but when when inspecting the used resources I'm getting 914311858n which I have no clue how to convert from one another or vice-versa.

**Comment by tg123** [comment]
those objects are `ResourceQuantity` and you can convert values whatever you want by using `ToInt32` or implicit cast 

n is short for nano

see definition here: 
https://github.com/kubernetes-client/csharp/blob/61025a02556d0bde823be7f53b262e4d3148b8fb/src/KubernetesClient/ResourceQuantity.cs#L259

**Comment by remus-corneliu** [comment]
@tg123 so just to make it clear 

Assuming I have a 40 CPU node this means that it translates to 40,000,000,000 n.

And if one Pod consumes 6002388n this translates to is 10^-9 which should be 0.006002388. And this is the usage from 40 ? 

Are mu assumptions correct ?

**Comment by tg123** [comment]
To my understanding `6002388n` mean `6002388n` of cpu unit consumed by the pod, no matter how many cores on your node.
see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu
