### ISSUE TITLE
api issue Patch Deployment make it crash, maybe wiki is not clear or other issue

### ISSUE THREAD

**Issue by legendsnow** [kubernetes-client/csharp#757]
When I use kubectl to patch k8s pod,
such as 
kubectl patch deployment {podname} -p '{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"podname\",\"image\":\"******:5000/***/***/******:v3.0.1.5\"}]}}}}' -n namespace
The pod works well

The Deployname Struct
   containers:
       image: ******:5000/***/***/******:v3.0.1.5
        imagePullPolicy: IfNotPresent
        name: podname

But use it in code
such as 
Code is following

var patchStr = @"{""spec"":{""template"":{""spec"":{""containers"":[{""name"":""podname"",""image"":""******:5000/***/***/******:v3.0.1.5""}]}}}}";
client.PatchNamespacedDeployment(new V1Patch(patchStr, V1Patch.PatchType.MergePatch), deploymentname, namesapce);
The Patch is submit sucess, but the pod is crash

kubectl edit deployment podname
The Deployname Struct
 containers:
      - image: ******:5000/***/***/******:v3.0.1.5

And name node missing, The pod crash

**Comment by tg123** [comment]
pod crash?
what is the output of kubectl log?

sounds like image issue

**Comment by legendsnow** [comment]
> pod crash? what is the output of kubectl log?
> 
> sounds like image issue

Let me show you deployment yaml

using kubectl

The Yaml is following


   spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: test-app
                operator: In
                values:
                - test-deployment
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /usr/bin/tail
        - -f
        - /dev/null
        env:
        - name: TestNamespace
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CmdName
          value: TestlTools
        - name: FORCE_RESTART_
          value: "13280569377692"
        image: 192.111.111.111:5000/test/project1/testpodname:v3.0.1.4


When I use coding to path the K8s

The deployment yaml changes to

    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: test-app
                operator: In
                values:
                - test-deployment
            topologyKey: kubernetes.io/hostname
      containers:
      - image: 192.111.111.111:5000/test/project1/testpodname:v3.0.1.4
        imagePullPolicy: IfNotPresent
        name: cbop-bill-tools

**Comment by legendsnow** [comment]
> pod crash? what is the output of kubectl log?
> 
> sounds like image issue

The kubectl exe patch  Runing well

is
Using Kubectl exe
kubectl patch deployment test-deployment -p '{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"test\",\"image\":\"192.111.111.111:5000/test/project1/testpodname:v3.0.1.4\"}]}}}}'  -n testnamespce

Using C# code  Crash
var patchStr = @"{""spec"":{""template"":{""spec"":{""containers"":[{""name"":""test"",""image"":""192.111.111.111:5000/test/project1/testpodname:v3.0.1.4""}]}}}}";
client.PatchNamespacedDeployment(new V1Patch(patchStr, V1Patch.PatchType.MergePatch), "test-deployment", "testnamespce");

Crah log  Namespace required,please set env TestNamespace first

I don't know the difference between kubecl.exe path and coding path update.

**Comment by tg123** [comment]
could you please test if `StrategicMergePatch` works

**Comment by legendsnow** [comment]
> 

it works, thanks a lot :)
what is the  different? 
Can I find any wiki about PatchType?

**Comment by legendsnow** [comment]
> could you please test if `StrategicMergePatch` works

it works, thanks a lot :)
what is the different?
Can I find any wiki about PatchType?

**Comment by tg123** [comment]
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#use-a-json-merge-patch-to-update-a-deployment

**Comment by legendsnow** [comment]
> https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#use-a-json-merge-patch-to-update-a-deployment

That's great. I will close this ticket and read the wiki.

Your suggestion is correct
