### ISSUE TITLE
How do i keep a shell open to a container?

### ISSUE THREAD

**Issue by joepvand** [kubernetes-client/csharp#760]
Hey there,

I found the example on how to use ExecInPodAsync and got it working. However i wonder how i can use this to keep open an interactive shell. Using kubectl i can do it by using '/bin/bash/' as the command. How can i do this using this client?

**Comment by tg123** [comment]
`stdin=true` (`-i`) is by default.

you may want `demux.getstream(stdout, stdin)` and copy your stdin/stdout to the returned stream

**Comment by joepvand** [comment]
> `stdin=true` (`-i`) is by default.
> 
> you may want `demux.getstream(stdout, stdin)` and copy your stdin/stdout to the returned stream

I now have it as follows: 
`private async static Task ExecInPod(IKubernetes client, V1Pod pod)
        {
            var webSocket =
               await client.WebSocketNamespacedPodExecAsync(pod.Metadata.Name, "default", "ls",
                   pod.Spec.Containers[0].Name).ConfigureAwait(false);

            var demux = new StreamDemuxer(webSocket);
            demux.Start();

            var buff = new byte[4096];
            var stream = demux.GetStream(ChannelIndex.StdIn, ChannelIndex.StdOut);

            await Console.OpenStandardInput().CopyToAsync(stream);
            await Console.OpenStandardOutput().CopyToAsync(stream);


            while (true)
            {
                stream.Read(buff, 0, 4096);

                var str = System.Text.Encoding.Default.GetString(buff);
                Console.WriteLine(str);
            }

        }`

This has working input but the output is now gone. Any ideas?

**Comment by tg123** [comment]
the api is confusing, you should put stdout first, it is not a typo
and you should not await first copy, make it async instead, or it would always wait there.

```
stream = demux.GetStream(ChannelIndex.StdOut, ChannelIndex.StdIn);


task.run  await Console.OpenStandardInput().CopyToAsync(stream);
task.run  await Console.OpenStandardOutput().CopyToAsync(stream);

wait 
```

**Comment by joepvand** [comment]
I feel like an absolute monkey, i can not figure this out. This is what i have now:
       
```
        private async static Task ExecInPod(IKubernetes client, V1Pod pod)
        {
            var webSocket =
               await client.WebSocketNamespacedPodExecAsync(pod.Metadata.Name, "default", "/bin/bash",
                   pod.Spec.Containers[0].Name).ConfigureAwait(false);

            var demux = new StreamDemuxer(webSocket);
            demux.Start();

            var buff = new byte[4096];
            var stream = demux.GetStream(ChannelIndex.StdOut, ChannelIndex.StdIn);

            Task.Run(async () => await Console.OpenStandardInput().CopyToAsync(stream));



            while (stream.CanRead)
            {
                stream.Read(buff, 0, 4096);
                var str = System.Text.Encoding.Default.GetString(buff);
                Console.WriteLine(str);

                stream.Flush();
            }

        }
    }

```
Adding Console.OpenStandardOutput(). causes an error 'Stream does not support reading'.

It is somewhat working now but the output is borked : 
```

Starting Request!
root@test-566c6c899d-ljrtw:/#
ls
ls
@test-566c6c899d-ljrtw:/#
bin   docker-entrypoint-initdb.d  home   media  proc  sbin  tmp
boot  entrypoint.sh               lib    mnt    root  srv   usr
dev   etc                         lib64  opt    run   sys   var

root@test-566c6c899d-ljrtw:/#
root@test-566c6c899d-ljrtw:/#
boot  entrypoint.sh               lib    mnt    root  srv   usr
dev   etc                         lib64  opt    run   sys   var

```
I only put 'ls' once and got that as a response.

**Comment by tg123** [comment]
`async await stream.CopyToAsync(Console.OpenStandardOutput());` <-- should copy steam to stdout
lol, did not test, i can test it later if you still cannot run it

**Comment by joepvand** [comment]
First off, Thanks for your help. I got it semi working with this:
```
var webSocket =
               await client.WebSocketNamespacedPodExecAsync(pod.Metadata.Name, "default", "/bin/bash",
                   pod.Spec.Containers[0].Name).ConfigureAwait(false);

            var demux = new StreamDemuxer(webSocket);
            demux.Start();

            var stream = demux.GetStream(ChannelIndex.StdOut, ChannelIndex.StdIn);

            Task.Run(async () => await Console.OpenStandardInput().CopyToAsync(stream));


            await stream.CopyToAsync(Console.OpenStandardOutput());
```

But that hangs after issueing the first command. The output however does look normal in the beginning

**Comment by tg123** [comment]
just a bit test. i guess the original code is due to deadlock

here is a working one
```
            using var reader = new StreamReader(stream);
            while (!reader.EndOfStream)
            {
                Console.WriteLine(reader.ReadLine());
            }
```

**Comment by joepvand** [comment]
That works great, thanks a lot!

**Comment by tg123** [comment]
BTW could you please contribute an example if you have time?

**Comment by joepvand** [comment]
> BTW could you please contribute an example if you have time?

Made a pr
