### ISSUE TITLE
exec auth support

### ISSUE THREAD

**Issue by LeiYangGH** [kubernetes-client/csharp#761]
My k8s cluster is in azure aks. I generate kube config using:
```bash
az login
az account set -s xxx
az aks get-credentials -g ggg -n nnn
```
It'll generate kube config like this:

> - name: clusterUser_oc-k8s-app-1-dev-use2-aks_oc-k8s-app-1-dev-use2-aks
>   user:
>     auth-provider:
>       config:
>         access-token: sometoken
>         apiserver-id: someguid  
>         client-id:  someguid
>         config-mode: "1"
>         environment: AzurePublicCloud
>         expires-in: "3907"
>         expires-on: "1641893838"
>         refresh-token: sometoken
>         tenant-id: someguid
>       name: azure

Then I can successfully use `kubectl` command.

But there is some very strange and annoying problem that asking me to login after a few minutes or hours randomly. [similiar question](https://docs.microsoft.com/en-us/answers/questions/206665/why-does-azure-kubernetes-service-prompt-for-crede.html)

So I used [kubelogin](https://github.com/Azure/kubelogin) to solve this issue and works well.
The kube config is like this:

> - name: clusterUser_oc-k8s-app-1-dev-use2-aks_oc-k8s-app-1-dev-use2-aks
>   user:
>     exec:
>       apiVersion: client.authentication.k8s.io/v1beta1
>       args:
>       - get-token
>       - --environment
>       - AzurePublicCloud
>       - --server-id
>       - someguid
>       - --client-id
>       - someguid
>       - --tenant-id
>       - someguid
>       command: kubelogin
>       env: null
>       provideClusterInfo: false

But `kubernetes-client/csharp` doesn't support this, apparently.

Is there any option in `kubernetes-client/csharp` that can achive the same purpose? i.e. get token before each request using the parameters in config and then use that token?

**Comment by brendandburns** [comment]
This is a definite gap in this library. I will work on the fix.

**Comment by LeiYangGH** [comment]
thanks! it's great!

**Comment by tg123** [comment]
close #774

**Comment by Ariahs0110** [comment]
Is this issue already solve?Because when I try to use the kubelogin, the kubernetes-client/csharp still doesn't work with it
