### ISSUE TITLE
Forbidden for some methods(I'm only using kube config on dev machine)

### ISSUE THREAD

**Issue by LeiYangGH** [kubernetes-client/csharp#762]
```csharp
                 //var config = KubernetesClientConfiguration.BuildDefaultConfig(); //also tried this
                 var config = KubernetesClientConfiguration.BuildConfigFromConfigFile(@"C:\Users\my.name\.kube\config");
                 IKubernetes client = new Kubernetes(config);
                 var pods = client.ListNamespacedPod("somenamespace");
                 string podName = pods.Items[0].Metadata.Name;
                 Console.WriteLine(podName); //working!
                 var dcs = client.ListNamespacedCustomObject("platform.company.com", "v1beta1", "somenamespace", "crdname"); //Forbidden!
```

please have a look at above code and comments.

error call stack:

> Microsoft.Rest.HttpOperationException
>   HResult=0x80131500
>   Message=Operation returned an invalid status code 'Forbidden'
>   Source=KubernetesClient
>   StackTrace:
>    at k8s.Kubernetes.<ListNamespacedCustomObjectWithHttpMessagesAsync>d__904.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at k8s.KubernetesExtensions.<ListNamespacedCustomObjectAsync>d__1753.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

This is on my dev machine, where i can successfully use kubectl to get any thing(including pods, and crd in each namespace).

I think this question is not related to rbac(i've searched issues and many similiar issues are categorized into) since i'm not in cluster and i'm using a local kube config that kubectl also uses.

**Comment by brendandburns** [comment]
Have you tried the exact same list CRD request in `kubectl`? It's definitely possible that you have RBAC privileges for Pods but not the CRD that you are trying to list.

Alternately, it's possible that your token expired in the middle.

Let's fix the other auth problem you reported first and then try to tackle this bug.

**Comment by LeiYangGH** [comment]
as i already said, using `kubectl` i can get any thing(including pods, global crds, and crd instances in each namespace).

More details:

1. The same code worked well when I was having a kube config with admin account.
2. Recently our company switched to a new cluster and now I don't have admin account, and can only generate kube config using above commands. this config can do anything i want using kubectl, though.
3. Now the same code don't work now. Nothing changed, except k8s cluster and credentials changed, and both are set as default current context.

**Comment by LeiYangGH** [comment]
i'm very sorry to found out the root cause was i used the different namespace in kubectl and csharp. in csharp the namespace is a configuration variable so the difference was not that obvious.
close now.
