### ISSUE TITLE
DeleteNamespacedService incorrect return value?

### ISSUE THREAD

**Issue by mattilaiatostek** [kubernetes-client/csharp#767]
With 7.0.5 nuget package, I'm unable to compile this piece of code
`V1Status deleteServiceStatus = client.DeleteNamespacedService("my-service", "default");`

as it returns error CS0029: Cannot implicitly convert type 'k8s.Models.V1Service' to 'k8s.Models.V1Status'

I have an old clone from github (8th Nov 2021) and if I compile kubernetes-client myself also that code works fine. I tried latest code from github, but I'm unable to compile that, but that's another story..

Thanks in advance for any comments!

**Comment by tg123** [comment]
it is correct, delete service now return a service obj instead of v1status (was in 1.22)

```
"responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/v1.Service"
            }
          },
          "202": {
            "description": "Accepted",
            "schema": {
              "$ref": "#/definitions/v1.Service"
            }
          }
        },
```

**Comment by mattilaiatostek** [comment]
Thanks, somehow I missed that I should be using an older version of the nuget package.
