### ISSUE TITLE
Can you explain how to work this client?

### ISSUE THREAD

**Issue by RouR** [kubernetes-client/csharp#78]
I have some config

```
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  template:
    metadata:
      labels:
        app: web
        ci: somedataForOverride        
```

And I write this code, dokerize it and deploy to cluster with  env KUBERNETES_SERVICE_HOST="kubernetes.default.svc.cluster.local" KUBERNETES_SERVICE_PORT="443"

```
            var config = KubernetesClientConfiguration.InClusterConfig();
            IKubernetes client = new Kubernetes(config);
            Console.WriteLine("Starting Request!");

            var list = client.ListNamespacedPod("default");
            foreach (var item in list.Items)
            {
                Console.WriteLine(item.Metadata.Name);
            }
            if (list.Items.Count == 0)
            {
                Console.WriteLine("Empty!");
            }

            Console.WriteLine("ListNamespacedDeployment!");
            foreach (var item in client.ListNamespacedDeployment("default").Items)
            {
                Console.WriteLine($"Name {item.Metadata.Name}");
                foreach (var label in item.Spec.Template.Metadata.Labels)
                {
                    Console.WriteLine($"Label {label.Key} = {label.Value}");
                    if (label.Key == "ci")
                    {
                        var newVal = "newdata";
                        Console.WriteLine($"\t\t\tFound! try set to {newVal}");
                        item.Spec.Template.Metadata.Labels.Add("ci2", "newVal");
                        client.PatchNamespacedDeployment(new
                        {
                            op = "replace",
                            path = "/spec/template/metadata/labels/"+ label.Key,
                            value = newVal
                        },item.Metadata.Name, "default"); //fail!
                    }
                }
                foreach (var container in item.Spec.Template.Spec.Containers)
                {
                    Console.WriteLine($"Image {container.Image}");
                }
            }

```

And I get 

> 2018-01-07T21:03:26.886868069Z Starting Request!
> 2018-01-07T21:03:27.398606591Z tool-deployment-664848d469-fdfqp
> 2018-01-07T21:03:27.398636889Z web-deployment-7d87b9fb8-r24c2
> 2018-01-07T21:03:27.398642596Z web-deployment-7d87b9fb8-s96d6
> 2018-01-07T21:03:27.398647321Z ListNamespacedDeployment!
> 2018-01-07T21:03:27.464030335Z Name tool-deployment
> 2018-01-07T21:03:27.464060924Z Label app = tool
> 2018-01-07T21:03:27.464066364Z Label ddd = dd6rty6
> 2018-01-07T21:03:27.464430225Z Image skipeddata/skipeddata:dev
> 2018-01-07T21:03:27.464444583Z Name web-deployment
> 2018-01-07T21:03:27.46444943Z Label app = web
> 2018-01-07T21:03:27.464453986Z Label ci = somedataForOverride
> 2018-01-07T21:03:27.464458516Z 			Found! try set to newdata
> 2018-01-07T21:03:47.549478912Z 
> 2018-01-07T21:03:47.577526422Z Unhandled Exception: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'InternalServerError'
> 2018-01-07T21:03:47.57769817Z    at k8s.Kubernetes.&lt;PatchNamespacedDeploymentWithHttpMessagesAsync&gt;d__321.MoveNext()
> 2018-01-07T21:03:47.577706886Z --- End of stack trace from previous location where exception was thrown ---

**Comment by tg123** [comment]
seems `PatchNamespacedDeployment` is not working as except, I will have a look at that api.

**Comment by brendandburns** [comment]
@tg123 I think this is the same underlying issue as this:

https://github.com/kubernetes-client/java/issues/127

**Comment by tg123** [comment]
@RouR sorry for the late reply, just another busy week

Your approach is right and there is a tricky thing in generated client:
"will serialize all anonymous into {}"
due to default SerializationSettings 

```
SerializationSettings = new JsonSerializerSettings
            {
               .........
                ContractResolver = new ReadOnlyJsonContractResolver(),
               .......
            };
```

workarounds might be:
 * change default SerializationSettings 
 * use <https://github.com/aaxelm/JsonPatch.NetStandard> to generate the json patch object

here is my tested using JsonPatch which is trying to add another label to pod.

```
                var newlables = new Dictionary<string, string>(p.Metadata.Labels)
                {
                    ["test"] = "test"
                };
                var patch = new JsonPatchDocument<V1Pod>();
                patch.Replace(e => e.Metadata.Labels, newlables);
                client.PatchNamespacedPod(patch, n, "default");
```

@brendanburns 
We need to support all 3 kinds of PatchType in the client
 * JSONPatchType
 * MergePatchType
 * StrategicMergePatchType

howerver the generated client, like Java client, treat all body object as JSONPatchType.
I will try to find a better way to support Patch calls

**Comment by RouR** [comment]
Hmm,
As I see Headers is forced to "application/json-patch+json; charset=utf-8", but it`s work (I check in debugger headers)

> _httpRequest.Content.Headers.ContentType =System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json-patch+json; charset=utf-8");


I use Microsoft.AspNetCore.JsonPatch instead of https://github.com/aaxelm/JsonPatch.NetStandard 
with this code:

```
var newlables = new Dictionary<string, string>(item.Spec.Template.Metadata.Labels)
{
	[ciLabel.Key] = "newData" 
};
var patch = new JsonPatchDocument<Appsv1beta1Deployment>();
patch.Replace(e => e.Spec.Template.Metadata.Labels, newlables);
client.PatchNamespacedDeployment(patch, item.Metadata.Name, k8Namespace);
```

The type **Appsv1beta1Deployment** is not defined in NuGet-package KubernetesClient 0.3.0-beta
Please, update NuGet
Thank`s for the help!

**Comment by RouR** [comment]
Hi!
I took the latest version today.
I see breaking changes - PatchNamespacedDeployment require V1Patch object.

Can you explain how to use it? Or provide some example - how to change label in deployment specification?

**Comment by tg123** [comment]
using Microsoft.AspNetCore.JsonPatch;

```
var newlables = new Dictionary<string, string>(p.Metadata.Labels)
{
    ["test"] = "test"
};
var patch = new JsonPatchDocument<V1Pod>();
patch.Replace(e => e.Metadata.Labels, newlables);
client.PatchNamespacedPod(new V1Patch(patch), n, "default");
```

**Comment by RouR** [comment]
Thanks!
