### ISSUE TITLE
.NET Core 3.1 SDK

### ISSUE THREAD

**Issue by WeihanLi** [kubernetes-client/csharp#788]
The library supported target frameworks are: `<TargetFrameworks>netstandard2.1;net5;net6</TargetFrameworks>`

https://github.com/kubernetes-client/csharp/blob/341580fb9b714ababc7e609f3b9f8473107726ef/src/KubernetesClient/KubernetesClient.csproj#L13

While our test projects include `.netcore3.1` and the Github Actions workflow also install the .NET Core 3.1 SDK, should we consider dropping support for .NET Core 3.1 and then we could clean up the .NET Core 3.1 SDK step in the Github Action workflow

![image](https://user-images.githubusercontent.com/7604648/155864156-ec7e9243-b442-4aa8-a799-48ea559f3143.png)

Besides, maybe we could upgrade the examples to .NET 6 since  .NET 6 is an LTS version while .NET 5 is not.

**Comment by tg123** [comment]
`.netcore3.1` here is to ensure `netstandard2.1` code path being tested
support of `netstandard2.1`  may be removed in next major version (expect mid this year) update or eol (end of this year)
