### ISSUE TITLE
NuGet package does not support .NET Standard 4.5.2

### ISSUE THREAD

**Issue by shaneqld** [kubernetes-client/csharp#80]
When attempting to add the package in a .NET Framework 4.5.2 project, nuget reports the following error:

Could not install package 'KubernetesClient 0.3.0-beta'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I believe this is because the package specifically targets only .NET Standard 1.4.

**Comment by tg123** [comment]
#32 

4.5 should work well but not yet tested

**Comment by shaneqld** [comment]
.NET 4.6 does not work from the public NuGet package.  Error below:

Could not install package 'KubernetesClient 0.3.0-beta'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by tg123** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

sorry please try net461, 3.0-beta complies with netstandard 1.4

**Comment by shaneqld** [comment]
Thanks, was just reading about that.  Perhaps add this to the README.

60 packages needed to get this installed.  That's a lot! :)

Any plans to make a vanilla .NET Framework version that does away with .NET Standard?

**Comment by tg123** [comment]
I will try to prune dependencies and make multi-target working

**Comment by brendandburns** [comment]
Closing this since #86 was merged.
