### ISSUE TITLE
Expose models const strings as a base type

### ISSUE THREAD

**Issue by stan-sz** [kubernetes-client/csharp#801]
## Problem

Current `k8s.Models` class design does not allow to use them in generic methods/classes to retrieve the `KubeApiVersion`, `KubeKind` or `KubeGroup` const strings. This would be handy in e.g. mutating webhooks where one could use pattern matching/switch against a compile-time constants (without the need to retype the kinds).

Today, the `KubernetesEntityAttribute` kind-of solves this problem, ideally the same information is available from an interface. "Kind-of", because retrieving the const strings can be done through reflection, which is a runtime component. Additionally, the new base interface could help expose the `PluralName`, present in `KubernetesEntityAttribute`, but missing in the class const strings.

**Comment by tg123** [comment]
not const?
https://github.com/kubernetes-client/csharp/blob/master/src/LibKubernetesGenerator/templates/ModelExtensions.cs.template

**Comment by tg123** [comment]
close with #811
