### ISSUE TITLE
enforce code style rules with dotnet format

### ISSUE THREAD

**Issue by WeihanLi** [kubernetes-client/csharp#803]
`dotnet-format` is an amazing tool to enhance code style defined with `.editorconfig`

Maybe we could introduce `dotnet-format` as a ci checker to enforce the code style likes #799 etc

And from .NET 6, dotnet-format is part of the .NET SDK.

<https://github.com/dotnet/format>

**Comment by tg123** [comment]
it was in https://github.com/kubernetes-client/csharp/blob/0f09a330bc4ce418933d8d241ef2890777813637/.github/workflows/buildtest.yaml#L26

but removed due to rule conflict
