### ISSUE TITLE
README instructions mistake

### ISSUE THREAD

**Issue by shaneqld** [kubernetes-client/csharp#81]
There is a small mistake in README.md.  Specifically where it says:

```bash
$ Where REPO_DIR points to the root of the csharp repository
cd ${REPO_DIR}/csharp/src
${GEN_DIR}/openapi/csharp.sh generated csharp.settings
```

`csharp.settings` is located in $REPO_DIR/csharp, but in the example we are in $REPO_DIR/csharp/src.  The last line of this block should instead say:

```bash
${GEN_DIR}/openapi/csharp.sh generated ../csharp.settings
```

Also:

- it might be helpful to list dependencies as: git, nodejs >= 7.10.0, docker
- it might be helpful to state that the instructions are intended to be run on a Linux system (since it's a C# library, people might assume they are Windows instructions)

**Comment by tg123** [comment]
the file in doc might referrer to any supported format in https://github.com/kubernetes-client/gen

c# is now support all platform, yet, `gen` only works on linux

**Comment by shaneqld** [comment]
Specifically referring to https://github.com/kubernetes-client/csharp/blob/master/README.md

The instructions are incorrect (as per above).  Other comments are ideas to make it easier to understand.
