### ISSUE TITLE
patching json document fails on 7.x+

### ISSUE THREAD

**Issue by schmitch** [kubernetes-client/csharp#815]
```
var cronJobPatch = new JsonPatchDocument<V1CronJob>().Replace(e => e.Spec.Suspend, true);
var cronJobWithHttp =
        await client.PatchNamespacedCronJobAsync(new V1Patch(cronJobPatch, V1Patch.PatchType.JsonPatch),
            name, namespace);
```

this code will fail on dotnet 6 and k8s dotnet client 7.x+ this worked perfectly fine on 6.x+

**Comment by tg123** [comment]
please see #772 
newtonjson is replaced by system.text.json

**Comment by kibernetik542** [comment]
> ```
> var cronJobPatch = new JsonPatchDocument<V1CronJob>().Replace(e => e.Spec.Suspend, true);
> var cronJobWithHttp =
>         await client.PatchNamespacedCronJobAsync(new V1Patch(cronJobPatch, V1Patch.PatchType.JsonPatch),
>             name, namespace);
> ```
> 
> this code will fail on dotnet 6 and k8s dotnet client 7.x+ this worked perfectly fine on 6.x+

I had also same issue please check it out my fix, I just made also [PR for this issue](https://github.com/kubernetes-client/csharp/pull/816)

P.S. My example for csrApproval but you will get point of using new approach for new patch logic

**Comment by schmitch** [comment]
thanks for your help, I will close my comment for now!
