### ISSUE TITLE
Can't install version 7.2.7 from nuget

### ISSUE THREAD

**Issue by buzzfrog** [kubernetes-client/csharp#821]
I tried to create a new project with the latest release and get this error.
No problem installing 7.1.9

PM> Install-Package KubernetesClient -Version 7.2.7
Restoring packages for C:\code-temp\yaml-to-k8s-manifest\yaml-to-k8s-manifest.csproj...
  GET https://api.nuget.org/v3-flatcontainer/kubernetesclient.basic/index.json
  GET https://api.nuget.org/v3-flatcontainer/kubernetesclient.models/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/kubernetesclient.models/index.json 510ms
  NotFound https://api.nuget.org/v3-flatcontainer/kubernetesclient.basic/index.json 514ms
Install-Package : NU1101: Unable to find package KubernetesClient.Basic. No packages exist with this id in source(s): Microsoft Visual Studio 
Offline Packages, nuget.org
At line:1 char:1
+ Install-Package KubernetesClient -Version 7.2.7
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1101: Unable to find package KubernetesClient.Models. No packages exist with this id in source(s): Microsoft Visual Studio
 Offline Packages, nuget.org
At line:1 char:1
+ Install-Package KubernetesClient -Version 7.2.7
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'yaml-to-k8s-manifest'.
At line:1 char:1
+ Install-Package KubernetesClient -Version 7.2.7
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.4693919
PM>

**Comment by dannystommen** [comment]
I'm experiencing the same issue.

**Comment by tg123** [comment]
fix on the way
due to not registered with nuget.org

**Comment by buzzfrog** [comment]
PM> dotnet add package KubernetesClient --version 7.2.8
  Determining projects to restore...
  Writing C:\Users\dagk\AppData\Local\Temp\tmp66EC.tmp
info : Adding PackageReference for package 'KubernetesClient' into project 'C:\code-temp\ConsoleApp3\ConsoleApp3.csproj'.
info : Restoring packages for C:\code-temp\ConsoleApp3\ConsoleApp3.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/kubernetesclient.basic/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/kubernetesclient.models/index.json
error: NU1102: Unable to find package KubernetesClient.Basic with version (>= 7.2.8)
error:   - Found 1 version(s) in nuget.org [ Nearest version: 7.2.6 ]
error:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
error: NU1102: Unable to find package KubernetesClient.Models with version (>= 7.2.8)
error:   - Found 1 version(s) in nuget.org [ Nearest version: 7.2.6 ]
error:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
error: Package 'KubernetesClient' is incompatible with 'all' frameworks in project 'C:\code-temp\ConsoleApp3\ConsoleApp3.csproj'.
PM>

**Comment by elessar-ch** [comment]
I'm having the same issue still.
As a workaround I've built the packages locally.

After pulling pulled this repo, building and packaging can be done using the command
```sh
dotnet pack
```

Then, I've added the following NuGet packages to a local NuGet repo (based on a directory):
- KubernetesClient.7.2.10.nupkg
- KubernetesClient.Basic.7.2.10.nupkg
- KubernetesClient.Models.7.2.10.nupkg
- LibKubernetesGenerator.7.2.10.nupkg

Finally, the add package command works:
```sh
dotnet add package KubernetesClient
```

**Comment by tg123** [comment]
7.2.10 is on nuget.org now, thanks for reporting
