### ISSUE TITLE
question: how to retrieve specific node information 

### ISSUE THREAD

**Issue by dannystommen** [kubernetes-client/csharp#822]
Hi,

I want to retrieve some information from our nodes. When using `kubectl get nodes` I can see the following
```
$ kubectl get nodes
NAME                                        STATUS   ROLES    AGE     VERSION
<blanked for security>                      Ready    <none>   6h42m   v1.20.4-eks-6b7464
<blanked for security>                      Ready    <none>   6h35m   v1.20.4-eks-6b7464
```
I'm want to retrieve the status using the SDK.
When using the `ListNodeAsync` method, this info doesn't seem to be retrieved. `node.Status.Phase`  (where `node` is `V1Node`) always is `null`. When using Fiddler, this information doesn't seem to be in the response JSON.

Further more, I want to see how many nodes are allocated to a node. When doing a `kubectl describe node ...`,  it returns `Non-terminated Pods:          (41 in total)` and also the list. Is this somehow possible to do using the "node api" only? I know I could retrieve all pods, and see which pod is assigned to wich node. But not sure if there's any easier way to do this.

**Comment by brendandburns** [comment]
Both the human readable `get` and `describe` are fairly complicated client-side calls. You will need to review the relevant code in the `kubectl` repository and try to emulate it using the dotnet client.

This client only contains the API to the Kubernetes API server (and a few extensions) it is not a drop-in replacement for `kubectl`

**Comment by tg123** [comment]
`ReadNode`

**Comment by dannystommen** [comment]
> `ReadNode`

Unfortunately this returns exactly the same information als `ListNodeAsync`.



> Both the human readable `get` and `describe` are fairly complicated client-side calls. You will need to review the relevant code in the `kubectl` repository and try to emulate it using the dotnet client.
> 
> This client only contains the API to the Kubernetes API server (and a few extensions) it is not a drop-in replacement for `kubectl`
Good to know, I'll see if I can find something in the kubectl's code base.
