### ISSUE TITLE
PDB ( Pod Disruption Budgets ) not working in older k8s versions

### ISSUE THREAD

**Issue by kibernetik542** [kubernetes-client/csharp#823]
I have code to retrieve PodDisruptionBudgets. Well issue is if k8s version is greater than or equal to v1.22 then it works fine otherwise it throws exception and does not say this issue related with older version. For quick fix I used generic client and it worked fine but if user is using old versions then I need to use this tricky way.

Code which works for v1.22 and above

` var pdbList = await client.ListPodDisruptionBudgetForAllNamespacesAsync(cancellationToken: cancellationToken);`

For below 1.22 versions

`var generic = new GenericClient(client, "policy", "v1beta1", "poddisruptionbudgets");
  var pdbList = await generic.ListAsync<V1PodDisruptionBudgetList>(cancellationToken);`

It will be better somehow handle out this scenarios without creating generic client. I know on k8s sometimes some options is deprecated or obsolete. But as far pdb works fine also with older versions.

**Comment by tg123** [comment]
only version n - 2 support is guaranteed 

https://kubernetes.io/releases/version-skew-policy/
