### ISSUE TITLE
Equals( observedRecord, oldLeaderElectionRecord ) is never equal causing lease is never acquired

### ISSUE THREAD

**Issue by tgckpg** [kubernetes-client/csharp#841]
This section of code always returns true and sets `observedTime` to `Now` because the `oldLeaderElectionRecord` is get from http request which makes new instance of `LeaderElectionRecord` most of the time.
https://github.com/kubernetes-client/csharp/blob/4db390f3afbf93256b1ed954db1db20f2b2b1839/src/KubernetesClient/LeaderElection/LeaderElector.cs#L151-L155

Which makes the following condition `observedTime + config.LeaseDuration > DateTimeOffset.Now` fails.
https://github.com/kubernetes-client/csharp/blob/4db390f3afbf93256b1ed954db1db20f2b2b1839/src/KubernetesClient/LeaderElection/LeaderElector.cs#L157-L160

**Comment by tgckpg** [comment]
sorry I'll need to debug more to confirm if this is the issue

**Comment by tgckpg** [comment]
Tested and confirmed this is an issue. Here's my dumb way to fix it:
```diff
151c159
<             if (!Equals(observedRecord, oldLeaderElectionRecord))
---
>             if ( IsModified( observedRecord, oldLeaderElectionRecord ) )
188a197,208
>       private bool IsModified( LeaderElectionRecord observedRecord, LeaderElectionRecord oldLeaderElectionRecord )
>       {
>               if ( observedRecord == null )
>                       return true;
>
>               return !(
>                       observedRecord.AcquireTime == oldLeaderElectionRecord.AcquireTime
>                       && observedRecord.RenewTime == oldLeaderElectionRecord.RenewTime
>                       && observedRecord.HolderIdentity == oldLeaderElectionRecord.HolderIdentity
>               );
>       }
>
```

**Comment by brendandburns** [comment]
We would gladly take a PR with this fix.

Thanks!

**Comment by tg123** [comment]
LeaderElectionRecord.Equals is same as your IsModified

```
 return HolderIdentity == other?.HolderIdentity && Nullable.Equals(AcquireTime, other.AcquireTime) && Nullable.Equals(RenewTime, other.RenewTime);
```

**Comment by tgckpg** [comment]
Sorry my mistake. It's fine now. Guess I was having a stroke or something :P
