### ISSUE TITLE
NullReferenceException on listing pods

### ISSUE THREAD

**Issue by CatalinAdlerDF** [kubernetes-client/csharp#854]
Hello,

Out of the sudden, on GKE i am getting an NPE.
Tried updating to latest client lib version and updated the GKE cluster to 1.23.5-gke.1501; no luck.
I am unable to repro locally; happens only when executing in the cluster.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.ListNamespacedPodWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ListNamespacedPodAsync(IBasicKubernetes operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, CancellationToken cancellationToken)
 ```

My code is just calling `ListNamespacedPodAsync` with a namespace specified and a cancellation token.
The k8s client is initialized as such

``` c#
if (KubernetesClientConfiguration.IsInCluster())
{
    var clientConfiguration = KubernetesClientConfiguration.InClusterConfig();
    this.KubernetesClient = new Kubernetes(clientConfiguration);
}
else
{
    var cfgData = await KubernetesClientConfiguration.LoadKubeConfigAsync();
    var clientConfiguration = KubernetesClientConfiguration.BuildConfigFromConfigObject(cfgData);
    this.KubernetesClient = new Kubernetes(clientConfiguration);                
}
```

Any ideas?

**Comment by tg123** [comment]
could you please add below to your csproj and run again, thus, the exception could show line number

```
  <ItemGroup>
    <PackageReference Include="SourceLink.Copy.PdbFiles" Version="2.8.3" PrivateAssets="All" />
  </ItemGroup>
```

**Comment by CatalinAdlerDF** [comment]
`at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken) in /_/src/KubernetesClient/Kubernetes.cs:line 168`

**Comment by tg123** [comment]
may i know which version are you using

Kubernetes.cs:line 168  is `}`

**Comment by CatalinAdlerDF** [comment]
I updates to 19 this week.
i think you can't get more accurate line for npe's

**Comment by tg123** [comment]
could you please share masked k8s config? is it running inside k8s cluster?

**Comment by CatalinAdlerDF** [comment]
> could you please share masked k8s config? is it running inside k8s cluster?

Running in GKE.
Which config do you need? the pod definition?

**Comment by CatalinAdlerDF** [comment]
Tested an upgrade to v8 and a downgrade to v7.0 and for now it seems to work with 8.
I'll monitor and close the issue if it's confirmed.

**Comment by tg123** [comment]
thanks for confirming 

maybe #848, but i do not think the npe related to it

**Comment by CatalinAdlerDF** [comment]
hmmm,

v8 seems to also fail.
i'll try 7.1 and get back.

**Comment by CatalinAdlerDF** [comment]
seems to b fine on 7.1
So 7.2 and 8 are affected.

**Comment by tg123** [comment]
`out of the sudden` ? so everything be good at the beginning?

**Comment by CatalinAdlerDF** [comment]
I think it might be related to concurrent use of the Kubernetes client class; testing a fix now.
Probably smth else changed in the system, bc this specific code hasn't been touched since a very long time.

I'll get back on this after I see the impact of removing concurrency.

**Comment by CatalinAdlerDF** [comment]
Seems stable for now.
I'll close this as it was a bug on my end completely.

Thanks for your support!

**Comment by tg123** [comment]
@CatalinAdlerDF could you please show us how it makes npe
i wonder if it can handled a better way
