### ISSUE TITLE
SSL Error when connecting to server with own CA Authority Chain

### ISSUE THREAD

**Issue by KLazarov** [kubernetes-client/csharp#859]
### Description:
The client fails to connect to the Kubernetes cluser if the Kubernetes cluser is using a self signed CA chain. A potential fix is presented for the HTTP Client.

### Problem:
If the Kubernetes cluster has it's own self signed CA chain, then the Kubernetes client is unable to connect to it as it trows a SSL error. As seen here:
![bug report ssl error](https://user-images.githubusercontent.com/74538639/169517885-86d0ce78-fc4d-4385-9f79-09e2c472c71f.png)

The kube.conf provides a self signed CA Authority chain that proves that the SSL connection is actually secure. The CA chain has been tested in both kubectl, in Postman, and in the solution and all of them work flawlessly.

### The suggested solution:
The issue lies in the Microsoft provided `HttpClient`. Even if you add the CA Authority with a `HttpClientHandler`, it still produced the same SSL error. The solution that I found and propose here is based on: [Using custom root CA with HttpClient](https://stackoverflow.com/a/71788784). By providing a `ServerCertificateCustomValidationCallback` to the `HttpClient` it's now able to connect to Kubernetes clusters with their own CA Authority chain, as long as the Certificates are provided to the clients, without having to use `insecure-skip-tls-verify: true`.

The full code for the `HttpClient` is a follows:

```
public async Task<IActionResult> GetKubernetes()
{
    var handler = new HttpClientHandler();
    handler.ClientCertificateOptions = ClientCertificateOption.Manual;
    handler.SslProtocols = SslProtocols.Tls13;
    handler.ClientCertificates.Add(new X509Certificate2(<name_of_ca.pem_file>));
    handler.ServerCertificateCustomValidationCallback = ServerCertificateCustomValidation;
    var client = new HttpClient(handler);
    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", <bearer_token>);
    var result = client.GetAsync(<url_to_kubernetes_cluster>).GetAwaiter().GetResult();
    return Ok(result);
}
private static bool ServerCertificateCustomValidation(
    HttpRequestMessage requestMessage,
    X509Certificate2? certificate,
    X509Chain? chain,
    SslPolicyErrors sslErrors)
{
    if (certificate == null) return false;
    if (chain == null) return false;
    chain.ChainPolicy.TrustMode = X509ChainTrustMode.CustomRootTrust;
    chain.ChainPolicy.CustomTrustStore.Add(new X509Certificate2(<name_of_ca.pem_file>));
    return chain.Build(certificate);
}
```

**Comment by tg123** [comment]
could you please take a look at current impl?

https://github.com/kubernetes-client/csharp/blob/d8e2236611897b8444543f8178e434fc453c90a2/src/KubernetesClient/Kubernetes.ConfigInit.cs#L76

**Comment by KLazarov** [comment]
@tg123 I tested both on .Net 6 and .Net Core 3.1 and both had the same issue.

**Comment by tg123** [comment]
do you mean `CaCerts` is wrong value?

**Comment by tg123** [comment]
do you mean `HttpClientHandler.SslOptions.RemoteCertificateValidationCallback` is not being called?

SendRaw calls the `HttpClient` which has `HttpClientHandler` preinstalled

**Comment by KLazarov** [comment]
From what I just found, it seems that `CaCerts` is actually populated, but when it verifies the CA Cert at `KubernetesClient -> Kubernetes.ConfigInit.cs -> CertificateValidationCallBack` it thinks that the CA Cert is Valid, but it's not Trusted. Which is kinda strange as both Postman, kubectl, and my suggested implementation works fine.

**Comment by tg123** [comment]
did not quite get why CA is valid but not trusted

could you please send PR of fix and test case
here is the current test cases for cert validation
https://github.com/kubernetes-client/csharp/blob/225bb1f59b650e6849858f52608ef917b2484ddb/tests/KubernetesClient.Tests/CertificateValidationTests.cs#L7

**Comment by KLazarov** [comment]
Ok, I will do so.

**Comment by KLazarov** [comment]
Just a small update, it seems to fail on this specific line of code:
![image](https://user-images.githubusercontent.com/74538639/169543402-dae38ddf-5b6a-4b4a-b5e1-954355cccc90.png)

As the `rootCert.RawData` and `cert.RawData` are not equal. This might be because the my `.pem` files containes the whole cert chain, which is 4 certs in a row, but the `foreach` loop grabs just one of them.

**Comment by KLazarov** [comment]
Found a possible solution, I will make a PR for this ASAP. Replace this:

```
foreach (var cert in caCerts)
{
    if (rootCert.RawData.SequenceEqual(cert.RawData))
    {
         isTrusted = true;
         break;
     }
}
```

with this

```
foreach (var cert in caCerts)
{
    isTrusted = chain.Build(cert);
    break;
}
```
so that it actually builds and verifies the cert that we want to use towards the CA chain.
