### ISSUE TITLE
Make `await ListNamespacedServiceAsync` return enumerable

### ISSUE THREAD

**Issue by dzmitry-lahoda** [kubernetes-client/csharp#861]
Currently, I have to 
```csharp
(await ListNamespacedServiceAsync(..)).Items.Where(..)
```
so I it would be nice 
```csharp
(await ListNamespacedServiceAsync(..)).Where(..)``
```

When I see `List` in method name, I always mistype `Where` as list kind of enumerable.

Thank you Sir

**Comment by tg123** [comment]
let me think if an extension method could make life simpler

**Comment by WeihanLi** [comment]
Maybe we could consider for the foreach extensions
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/extension-getenumerator
