### ISSUE TITLE
Patching doesn't work in Classic

### ISSUE THREAD

**Issue by cody-malcolm** [kubernetes-client/csharp#892]
In the Classic version, when I try to patch a pod or deployment, eg:

```
            try
            {                
                var config = KubernetesClientConfiguration.BuildConfigFromConfigFile("C:\\my-config");
                var client = new Kubernetes(config);
                
                var deployments = client.ListNamespacedDeployment("my-namespace");
                var deployment = deployments.Items.First();
                var patchStr = "{\"spec\": {\"replicas\": 0}}";

                var patch = new k8s.Models.V1Patch(patchStr, k8s.Models.V1Patch.PatchType.MergePatch);
                var name = deployment.Metadata.Name;

                client.PatchNamespacedDeploymentScale(patch, name, "my-namespace");                
                
            }
            catch (HttpOperationException e)
            {
                Console.WriteLine(e);
                Console.WriteLine(e.Response.ReasonPhrase);
                Console.WriteLine(e.Response.Content);
            }
```

I get the following error `k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'Forbidden'
   at k8s.Kubernetes.<SendRequestRaw>d__33.MoveNext() in /_/src/KubernetesClient/Kubernetes.cs:line 127` with the following Response.Content:

```
{
"kind":"Status",
"apiVersion":"v1",
"metadata":{},
"status":"Failure",
"message":"deployments.apps \"my-deployment\" is forbidden: User \"oidc:my-username@my-host.com\" cannot  resource \"deployments/scale\" in API group \"apps\" in the namespace \"my-namespace\"",
"reason":"Forbidden",
"details":
  {
    "name":"my-deployment",
    "group":"apps",
    "kind":"deployments"
  },
"code":403
}
```
Note in the Response.Content that there are two spaces in "cannot  resource" and ordinarily the type of request is listed (eg. it should say something like "cannot patch resource", "cannot list resource", etc). It seems like something is missing in the API request that is being sent, which is causing the Kubernetes side of things to reject the request.

This is not an RBAC issue, I am able to execute `kubectl -n my-namespace patch deployment my-deployment --subresource='scale' --type='merge' -p '{"spec":{"replicas":0}}'` with the correct results. Further and more importantly, if I uninstall the Classic library and use version 4.0.26 of the "standard" library, the same code works (with minor changes to account for differences between versions). 
Additionally, other methods such as `client.CoreV1.DeleteNamespacedPod()` work within the Classic library, it is only patching methods (at least `client.PatchNamespacedDeployment()`, `client.PatchNamespacedDeploymentScale()`, and `client.CoreV1.PatchNamespacedPod()`) that do not work (and as I mentioned, I specifically checked that the latter two work properly with my Kubernetes configuration using version 4.0.26 of the standard library).

**Comment by brendandburns** [comment]
I suspect that this is bug in credential loading that was fixed somewhere along the line. What is your kubeconfig using for auth?

**Comment by kibernetik542** [comment]
I'd recommend to take a look different way of patching. I have example of restart.
[example](https://github.com/kubernetes-client/csharp/blob/master/examples/restart/Program.cs)

**Comment by cody-malcolm** [comment]
> I suspect that this is bug in credential loading that was fixed somewhere along the line. What is your kubeconfig using for auth?

With Classic I have tried using both a namespace that uses basic token authentication and a namespace that uses OIDC authentication, and both fail in the same way. With standard version 4.0.26, the basic token authentication works. OIDC doesn't work properly with that version, which is why we are trying to use Classic in the first place. This suggests to me the issue is not related to the configuration or authentication of our K8s cluster. Especially considering the request is missing information.

**Comment by tg123** [comment]
@cody-malcolm could you please test #894
in netcore, the value was normalized but not in netframework

seems you are doing a unknown method and return 403
here is why the `Patch` is mapped to `""`
https://github.com/kubernetes/kubernetes/blob/609db7ed0b1f2839e414c17d29fe4d76edc994bd/staging/src/k8s.io/apiserver/pkg/endpoints/request/requestinfo.go#L163

**Comment by cody-malcolm** [comment]
@tg123 
Tested #894, the issue is resolved and the code above now works as expected. Thank you!
