### ISSUE TITLE
"Error while copying content to a stream" when watching empty set

### ISSUE THREAD

**Issue by nabsul** [kubernetes-client/csharp#893]
When I attempt to watch for changes on a set of objects that is empty, the response body from the Kubernetes API is empty and causes an exception.

I am able to repro this in Linqpad with this code:

```cs
var cfg = KubernetesClientConfiguration.BuildDefaultConfig();
var client = new Kubernetes(cfg);
var result = await client.ListConfigMapForAllNamespacesWithHttpMessagesAsync(watch: true, labelSelector: "test-not-exist=val", timeoutSeconds: 10);
```

Notes: 

- For this error to repro, you must create a `List` request that returns zero results
- I have observed this error with other data types, not just `ConfigMap`

The resulting error is:

<table id="t2" style="border-color:#B56172"><thead><tr><td class="typeheader" style="background:#B56172" colspan="2"><span class="arrow-up" id="t2ud"></span>HttpRequestException</td></tr><tr id="sum1"><td colspan="2" class="summary" style="background:#F4DEE3;color:black">Error while copying content to a stream.</td></tr></thead><tbody><tr><th class="member" title="System.Collections.IDictionary">Data</th><td><table id="t3"><thead><tr><td class="typeheader" colspan="1">(0 items)</td></tr></thead></table></td></tr><tr><th class="member" title="System.String">HelpLink</th><td><span class="null">null</span></td></tr><tr><th class="member" title="System.Int32">HResult</th><td>-2147024858</td></tr><tr><th class="member" title="System.Exception">InnerException</th><td><table id="t5" class="expandable"><thead><tr><td class="typeheader" colspan="2"><span class="arrow-down" id="t5ud"></span>EndOfStreamException</td></tr><tr id="sum4"><td colspan="2" class="summary" style="">Attempted to read past the end of the stream.</td></tr></thead><tbody><tr><th class="member" title="System.Reflection.MethodBase">TargetSite</th><td><div id="c6">TargetSite</div></td></tr><tr><th class="member" title="System.String">Message</th><td>Attempted to read past the end of the stream.</td></tr><tr><th class="member" title="System.Collections.IDictionary">Data</th><td><table id="t7"><thead><tr><td class="typeheader" colspan="1">(0 items)</td></tr></thead></table></td></tr><tr><th class="member" title="System.Exception">InnerException</th><td><span class="null">null</span></td></tr><tr><th class="member" title="System.String">HelpLink</th><td><span class="null">null</span></td></tr><tr><th class="member" title="System.String">Source</th><td>KubernetesClient</td></tr><tr><th class="member" title="System.Int32">HResult</th><td>-2147024858</td></tr><tr><th class="member" title="System.String">StackTrace</th><td>   at k8s.LineSeparatedHttpContent.PeekableStreamReader.PeekLineAsync() in /_/src/KubernetesClient/LineSeparatedHttpContent.cs:line 180<br />   at k8s.LineSeparatedHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context) in /_/src/KubernetesClient/LineSeparatedHttpContent.cs:line 30<br />   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)</td></tr></tbody></table></td></tr><tr><th class="member" title="System.String">Message</th><td>Error while copying content to a stream.</td></tr><tr><th class="member" title="System.String">Source</th><td>System.Net.Http</td></tr><tr><th class="member" title="System.String">StackTrace</th><td>   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)<br />   at System.Net.Http.HttpContent.WaitAndReturnAsync[TState,TResult](Task waitTask, TState state, Func`2 returnFunc)<br />   at k8s.Kubernetes.CreateResultAsync[T](HttpRequestMessage httpRequest, HttpResponseMessage httpResponse, Nullable`1 watch, CancellationToken cancellationToken) in /_/src/KubernetesClient/Kubernetes.cs:line 84<br />   at k8s.AbstractKubernetes.ListConfigMapForAllNamespacesWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, Nullable`1 pretty, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken) in /_/src/KubernetesClient.Basic/LibKubernetesGenerator/LibKubernetesGenerator.KubernetesClientSourceGenerator/Kubernetes.g.cs:line 972<br />   at UserQuery.Main(), line 3</td></tr><tr><th class="member" title="System.Net.HttpStatusCode?">StatusCode</th><td><span class="null">null</span></td></tr><tr><th class="member" title="System.Reflection.MethodBase">TargetSite</th><td><table id="t9" class="expandable"><thead><tr><td class="typeheader" colspan="2"><span class="arrow-down" id="t9ud"></span>RuntimeMethodInfo</td></tr><tr id="sum8"><td colspan="2" class="summary" style="">&lt;LoadIntoBufferAsyncCore&gt;d__63.MoveNext ()</td></tr></thead><tbody><tr><th class="member" title="System.String">Name</th><td>MoveNext</td></tr><tr><th class="member" title="System.Type">DeclaringType</th><td><div id="c10">typeof (&lt;LoadIntoBufferAsyncCore&gt;d__63)</div></td></tr><tr><th class="member" title="System.Type">ReflectedType</th><td><div id="c11">typeof (&lt;LoadIntoBufferAsyncCore&gt;d__63)</div></td></tr><tr><th class="member" title="System.Reflection.Module">Module</th><td><div id="c12">Module</div></td></tr><tr><th class="member" title="IEnumerable&lt;System.Reflection.CustomAttributeData&gt;">CustomAttributes</th><td><table id="t13"><thead><tr><td class="typeheader" colspan="1">(0 items)</td></tr></thead></table></td></tr><tr><th class="member" title="System.Boolean">IsCollectible</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Int32">MetadataToken</th><td>100664069</td></tr><tr><th class="member" title="System.Reflection.MethodAttributes">Attributes</th><td>PrivateScope, Private, Final, Virtual, HideBySig, VtableLayoutMask</td></tr><tr><th class="member" title="System.Reflection.MethodImplAttributes">MethodImplementationFlags</th><td>Managed</td></tr><tr><th class="member" title="System.Reflection.CallingConventions">CallingConvention</th><td>Standard, HasThis</td></tr><tr><th class="member" title="System.Boolean">IsAbstract</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsConstructor</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsFinal</th><td><span class="true">True</span></td></tr><tr><th class="member" title="System.Boolean">IsHideBySig</th><td><span class="true">True</span></td></tr><tr><th class="member" title="System.Boolean">IsSpecialName</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsStatic</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsVirtual</th><td><span class="true">True</span></td></tr><tr><th class="member" title="System.Boolean">IsAssembly</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsFamily</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsFamilyAndAssembly</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsFamilyOrAssembly</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsPrivate</th><td><span class="true">True</span></td></tr><tr><th class="member" title="System.Boolean">IsPublic</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsConstructedGenericMethod</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsGenericMethod</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsGenericMethodDefinition</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">ContainsGenericParameters</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.RuntimeMethodHandle">MethodHandle</th><td><table id="t15" class="expandable"><thead><tr><td class="typeheader" colspan="2"><span class="arrow-down" id="t15ud"></span>RuntimeMethodHandle</td></tr><tr id="sum14"><td colspan="2" class="summary" style="">System.RuntimeMethodHandle</td></tr></thead><tbody><tr><th class="member" title="System.IntPtr">Value</th><td>140704672329552</td></tr></tbody></table></td></tr><tr><th class="member" title="System.Boolean">IsSecurityCritical</th><td><span class="true">True</span></td></tr><tr><th class="member" title="System.Boolean">IsSecuritySafeCritical</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsSecurityTransparent</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Reflection.MemberTypes">MemberType</th><td>Method</td></tr><tr><th class="member" title="System.Reflection.ParameterInfo">ReturnParameter</th><td><table id="t17" class="expandable"><thead><tr><td class="typeheader" colspan="2"><span class="arrow-down" id="t17ud"></span>RuntimeParameterInfo</td></tr><tr id="sum16"><td colspan="2" class="summary" style="">Void</td></tr></thead><tbody><tr><th class="member" title="System.Reflection.ParameterAttributes">Attributes</th><td>None</td></tr><tr><th class="member" title="System.Reflection.MemberInfo">Member</th><td><table id="t19" class="limit" title="Cyclic reference"><thead><tr><td class="typeheader" colspan="2"><span class="cyclic">∞</span>RuntimeMethodInfo</td></tr><tr id="sum18"><td colspan="2" class="summary" style="">&lt;LoadIntoBufferAsyncCore&gt;d__63.MoveNext ()</td></tr></thead><tbody /></table></td></tr><tr><th class="member" title="System.String">Name</th><td><span class="null">null</span></td></tr><tr><th class="member" title="System.Type">ParameterType</th><td><div id="c20">typeof (Void)</div></td></tr><tr><th class="member" title="System.Int32">Position</th><td>-1</td></tr><tr><th class="member" title="System.Boolean">IsIn</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsLcid</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsOptional</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsOut</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsRetval</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Object">DefaultValue</th><td><span class="null">null</span></td></tr><tr><th class="member" title="System.Object">RawDefaultValue</th><td><span class="null">null</span></td></tr><tr><th class="member" title="System.Boolean">HasDefaultValue</th><td><span class="true">True</span></td></tr><tr><th class="member" title="IEnumerable&lt;System.Reflection.CustomAttributeData&gt;">CustomAttributes</th><td><table id="t21"><thead><tr><td class="typeheader" colspan="1">(0 items)</td></tr></thead></table></td></tr><tr><th class="member" title="System.Int32">MetadataToken</th><td>134217728</td></tr></tbody></table></td></tr><tr><th class="member" title="System.Type">ReturnType</th><td><div id="c22">typeof (Void)</div></td></tr><tr><th class="member" title="System.Reflection.ICustomAttributeProvider">ReturnTypeCustomAttributes</th><td><table id="t24" class="expandable"><thead><tr><td class="typeheader" colspan="2"><span class="arrow-down" id="t24ud"></span>ICustomAttributeProvider (RuntimeParameterInfo)</td></tr><tr id="sum23"><td colspan="2" class="summary" style="">Void</td></tr></thead><tbody><tr><th class="member" title="System.Reflection.ParameterAttributes">Attributes</th><td>None</td></tr><tr><th class="member" title="System.Reflection.MemberInfo">Member</th><td><table id="t26" class="limit" title="Cyclic reference"><thead><tr><td class="typeheader" colspan="2"><span class="cyclic">∞</span>RuntimeMethodInfo</td></tr><tr id="sum25"><td colspan="2" class="summary" style="">&lt;LoadIntoBufferAsyncCore&gt;d__63.MoveNext ()</td></tr></thead><tbody /></table></td></tr><tr><th class="member" title="System.String">Name</th><td><span class="null">null</span></td></tr><tr><th class="member" title="System.Type">ParameterType</th><td><div id="c27">typeof (Void)</div></td></tr><tr><th class="member" title="System.Int32">Position</th><td>-1</td></tr><tr><th class="member" title="System.Boolean">IsIn</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsLcid</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsOptional</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsOut</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Boolean">IsRetval</th><td><span class="false">False</span></td></tr><tr><th class="member" title="System.Object">DefaultValue</th><td><span class="null">null</span></td></tr><tr><th class="member" title="System.Object">RawDefaultValue</th><td><span class="null">null</span></td></tr><tr><th class="member" title="System.Boolean">HasDefaultValue</th><td><span class="true">True</span></td></tr><tr><th class="member" title="IEnumerable&lt;System.Reflection.CustomAttributeData&gt;">CustomAttributes</th><td><table id="t28"><thead><tr><td class="typeheader" colspan="1">(0 items)</td></tr></thead></table></td></tr><tr><th class="member" title="System.Int32">MetadataToken</th><td>134217728</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>

**Comment by nabsul** [comment]
I made it small to easily demo the issue. But the same happens with a large timeout.

**Comment by nabsul** [comment]
Also, I saw the above issue and PR which seem very similar to my issue. I'm on the latest client version, but I still get the above error.

**Comment by tg123** [comment]
tested `var result = await client.ListConfigMapForAllNamespacesWithHttpMessagesAsync(watch: true, labelSelector: "test-not-exist=val");` (no timeout param) locally

cant repro
looks like the connection is closed from server side, could you please do tcpdump to verify?

**Comment by nabsul** [comment]
@tg123: How long did you wait for that statement to complete? If I remove the timeout, the error happens, but only after about an hour.

That's the reason I added the 10 second timeout. It's to reproduce the error faster.

**Comment by nabsul** [comment]
Below are some sample logs with timestamps from my open source project. I'm currently working around this error with a try-catch and infinite loop of the watch: https://github.com/nabsul/kcert/blob/0e3e5ad998bd4b0063accfe2dbc1d0eca18f0ba4/Services/K8sWatchClient.cs#L66

```
{
  "Timestamp": "2022:06:20 10:05:18.377804",
  "EventId": 0,
  "LogLevel": "Information",
  "Category": "KCert.Services.K8sClient",
  "Message": "Empty Kubernetes client result threw an exception. Retrying V1ConfigMap[kcert.dev/cert-request=request].",
  "State": {
    "Message": "Empty Kubernetes client result threw an exception. Retrying V1ConfigMap[kcert.dev/cert-request=request].",
    "type": "V1ConfigMap",
    "label": "kcert.dev/cert-request=request",
    "{OriginalFormat}": "Empty Kubernetes client result threw an exception. Retrying {type}[{label}]."
  }
}
{
  "Timestamp": "2022:06:20 11:01:06.095747",
  "EventId": 0,
  "LogLevel": "Information",
  "Category": "KCert.Services.K8sClient",
  "Message": "Empty Kubernetes client result threw an exception. Retrying V1ConfigMap[kcert.dev/cert-request=request].",
  "State": {
    "Message": "Empty Kubernetes client result threw an exception. Retrying V1ConfigMap[kcert.dev/cert-request=request].",
    "type": "V1ConfigMap",
    "label": "kcert.dev/cert-request=request",
    "{OriginalFormat}": "Empty Kubernetes client result threw an exception. Retrying {type}[{label}]."
  }
}
{
  "Timestamp": "2022:06:20 11:32:03.076967",
  "EventId": 0,
  "LogLevel": "Information",
  "Category": "KCert.Services.K8sClient",
  "Message": "Empty Kubernetes client result threw an exception. Retrying V1ConfigMap[kcert.dev/cert-request=request].",
  "State": {
    "Message": "Empty Kubernetes client result threw an exception. Retrying V1ConfigMap[kcert.dev/cert-request=request].",
    "type": "V1ConfigMap",
    "label": "kcert.dev/cert-request=request",
    "{OriginalFormat}": "Empty Kubernetes client result threw an exception. Retrying {type}[{label}]."
  }
}
```

**Comment by tg123** [comment]
I mean it is a feature, not a bug
the server side cut the connection because of `timeout` and you get eof exception because no more event coming.

**Comment by nabsul** [comment]
I'm not super convinced that this should be considered a feature. The behavior of the API timing out and returning an empty body is normal and expected. Shouldn't the client check for this case and handle it instead of throwing an exception while trying to read an empty stream?

**Comment by tg123** [comment]
the behavior is same in golang client
the server side `cut` the connection and you will see `no more event`
 
```
opt := v1.ListOptions{
		LabelSelector: "not-exists",
		Watch:         true,
		TimeoutSeconds: new(int64),
	}

	*opt.TimeoutSeconds = 5

	wacher, err := api.Pods("default").Watch(context.TODO(), opt)

	if err != nil {
		panic(err)
	}

	fmt.Println("start watch")
	for evt := range wacher.ResultChan() {
		fmt.Println(evt)
	}
	fmt.Println("no more events")
```

also in tcp level  (127.0.0.1.8001 as api server)


```
16:38:06.023277 IP 127.0.0.1.8001 > 127.0.0.1.37494: Flags [P.], seq 342:347, ack 172, win 512, options [nop,nop,TS val 387078250 ecr 387073250], length 5
        0x0000:  0000 0304 0006 0000 0000 0000 0000 0800
        0x0010:  4500 0039 22ef 4000 4006 19ce 7f00 0001
        0x0020:  7f00 0001 1f41 9276 2968 3680 ad95 b9b8
        0x0030:  8018 0200 fe2d 0000 0101 080a 1712 586a
        0x0040:  1712 44e2 300d 0a0d 0a
```

you can see `0d 0a0d 0a` from the server which means end of http response

**Comment by tg123** [comment]
@nabsul let me know if you still have any idea about this issue
I also revisited current impl, I believe the async foreach should yield break comparing to go impl
here is `yield break` if the first line is not null
https://github.com/kubernetes-client/csharp/blob/56646aeed3ee289146be9efda4d8da8756b8ac69/src/KubernetesClient/Watcher.cs#L182

**Comment by nabsul** [comment]
Thanks for the follow up @tg123. a `yield break` makes a lot more sense to me. That way I would not need to wrap my code like I'm doing here: https://github.com/nabsul/kcert/blob/0e3e5ad998bd4b0063accfe2dbc1d0eca18f0ba4/Services/K8sWatchClient.cs#L66

**Comment by nabsul** [comment]
No worries. We had a difference in opinion on what should be done here anyways. I'm closing this issue.
