### ISSUE TITLE
Drop support for NET 5.0

### ISSUE THREAD

**Issue by m3nax** [kubernetes-client/csharp#900]
NET 5.0 in May 2022 entered the "End of Support" state (as reported on the dotnet.microsoft.com site) and will no longer receive security patches and fixes. I believe that in order to ensure package security, NET 5.0 support should be removed.
Source: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

The library will still be usable in NET 5.0 projects with .NET Standard 2.1 version.
Source: https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1

**Comment by tg123** [comment]
It is true to encourage everyone to upgrade .net to 6
the reason net5 is still in current targeting is that some impl of netstandard2.1 is not as good as net5.

for example, http client handler and cancel token for some async method. this would lead some drawback of net5 users
the current plan is to drop net5 (and standardard 2.1) at the end of this year when net7 is released and netcore3.1 is eol.
most likely along with k8s 1.26 or 1.27

**Comment by stan-sz** [comment]
See PR #1085 that drops targeting .Net 5.0.
