### ISSUE TITLE
Fix Nuget workflow errors

### ISSUE THREAD

**Issue by m3nax** [kubernetes-client/csharp#913]
# Goal
Fix **Nuget** workflow errors present since v7.2.7 version.

 [https://github.com/kubernetes-client/csharp/actions/workflows/nuget.yaml](https://github.com/kubernetes-client/csharp/actions/workflows/nuget.yaml)

**Comment by m3nax** [comment]
> Thanks for pointing this out, the `push` part was working so I don't think anybody noticed :)
> 
> Looks like the `delete` part is failing, we'll look into it.

If you want I can take a look.

**Comment by m3nax** [comment]
Assign to me

**Comment by m3nax** [comment]
Packages are pushed to ***nuget.pkg.github.com*** and ***nuget.org** and will only be deleted from ***nuget.pkg.github.com***, correct?

https://github.com/kubernetes-client/csharp/blob/8026ccdc14b7eb4e2cffe1a61575fc5b6b5a88f9/.github/workflows/nuget.yaml#L41-L44

**Comment by tg123** [comment]
yup, deleting is gh only.
