### ISSUE TITLE
ClientCertificateKeyStoreFlags Ignored When Using Windows + NET5 or Above

### ISSUE THREAD

**Issue by bootleg224** [kubernetes-client/csharp#937]
This fix corrects the case when ClientCertificateKeyStoreFlags are not used
https://github.com/kubernetes-client/csharp/pull/936

**Comment by m3nax** [comment]
Pull request https://github.com/kubernetes-client/csharp/pull/936 has been mergetd 3 day ago, the issue can be closed?
